### ISSUE TITLE
Support for key-chords and mode-maps

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/hydra#1]
This is an awesome package! Do you have plans to support key-chords and mode-maps? Currently I see that it always does `global-set-key`.

You already [saw the application of key-chords in `hydra` context](https://github.com/kaushalmodi/.emacs.d/commit/36f02b88d8a281f4be2403d408f8a8a7948892b7).

I find the support of mode-maps even more useful because I always define my bindings in [my minor mode that rules them all](http://emacs.stackexchange.com/a/358/115). I rarely ever bind anything to the global map because I like to have the option to revert back to pristine emacs default bindings by simply disabling that minor mode that ruled them all :)

**Comment by abo-abo** [comment]
See if this is enough for key chords. It works for minor modes for sure.

**Comment by kaushalmodi** [comment]
I tried it out and eebugged it understand what's it doing.

This will not work with `key-chord` as a key chord can be only 2 keys.

e.g. I can set "33" to call a command.

But this code is concatenating the primary binding with the keys in transient map.

<pre>
 ,@(cl-mapcar
          (lambda (head name)
            `(,method ,(kbd (concat body " " (car head))) #',name))
          heads names))))
</pre>

So that's a problem..

Here's my intended use with key-chord-mode:

<pre>
(hydra-create "33"
  `(("3" . toggle-comment-on-line-or-region)
    ("p" . previous-line)
    ("n" . next-line))
  (lambda (key command)
    (key-chord-define-global key command)))
<./pre>

This causes that concatenation part of the code to try to bind to "333", "33p" and "33n" which is not possible.

But in any case, this older method works for me:

<pre>
(key-chord-define-global "33" (def-rep-command
                                `(("3" . toggle-comment-on-line-or-region)
                                  ("p" . previous-line)
                                  ("n" . next-line))))
</pre>
Thank you for adding the support for minor modes!

**Comment by abo-abo** [comment]
Here is your solution:

```
(hydra-create
    "3"
    `(("3" . toggle-comment-on-line-or-region)
      ("p" . previous-line)
      ("n" . next-line))
    (lambda (key command)
      (when command
        (key-chord-define-global key command))))
```

It takes advantage of the fact that `(kbd "3 3")` evaluates to "33".

**Comment by kaushalmodi** [comment]
I tried this quick hack to at least make hydra workable with key-chords and that works.

<pre>
,@(cl-mapcar
          (lambda (head name)
            `(,method ,(kbd body ) #',name))
          heads names))))
</pre>

When I say that it works, I mean that the transient mode map works as expected.

Above hack binds the key-chord "33" to `hydra-33-next-line` because `("n" . next-line)` is the last element in the `heads` alist. When I press `3 3` key chord, `next-line` is executed and then pressing `3`, `p`, and `n` works as expected.

What I believe would be a clean solution would be an option to NOT dynamically create the functions and their concatenated bindings, but simply activate the transient map.

But then that would probably make the point of using hydra useless :)

**Comment by kaushalmodi** [comment]
That solution works! I also got the "3p" and "3n" bindings defined for free.

I just need to make sure that I don't end up creating unintended key chords this way.

Example: Below would be bad

<pre>
(hydra-create
    "c"
    `(("1" . toggle-comment-on-line-or-region)
      ("l" . previous-line)
      ("n" . next-line))
    (lambda (key command)
      (when command
        (key-chord-define-global key command))))
</pre>

Guess what happens when I speedily type **cl**ass to start defining a class :)

But thank you for this real-time support!
