### ISSUE TITLE
Hydra timer not cancelled if exit by nil head or foreign keys

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#100]
Given the following two testing hydras:
```elisp
(bind-key
 "C-c g"
(defhydra foo (:timeout 9.0)
  "foo"
  ("f" (message "ffff"))
  ("v" (message "vvvv") :exit t)
  ("q" nil)))

(bind-key
 "C-c t"
(defhydra bar ()
  "
bar

_b_: message bbb
_q_: quit

"
  ("b" (message "bbb"))
  ("q" nil)))
```

1. Enter the first hydra with <kbd>C-c g</kbd>.
2. Press <kbd>f</kbd> to start the timer.
3. Then immediately press <kbd>q</kbd> followed by <kbd>C-c t</kbd> to exit from the first hydra and enter the second one.
4. Watch the second hydra exiting on its own in a few seconds. I am guessing that the timer left over from the first hydra "bleeds" into the second one.

In step 3 replacing <kbd>q</kbd> with:

1. any foreign key reproduces the issue, too.
2. <kbd>f v</kbd> also reproduces the issue.
3. <kbd>C-g</kbd> does *not* reproduce the issue.
4. <kbd>v</kbd> does *not* reproduce the issue.

Running the MELPA version 20150328.1117.

**Comment by abo-abo** [comment]
Thanks for the help in tracking this down. Could you please check if all issues are solved?

**Comment by zhaojiangbin** [comment]
It no longer happens to me. Thanks for the quick fix.
