### ISSUE TITLE
Lisp nesting exceeds `max-lisp-eval-depth'

### ISSUE THREAD

**Issue by halbtuerke** [abo-abo/hydra#101]
I just updated hydra through package.el (with Paradox) and now every time I try to call a hydra head I get the following message:

```
Lisp nesting exceeds `max-lisp-eval-depth'
```

The hydra stays active and I can't close it.

hydra 20150331.240
Emacs GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.1.0, NS appkit-1344.72 Version 10.10.2 (Build 14C1514)) of 2015-03-23

If you need more information please let me know.

**Comment by abo-abo** [comment]
OK, I can reproduce on 25, but not on 24.4. I'll see what I can do.

**Comment by abo-abo** [comment]
See if this solves it.

**Comment by SimonAB** [comment]
Seeing this here too, on 25, with hydra-20150331.240

**Comment by abo-abo** [comment]
I guess you'll have to wait an hour for MELPA to update.

I should write down a few integration tests at some point.

**Comment by abo-abo** [comment]
The test that I just added would fail with:

    Lisp nesting exceeds `max-lisp-eval-depth'

for `hydra 20150331.240`. So at least this one shouldn't happen in the future.
I just have to make sure that Travis CI is using emacs25 as well for the testing.

**Comment by SimonAB** [comment]
Works fine for me now -- thanks Oleh!

**Comment by halbtuerke** [comment]
Now it works again. Thanks for the quick fix.
