### ISSUE TITLE
Heads made from symbols don't colorize correctly in doc string

### ISSUE THREAD

**Issue by nandryshak** [abo-abo/hydra#102]
Take this Hydra:

    (global-set-key
    (kbd "C-c RET")
    (defhydra hydra-mode-switch (global-map "C-c RET" :color blue)
    "
    _c_ C  _+_ C++   _#_ C#"
    ("c" c-mode nil)
    ("+" c++-mode nil)
    ("#" csharp-mode nil)))

This incorrectly results in the following doc string:

Screenshot:

![Example Screenshot](http://i.imgur.com/Dd34ahm.png)

Text:

    c C  _+_ C++  _#_  C#

**Comment by mrBliss** [comment]
I've just (minutes ago) encountered the same issue! `*` is also problematic, which leads me to think this has to do with regular expressions.

**Comment by mrBliss** [comment]
I found the cause and fixed it, see #103.

**Comment by nandryshak** [comment]
Nice, thanks! 

I'll let abo close this issue when he merges the fix.

**Comment by abo-abo** [comment]
Thanks for noticing, that particular thing had way too many issues:)
Finally, everything should be covered now.

**Comment by abo-abo** [comment]
Spoke too soon. Matching everything is bad as well.
For instance, "foo_ Emacs Rocks! _#_" will think that ` Emacs Rocks! ` is a binding, which is wrong.
I've added `#+*` to the regex. Let's keep increasing it incrementally.
