### ISSUE TITLE
suggestion: add an idle time option

### ISSUE THREAD

**Issue by joedicastro** [abo-abo/hydra#108]
I'm using hydra to replace the same "menus" that I was displaying with `evil-leader` and `guide-key` packages in a similar way as the _spacemacs_ distributions does. 

A nice thing that `guide-key` has is that you can set an idle time to wait until you press a key to activate any head before show the hydra hints buffer (explained in hydra terms). This is very helpful when you know the key bindings by memory and you do not need to see the hints buffer, but if you forget how to activate any head, you simple press the hydra binding and wait the "idle time" and the hints buffer is shown to help you to choose the right next binding.

I don't know if to add this is hard or not, but it could be a great idea.

Thanks for hydra, I love it!

**Comment by abo-abo** [comment]
> I don't know if to add this is hard or not, but it could be a great idea.

Nice idea. Take a look at the `idle` branch and the new commit message.
So far, only `foo/body` has a timer. Let me know if you need more.

> Thanks for hydra, I love it!

And thank you for the twittering hydra, it's insane!

**Comment by joedicastro** [comment]
:OK: I tested it and works perfectly nice! Thanks you very much!

**Comment by abo-abo** [comment]
OK, the feature is in master now.
