### ISSUE TITLE
Red heads calling commands that read from minibuffer broken

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#109]
Somewhere in the second half of last week (ended on April 10th), I updated hydra from MELPA. Some of my hydras have been broken since - they all have red heads that call commands that read from minibuffer. A few examples are `goto-line`, `ido-find-file`.

I only realized the problem and figured out how it is broken now. So I don't have the exact info of the "last good version".

The following hydra reproduces the problem:
```elisp
(bind-key
 "C-c l"
 (defhydra foo()
   "go to"
   ("l" goto-line)
   ("f" ido-find-file)
   ("c" recenter-top-bottom)
   ("s" swiper)
   ("q" nil)))
```
Among the heads, <kbd>l</kbd> and <kbd>f</kbd> do not work properly. To see how <kbd>f</kbd> is broken, start the ido search pattern with one of the head letters - "l", "f", "c", "s", and "q".

The problem disappears if these heads are turned into blue (i.e. with `:exit t`).

Meanwhile, the other heads, namely <kbd>c</kbd>, <kbd>s</kbd> and <kbd>q</kbd> are not affected.

I am running:
  - Emacs version "GNU Emacs 24.5.3 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2015-04-11 on Atago.local"
  - hydra version "MELPA 20150413.1414".

**Comment by abo-abo** [comment]
Sorry for the regression, I forgot what a branch of code was for when I deleted it.

**Comment by abo-abo** [comment]
OK, this bug should trigger a test in the future if it surfaces.

**Comment by zhaojiangbin** [comment]
Thanks for the quick fix.
