### ISSUE TITLE
can we customise the color

### ISSUE THREAD

**Issue by bixuanzju** [abo-abo/hydra#11]
I was very happy to see colourful `hydra`, but I myself had difficultly reading red letter in a dark theme. Could you provide a customised variable or something so I can choose whatever colour I like for persistent commands?

**Comment by abo-abo** [comment]
Isn't the option already there? <kbd>M-x</kbd> `customize-group` `hydra`.

You can set `hydra-face-red` and `hydra-face-blue`. If you need more, let me know.

**Comment by bixuanzju** [comment]
Oh yes!
