### ISSUE TITLE
Capitalized error and space problem

### ISSUE THREAD

**Issue by llcc** [abo-abo/hydra#110]
Dear @abo-abo 

I used the twitter-mode hydra. But it did not appear normally in Capitalized char. And I also think that there is also a problem about the space.
![image](https://cloud.githubusercontent.com/assets/3996879/7178554/a353723e-e46a-11e4-95c9-08c402d8c528.png)

Thanks if you can dig into it.

**Comment by abo-abo** [comment]
I'm not getting this error on my end. Can you try to re-install hydra and restart Emacs?

**Comment by llcc** [comment]
I found the reason.
I installed the hydra from melpa, and I thought I was using the updated one. 
Buy actually I was using the 0-4-1 version in gnu.
Thanks!

**Comment by abo-abo** [comment]
OK.
