### ISSUE TITLE
actions out side of hydra-buffer

### ISSUE THREAD

**Issue by yitang** [abo-abo/hydra#111]
Hi,

I am trying to use Hydra to bind all the search functions together,  I have 
``` emacs-lisp
(defhydra hydra-search (:color red
			       :hint nil)
  "
Current Buffer: _i_search helm-_s_woop _a_ce-jump-word 
Multiple Buffer: helm-multi-_S_woop 
Project Directory: projectile-_g_rep  helm-projectile-_G_rep
"
  ("i" isearch-forward)
  ("s" helm-swoop)
  ("a" ace-jump-word-mode)
  ("S" helm-multi-swoop)
  ("g" projectile-grep)
  ("G" helm-projectile-grep))
(hydra-search/body)
```
I really like this setting and I believe will use it a lot but there are two probelms to get it works: 

1. `ace-jump-word-mode` can be activated, but when I press a key, say "t", to jump, it will insert "t" character at the point, 
2. If active `isearch-forward` and search for "S", which are defined inside of this hydra, it will trigger another action (`helm-multi-swoop` in this case), and I don't know what status of the unfinished action.  

I wonder if there is an setting that could force the actions are applied out side of the hydra-buffer? This will solve the second problem, and I have no clue about the first one. 

-Yi

**Comment by abo-abo** [comment]
Just change red to blue.

**Comment by yitang** [comment]
it's awesome! I thought it just changes the colours of the text....

**Comment by abo-abo** [comment]
:)
