### ISSUE TITLE
How to activate a prefix keymap?

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/hydra#112]
This isn't strictly hydra specific.

I'm currently using this to call commands from active keymaps:

```emacs-lisp
(defun hydra-kbd (key-bind)
  "Call definition of `KEY-BIND' in current keymaps interactively."
  (let* ((k (or (and (vectorp key-bind) key-bind)
		(kbd key-bind)))
	 (c (hydra--get-origial-cmd k)))
    (cond
     ((commandp c) (call-interactively c))
     ((keymapp c) (message "execute %S" k) (execute-kbd-macro k)) ; Doesn't work
     (t (message "No command for %S" key-bind)))))

(defun hydra--get-origial-cmd (key-bind)
  "`KEY-BIND' can be a string as returned by `kbd' or a key
sequence vector."
  (catch 'break
    (mapc (lambda (m)
	    (let ((c (lookup-key m key-bind)))
	      (if (and c (not (numberp c)))
		  (throw 'break c))))
	  (current-active-maps))
    nil))
```

For example a head `("j" (hydra-kbd "C-n") :exit t)` calls `next-line` (usually).

I'm looking for a method to activate a prefix keymap. I'd like `("p" (hydra-kbd "C-c p") :exit t)` to make it so that <kbd>p</kbd> activates the normal projectile prefix map. Preferably in a way which keeps guide-keys working.

`(hydra--get-origial-cmd (kbd "C-c p"))` returns the prefix keymap. I just don't know what to do with it. Also `(execute-kbd-macro (kbd "C-c p"))` doesn't seem to activate the keymap.

Any ideas are welcome.

**Comment by abo-abo** [comment]
> I'm looking for a method to activate a prefix keymap

I've had [the same question](http://stackoverflow.com/questions/24914202/elisp-call-keymap-from-code) a year ago. The answer is Hydra. Hydras can implement callable prefix keymaps. I know of no other way to do this in a robust way. But maybe the linked answer is good enough for you.

**Comment by jhonnyseven** [comment]
This seems to work (from [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Event-Input-Misc.html#Event-Input-Misc)):
`(setq unread-command-events (listify-key-sequence (kbd "C-c p")))`

Have to test it a bit more.

It doesn't work with guide-keys, though.

**Comment by abo-abo** [comment]
> unread-command-events

I've head a reply from Stefan Monnier that this kind of thing will [never work reliably](http://emacs.stackexchange.com/questions/10423/set-transient-map-oddity-for-emacs-nw) in all cases and it's best to avoid it.

**Comment by jhonnyseven** [comment]
You mean this:

> The whole motivation behind set-transient-map was actually to avoid
> using t bindings (which are typically used to exit from some transient
> mode, so they just take the event and then want to "unread" it by
> putting it on unread-command-event but "unreading" can't be done
> reliably).

I'm not unreading, though. I'm inserting something new.

I got it to "work" with guide keys by replaying the key sequence with timers:

```emacs-lisp
(run-with-timer 0.1 nil
		    (lambda ()
		      (setq unread-command-events
			    (listify-key-sequence (kbd "C-c")))
		      (run-with-timer 0.1 nil
				      (lambda ()
					(setq unread-command-events
					      (listify-key-sequence (kbd "p")))
					(message "this %S" (this-single-command-keys))))))
```

Yeah, that's not going to end well..

**Comment by jhonnyseven** [comment]
That approach seems to work pretty reliably:

```emacs-lisp
(defun hydra--call-prefix-seq (key-seq)
  (interactive)
  (let ((f (lambda (f ks)
	     (setq unread-command-events (list (car ks)))
	     (when (cdr ks)
	       (run-with-timer 0.001 nil f f (cdr ks))))))
    (funcall f f (listify-key-sequence key-seq))))

(global-set-key (kbd "C-c C-p C-c C-p p") 'next-line)
(global-set-key (kbd "C-c i") (lambda () (interactive) (hydra--call-prefix-seq (kbd "C-c C-p C-c C-p "))))
```

**Comment by abo-abo** [comment]
Doesn't work for me: <kbd>C-c i</kbd> says `C-h is undefined`. That's unreliable in my book:)

**Comment by jhonnyseven** [comment]
Hehe :)
I only get problems if the delay is shorter, like `0.0001` or just `0`.

I wonder where the `C-h` is coming from... Does it work like that with clean setup?

**Comment by abo-abo** [comment]
Nice, it actually works with `emacs -Q`. But I don't think it's worth unless you can make it work reliably without the timer.

**Comment by abo-abo** [comment]
Closing this one, since it's not actually a Hydra issue.
But we can still discuss further if you want.
