### ISSUE TITLE
Feature Request: Update the hydra docstring programatically by heads

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#113]
Say I am using the ```%s`foo``` syntax in docstring of a hydra, and the hydra has some red heads that can update value of the variable `foo`. Ideally, I'd like to be able to have the ```*LV*``` buffer updated accordingly after such a head returns to the hydra.

I wouldn't mind if I will have to call a separate hydra function for each of these heads.

**Comment by zhaojiangbin** [comment]
Update the title.

**Comment by abo-abo** [comment]
A small example would be nice. I thought this was already working like this:

```elisp
(defhydra hydra-marked-items (dired-mode-map "")
  "
Number of marked items: %(length (dired-get-marked-files))
"
  ("m" dired-mark "mark"))
```

**Comment by zhaojiangbin** [comment]
Of course! My mind was fixated on using variable. Now it is turned into a function, the *LV* buffer is updated automatically after the red heads return. Works as advertised. :)

Closing the issue.
