### ISSUE TITLE
Feature request: Force quit the hydra from a red head

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#115]
Given the following hydra:
```elisp
(defhydra foo ()
  "foo"
  ("a" (lambda () (interactive) (unless (my-command) ???)) :exit nil)
  ("q" nil))
```
I hope there is a way to force quit or cancel the hydra from within head <kbd>a</kbd>. In other words, is there something I can replace the `???` with above that makes it as if <kbd>q</kbd> was pressed instead.

I have tried `hydra-keyboard-quit`. It does not work.

**Comment by abo-abo** [comment]
There was a feature for this, which I used for a day until choosing a different strategy.
No one else was using it so I removed it.

This one implements this feature in a different way.

**Comment by zhaojiangbin** [comment]
Wonderful. It works for my needs. Thanks.
