### ISSUE TITLE
Fontifying a key SEQUENCE in docstring (i.e. C-a C-a)

### ISSUE THREAD

**Issue by Abraxas228** [abo-abo/hydra#116]
Hi, as the title says, I'm using a sequence of keys in hydra and I want it colored in docstring
i.e. \_g\_ can be used to print a fontified  "g" but \_C-d C-o\_ doesn't seem to work.

(defhydra hydra-window-management (:color teal)
  "
....
[\_C-d C-o\_] delete all others
...

"
 ("C-d C-o" delete-other-windows nil :color blue)
...)

**Comment by abo-abo** [comment]
Should work now. You might prefer to write it like this:

```elisp
(defhydra hydra-window-management (:color teal
                                   :hint nil)
  "
....
[_C-d C-o_] delete all others
...

"
  ("C-d C-o" delete-other-windows))
```

- `:hint nil` frees you up from adding a `nil` hint to each head.
- `:color teal` implies `:blue` in all heads, you don't need to specify it extra (it doesn't hurt, but it's nicer to keep it short).

**Comment by Abraxas228** [comment]
Thanks for the quick response! Hydra rocks
