### ISSUE TITLE
[feature] Hooks !

### ISSUE THREAD

**Issue by csantosb** [abo-abo/hydra#12]
Great package. Really.

I am an avid user of guide-key, but the two packages conflict in trying to show helper keys at the same time. To fix the issue, I guess the easier would be to disable guide-key temporaly throught a hydra-pre-hook or similar. The idea might extend to other possible conflicts (and custom advanced features)

What do you think about pre and post hooks ?

**Comment by abo-abo** [comment]
I'm open to playing around other packages, although it could be that
`guide-key` will have to play around `hydra`, since `hydra` is in GNU
ELPA, while `guide-key` is not.

But let me first see the conflict in question. Just give me some
example code where `hydra` and `guide-key` are in conflict. Then I'll
think about how it's best to resolve it.

**Comment by csantosb** [comment]
That's right. I didn't think about GNU.
Let's say for example, taking 
    
    (setq guide-key/guide-key-sequence '("C-x"))
    (setq guide-key/recursive-key-sequence-flag t)

Will conflict with an hydra using a "C-x t" as base keybind.

**Comment by abo-abo** [comment]
You'll have to be a lot more specific. I'm getting no error at all.

**Comment by csantosb** [comment]
Here we go.

This is my guide-key config

    (require 'guide-key)
    (setq guide-key/guide-key-sequence '("C-o" "C-x" "C-h" "C-c"))
    (setq guide-key/highlight-command-regexp "rectangle\\|register")
    (guide-key-mode 1)
    (setq guide-key/idle-delay 1)
    (setq guide-key/popup-window-position 'bottom)
    (setq guide-key/polling-time 0.1)
    (setq guide-key/recursive-key-sequence-flag t)
    ;;
    (defun guide-key/my-hook-function-for-org-mode ()
      (guide-key/add-local-guide-key-sequence "C-c")
      ;; (guide-key/add-local-guide-key-sequence "C-c C-x")
      (guide-key/add-local-highlight-command-regexp "org-"))
    (add-hook 'org-mode-hook 'guide-key/my-hook-function-for-org-mode)

Then, for resizing windows I am using

    (global-unset-key (kbd "C-o"))
    (define-prefix-command 'window-map)
    (global-set-key (kbd "C-o") 'window-map)

An the hydra

    (defhydra hydra-win-resizing (window-map "r")
      "window resize"
      ("0" balance-windows "balance")
      ("'" balance-windows-area "balance area")
      ("n" minimize-window "minimize")
      ("m" maximize-window "maximize")
      ("s" shrink-window-if-larger-than-buffer "shrink")
      ("f" fit-window-to-buffer "fit"))

When I press "C-o r" guide-key appears (showing the full functions names), instead of the hydra menu.

Hope it is clear now.

**Comment by abo-abo** [comment]
Here's a solution that requires no changes to either `hydra` or `guide-key`:

```cl
(global-set-key
 (kbd "C-o r")
 (defhydra hydra-win-resizing ()
   "window resize"
   ("0" balance-windows "balance")
   ("'" balance-windows-area "balance area")
   ("n" minimize-window "minimize")
   ("m" maximize-window "maximize")
   ("s" shrink-window-if-larger-than-buffer "shrink")
   ("f" fit-window-to-buffer "fit")))
```

**Comment by csantosb** [comment]
Great, thanks! That fixes the issue for me. Just out of curiosity, is it possible to proceed similarly with local maps ?

**Comment by abo-abo** [comment]
Yes, of course. If you look at the macroexpansions in hydra-test.el, you'll see that there's almost no magit behind it.

**Comment by Stebalien** [comment]
I'd like to revive this issue (the original one about hooks). I'm trying to use hydra with [EXWM](https://github.com/ch11ng/exwm) (Emacs X Window Manager) but EXWM intercepts (almost) all input unless `exwm-input-line-mode-passthrough` is set. Therefore, I'd like to set this variable from within `hydra-pre-hook` and unset it from within `hydra-post-hook` so all input goes to emacs . I can currently do this by watching the `hydra-curr-map` variable but that's not a good solution.

**Comment by abo-abo** [comment]
@Stebalien Just advice `hydra-default-pre` and `hydra-keyboard-quit`. Open a new issue if you're still having problems.
