### ISSUE TITLE
Problem with the thin line separating LV window and echo area

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#123]
Re #122.

It happens when the hydra has two trailing newlines in docstring. The screenshot says it all:
![screen shot 2015-04-27 at 9 19 21 am](https://cloud.githubusercontent.com/assets/4935788/7352401/173b9048-ecc0-11e4-8807-ab5c6ec82547.png)

Also reproduced with solarized-light and the default theme.

The fix is to remove the extra trailing newline:
![screen shot 2015-04-27 at 9 24 31 am](https://cloud.githubusercontent.com/assets/4935788/7352404/1e1c7cd8-ecc0-11e4-821b-75fac0c213ec.png)

**Comment by zhaojiangbin** [comment]
Actually, this happens with any docstring that has two consecutive newlines:
```elisp
(defhydra foo ()
  "
  foo

  _a_ foo
"
  ("a" (message "a") "a")
  ("q" nil))
```

![screen shot 2015-04-27 at 11 59 49 am](https://cloud.githubusercontent.com/assets/4935788/7355157/f9f0ca34-ecd4-11e4-8408-357ec8e7c7e9.png)

**Comment by abo-abo** [comment]
Thanks!
