### ISSUE TITLE
When fast switching, hydra disables all the other custom keybindings. 

### ISSUE THREAD

**Issue by ReneFroger** [abo-abo/hydra#130]
Hello abo-abo. Sorry for bothering you again. Your help on packages is really appreciated. 

I use a keybinding init file where I store my custom keybindings. 
In the last time, I noticed that my custom keybindings are sometimes disabled. I couldn't find the culprit for this. Then I usually load my keybindings file again. 

But finally I found the culprit, the hydra!

This is my relevant configuration file
```
(key-chord-define evil-normal-state-map "qq" 'evil-quit) ;; Exit window

;; Hydra for in Helm
(defhydra helm-like-unite ()
  "vim movement"
  ("?" helm-help "help")
  ("q" keyboard-escape-quit "exit")
  ("<SPC>" helm-toggle-visible-mark "mark")
  ("d" helm-buffer-run-kill-persistent "Delete selection")
  ("a" helm-toggle-all-marks "(un)mark all")
  ;; not sure if there's a better way tkjukj this
  ("/" (lambda ()
         (interactive)
         (execute-kbd-macro [?\C-s]))
   "search")
  ("v" helm-execute-persistent-action)
  ("g" helm-beginning-of-buffer "top")
  ("h" helm-previous-source)
  ("l" helm-next-source)
  ("G" helm-end-of-buffer "bottom")
  ("j" helm-next-line "down")
  ("k" helm-previous-line "up")
  ("i" nil "cancel"))

(key-chord-define helm-map "jk" 'helm-like-unite/body)  
```

How to reproduce this? Load the configuration as described above. 

Ok, when you open `helm-for-files`, press `jk` and then Hydra will open. Press `q` twice really fast (like `qq`.  

Then the Helm Window will be closed down. 

Ok, then open helm window again, and reproduce the steps (press `jk` to open Hydra), and press `qq` again fast. 

Then my custom keybindings don't apply anymore. Makes me wonder why it occurs after the second time, and not on the first time. :frowning: 

Any suggestion to solve this?

**Comment by abo-abo** [comment]
> Any suggestion to solve this?

Not really sure what "this" means. Can you make a clear separation:

- initial state
- action
- desired behavior
- actual behavior

Especially the last two points.

**Comment by ReneFroger** [comment]
Thanks for your reply. I will try to be more specific.  

## Initial state

I use 4 packages: Helm, Evil, key-chord and Hydra.

This is my setup:

```
(key-chord-define evil-normal-state-map "qq" 'evil-quit) ;; Exit window

;; Hydra for in Helm
(defhydra helm-like-unite ()
  "vim movement"
  ("?" helm-help "help")
  ("q" keyboard-escape-quit "exit")
  ("<SPC>" helm-toggle-visible-mark "mark")
  ("d" helm-buffer-run-kill-persistent "Delete selection")
  ("a" helm-toggle-all-marks "(un)mark all")
  ;; not sure if there's a better way tkjukj this
  ("/" (lambda ()
         (interactive)
         (execute-kbd-macro [?\C-s]))
   "search")
  ("v" helm-execute-persistent-action)
  ("g" helm-beginning-of-buffer "top")
  ("h" helm-previous-source)
  ("l" helm-next-source)
  ("G" helm-end-of-buffer "bottom")
  ("j" helm-next-line "down")
  ("k" helm-previous-line "up")
  ("i" nil "cancel"))

(key-chord-define helm-map "jk" 'helm-like-unite/body)  
```

## Actions:
Load the configuration as described in the initial state.
When you call the function `helm-for-files`, press `jk` and then Hydra will open.
Press `q` twice fast (like `qq`).

Then the `helm-for-files` window will be closed.
Open `helm-for-files` again, press `jk` and press `qq` again, still in a fast way.


## Desired behaviour:
Hydra and `helm-for-files` will exit, but my custom keybindings, stored in dot-emacs configuration, will be still active.


## Actual behaviour:
When exiting Hydra and `helm-for-files`, it seems my custom keybindings are not active anymore. I have no idea why they do no apply anymore in my Emacs. I need to reload my dot-emacs configruation, in order to get my custom keybindings configuration reactived.

**Comment by abo-abo** [comment]
> keyboard-escape-quit

This could be the source of the bug. Can you try to use `nil` instead?  Also, show me the value of `input-method-function` after the bug happens.

**Comment by ReneFroger** [comment]
Thanks for your reply, it's appreciated. 
It seems that `keyboard-escape-quit` causes this bug. When I do `C-g`, I quit in the same way, but the custom keyboard keybindings will not quit. But I'm not sure why `keyboard-escape-quit` causes this bug.

After reproducing the bug, I got the value `nil` when `(message input-method-function)`.

Declaring the following solves my issue:

```
(defhydra helm-like-unite ()
  ("q" nil "exit")
  )
  ```

But I would like to use `keyboard-escape-quit`, it enables me to press `qq` only twice in order to quit Helm window and Hydra simultaneously. Any other suggestion?

**Comment by abo-abo** [comment]
> But I would like to use keyboard-escape-quit, it enables me to press qq only twice in order to quit Helm window and Hydra simultaneously. Any other suggestion?

You probably need `helm-keyboard-quit`. See [here](https://github.com/abo-abo/hydra/wiki/Helm-2).

**Comment by ReneFroger** [comment]
`helm-keyboard-quit` causes the same bug.

**Comment by abo-abo** [comment]
> helm-keyboard-quit causes the same bug in my case, when pressing qq fast.

I just tried this again, and there's no error when pressing <kbd>q</kbd> once: helm quits and all is well.

Just make sure that <kbd>q</kbd> is exiting:

    ("q" helm-keyboard-quit "exit" :exit t)

Other than that, hydra can't be blamed when calling `evil-quit` - a command designed for exiting Emacs, causes problems.
