### ISSUE TITLE
Hydra does not function correctly when name starts with hydra- prefix but does when renamed

### ISSUE THREAD

**Issue by otijhuis** [abo-abo/hydra#132]
I encountered a rather strange issue with a hydra and multiple cursors. When I name the hydra "hydra-mc" or "hydra-multiple-cursors" for example, the command is executed multiple times. In the following case pressing "n" the first time causes 2 extra selections, press "n" again it's 4 extra selections and so on.

(defhydra hydra-mc ()
  "Multiple cursors"
  ("n" mc/mark-next-like-this "next"))

(bind-key "C-c m" 'hydra-mc/body)

If I rename the hydra to "mc-hydra", the problem goes away and it works like expected.

(defhydra mc-hydra ()
  "Multiple cursors"
  ("n" mc/mark-next-like-this "next"))

(bind-key "C-c m" 'mc-hydra/body)

Any idea what could cause this? Other than the name of the hydra the rest is identical.

**Comment by otijhuis** [comment]
You can disregard this. For some reason the call to multiple-cursors ended up in the run-for-all command list of multiple-cursors. Deleted the entry from the file and now it works properly.

**Comment by abo-abo** [comment]
> For some reason the call to multiple-cursors ended up in the run-for-all command list of multiple-cursors. Deleted the entry from the file and now it works properly.

Yeah, that can happen sometimes. Glad the problem solved itself:)

**Comment by otijhuis** [comment]
Thought both hydra's would execute the same function but it was wrapped with a function based on the hyrda name. That explains why multiple-cursors sees them as different :)

Thanks for another great package. Switched to swiper and avy as well.
