### ISSUE TITLE
How to rebind keys of my hydra in different mode?

### ISSUE THREAD

**Issue by QiangF** [abo-abo/hydra#133]
Hello,
I really likes hydra, it is almost replaced evil-leader for me. One reason I still keep evil-leader is that I can bind keys according to mode, which I think is a more economic way of using the key bindings, as some functions only works in certain mode.
My question is if I creat a hydra and bind it to a key, eg. space key in evil normal state,  how do I reuse key binding in this hydra and rebind the key to other functions maybe with mode hooks? 
If that can be done easily, hydra will completely replace evil-leader and much better since it has key hint.
Thank you for this amazing package.

**Comment by abo-abo** [comment]
Generally, you should just do something like this:

```elisp
(require 'dired)
(define-key dired-mode-map (kbd "SPC") 'hydra-foo/body)
```

Here, `hydra-foo/body` is just a regular command, you can use it anywhere you can use a command.  Even call it with <kbd>M-x</kbd>.

**Comment by QiangF** [comment]
Thank you for your reply. I need to clarify a little bit. For example, I have defined a hydra named my-hydra and binded it to C-tab. In the hydra I have a key binding "pp" that shows preview for current latex environment, now "pp" is occupied by this function even not in latex mode. What if I want "pp" to go to previous error in python mode. Sure I can define another hydra, but then I need to assign another key for that hydra/body. I think it more efficient to reuse my-hydra.
(defhydra my-hydra ()
  ("q" nil "quit")
 "pp" preview-at-point "preview" :color blue))
(define-key my-mode-map (kbd "C-<tab>") 'my-hydra/body)

In evil leader I can set binding for mode, so I can set pp to be preview-at-point for latex mode and others in python mode.
(evil-leader/set-key-for-mode 'LaTeX/MPS-mode
  "pp" 'preview-at-point)

My question is can I do set key for mode with hydra? Or can I change the binding for pp with a mode hook?

**Comment by abo-abo** [comment]
I suggest to do something like this:

```elisp
(defhydra my-hydra-latex ()
  "latex"
  ("p" preview-at-point "preview" :color blue))
(define-key LaTeX-mode-map [C-tab] 'my-hydra-latex/body)

(defhydra my-hydra-python ()
  "python"
  ("p" previous-error "prev error"))
(define-key python-mode-map [C-tab] 'my-hydra-python/body)
```

The point is to have a separate hydra for each mode. You can still bind them to the same key in each mode, if you want.

**Comment by QiangF** [comment]
But I have other keys in my-hydra,  for example
  "cd" 'copy_work_path
  "hh" 'highlight-symbol-at-point
  "hn" 'highlight-symbol-next
  "hp" 'highlight-symbol-prev
  "hq" 'highlight-symbol-query-replace
  "hr" 'highlight-symbol-remove-all
  "im" 'imenu
  "kk" 'kill-this-buffer
In that way I have to defined these keys in all these hydras. Or I have to create many hydra and bind keys to each of them.

**Comment by abo-abo** [comment]
> Or I have to create many hydra and bind keys to each of them.

Yes, that's the approach. But you can use head inheritance to not repeat code:

```elisp
(defhydra my-hydra-base (:color blue)
  ("cd" copy_work_path)
  ("hh" highlight-symbol-at-point)
  ("hn" highlight-symbol-next)
  ("hp" highlight-symbol-prev)
  ("hq" highlight-symbol-query-replace)
  ("hr" highlight-symbol-remove-all)
  ("im" imenu)
  ("kk" kill-this-buffer))

(defhydra my-hydra-latex (:inherit (my-hydra-base/heads))
  "latex"
  ("p" preview-at-point "preview" :color blue))
(define-key LaTeX-mode-map [C-tab] 'my-hydra-latex/body)

(defhydra my-hydra-python (:inherit (my-hydra-base/heads))
  "python"
  ("p" previous-error "prev error"))
(define-key python-mode-map [C-tab] 'my-hydra-python/body)
```

Any hydra can inherit the heads of many previously defined hydras.

**Comment by abo-abo** [comment]
Also, you can separate the highlight like this:

```elisp
(defhydra my-hydra-highlight (:color blue)
  ("h" highlight-symbol-at-point)
  ("n" highlight-symbol-next)
  ("p" highlight-symbol-prev)
  ("q" highlight-symbol-query-replace)
  ("r" highlight-symbol-remove-all))

(defhydra my-hydra-base (:color blue)
  ("cd" copy_work_path)
  ("h" my-hydra-highlight/body)
  ("im" imenu)
  ("kk" kill-this-buffer))
```

**Comment by QiangF** [comment]
I didn't know the inheritance. Looks very good. I'll just redefined my key for my-hydra in the mode maps. 
Thank you!

**Comment by nettoyoussef** [comment]
> > Or I have to create many hydra and bind keys to each of them.
> 
> Yes, that's the approach. But you can use head inheritance to not repeat code:
> 
> ```emacs-lisp
> (defhydra my-hydra-base (:color blue)
>   ("cd" copy_work_path)
>   ("hh" highlight-symbol-at-point)
>   ("hn" highlight-symbol-next)
>   ("hp" highlight-symbol-prev)
>   ("hq" highlight-symbol-query-replace)
>   ("hr" highlight-symbol-remove-all)
>   ("im" imenu)
>   ("kk" kill-this-buffer))
> 
> (defhydra my-hydra-latex (:inherit (my-hydra-base/heads))
>   "latex"
>   ("p" preview-at-point "preview" :color blue))
> (define-key LaTeX-mode-map [C-tab] 'my-hydra-latex/body)
> 
> (defhydra my-hydra-python (:inherit (my-hydra-base/heads))
>   "python"
>   ("p" previous-error "prev error"))
> (define-key python-mode-map [C-tab] 'my-hydra-python/body)
> ```
> 
> Any hydra can inherit the heads of many previously defined hydras.

This really should be in the docs somewhere. I found no references to `:inherit` in the wiki or readmes. 
Kind of surprised this still works. The feature to rewrite the hydra in a context specific mode is perfect for programming modes' hydras (I use it for `R` and `Python`).

(ps: thanks for the awesome package!).
