### ISSUE TITLE
wishlist: pause and resume a hydra with one key

### ISSUE THREAD

**Issue by QiangF** [abo-abo/hydra#135]
Hello Sir,
Some times we want to do something else and then back to excecute commands in a hydra, enable foreign keys is not enough since it takes away some keys. 
What about assigning a pause key, when the pause key is pressed, the pink hydra is temperarily disabled and bring to the back ground, press the pause key again resumes the pink hydra. 
If in the middle another hydra is executed and not exited, press the pause key pushes that hydra to be the new hydra in the backgroud. 
This gives us some add hoc mode editing and can be very useful when a hydra is nested 2 or 3 levels in another hydra. 

One step further is in a hydra the pause key push that hydra to a hydra ring, outside the hydra pause key runs the top hydra on the ring, press it again cycles through the ring. 

I am thinking of creating a function, if it is called inside a hydra, it stores the hydra name in a variable, if it called outside a hydra, it runs the hydra/body. How do I get the name of the current hydra?
Thank you.

**Comment by abo-abo** [comment]
Thanks, added the feature. Just bind `hydra-pause-resume` to whatever you like.

**Comment by QiangF** [comment]
For future reference, there is a package here
https://github.com/jhonnyseven/hydra-stack
