### ISSUE TITLE
Programmatic Interface / Extract macro functionality

### ISSUE THREAD

**Issue by cqql** [abo-abo/hydra#137]
At the moment hydras are created exclusively through the `defhydra` macro. This makes it hard to generate them programmatically. I think, it would be nice to extract the magic from the macro and make it syntactic sugar for creating hydra "objects" instead, probably a plist or a struct. So the macro would produce something akin to

```emacs-lisp
(defvar my-hydra
  (make-hydra :description "" :heads (list ...))

;; For backwards compatibility
(defun my-hydra/body ()
  (hydra-run my-hydra))
```

So other packages could use `make-hydra` and `hydra-run` to create hydra on the fly. I originally had this idea, when I wanted to create a hydra with a head for every org file in my notes directory. I think, that more use cases would arise, once that possibility exists.

Would you be interested in that? I would try it out, unless you say, that it is a hopeless endeavour.

**Comment by abo-abo** [comment]
> This makes it hard to generate them programmatically

Not really. You can still use `eval` with macros.

> I wanted to create a hydra with a head for every org file in my notes directory

Here's an example of a dynamically defined hydra for this purpose:

```elisp
(global-set-key
 (kbd "C-c o")
 (lambda ()
   (interactive)
   (let ((file-list (file-expand-wildcards "~/Dropbox/org/*.org"))
         (c ?a))
     (call-interactively
      (eval `(defhydra hydra-file (:color blue)
               "open file"
               ,@(mapcar
                  (lambda (x)
                    (list (format "%c" (cl-incf c))
                          `(find-file ,x)
                          (file-name-nondirectory x)))
                  file-list)))))))
```

Be careful though: the hydra will auto-update if the file names in the directory change. This means that the key shortcuts will not be consistent. Which is kind of the reason why `defhydra` is static (although it doesn't have to be).

Here's what I use for jumping to org files: [plain-org-wiki](https://github.com/abo-abo/plain-org-wiki). Just a completion wrapper around a directory - plain and simple.

**Comment by cqql** [comment]
> Not really. You can still use eval with macros.

It is possible, though `eval`ing some macro is not my preferred way to interact with packages. I was just in the mood to program some elisp and thought, this would make a nice improvement :)

> Here's what I use for jumping to org files: plain-org-wiki. Just a completion wrapper around a directory - plain and simple.

Thanks for the suggestion, but I have since merged all my org files into one.

**Comment by abo-abo** [comment]
> It is possible, though evaling some macro is not my preferred way to interact with packages

Having one interface instead of two means there's 50% less debugging work. Also consider that `defun` is a macro, which you should checkout if you want to improve your Elisp; `defhydra` is not too different from a `defun`.
