### ISSUE TITLE
REQUEST: custom "secondary" color for commands (make it more visible)

### ISSUE THREAD

**Issue by zeltak** [abo-abo/hydra#138]
Hi again :)

I wondered if i could request (and if other people would find this useful) to add custom "secondary" color (which do nothing) to any command. the reason behind this is that it would make highlighting specific command (most used) possible which i find useful.
for example this little code:

("=" text-scale-increase :color red :viewcolor: green)
("-" text-scale-decrease :color blue :viewcolor: #eeefff )

an alternative could be to just add a hint color or maybe add faces to the hint section?

thx so much!

Z

**Comment by abo-abo** [comment]
You can customize the faces:

```elisp
(custom-set-faces
 '(hydra-face-red ((t (:foreground "green"))))
 '(hydra-face-blue ((t (:foreground "#eeefff")))))
```

I think it should be enough. There is value in keeping the style consistent everywhere.  In the end, you can modify the `hydra-test/hint` variable if you really want.

**Comment by zeltak** [comment]
Hi again

sorry i may have not explained myself correctly.  i mean that for each "blue" hydra i would have a differnet color. so one blue hydra would get a cyan hint and another a green hint etc.
is that possible?

thx again and sorry for the confusion

Z

**Comment by abo-abo** [comment]
This Code:

```elisp
(defhydra hydra-zoom (global-map "<f2>")
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))
```

macroexpands to this code:

```elisp
(set
   (defvar hydra-zoom/hint nil
     "Dynamic hint for hydra-zoom.")
   '(format
     #("zoom: [g]: in, [l]: out."
       7 8 (face hydra-face-red)
       16 17 (face hydra-face-red))))
```

So if you really want extra faces, you could do:

```elisp
(defhydra hydra-zoom (global-map "<f2>")
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))
(setq hydra-zoom/hint 
      #("zoom: [g]: in, [l]: out." 7 8 (face org-level-4) 16 17 (face org-level-5)))
```

I would prefer not to complicate the `defhydra` interface for something that can be solved easily with `setq`.
