### ISSUE TITLE
 Errors while package install with MELPA in GNU Emacs 24.5.1

### ISSUE THREAD

**Issue by vochor** [abo-abo/hydra#139]
There exist errors while "hydra-20150624.203" package install with MELPA

My emacs version is: "GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.4) of 2015-06-28 on trouble, modified by Debian"

```
Compiling file /home/vochor/.emacs.d/elpa/hydra-20150624.203/hydra-init.el at Tue Jul  7 08:39:51 2015
    ...
hydra-init.el:26:1:Error: Cannot open load file: no such file or directory, hydra-test
```

"hydra-test.el" doesn't exist in "/home/vochor/.emacs.d/elpa/hydra-20150624.203/hydra-examples.el" folder after the installation.

**Comment by abo-abo** [comment]
Thanks.
