### ISSUE TITLE
`hydra-disable` broken

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/hydra#14]
So, I think there's something wrong with the hydra-disable logic (or, at least, it's broken in my case).

`hydra-disable` never actually works for me because it does a `consp` on the `car` of `emulation-mode-map-alists`, which fails every time, because my `emulation-mode-map-alists` looks like this, so the check under the `while` fails:

```
(yas--direct-keymaps
 ((override-global-mode keymap
			#^[nil nil keymap
			       #^^[3 0 nil nil nil nil nil ..........
```

^^ Truncated for your sanity.

Anyway, all in all, the single-key escape doesn't work (for me).

Hydra in question:
```
(defhydra hydra-window ()
      "window"
      ("h" windmove-left "left")
      ("j" windmove-down "down")
      ("k" windmove-up "up")
      ("l" windmove-right "right")
      ("a" ace-window "ace-window")
      ("v" (lambda ()
             (interactive)
             (split-window-right)
             (windmove-right))
       "open vertically")
      ("x" (lambda ()
             (interactive)
             (split-window-below)
             (windmove-down))
       "open vertically")
      ("s" (lambda () (interactive) (ace-window 4)) "swap")
      ("d" (lambda () (interactive) (ace-window 16)) "delete")
      ("Q" bc/narrow-or-cycle-window "cycle")
      ("q" nil "cancel"))
```

Emacs version: 24.4.1

**Comment by abo-abo** [comment]
The way it's supposed to work, `set-temporary-overlay-map` modifies `emulation-mode-map-alists` so that Hydra stuff is ahead of `yas--direct-keymaps`. The whole hassle around `hydra-disable` is to
not touch other packages' stuff. A quick solution that disregards other packages would be:

```cl
(defun hydra-disable ()
  "Disable the current Hydra."
  (if (functionp hydra-last)
      (funcall hydra-last)
    (setq emulation-mode-map-alists nil)))
```

You can try this, if you want. I'll look into the problem further a bit later.

**Comment by abo-abo** [comment]
Btw, I just pushed a new version that supports <kbd>0</kbd>..<kbd>9</kbd> and <kbd>C-u</kbd>
in all hydras. Can you test if it works?

```cl
(global-set-key
 (kbd "C-z")
 (defhydra hydra-vi ()
   "vi"
   ("l" forward-char)
   ("h" backward-char)
   ("j" next-line)
   ("k" previous-line)))
```

<kbd>C-z 5j7l</kbd> should work.

**Comment by bcarrell** [comment]
The Hydra I posted above is broken in the latest push.

`Wrong type argument: commandp, (function (lambda nil (interactive) (split-window-right) (windmove-right)))`

Your example, however, works fine.  `C-z 5j7l` etc work.

**Comment by bcarrell** [comment]
All of the lambdas in my above Hydra are broken in latest push. ^^

**Comment by abo-abo** [comment]
Seems to be related to Emacs version.
Could you `toggle-debug-on-error` and show the backtrace?

**Comment by bcarrell** [comment]
Yep, I'll get to it in an hour or two!

**Comment by abo-abo** [comment]
Works on `24.4.51.1`, which is the tip of `emacs-24` branch in git. Now building 24.4 from the website.

**Comment by abo-abo** [comment]
Works on `24.4.1` with both <kbd>x</kbd> and <kbd>v</kbd> working properly.

**Comment by bcarrell** [comment]
Odd, it works fine now for me after restarting Emacs.  Not sure what I did to cause the error previously; sorry for making you dig!

**Comment by abo-abo** [comment]
Alright, at least I have `24.4.1` installed now:). Test drive some more and close the issue if nothing happens.

**Comment by abo-abo** [comment]
Wow, just got it. There are **three** methods of disabling `hydra-set-transient-map` depending
on Emacs version, none of them compatible. Adding the third one, which should work for `24.4.1`.

**Comment by bcarrell** [comment]
hah, that's a tricky one.

**Comment by bcarrell** [comment]
6cb221a fixed the `hydra-disable` issue; thanks!
