### ISSUE TITLE
Feature request: add an option to format default hints vertically or in columns

### ISSUE THREAD

**Issue by Fuco1** [abo-abo/hydra#140]
When I have a hydra

```elisp
(defhydra hydra (:color blue)
  "A hydra"
  ("a" a "do a")
  ("b" b "do b" )
  ("c" c "do c"))
```

The hints for a,b,c get formatted one after the other.

I would like a toggle (like `:color blue` there, something like `:vertical t`) to format them one under another.

I don't want to create elaborate interfaces with the docstring `_foo_` feature, just to have the hints vertically as it's much more pleasant to read...

Bonus points would be something like `:columns n`, where the hints would get formatted in `n` columns, `nil` or `t` representing infinity (= current behaviour)

**Comment by abo-abo** [comment]
> Bonus points would be something like :columns n, where the hints would get formatted in n columns

Thanks, I'll think about making the interface better.  I've had something of the sort (i.e. docstrings in a matrix) working, it only needs a bit more work to avoid having to use `defhydradio` macro:

```elisp
(require 'hydra)
(defhydradio hydra-tng ()
  (picard "_p_ Captain Jean Luc Picard:")
  (riker "_r_ Commander William Riker:")
  (data "_d_ Lieutenant Commander Data:")
  (worf "_w_ Worf:")
  (la-forge "_f_ Geordi La Forge:")
  (troi "_t_ Deanna Troi:")
  (dr-crusher "_c_ Doctor Beverly Crusher:")
  (phaser "_h_ Set phasers to " [stun kill]))

(defhydra hydra-tng (:foreign-keys run :hint nil)
  (concat (hydra--table hydra-tng/names 5 3
                        '("  % -30s %% -3`%s"
                          "%s %%`%s"))
          "\n\n")
  ("p" (hydra-tng/picard))
  ("r" (hydra-tng/riker))
  ("d" (hydra-tng/data))
  ("w" (hydra-tng/worf))
  ("f" (hydra-tng/la-forge))
  ("t" (hydra-tng/troi))
  ("c" (hydra-tng/dr-crusher))
  ("h" (hydra-tng/phaser))
  ("b" beam-down "beam down" :exit t)
  ("o" (hydra-reset-radios hydra-tng/names) "reset")
  ("q" nil "cancel"))

(defun beam-down ()
  (interactive)
  (message
   "Beaming down: %s."
   (mapconcat
    #'identity
    (delq nil
          (mapcar
           (lambda (p) (when (symbol-value p)
                    (substring (symbol-name p) 10)))
           '(hydra-tng/picard
             hydra-tng/riker
             hydra-tng/data
             hydra-tng/worf
             hydra-tng/la-forge
             hydra-tng/troi
             hydra-tng/dr-crusher)))
    ", and ")))

(global-set-key (kbd "C-c C-,") 'hydra-tng/body)
```

**Comment by abo-abo** [comment]
Please give it a try, there's an example in the commit as well.

**Comment by Fuco1** [comment]
Thanks, this looks exactly as what I had in mind.  I'll play with it when I get home!

**Comment by Fuco1** [comment]
One small thing, maybe the `:columns` thing should be renamed to `:hint-columns` or something (I don't know your terminology) as `:columns` is rather general and might conflict with something else later? Just a thought.
