### ISSUE TITLE
Bugs occur when I compile Hydra to .elc-package. 

### ISSUE THREAD

**Issue by ReneFroger** [abo-abo/hydra#141]
I have the [following Hydra setup](http://pastebin.com/9PqZXz43) in my configuration. Everything worked well. So far, so good. 

When I compile it to .elc file, and start Emacs from the `.elc` file with the compiled Hydra, I get the following error.

`helm-like-unite/body: Symbol's function definition is void: hydra-default-pre` 

I found it weird that this issue will occur when the `.el` file gets compiled with `byte-compile-file`. If not compiled, then this error will never arise.

**Comment by abo-abo** [comment]
> helm-like-unite/body: Symbol's function definition is void: hydra-default-pre

Looks like you're missing `(require 'hydra)` somewhere.

**Comment by ReneFroger** [comment]
I use `package.el`, so requiring packages are not need anymore. But thanks for your reply, will set it somewhere.
