### ISSUE TITLE
'[' and ']' are not recognized inside _a_ docstring format

### ISSUE THREAD

**Issue by yangchenyun** [abo-abo/hydra#143]
<img width="1440" alt="screen shot 2015-07-17 at 9 59 13 am" src="https://cloud.githubusercontent.com/assets/1043403/8752666/8d85a5d8-2c6a-11e5-89c1-3ca02aa77d8b.png">

**Comment by abo-abo** [comment]
Thanks.

**Comment by yangchenyun** [comment]
This the best emacs extension ever, especially for people like me trying to master modes one by one :)
