### ISSUE TITLE
Hint buffer is not displayed when keybinding passed as argument to defhydra

### ISSUE THREAD

**Issue by jaycotton** [abo-abo/hydra#145]
Hello,

I am enjoying your blog and all your creative emacs packages.

When a keybinding is passed as the first two arguments to defhydra (ie., BODY-MAP and BODY-KEY), the hint buffer does not get displayed until after the head has been executed (ie., after it is no longer useful).

If instead I bind hydra-name/body, *after* the hydra has been defined, then the hint buffer is displayed as expected (before the head is chosen).

**Comment by abo-abo** [comment]
> the hint buffer does not get displayed until after the head has been executed (ie., after it is no longer useful).

This is the planned behavior. The `defhydra` macro will produce a red hydra by default, which means that after you call one head, even not through `hydra-test/body`, the hydra will remain active and the docstring is very relevant.

Both calling styles have their merit:

- the `(global-set-key "C-c" 'hydra/test/body)` approach is a more descriptive, but denies you from binding anything else to "C-c" prefix, besides that one hydra.

- the body-map/body-key approach is less descriptive (no less than usual Emacs bindings though), but you get to keep your "C-c" prefix for other bindings and other hydras.

**Comment by jaycotton** [comment]
Thanks for explaining. And again, great work.
