### ISSUE TITLE
:columns option creates trailing whitespace

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/hydra#146]
Thanks for this option, I've been missing it!

Currently there's trailing whitespace in the hint, which is not so pretty when `show-trailing-whitespace` is set.

**Comment by abo-abo** [comment]
Thanks. How to did you see the trailing whitespace in the first place? Did you use:

    (setq-default show-trailing-whitespace t)

In that case, there's bad whitespace showing up in other places, like the buffers list.
