### ISSUE TITLE
How to keep Hydra closed when an action is executed?

### ISSUE THREAD

**Issue by ReneFroger** [abo-abo/hydra#148]
For example, this code snippet 

    (defhydra foobar (:color red :hint nil)
     "    _f8_: Helm For Files   "
    ("<f8>" helm-for-files)
    ))

    (define-key evil-normal-state-map (kbd "<tab>") #'foobar/body) 

When I call Hydra `foobar` with the `TAB`, then press `F8`, and `Helm-for-files`will be popping up. Everything worked fine, then I give my input in the helm window. Helm will open the selected file. Then Helm closes down, but then Hydra will pop up. How could I prevent Hydra to pop up again? I couldn't find anything about this in the documentation and the examples.

Thanks in advance for your reply, your contribution to Emacs communnity is really appreciated.

**Comment by abo-abo** [comment]
Just change the color to blue. Red one is for multiply repeating actions.

**Comment by ReneFroger** [comment]
Sorry, it was even clearly mentioned in your documentation. My first impression after quickscanning the documentation, was that the colors are just for the looks. 

Sorry to bother you, and thanks!
