### ISSUE TITLE
Hydras don't like commands that prompt you to enter some numbers (like `goto-line`)

### ISSUE THREAD

**Issue by nandryshak** [abo-abo/hydra#15]
Take a Hydra like this:

    (defhydra hydra-goto-line (global-map "M-g")
      "goto"
      ("g" goto-line "line"))
    (global-set-key (kbd "M-g") 'hydra-goto-line/body)

Invoking it by pressing `M-g g` will give you the prompt `Goto line:`. Numbers won't appear, instead, they are interpreted as numerical arguments. Typing `1 0 x` will give you ten x's. But after you type letters, you can kill the line and type numbers and they are inputted just fine.

Assigning colors to the head doesn't change the behavior.

**Comment by abo-abo** [comment]
I think you need:

```cl
(defhydra hydra-goto-line (global-map "M-g")
  "goto"
  ("g" goto-line "line" :color blue))
```

and don't bind `hydra-goto-line/body` to <kbd>M-g</kbd>, or you'll lose <kbd>M-g</kbd> as a prefix.

**Comment by abo-abo** [comment]
See the update in the `next` branch. I will merge it to `master` later, because some other code might need changing because of this update.
With this update, this code will work:

```cl
(defhydra hydra-test (global-map "C-,") ; Any undefined key
  ("g" goto-line "goto-line"))
```

**Comment by abo-abo** [comment]
The update is now live in `master`. If it's solves your problem, close the issue.

**Comment by abo-abo** [comment]
The problem appears to be solved, closing.
