### ISSUE TITLE
Hydra for expand-region package. It expands it but doesn't contract it.

### ISSUE THREAD

**Issue by rafaelgp** [abo-abo/hydra#150]
Hello,

I've create a very simple hydra to use with the fantastic package [expand-region] (https://github.com/magnars/expand-region.el)

Here it is:
```
(defhydra hydra-expand (:hint nil :color red :columns 1 :pre (er/expand-region 1))
("c" er/contract-region "Contract")
("e" er/expand-region "Expand"))
```
The idea is to expand the region as soon as I enter in a red hydra and then expand or contract the selection.
The problem is that it doesn't contract the selection!

It works by using the original expand-region keybinding (C-+) but not using the hydra key (c)

Any idea what's wrong in my hydra?

Many thanks

**Comment by abo-abo** [comment]
No need to use `:pre`. This works fine for me:

```elisp
(defhydra hydra-expand (global-map "C-c"
                        :color red :columns 1)
  "expand-region"
  ("c" er/contract-region "Contract" :bind nil)
  ("e" er/expand-region "Expand"))
```

The above will also bind the expansion to <kbd>C-c e</kbd> (but not <kbd>C-c c</kbd>).

**Comment by abo-abo** [comment]
Also, `:color red` is implicit. I usually prefer to type less.

**Comment by rafaelgp** [comment]
Let's take this sentence as example:
```
(global-map "C-c" :color |red :columns 1)
```
Cursor is just before the word 'red'

By using your code, if I want to select what it's inside the parenthesis, I need to type C-c eee. Correct?
What I'd like to achieve is to save one keystroke and expand the selection once when I enter the hydra. To me it makes sense to expand the selection when I enter the hydra because I always going to do this at least once.

**Comment by abo-abo** [comment]
After <kbd>C-c e</kbd> I'm getting:

    (global-map "C-c" :color |red~ :columns 1)

Here, `~` represents the mark. Isn't this what you want?

**Comment by rafaelgp** [comment]
I'd like to get that selection after typing just `C-c`
If you use the code I included in my question (using `:pre` you'll see what I mean. All works OK except contracting the selection.

**Comment by abo-abo** [comment]
> I'd like to get that selection after typing just C-c

To get something done right after <kbd>C-c</kbd> you'd have to bind a function to <kbd>C-c</kbd>.  This is highly not recommended, since <kbd>C-c</kbd> is a very common Emacs prefix.

> If you use the code I included in my question (using :pre you'll see what I mean. All works OK except contracting the selection.

The code that you included doesn't bind any bindings. If you've bound `hydra-expand/body` to something, and you want it to do something, use `:body-pre` instead of `:pre`:

- `:pre` is appended to *each* head. 
- `:body-pre` is appended only to the body.

**Comment by rafaelgp** [comment]
Sorry about that. Here is the complete code:

```
    (define-key evil-visual-state-map (kbd "SPC") 'hydra-all/body)

    (defhydra hydra-all (:hint nil :color blue :columns 1)
      "Hydras"
      ("e" hydra-expand/body "Expand"))

    (defhydra hydra-expand (:hint nil :columns 1)
      ("c" er/contract-region "Contract")
      ("e" er/expand-region "Expand"))
```
The following code does exactly what I wanted (by using ```:body-pre```):

```
    (defhydra hydra-expand (:hint nil :columns 1 :body-pre (er/expand-region 1))
      ("c" er/contract-region "Contract")
      ("e" er/expand-region "Expand"))
```

**Comment by abo-abo** [comment]
I'm glad it works. It's usually best to post the full code: much faster to see where the problem is.
