### ISSUE TITLE
hydra bookmarking tool: is this the smartest way to do it? :)

### ISSUE THREAD

**Issue by zeltak** [abo-abo/hydra#152]
Hi again. im trying to use hydra as a quick bookmarking tool for dired/sunrise commander.
i have this setup which work great!

```
(defun chd/dired-Dowloads ()
  "  "
  (interactive)
  (find-file "~/Downloads/")     
)

(global-set-key
   (kbd "")
(defhydra hydra-sr-chd  (:color blue :hint nil :columns 4)
""
("d"  chd/dired-Dowloads "Downloads" )
))
```

my question is i define always a function (chdir) and then add that to the hydra letter (ie 'd'). can hydra take a command like the find-file so i can skip adding a function per command
so the hydra will look like this

```
("d"  (find-file "~/Downloads/")     "Downloads" )
``` 
thx!

z

**Comment by abo-abo** [comment]
It's not clear what you're asking. Please show me the full code, and specify more clearly what you want.

**Comment by zeltak** [comment]
Hi again and thx for the answer. sorry for not being clearer. i guess my question is much simpler. in a hydra when i define a "head" ie 
```
("d"  COMMAND    "Downloads" )
```
can the COMMAND be written inside that line like this
find file FILEX 
ie 
```
("d"  (find-file "~/Downloads/")     "Downloads" )
```
or does hydra only work with pre-defined functions so i have to first define the command/function like this:

```
(defun chd/dired-Dowloads ()
  "  "
  (interactive)
  (find-file "~/Downloads/")     
)
```

and then adjust the code like this (which works well)

```
("d"  chd/dired-Dowloads   "Downloads" )
```

i just thought it would be quicker to not build a function for every change dir command i want to launch from hydra and just write the change dir (find file command) inside the hydra head line.

I hope i explained it better this time but im aware that since i cant code and dont know the terminology maybe i didnt :)

in any case here is the full code i currently use 

```
**** change dirs
#+BEGIN_SRC emacs-lisp :results none
(defun chd/dired-Dowloads ()
  "  "
  (interactive)
  (find-file "~/Downloads/")     
)
#+END_SRC

**** hydra chd
#+BEGIN_SRC emacs-lisp :results none
(global-set-key
   (kbd "")
(defhydra hydra-sr-chd  (:color blue :hint nil :columns 4)

"
"
("a" nil )
("b"  nil  )
("c"  nil )
("d"  chd/dired-Dowloads "Downloads" )
("e"  nil )
("f"  nil )
("g"  nil )
("h"  nil )
("i"  nil )
("j"  nil )
("k"  nil )
("l"  nil )
("m"  nil )
("n"  nil )
("o"  nil )
("p"  nil )
("r"  nil )
("s"  nil )
("t"  nil )
("u"  nil )
("v"  nil)
("w"  nil )
("x"  nil )
("y"  nil )
("z"  nil )
("q"  nil )

))

#+END_SRC
```

**Comment by abo-abo** [comment]
> ("d" (find-file "~/Downloads/") "Downloads" )

Yes, this is valid: there's no need for an auxiliary function.

**Comment by zeltak** [comment]
awesome:) for some reason i thought it wasnt possible, should have checked :)

LOVE! hydra :)

best

Z
