### ISSUE TITLE
open hydra definition in source for editing

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/hydra#153]
use case:
I would consider it to be helpfull to be able to jump from a hydra menu to it's definition in order to adapt it quickly. (using an extra key or keybinding)
difficulty:
Because defhydra is an elisp macro find-function only navigates to the source file but not to the definition of the defhydra application.
solutions:
What solutions (excluding fulltext search) would be possible?

**Comment by abo-abo** [comment]
Should work now with this new defadvice. Please check.

**Comment by drorbemet** [comment]
Hi, thanks for responding to my feature request. I am unsure for which use case you actually prepared. Unfortunately I am still lacking the skills to debug this one with ease. I have to learn about defadvice first though I think. Therefore in order to keep in touch with you about this thing I just paste my test cases with an example hydra here (should I use a gist for that?):
;;; Code:
;; an example hydra
(defhydra hydra-example (:hint nil)
  "
example
-----------
_s_: example command
"
  ("s" sp-split-sexp)
  ("." (find-hydra "hydra-example") "edit this hydra - How do I make it accessible in the hydra menu without disturbing the menue itself? Could the key for this be assignd in the awesome-plist?"))
(global-set-key (kbd "C-s-4") 'hydra-example/body)

;; that's what I tried untill now.
;; this doesn't work:
;; evaluating
(describe-function 'hydra-example/body)
;; anc clicking: The body can be accessed via `hydra-example/body'.

;; and these don't work
(find-function 'hydra-example/body)     ;; returns with Don't know where `hydra-example/body' is defined
(find-function 'hydra-example)     ;; doesn't return ... it seems to dissapear into some infinit loop

;; these return argument related exeptions because I don't know hwo to pass TYPE and LIBRARY in (find-function-search-for-symbol SYMBOL TYPE LIBRARY)
(find-function-search-for-symbol 'hydra-example/body 'defhydra "hydra") ;; Wrong type argument: stringp, nil

(find-function-search-for-symbol 'hydra-example/body)
(find-function-search-for-symbol 'hydra-example)

**Comment by abo-abo** [comment]
> (find-function 'hydra-example/body)

This one is supposed to work. Just put your definition in say `init.el` and restart Emacs.
Evaluating the above code in scratch should bring you to the definition.

Note that restarting Emacs is the key, the location info doesn't work if you define the hydra on the fly.

**Comment by drorbemet** [comment]
Oh ok thanks, now I got it and (find-function 'hydra-example/body) working.
I have two more questions regarding accessibility of the source of defhydra definitions:

a) Would this be desirable? - Access in the hydra menu buffer via key assignd in the awesome-plist.
It would be a second bound key for editing in addition to a specific exit key.

b) Would this be desirable? - Access in the help buffer doesn't work.
1. (describe-function 'hydra-example/body)
2. and then clicking: The body can be accessed via `hydra-example/body'.

**Comment by abo-abo** [comment]
> I have two more questions regarding accessibility of the source of defhydra definitions:
> 
> a) Would the following be desirable? - Access in the hydra menu buffer via key assignd in the awesome-plist.
> It would be a second bound key for editing in addition to a specific exit key.

This you can customize by yourself:

```elisp
(define-key hydra-base-map
    (kbd "C-M-m")
  (lambda ()
    (interactive)
    (find-function hydra-curr-body-fn)))
```

This customization needs to be done before any hydras are defined, so right after `(require 'hydra)`.

> b) Would the following be desirable? - Access in the help buffer doesn't work.
> 1. (describe-function 'hydra-example/body)
> 2. and then clicking: The body can be accessed via `hydra-example/body'.

I'll see if it's possible to do something about this. There are actually two links in `*Help*` buffer.
The top one, which refers to the file will actually take you to `defhydra`. The bottom one doesn't work currently.

**Comment by drorbemet** [comment]
Oh, right in *Help* the link at the top works. Great!
