### ISSUE TITLE
don't show square brackets if only 1 option

### ISSUE THREAD

**Issue by listx** [abo-abo/hydra#154]
Here's what a sample hydra message looks like:

```
vim movement: [h]: parent, [j]: down, [k]: up, [l RET]: open, [<SPC>]: exit hyrda, [TAB]: action, [g]: top, [G]: bottom, [q]: exit.
```

but I want it to look like this:

```
vim movement: h: parent, j: down, k: up, [l RET]: open, <SPC>: exit hyrda, TAB: action, g: top, G: bottom, q exit.
```

. I.e., I don't want the square brackets to show up if there is only 1 possible option (notice how `[l RET]` stays the same because it has two possibilities).

Going further, how about this (all colons removed)?

```
vim movement: h parent, j down, k up, [l RET] open, <SPC> exit hyrda, TAB action, g top, G bottom, q exit.
```

**Comment by abo-abo** [comment]
Customize `hydra-head-format` variable:

    (setq hydra-head-format "%s ")

**Comment by listx** [comment]
Hm, this is close enough to what I wanted. Thank you very much!
