### ISSUE TITLE
Accept #'function notation in hydra heads

### ISSUE THREAD

**Issue by tsdh** [abo-abo/hydra#156]
I just started using hydras, and like all of your packages, it rocks!

The first trap I've fallen into is that I defined my heads as `("key" #'command "description")` which didn't work.  The `command` must be given as a plain, unquoted symbol.  It would be nice if the function syntax was accepted, too, simply because then completion will actually complete function names.  The way it is, it just completes variable names.  (That's especially painful if you use `company-mode` and get a popup with tons of completions which are all not usable.)

I'd even go that far and require the function syntax for functions.  That would allow to have a head `("key" completion-at-point-function "Complete at point")` which actually uses a variable which is bound to a function, and then the buffer-local binding of the variable in the buffer from where the hydra is invoked would be called.  Well, I guess that ship has sailed already because of backwards-compatibility.

**Comment by abo-abo** [comment]
> The first trap I've fallen into is that I defined my heads as ("key" #'command "description") which didn't work. The command must be given as a plain, unquoted symbol. It would be nice if the function syntax was accepted, too, simply because then completion will actually complete function names. The way it is, it just completes variable names. (That's especially painful if you use company-mode and get a popup with tons of completions which are all not usable.)

I can add this, just to have it. But it looks nicer without it. And I have no problem completing function names with `company-mode`: I get functions and variables at once, always.

Here's my company [setup](https://github.com/abo-abo/oremacs/blob/github/oleh/modes/ora-company.el).  It looks like `company-elisp-detect-function-context` might do it.

**Comment by tsdh** [comment]
Ah, indeed, `company-elisp-detect-function-context` is the culprit but in general I like that behavior very much.  And to my eyes, `#'command` does actually look nice but I'm famous for my bad taste so, well,...

**Comment by abo-abo** [comment]
Please test. It seems to work for a simple case.

**Comment by tsdh** [comment]
Yes, works for me.  Thanks!
