### ISSUE TITLE
In the defhydra, how to define an function with modifier on?

### ISSUE THREAD

**Issue by yangchenyun** [abo-abo/hydra#157]
Hi, 
This is no specifically related with hydra, but how could I define a function which will invokes an emacs command (defun + interactive) with a modifier(C-u) on?

**Comment by abo-abo** [comment]
Generally, like this:

```elisp
(defhydra hydra-zoom (global-map "<f2>")
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out")
  ("G" (progn
         (setq current-prefix-arg '(4))
         (call-interactively 'text-scale-increase)) "in with C-u"))
```

But if you know how the function will interpret the prefix arg, you can simplify:

```elisp
(defhydra hydra-zoom (global-map "<f2>")
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out")
  ("G" (text-scale-increase 4) "in with C-u"))
```

**Comment by yangchenyun** [comment]
Thanks! The first example is very straight forward; the second example seems an interactive `defun` such as `text-scale-increate` is a high-order function too?

Both the example you given and the [emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Command-Arguments.html) uses the value `4` as the numeric value for `C-u`. Why is it `4` instead of other value, is there some doc for this?

**Comment by abo-abo** [comment]
> Why is it 4 instead of other value, is there some doc for this?

There should be, since to insert `aaaa` you can press <kbd>C-u a</kbd> in the standard Emacs.  Pressing <kbd>C-u</kbd> further multiplies, so <kbd>C-u C-u a</kbd> will insert 16 chars.

The doc in the Emacs manual under the index of `universal-argument`:

       Instead of typing ‘M-1’, ‘M-2’, and so on, another way to specify a
    numeric argument is to type ‘C-u’ (‘universal-argument’) followed by
    some digits, or (for a negative argument) a minus sign followed by
    digits.  A minus sign without digits normally means −1.
    
       ‘C-u’ alone has the special meaning of “four times”: it multiplies
    the argument for the next command by four.  ‘C-u C-u’ multiplies it by
    sixteen.  Thus, ‘C-u C-u C-f’ moves forward sixteen characters.  Other
    useful combinations are ‘C-u C-n’, ‘C-u C-u C-n’ (move down a good
    fraction of a screen), ‘C-u C-u C-o’ (make “a lot” of blank lines), and
    ‘C-u C-k’ (kill four lines).

**Comment by yangchenyun** [comment]
Found this section. Wow, I didn't know this standalone behavior of `C-u`, thanks for that.
