### ISSUE TITLE
proper way to install hydra using use-package?

### ISSUE THREAD

**Issue by sooheon** [abo-abo/hydra#159]
My current hydra config looks something like this:
```
(defun sooheon/init-hydra ()
  (use-package hydra
    :ensure
    :config
    ;;;various hydras))
```
Hydras I have defined in there work, but calling `hydra-ivy/body` in swiper gives me `Package 'hydra' not installed. Install? (y or n)`

Of course this only happens the first time, but I'm curious why, and I'd rather that my config not be so stateful.

**Comment by abo-abo** [comment]
When the swiper package is being installed (more importantly, compiled), this check is performed:

    (or (featurep 'hydra) (package-installed-p 'hydra))

If this evaluates to false, you get the warning that you mention.  Basically, you need to have hydra required or at least installed at the moment when swiper is installed.
In your situation, when you already have both packages, simply recompile `ivy-hydra.el`.

**Comment by sooheon** [comment]
Ok. `require`ing hydra in the `:init` of `swiper`'s use-package seems to solve the issue. Thanks.
