### ISSUE TITLE
Change cursor color

### ISSUE THREAD

**Issue by atykhonov** [abo-abo/hydra#16]
Hello! Thank you for the hydra!

I want to change cursor color if any head is active. What is the most simple and effective way to call the function which will change the color?

**Comment by abo-abo** [comment]
I'll think about adding -before and -after hooks for the Hydra body.
Meanwhile, something like this is possible:

```cl
(global-set-key
 (kbd "C-z")
 (defhydra hydra-vi ()
   "vi"
   ("l" (lambda (arg)
          (interactive "p")
          (set-cursor-color "#40e0d0")
          (forward-char arg)))
   ("h" (lambda (arg)
          (interactive "p")
          (set-cursor-color "#40e0d0")
          (backward-char arg)))
   ("j" (lambda (arg)
          (interactive "p")
          (set-cursor-color "#40e0d0")
          (next-line arg)))
   ("k" (lambda (arg)
          (interactive "p")
          (set-cursor-color "#40e0d0")
          (previous-line arg)))
   ("q" (lambda ()
          (interactive)
          (set-cursor-color "#ffffff"))
        :color blue)))
```

**Comment by atykhonov** [comment]
Thank you! That's definitely allow me to change cursor color but it would be great to be able to change the color for all `defhydra`. Is that possible to implement?

**Comment by abo-abo** [comment]
It is possible, but I'm not sure it's the way to go.
`defhydra` is a macro similar to `defun`. In fact, it generates a bunch of `defun`s.
There's probably a reason why we're not allowed to add some static code to each `defun` automatically.

This code looks better to me:

```cl
(global-set-key
 (kbd "C-z")
 (defhydra hydra-vi
     (:pre
      (set-cursor-color "#40e0d0")
      :post
      (set-cursor-color "#ffffff"))
   "vi"
   ("l" forward-char)
   ("h" backward-char)
   ("j" next-line)
   ("k" previous-line)
   ("q" nil)))
```

than this code:

```cl
(defvar hydra-default-pre '(set-cursor-color "#40e0d0"))
(defvar hydra-default-post '(set-cursor-color "#ffffff"))

(global-set-key
 (kbd "C-z")
 (defhydra hydra-vi ()
   "vi"
   ("l" forward-char)
   ("h" backward-char)
   ("j" next-line)
   ("k" previous-line)
   ("q" nil)))
```

Just think how much of a hassle it would be to juggle
`hydra-default-pre` in case it happens that you don't want it for just
one or two Hydras.

However, I think this could be reasonable:

```cl
(defun hydra-my-pre ()
  (set-cursor-color "#40e0d0"))

(defun hydra-my-post ()
  (set-cursor-color "#ffffff"))

(global-set-key
 (kbd "C-z")
 (defhydra hydra-vi
     (:pre hydra-my-pre
      :post hydra-my-post)
   "vi"
   ("l" forward-char)
   ("h" backward-char)
   ("j" next-line)
   ("k" previous-line)
   ("q" nil)))
```

Here, you define `hydra-default-pre` - an arbitrary function with an arbitrary name,
and `defhydra` will call it. Would this be OK? Although it's actually longer for this simple case.

**Comment by atykhonov** [comment]
```
(defun hydra-my-pre ()
  (set-cursor-color "#40e0d0"))

(defun hydra-my-post ()
  (set-cursor-color "#ffffff"))

(global-set-key
 (kbd "C-z")
 (defhydra hydra-vi
     (:pre hydra-my-pre
      :post hydra-my-post)
   "vi"
   ("l" forward-char)
   ("h" backward-char)
   ("j" next-line)
   ("k" previous-line)
   ("q" nil)))
```

That (quite obvious) solution is pretty good for me! Thank you very much for such detailed explanation!

**Comment by abo-abo** [comment]
Alright, I'll add a feature to give function names as `:pre` and `:post` soon.
