### ISSUE TITLE
Ruby-style string interpolation for head-hint (and/or forms evaluating to string, maybe)

### ISSUE THREAD

**Issue by Antoine-Patel** [abo-abo/hydra#160]
I'm trying to use the return value of a function, which is a string, as a hint of a head of one of my hydra. I can't get it to work.

First I tried to use lisp forms evaluating to a string, because it seemed like a reasonable thing to do. But I'll come back to it later. It fails (in strange ways by the way).

Then I read the readme again, and found about the Ruby-style string interpolation of a hydra docstring. There's not much about head-hint however, so I thought it might works like an hydra docstring. It seems it's not the case.

Maybe head-hint was supposed to be simple, without string-interpolation (?). However, because the :columns argument was introduced (http://oremacs.com/2015/07/20/hydra-columns/), it could be really useful to have that for head-hints too. I'm lazy, and I change my hydras *a lot*. I don't want to write the docstring myself (ever) to have the fancy columns and such. But I'd still like to use string-interpolation (I think I like forms evaluating to string better, but it's your project).

Here's what I tried:
```elisp
;; Note: s-lines comes from https://github.com/magnars/s.el#s-lines.
(defvar ap--toast-hydra-hint-var (car (s-lines (documentation 'newline))))
;; >> "Insert a newline, and move to left margin of the new line if
;; >> it's blank."

(defhydra ap--toast-hydra (:color red :columns 3)
  "
Toast : %`ap--toast-hydra-hint-var
"
  ("o" newline))

(defhydra ap--toast-hydra-2 (:color red :columns 3)
  "Toast 2."
  ("o" newline "%`ap--toast-hydra-hint-var"))

(defhydra ap--toast-hydra-3 (:color red :columns 3)
  "Toast 3."
  ("o" newline "
%`ap--toast-hydra-hint-var
"))

(defhydra ap--toast-hydra-4 (:color red :columns 3)
  "Toast 4."
  ("o" newline "

%`ap--toast-hydra-hint-var

"))
```
`ap--toast-hydra` works (but that's not what I want, it's just a test). `ap--toast-hydra-2`, `ap--toast-hydra-3`, `ap--toast-hydra-4` all trigger a similar error. Eg. for  `ap--toast-hydra-4`:
```
Debugger entered--Lisp error: (error "Not enough arguments for format string")
  format(#("Toast 4.:\no:\n\n%`ap--toast-hydra-hint-var\n\n" 10 11 (face hydra-face-red)))
  apply(format #("Toast 4.:\no:\n\n%`ap--toast-hydra-hint-var\n\n" 10 11 (face hydra-face-red)) nil)
  lv-message(#("Toast 4.:\no:\n\n%`ap--toast-hydra-hint-var\n\n" 10 11 (face hydra-face-red)))
  (if hydra-lv (lv-message (eval ap--toast-hydra-4/hint)) (message (eval ap--toast-hydra-4/hint)))
  (progn (if hydra-lv (lv-message (eval ap--toast-hydra-4/hint)) (message (eval ap--toast-hydra-4/hint))))
  (if hydra-is-helpful (progn (if hydra-lv (lv-message (eval ap--toast-hydra-4/hint)) (message (eval ap--toast-hydra-4/hint)))))
  (when hydra-is-helpful (if hydra-lv (lv-message (eval ap--toast-hydra-4/hint)) (message (eval ap--toast-hydra-4/hint))))
  ap--toast-hydra-4/body()
  eval((ap--toast-hydra-4/body) nil)
  eval-expression((ap--toast-hydra-4/body) nil)
  call-interactively(eval-expression nil nil)
```
-----------------------------------------
Now about using forms evaluating to string. It looked like it could reasonably just work (I don't really know elisp enough to be *that guy*, but whatever). If I'm not wrong, you might want to consider something similar to this as well/instead?:

```elisp
(defvar ap--toast-hydra-hint-var "hint var")

(defhydra ap--toast-hydra (:color red :columns 3)
  "Toast hydra."
  ("o" newline ap--toast-hydra-hint-var))
```
```elisp
(defhydra ap--tasty-toast-hydra (:color red :columns 3)
  "Tasty toast"
  ("o" newline (car (s-lines (documentation 'newline)))))
```
-------------------------------------
Hydra: 20150811.2253 (according to `M-x package-list-packages`)
emacs: GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian

**Comment by abo-abo** [comment]
Thanks, please test.

Here's an example:

```elisp
(defhydra hydra-test (:columns 2)
  "Test"
  ("j" next-line (format-time-string "%H:%M:%S" (current-time)))
  ("k" previous-line (format-time-string "%H:%M:%S" (current-time)))
  ("h" backward-char (format-time-string "%H:%M:%S" (current-time)))
  ("l" forward-char (format-time-string "%H:%M:%S" (current-time))))
```

**Comment by Antoine-Patel** [comment]
Thanks !

I tested your hydra, it works. What I really wanted to do from the beginning was dynamic hydras, and now it seems possible/easier (it was already possible for the commands, but not the head docstrings). Example:
```elisp
(defvar ap--hydra-cmd "")
(setq ap--hydra-cmd 'next-line)

(defhydra ap--tasty-toast-hydra (:color red :columns 1)
  "Tasty toast"

  ("M-SPC" (setq ap--hydra-cmd 'next-line) 
   "Restore the 'j' head back to original state.")
  ("SPC" (setq ap--hydra-cmd 'previous-line) "Change the 'j' head")
  ("j" (call-interactively ap--hydra-cmd)
   (car (s-lines (documentation ap--hydra-cmd)))))
```

I should have made the "SPC" head toggle between the two states, but it was just a quick test.

Thanks again. Maybe a nice "dynamic" hydra (not this one obviously, and with the commands properly stored into an alist, not a dummy variable) should go to the wiki now this issue is solved ?

**Comment by abo-abo** [comment]
> Thanks again. Maybe a nice "dynamic" hydra (not this one obviously, and with the commands properly stored into an alist, not a dummy variable) should go to the wiki now this issue is solved ?

I've added an entry [here](https://github.com/abo-abo/hydra/wiki/internals#hint-1).
