### ISSUE TITLE
Cannot notate an underscore key in docstring:

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/hydra#161]
![hydra_underscore](https://cloud.githubusercontent.com/assets/5009546/9565056/ae0dbd42-4e6e-11e5-981a-40c3e17908b3.PNG)

`___` is parsed as `___` in hydra docstrings, when it's meant to be parsed as <kbd>_</kbd>

**Comment by PythonNut** [comment]
Also `^_!_^` and `^_&_^` cause errors for some reason.

**Comment by abo-abo** [comment]
Thanks.

**Comment by PythonNut** [comment]
I'm still seeing:
```emacs
Error in defhydra hydra/isearch-map: (Unrecognized key: ___)
```

**Comment by abo-abo** [comment]
Must be a bug on your end, since it works for me. Can you reproduce with `emacs -Q`?

**Comment by PythonNut** [comment]
@abo-abo yes, it did end up being a bug on my end?
