### ISSUE TITLE
Hydras does not create prefix args for numbers

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/hydra#162]
See minimal example:
```emacs
;; this works
(defhydra hydra-test-alpha ()
  ("aa" forward-char))

;; this does not
(defhydra hydra-test-number ()
  ("1a" forward-char))

```

**Comment by abo-abo** [comment]
This is because the digits are already bound in `hydra-base-map`. You can fiddle with it if you want, but I don't want to change the current behavior.
