### ISSUE TITLE
Activate hydra from key-chord?

### ISSUE THREAD

**Issue by metatron-the-chronicler** [abo-abo/hydra#167]
Say a root key binding for Hydra is F2, is it possible to have the menu for this hydra come up when pressing F2 instead of having to activate one of the heads first?

**Comment by abo-abo** [comment]
Of course, like this:

```elisp
(global-set-key (kbd "<f2>") 'hydra-zoom/body)
```

**Comment by metatron-the-chronicler** [comment]
Thanks alot.  This package is really an excellent piece of accessibility tooling.
