### ISSUE TITLE
Blue face is a little hard to read on dark themes

### ISSUE THREAD

**Issue by Malabarba** [abo-abo/hydra#168]
I see that the face definitions use the same color regarless of the background. It might be best to use a slightly brighter blue on dark backgrounds, and a slightly darker blue on light backgrounds.

For instance, here's how I do that in paradox:

    (defface paradox-comment-face
      '((((background light)) :foreground "Grey30")
        (((background dark)) :foreground "Grey60"))
      "Face used on faded out stuff."
      :group 'paradox-menu
      :group 'paradox-commit-list)

**Comment by abo-abo** [comment]
Here's the current definition:

```elisp
(defface hydra-face-blue
  '((((class color) (background light))
     :foreground "#0000FF" :bold t)
    (((class color) (background dark))
     :foreground "#8ac6f2" :bold t))
  "Blue Hydra heads exit the Hydra.
Every other command exits as well.")
```

If you'd like a different color for the dark themes, please make a suggestion.

**Comment by Malabarba** [comment]
Oh, is that on Melpa? I have the latest stable version (`0.13.2`), and the definition in there is this:

    (defface hydra-face-blue
        '((t (:foreground "#0000FF" :bold t)))
      "Blue Hydra heads exit the Hydra.
    Every other command exits as well.")

**Comment by abo-abo** [comment]
Just pushed the 0.13.2 tag. The change should appear on MELPA stable soon.

**Comment by Malabarba** [comment]
Small thing. IIUC, you already had a 0.13.2 on Gelpa. But the Gelpa package only gets updated when the version changes, so now there are two different 0.13.2 versions out there (gelpa and melpa-stable).

**Comment by abo-abo** [comment]
OK, 0.13.3 are in sync on both GELPA and MELPA Stable. Thanks.
