### ISSUE TITLE
Possible race condition between :post and foreign key action?

### ISSUE THREAD

**Issue by larkery** [abo-abo/hydra#169]
I have a hydra set up like this (minimal-ish example)

```elisp
(bind-key "#" nil)
(defvar did-something 0)
(defvar did-where nil)
(defhydra hydra-hash 
  (:exit
   t
   :idle
   0.5
   :pre
   (progn (cl-incf did-something)
          (setq did-where (current-buffer)))
   :post
   (progn
     (unless (> did-something 1)
       (with-current-buffer did-where (insert "#")))
     (setq did-something 0 did-where nil))
   )
  ("a" (message "hello world")))
(bind-key "#" hydra-hash/body)
```

The hope is to make it so that if I type (for example) `#'` it inserts `#` because of `:post` and then the foreign key command fires which is `self-insert-command` with `'`.

This is because I don't type # very often, so I can use it as a prefix for dispatching some commands I do frequently, but by avoiding binding things that I do write after # somethings (like the quote char for lisp function-quote) I can still just type those.

What I find is that this mostly works, but sometimes the # is inserted _after_ the foreign key rather than before. The difference seems to depend on what frame I am in - if I view the same buffer in two frames, it will (somtimes) reliably do the insertions in one order in one frame and in another order in the second frame. I presume there is a loop over buffers or over frames somewhere (I added the current-buffer because sometimes it would otherwise insert into a different buffer).

Am I doing something insane? Is there a way to make this not mad? Can the `:post` command be made to execute in the current buffer and definitely before the foreign key is typed?

Many thanks,

Tom

**Comment by abo-abo** [comment]
Thanks, you found a tricky bug.

Also, here's a more simple version of your code, there's no need to save the buffer, it should be automatic:

```elisp
(defvar did-something 0)
(defhydra hydra-hash (:exit t
                      :idle 0.5
                      :pre (cl-incf did-something)
                      :post (progn
                              (unless (> did-something 1)
                                (insert "#"))
                              (setq did-something 0)))
  ("a" (message "hello world")))
(global-set-key (kbd "#") 'hydra-hash/body)
```

**Comment by larkery** [comment]
Excellent, thank you for fixing that - I kept the buffer because otherwise the insert would run in the wrong buffer, but I think that was also due to the bug :)
