### ISSUE TITLE
Avoid exiting the hydra on hitting a wrong key. 

### ISSUE THREAD

**Issue by vkazanov** [abo-abo/hydra#17]
While testing the Hydra I noticed that sometimes I accidentally quit the hydra 'mode' by clicking the wrong button. As much as I know from reading your blog this is a design decision.

For some hydras it's ok, for others - might be a problem. If you have, say, a simple hydra using only two bindings - it might be alright, as you don't move your hands a lot.

If you use hydra to build a special mode of sorts - a better code browsing mode, for example - chances are that you will click a wrong button at some point, killing the hydra.

So, the question is... Do you plan to implement a way to disable all non-hydra keybindings while using the hydra?

**Comment by abo-abo** [comment]
See if the code on branch `amaranth` is what you want.

**Comment by vkazanov** [comment]
Yes, this is exactly what I want. 

Do you plan to merge the branch into master? Or..?

**Comment by abo-abo** [comment]
Yep, I'll merge this soon (today). Just need to test for a while, and add docs.

**Comment by vkazanov** [comment]
I'll test it as soon as you finish the merge. Thanks!

**Comment by abo-abo** [comment]
It's merged, have a look.

**Comment by vkazanov** [comment]
Everything works as intended, great!

One detail: pushing the wrong button calls the `:post`, `:pre` hooks. Is it supposed to be like that?

**Comment by abo-abo** [comment]
Probably not. Are you sure that it's calling `:pre` though? The `:post` one I can see, and I'll need quite a bit more code to stop it from doing that. But I don't see it calling `:pre`.

**Comment by vkazanov** [comment]
Well... I did not debug it, but it does switch the color both ways, doesn't it? :-)

**Comment by abo-abo** [comment]
No, it switches go black when I press e.g. <kbd>C-f</kbd>. It doesn't switch to amaranth. It's supposed
to switch to amaranth for each head except blue.

**Comment by vkazanov** [comment]
Thanks a lot! Hydra turns out to be a great idea.
