### ISSUE TITLE
Option to delay hint

### ISSUE THREAD

**Issue by mkleehammer** [abo-abo/hydra#173]
I have a hydra for M-g that includes "goto" commands - enough that the hint takes up 2 lines.  When the frame is split horizontally, the bottom buffer moves up and the top buffer shrinks when the hint is displayed.  When I need to read the commands it is not an issue, but when using the very common commands it is very distracting to have the buffers shuffle around a bit.

Hydras seemed designed for two things:

1) To easily consolidate a group of commands under a prefix key.
2) To provide easy access to commands I don't use often.

An optional delay seems ideal for situations like this where 1 and 2 conflict.

**Comment by abo-abo** [comment]
You can delay the hydra hint e.g. by 1.5 seconds with `:idle 1.5` in the body plist. This is described here: https://github.com/abo-abo/hydra/wiki/internals#idle.

**Comment by mkleehammer** [comment]
Wow - thanks.  I expected it to be there and looked for delay and a couple of keywords, but somehow missed idle.  Thanks for the great package.
