### ISSUE TITLE
Feature: Show doc when body keybinding has been entered without specifying a head

### ISSUE THREAD

**Issue by duncanburke** [abo-abo/hydra#174]
I was looking for a way to have the documention pop up immediately on entering the body keybinding. After some experimentation, I discovered it was sufficent to have the following as the last head in the hydra:

    ("" ignore :exit nil)

I doubt this is intended behaviour, however it is useful. In my opinion it should be default behaviour to show the doc on the body keybinding. This will serve well in the mean time as a hack, however it would be nice to have this as an option in the plist.

**Comment by abo-abo** [comment]
> In my opinion it should be default behaviour to show the doc on the body keybinding

Consider this:

```elisp
(global-set-key (kbd "M-s o") 'occur)
(defhydra hydra-test (global-map "M-s")
  "test"
  ("g" magit-status "magit"))
```

The code above is OK. Even after defining the hydra, you can call the built-in binding <kbd>M-s o</kbd>.

But this code isn't OK:
```elisp
(global-set-key (kbd "M-s o") 'occur)

(defhydra hydra-test (global-map "M-s")
  "test"
  ("g" magit-status "magit")
  ("" ignore))
```

It occupies the <kbd>M-s</kbd> prefix with `hydra-test/body`, hindering all previous bindings that were using <kbd>M-s</kbd> prefix.

In actuality, the code above is equivalent to:

```elisp
(defhydra hydra-test ()
  "test"
  ("g" magit-status "magit"))
(global-set-key (kbd "M-s") 'hydra-test/body)
```

The difference between the two approaches is described in the [documentation](https://github.com/abo-abo/hydra/wiki/internals#body-plist).  Both approaches are valid but have advantages and disadvantages.  The first approach plays better with the Emacs defaults, so it's more visible in the documentation.

**Comment by bburns** [comment]
I also think it would be nice if this was the default behavior, to show the hint when you first call the hydra. Then you could override the behavior if you needed to - or maybe it could be an option with a defcustom, to show the hint first. 

It would be like the behavior of Lotus 123 from the old DOS days - you hit "/" and it showed a menu along the bottom, though hydra lets you have larger menus. 

And I like how use-package has everything in one top-level form - it really helps organize your code, so it would be nice to have the same with defhydra, if possible. If not I'll try duncan's hack.

**Comment by abo-abo** [comment]
> to show the hint when you first call the hydra

The hint is always shown when you call the hydra. The difference is that e.g. with one binding method hydra is called after <kbd>M-s g</kbd>, and with the other binding method it's called after <kbd>M-s</kbd>.

See the newly created entry on the [wiki](https://github.com/abo-abo/hydra/wiki/Binding-Styles).
