### ISSUE TITLE
Keep region active when calling hydra

### ISSUE THREAD

**Issue by jagrg** [abo-abo/hydra#176]
When you select a region and call hydra, the region is deactivated. If this is intentional, is there a way to keep the region active instead? Version: `hydra-20151214.417`.

**Comment by abo-abo** [comment]
Please add specifics. I don't see the problem with this code:

```elisp
(defhydra hydra-test ()
  ("f" forward-char "forward"))

(defun test ()
  (interactive)
  (set-mark (point))
  (hydra-test/forward-char))
```

**Comment by jagrg** [comment]
I meant selecting a region in the buffer, not programmatically.

1. select region
2. `M-x hydra-test/body`

**Comment by abo-abo** [comment]
Still works fine for me. The issue is probably with your config, see if you can reproduce with `emacs -Q`.

**Comment by jagrg** [comment]
You are right. I cannot reproduce it with `Emacs -Q`.

**Comment by jagrg** [comment]
I wish I had a more sophisticated solution but all I had to was restart Emacs, which I hadn't done in a while.

**Comment by abo-abo** [comment]
There you go, problem solved:)

**Comment by Fuco1** [comment]
@jagrg I have the same issue and restarting emacs doesn't help.  Did you use cua or delsel or some similar package? I have a hard time pinning this down :/

**Comment by jagrg** [comment]
The problem still shows up once in a while, but I haven't been able to track it down. I don't think I use any of the packages you mention. You will probably need to bisect your init file. I'd be curious to know.

**Comment by Tiv0w** [comment]
Sorry to revive this old issue, but I stumbled across this problem today, and I think I know where the problem comes from.
I'm using `expand-region` most of the time, and calling hydra disables the region when it was marked with `expand-region`.

So for anyone who may encounter this issue later, it might come from `expand-region`, and if it is the case, this has nothing to do with `hydra`.

**Comment by abo-abo** [comment]
@Tiv0w thanks for the info

**Comment by abo-abo** [comment]
@Tiv0w thanks for the info
