### ISSUE TITLE
Using `^` in keybinding docstrings

### ISSUE THREAD

**Issue by shosti** [abo-abo/hydra#178]
Hi! Apologies if I missed this in the docs somewhere, but what's the right way to "escape" the `^` character in keybinding docstrings? I tried:
```elisp
"
_M-^_: foo
"
```
which doesn't work because it doesn't understand the keybinding, but 
```elisp
"
_M-\\^_: foo
"
```
doesn't highlight/colorize the keybinding properly. Is there currently a way to escape the `^`?

**Comment by abo-abo** [comment]
Thanks, `_M-\\^_` should work now.
