### ISSUE TITLE
FR: Local override of `hydra-is-helpful'

### ISSUE THREAD

**Issue by jiri** [abo-abo/hydra#181]
I have `(setq hydra-is-helpful nil)` by default, because I know most of the bindings by heart and displaying the pop-up is disruptive.

However, there are cases where I'd quite like the pop-up to appear, especially for displaying additional info in the pop-up. At the moment, I just re-enable `hydra-is-helpful` in `:body-pre` an disable it on quit, but being able to do `:helpful t` would be not only easier, but would enable the pop-up to show only on certain heads :)

**Comment by abo-abo** [comment]
I was working on a similar idea this week.  Something like a `help-level` that's dynamically modifiable in every hydra:

- level-0: no help.
- level-1: alternative single line description in the Echo area, usually just the keys concatenated with single spaces.
- level-2: actual hydra doc.

By default, each hydra would have the initial state level-2, unless level-1 or level-0 are specified in the definition. Then use something like <kbd>?</kbd> to bump the level up by one.

**Comment by jiri** [comment]
I'm not sure whether this isn't out of the scope of hydra, but it does sound interesting!

:+1:

**Comment by pmagwene** [comment]
I'd find help-level to be very useful!

**Comment by abo-abo** [comment]
This was implemented sometime ago, I didn't update this issue:

```elisp
;; turn off the hint
(hydra-set-property 'hydra-zoom :verbosity 0)
;; show the hint only in the echo area
(hydra-set-property 'hydra-zoom :verbosity 1)
;; show the hint normally
(hydra-set-property 'hydra-zoom :verbosity 2)
```

For more advanced stuff, see `hydra-lispy-x` from lispy.
