### ISSUE TITLE
hydra-test.el is loaded

### ISSUE THREAD

**Issue by phillord** [abo-abo/hydra#182]
I've just added hydra from melpa-stable to a clean emacs, and find that C-cd has been bound to a hydra from hydra-test.el, which is, I think, the wrong behaviour.

**Comment by abo-abo** [comment]
This doesn't happen in MELPA, since hydra-test.el isn't bundled automatically. But this problem occurs in GNU ELPA. 

Do you know the procedure for excluding files from the GELPA build?

**Comment by phillord** [comment]
You are correct, I hadn't realised it was coming from ELPA. It's actually only a problem after installing the package -- hydra-test.el is byte-compiled at this time. After a restart, it's not automatically loaded.

I don't know how files are excluded on ELPA, or if it is possible. I'll investigate. If it isn't possible, then we can add something.

**Comment by abo-abo** [comment]
Thanks for the report. I'm updating GELPA right now. The 0.13.5 will hopefully be available within 24 hours.

**Comment by phillord** [comment]
You got there before me! .elpaignore is the way to go.

Thanks for the fix.
