### ISSUE TITLE
Feature request: pre hook that fires once

### ISSUE THREAD

**Issue by svend** [abo-abo/hydra#183]
I'd like a way to execute a pre hook once. This is my hydra for winner mode:

```emacs-lisp
(global-set-key
 (kbd "C-c w")
 (defhydra hydra-winner ()
   "Winner"
   ("w" winner-undo "back")
   ("r" winner-redo "forward" :exit t)))))
```

With this hydra, calling winner-undo requires pressing "C-c w w".

I'd like winner-undo to be called on the first press of "C-c w", after that each "w" will call winner-undo again.

**Comment by abo-abo** [comment]
You can reach a wrapped function like this:

```elisp
(defhydra hydra-winner ()
  "Winner"
  ("w" winner-undo "back")
  ("r" winner-redo "forward" :exit t))

(global-set-key (kbd "C-c w") 'hydra-winner/winner-undo)
```

If you'd like to see how `hydra` works, eval this and look at the output:

```elisp
(macroexpand
 '(defhydra hydra-winner ()
   "Winner"
   ("w" winner-undo "back")
   ("r" winner-redo "forward" :exit t)))
```

**Comment by svend** [comment]
That's perfect, thanks!
