### ISSUE TITLE
Hint with unicode symbols?

### ISSUE THREAD

**Issue by lunaryorn** [abo-abo/hydra#186]
Hello,

I have a hydra that binds `<up>`, `<down>` and similar keys.  It works perfectly so far, but there's a small nuisance: In the custom hint I have to use `_<up>_`, but I'd love to use the unicode arrow `↑` instead.  `_↑_` doesn't work; the key isn't highlighted.

Is there a way to substitute certain keys with unicode symbols?

**Comment by lunaryorn** [comment]
PS: Thanks for this awesome package.  Took me a while to see its purpose, but by now it's slowly taking over all my keybindings and has already completely revolutionised my smartparens bindings :heart_eyes:

**Comment by abo-abo** [comment]
Please have a look in the fix-186 branch.

It's not complete, since there's only one key being substituted. I'm also unhappy with the huge regex:

> "\\(?:%\\( ?-?[0-9]*s?\\)\\(`[a-z-A-Z/0-9]+\\|(\\)\\)\\|\\(?:[_?]\\( ?-?[0-9]*?\\)\\(\\[\\|]\\|[-[:alnum:] ~.,;:/|?<>={}*+#%@!&^↑]+?\\)[_?]\\)"

Do you know if it's possible to simplify it?

**Comment by lunaryorn** [comment]
@abo-abo Uh, uhm, no.  I don't even know what the expression is supposed to match :flushed: :grin: It's to great a beast for me to tackle :blush:

**Comment by abo-abo** [comment]
Can you just propose extra entries for `hydra-docstring-keys-translate-alist`? I'll update the regex myself.

**Comment by lunaryorn** [comment]
@abo-abo That's my which-key replacement list:

```elisp
  '(("<\\([[:alnum:]-]+\\)>" . "\\1")
          ("up"                    . "↑")
          ("right"                 . "→")
          ("down"                  . "↓")
          ("left"                  . "←")
          ("DEL"                   . "⌫")
          ("deletechar"            . "⌦")
          ("RET"                   . "⏎"))
```

It's mostly the arrow keys, and delete forward/backwards.

**Comment by abo-abo** [comment]
OK, I added the rest of them.

**Comment by lunaryorn** [comment]
@abo-abo Great, thank you very much :heart_eyes:

**Comment by manuel-uberti** [comment]
Mmm, this is on my setup.
![2016-04-07-155601_869x523_scrot](https://cloud.githubusercontent.com/assets/8199224/14353402/2da9505c-fcd9-11e5-8946-ca36b715eb5c.png)

**Comment by abo-abo** [comment]
@manuel-uberti thanks, fixed.

**Comment by manuel-uberti** [comment]
Thank you!

**Comment by manuel-uberti** [comment]
Trying this out:
```
(defhydra mu-smartparens (:hint nil)
    "
Sexps (quit with _q_)
^Nav^            ^Barf/Slurp^                 ^Depth^
^---^------------^----------^-----------------^-----^-----------------
_f_: forward     _→_:          slurp forward   _R_: splice
_b_: backward    _←_:          barf forward    _r_: raise
_u_: backward ↑  _C-<right>_:  slurp backward  _↑_: raise backward
_d_: forward ↓   _C-<left>_:   barf backward   _↓_: raise forward
_p_: backward ↓
_n_: forward ↑
^Kill^           ^Misc^                       ^Wrap^
^----^-----------^----^-----------------------^----^------------------
_w_: copy        _j_: join                    _(_: wrap with ( )
_k_: kill        _s_: split                   _{_: wrap with { }
^^               _t_: transpose               _'_: wrap with ' '
^^               _c_: convolute               _\"_: wrap with \" \"
^^               _i_: indent defun"
    ("q" nil)
    ;; Wrapping
    ("(" (lambda (a) (interactive "P") (sp-wrap-with-pair "(")))
    ("{" (lambda (a) (interactive "P") (sp-wrap-with-pair "{")))
    ("'" (lambda (a) (interactive "P") (sp-wrap-with-pair "'")))
    ("\"" (lambda (a) (interactive "P") (sp-wrap-with-pair "\"")))
    ;; Navigation
    ("f" sp-forward-sexp )
    ("b" sp-backward-sexp)
    ("u" sp-backward-up-sexp)
    ("d" sp-down-sexp)
    ("p" sp-backward-down-sexp)
    ("n" sp-up-sexp)
    ;; Kill/copy
    ("w" sp-copy-sexp)
    ("k" sp-kill-sexp)
    ;; Misc
    ("t" sp-transpose-sexp)
    ("j" sp-join-sexp)
    ("s" sp-split-sexp)
    ("c" sp-convolute-sexp)
    ("i" sp-indent-defun)
    ;; Depth changing
    ("R" sp-splice-sexp)
    ("r" sp-splice-sexp-killing-around)
    ("<up>" sp-splice-sexp-killing-backward))
```
I get this message:
```
Warning (emacs): Unrecognized key: _→_
Warning (emacs): Unrecognized key: _←_
Warning (emacs): Unrecognized key: _C-<right>_
Warning (emacs): Unrecognized key: _C-<left>_
Warning (emacs): Unrecognized key: _↓_
Error (use-package): smartparens :init: Invalid function: "<down>"
```

**Comment by abo-abo** [comment]
@manuel-uberti `_→_` is translated to `<left>` by `hydra-docstring-keys-translate-alist`. But you don't have a `<left>` head in your `defhydra`.

**Comment by manuel-uberti** [comment]
Fixed, I slurped too much ;)
