### ISSUE TITLE
Warning: Unrecognized key

### ISSUE THREAD

**Issue by TheBB** [abo-abo/hydra#189]
This is a continuation of https://github.com/syl20bnr/spacemacs/issues/5714. I have reproduced this bug on the master branch with `make run` so I figured it would be best to move here.

A small reproducing sample:

    (defhydra test () "_SPC_" ("SPC" test))

Produces an infinite loop of warnings until killed by `C-g`:

    Warning (emacs): Unrecognized key: _PC_

I know you said that very similar cases to this one worked fine for you, but it does not on my setup and that of many others so evidently something is wrong.

I'm using Emacs version 24.5.1.

**Comment by abo-abo** [comment]
> "_SPC_"

This is the wrong part, it should be `"\n_SPC_"`. In order to get the Ruby-style docstrings, the docstring needs to start with a newline.

Quote the docstring:

> DOCSTRING will be displayed in the echo area to identify the
> Hydra.  When DOCSTRING starts with a newline, special Ruby-style
> substitution will be performed by `hydra--format'.

I've pushed another fix for #188, try if that fixes your problem. But in any case, the leading `\n` rule stays, since it helps with alignment anyway.

**Comment by abo-abo** [comment]
I just reproduced the problem with `spacemacs|define-transient-state org-agenda`. It should now be fixed. Please check.

**Comment by TheBB** [comment]
Yep, I wasn't aware of that rule. It reproed with leading newlines anyway, but I can confirm that https://github.com/abo-abo/hydra/commit/83b9019944b768ec4a213f99594b31209b36e8c2 fixes the problem.

**Comment by abo-abo** [comment]
OK, thanks.
