### ISSUE TITLE
Error: Wrong type argument: stringp, highlight

### ISSUE THREAD

**Issue by robbyoconnor** [abo-abo/hydra#194]
ivy-hydra.el:29:1:Error: Wrong type argument: stringp, highlight

Running on spacemacs if that means anything on emacs 24.5

**Comment by abo-abo** [comment]
This is probably related to a bug in monokai-theme, see https://github.com/abo-abo/swiper/issues/506.

**Comment by robbyoconnor** [comment]
Confirm this is fixed. Closing.
