### ISSUE TITLE
Is it possible in hydra docstrings to highlight a key right before a list form?

### ISSUE THREAD

**Issue by sp3ctum** [abo-abo/hydra#197]
What I'd like to achieve is something like this:

```elisp
(defhydra test-hydra ()
  "
_a_(some example code)"
  ("a" identity))
```

What I'd like to see is the `_a_` key highlighted before the `(some example code)` form. Do you have a suggestion for this?

My use case:
I'd like to create a visual cheat sheet for the most common lispy commands in evil-lispy.

**Comment by abo-abo** [comment]
> What I'd like to see is the _a_ key highlighted before the (some example code) form.

I don't get it, please give an example.

**Comment by sp3ctum** [comment]
Here's an example I'd like to include in the cheat sheet:

```lisp
;; point is at |
h(-> k(+ 2 3)
     |(+ 2)
     j(* 8))l
```

In the example, pressing `j` for example would move point to the position where `j` is.

Now, I'd like to actually be able to write this and get the different positions highlighted:
```lisp
(defhydra test ()
  "
_h_(-> _k_(+ 2 3)
       |(+ 2)
       _j_(* 8))_l_
"
  ("h" special-lispy-left)
  ("j" special-lispy-down)
  ("k" special-lispy-up)
  ("l" special-lispy-right))
```

But in this case lispy seems to think the entire form following `_h_` should be evaluated and the result be included in the docstring instead of what we see here.

**Comment by abo-abo** [comment]
Thanks, should be fixed now.

**Comment by sp3ctum** [comment]
Works beautifully. Thank you very much!
Could you increase the version number so I can reliably depend on this change being included in evil-lispy's dependencies?
