### ISSUE TITLE
Amaranth hydra exits on calling a head

### ISSUE THREAD

**Issue by AssailantLF** [abo-abo/hydra#198]
I'm making some hydras for `ibuffer` similar to the example given for `buffer-menu`. I have some "sub-hydras" under the main one to mark, sort, or filter buffers more specifically:

          (defhydra hydra-ibuffer-menu (:color pink                
                                              :hint nil)           
            "                                                      
    | ^Nav^ | ^Mark^          | ^Actions^    | ^View^      |       
    +-^---^-+-^----^----------+-^-------^----+-^----^------+       
    |  _k_  | _m_: mark       | _RET_: open  | _s_: sort   |       
    |  ^ʌ^  | _u_: unmark     | _D_: delete  | _/_: filter |       
    |  ^v^  | _*_: specific   | _S_: save    | ^ ^         |       
    |  _j_  | ^ ^             | _g_: refresh | ^ ^         |       
    +--^-^--+-^----^----------+-^-------^----+-^----^------+       
    "                                                              
            ("j" ibuffer-forward-line)                             
            ("k" ibuffer-backward-line)                            
                                                                   
            ("m" ibuffer-mark-forward)                             
            ("u" ibuffer-unmark-forward)                           
            ("*" hydra-ibuffer-mark/body :color blue)              
                                                                   
            ("RET" ibuffer-visit-buffer)                           
            ("D" ibuffer-do-delete)                                
            ("S" ibuffer-do-save)                                  
            ("g" ibuffer-update)                                   
                                                                   
            ("s" hydra-ibuffer-sort/body :color blue)              
            ("/" hydra-ibuffer-filter/body :color blue)            
                                                                   
            ("q" ibuffer-quit "quit" :color blue)                  
            ("c" nil "close-hydra" :color blue))                   
          (defhydra hydra-ibuffer-mark                             
            (:color amaranth                                       
                    :after-exit (hydra-ibuffer-menu/body)          
                    :columns 3)                                    
            "Mark"                                                 
            ("*" ibuffer-unmark-all "unmark all")                  
            ("M" ibuffer-mark-by-mode "mode")                      
            ("m" ibuffer-mark-modified-buffers "modified")         
            ("u" ibuffer-mark-unsaved-buffers "unsaved")           
            ("s" ibuffer-mark-special-buffers "special")           
            ("r" ibuffer-mark-read-only-buffers "read-only")       
            ("/" ibuffer-mark-dired-buffers "dired")               
            ("e" ibuffer-mark-dissociated-buffers "dissociated")   
            ("h" ibuffer-mark-help-buffers "help")                 
            ("z" ibuffer-mark-compressed-file-buffers "compressed")
            ("b" nil "back" :color blue))                          
          (defhydra hydra-ibuffer-sort                             
            (:color amaranth                                       
                    :after-exit (hydra-ibuffer-menu/body)          
                    :columns 3)                                    
            "Sort"                                                 
            ("i" ibuffer-invert-sorting "invert")                  
            ("a" ibuffer-do-sort-by-alphabetic "alphabetic")       
            ("v" ibuffer-do-sort-by-recency "recently used")       
            ("s" ibuffer-do-sort-by-size "size")                   
            ("f" ibuffer-do-sort-by-filename/process "filename")   
            ("m" ibuffer-do-sort-by-major-mode "mode")             
            ("b" nil "back" :color blue))                          
                                                                   
          (defhydra hydra-ibuffer-filter                           
            (:color amaranth                                       
                    :exit nil                                      
                    :after-exit (hydra-ibuffer-menu/body)          
                    :columns 3)                                    
            "Filter"                                               
            ("m" ibuffer-filter-by-used-mode "mode")               
            ("n" ibuffer-filter-by-name "name")                    
            ("c" ibuffer-filter-by-content "content")              
            ("f" ibuffer-filter-by-filename "filename")            
            (">" ibuffer-filter-by-size-gt "size")                 
            ("<" ibuffer-filter-by-size-lt "size")                 
            ("/" ibuffer-filter-disable "disable")                 
            ("b" nil "back" :color blue))                          

However, these amaranth sub-hydras are exiting when I call their amaranth-colored heads. Any idea what's going on here? I'm probably doing something wrong, or missed some documentation.

Also I want to say how much of a fan I am of your packages after a very short time using them. I plan on making some really awesome hydras soon.

**Comment by AssailantLF** [comment]
Hm.. I still don't know why this is happening, but I can get my desired behavior by removing `:after-exit` and just calling `hydra-ibuffer-menu/body` on the exiting heads, which looks better anyway.

**Comment by abo-abo** [comment]
> However, these amaranth sub-hydras are exiting when I call their amaranth-colored heads. Any idea what's going on here? I'm probably doing something wrong, or missed some documentation.

Hydra makes use of Emacs' first priority map. Whoever holds this first priority map is in charge of the bindings. This means that only one hydra can be active at a time, and before a hydra calls a sub-hydra it has to exit (to release the priority map).  So when you're nesting hydras the sub-hydra is always exiting. If it needs to call the parent after it itself exits, use the parent's `.../body` function.  For a good example, look at `pandoc-mode`.

> Also I want to say how much of a fan I am of your packages after a very short time using them. I plan on making some really awesome hydras soon.

Thanks!

> Hm.. I still don't know why this is happening, but I can get my desired behavior by removing :after-exit and just calling hydra-ibuffer-menu/body on the exiting heads, which looks better anyway.

You figured out the recommended way of doing things yourself.
