### ISSUE TITLE
Allow a head to override :after-exit

### ISSUE THREAD

**Issue by AssailantLF** [abo-abo/hydra#199]
So in improving the hydra I mentioned in [this issue](https://github.com/abo-abo/hydra/issues/198), I've added a sub-hydra for actions that are performed on buffers. It's teal, and `:after-exit`s to the main ibuffer hydra by default. However, for some of the actions (like `view`) I want it to exit both hydras.

Here's the code for it:

      (defhydra hydra-ibuffer-action
        (:color teal
                :columns 4
                :after-exit (hydra-ibuffer-main/body))
        "Action"
        ("b" nil "back")
        ("A" ibuffer-do-view "view")
        ("E" ibuffer-do-eval "eval")
        ("F" ibuffer-do-shell-command-file "shell-command-file")
        ;; etc.
        )

I can't think of a better way to do what I want other than to override `:after-exit` in the head e.g. `("A" ibuffer-do-view "view" :after-exit nil)`. 

Any ideas or solutions? If it's too complicated a feature, I can easily do something else.

**Comment by abo-abo** [comment]
> Any ideas or solutions? If it's too complicated a feature, I can easily do something else.

First idea is not to use `:after-exit` and instead put `(hydra-ibuffer-main/body)` into all the heads that you need:

```elisp
(defhydra hydra-ibuffer-action (:color teal
                                :columns 4)
  "Action"
  ("b" (hydra-ibuffer-main/body) "back")
  ("A" ibuffer-do-view "view")
  ("E" (progn
         (ibuffer-do-eval)
         (hydra-ibuffer-main/body)) "eval")
  ("F" (progn
         (ibuffer-do-shell-command-file)
         (hydra-ibuffer-main/body)) "shell-command-file")
  ;; etc.
  )
```

Not the most compact way, but should work.

Second idea, if only a few functions need to exit everything, it's possible to re-define them:

```elisp
(defun hydra-ibuffer-action/ibuffer-do-view ()
  (interactive)
  (hydra-keyboard-quit)
  (setq hydra-curr-body-fn 'hydra-ibuffer-action/body)
  (ibuffer-do-view))
```

You can always look at the default definition by evaluating e.g.:

    (symbol-functon 'hydra-ibuffer-action/ibuffer-do-view)

Third idea is to put a more complex statement as `:after-exit`:

    (defhydra hydra-ibuffer-action (:color teal :columns 4
                                    :after-exit
                                    (if hydra-call-after-exit
                                        (hydra-ibuffer-main/body)
                                      (setq hydra-call-after-exit t)))
      ("A" (progn (ivy-buffer-do-view)
                  (setq hydra-call-after-exit nil)) "view"))

**Comment by AssailantLF** [comment]
I'll go with the first way since it seems the most clear. I actually had that idea, but figured it wouldn't work for some reason. I should've just tried it before posting an issue.

Thanks!

**Comment by AssailantLF** [comment]
Oh hey, just wanted to say that I came up with a way better solution somewhat based on your 3rd idea that is very simple and pretty:

    defhydra hydra-ibuffer-action
      (:color teal :columns 4
              :after-exit
              (if (eq major-mode 'ibuffer-mode)
                  (hydra-ibuffer-main/body)))
      "Action"
      ("A" ibuffer-do-view "view")
      ("E" ibuffer-do-eval "eval")

Also a side question: Any idea why my `:color`, `:columns`, `:after-exit`, etc. stuff is indenting so strangely?

**Comment by abo-abo** [comment]
> Also a side question: Any idea why my :color, :columns, :after-exit, etc. stuff is indenting so strangely?

Try `(setq lisp-indent-function 'common-lisp-indent-function)`.
