### ISSUE TITLE
Adding descriptions to hydra & its heads

### ISSUE THREAD

**Issue by immerrr** [abo-abo/hydra#2]
It would be nice to be able to have some feedback on currently active hydra.  I'm yet to try out the code, but it should be rather easy to change your prime example to:
```lisp
(require 'hydra)
(hydra-create "<f2>"
  '(("g" text-scale-increase "increase")
    ("l" text-scale-decrease "decrease"))
 "Text scale")
```
And make it display something like `Text scale: <g> increase <l> decrease` in minibuffer or popwin window.

I have smth [like this](https://github.com/masaaki1001/.emacs.d/blob/07f779b1af4b55427f9ea96993b13548aa7c543c/config/init-smartrep.el#L30-L48) in my dot-emacs and since I don't use symbol highlighting very often the hint that appears in the minibuffer (see `(message ...)`) is very helpful.

**Comment by abo-abo** [comment]
I've miscalculated using an alist as `hydra-create`'s interface.  It needs to be changed to a list of lists to proceed with your plan.  But then I'll also need to update the blog entry and stuff. It will take some more time to implement your proposal, I'll release a `v0.2.0` with the new interface soon.

**Comment by abo-abo** [comment]
Marking it a solved for now. Raise another issue if you want to improve the documentation further.

**Comment by immerrr** [comment]
Awesome, thank you!
