### ISSUE TITLE
Major mode hydras

### ISSUE THREAD

**Issue by sondr3** [abo-abo/hydra#204]
The way I use Hydra right now is that I have a main menu that I invoke with `SPC` that lists all the sub-menus, and I'd like to be able to do `SPC-m` to invoke the specific major mode menu, but I'm not sure if that is even possible. So if I'm editing Emacs LISP invoking `SPC-m` would open a Elisp specific Hydra, when I'm editing a Org-mode file invoking `SPC-m` would open a Org-mode Hydra and so on. Would that even be possible?

**Comment by abo-abo** [comment]
Just use a plain command:

```elisp
(defun hydra-by-major-mode ()
  (interactive)
  (cl-case major-mode
    (emacs-lisp-mode
     (hydra-elisp/body))
    (c-mode
     (hydra-c/body))
    (org-mode
     (hydra-org/body))
    (t
     (error "%S not supported" major-mode))))

(global-set-key (kbd "SPC-m") 'hydra-by-major-mode)
```

**Comment by sondr3** [comment]
Fantastic, I'll try this out as soon as I can!

**Comment by sondr3** [comment]
It works! 😀

**Comment by apnewberry** [comment]
There's also https://github.com/jerrypnz/major-mode-hydra.el
