### ISSUE TITLE
Tmux mode

### ISSUE THREAD

**Issue by ksrb** [abo-abo/hydra#206]
I have a hydra that looks like this:
```elisp
(defhydra hydra-tmux-mode
  (:foreign-keys nil)
  "Tmux mode"
  ("C-h" move-border-left "Move border left 3")
  ("C-j" move-border-down "Move border down 3")
  ("C-k" move-border-up "Move border up 3")
  ("C-l" move-border-right "Move border right 3")
  )
(define-key global-map (kbd "C-a") 'hydra-tmux-mode/body)
```

The problem is C-a is used quite frequently in other modes and I was wondering **if there was a way to pass C-a through to the underlying modes when it's pressed twice**. I tried foreign keys but didn't get anywhere with it.

Alternatively I could add a head that conditionally calls functions based on what major/minor mode is active but that's fairly complicated i.e.:
```elisp
("C-a" (lambda() (interactive) (cond ...) "Major/minor mode dependent")
```

**Comment by abo-abo** [comment]
> Alternatively I could add a head that conditionally calls functions based on what major/minor mode is active but that's fairly complicated i.e.:

> (define-key global-map (kbd "C-a") 'hydra-tmux-mode/body)

Your code above has lower priority than major or minor modes. Which means that <kbd>C-a</kbd> will not call `hydra-tmux-mode/body` if any current major or minor mode binds it.

So you might as well have it this way:

```elisp
(defhydra hydra-tmux-mode (:foreign-keys nil)
  "Tmux mode"
  ("C-h" move-border-left "Move border left 3")
  ("C-j" move-border-down "Move border down 3")
  ("C-k" move-border-up "Move border up 3")
  ("C-l" move-border-right "Move border right 3")
  ("C-a" move-beginning-of-line "line" :exit t))
```

No need for `cond` statements, the only thing you're overriding is the global binding <kbd>C-a</kbd> which is usually `move-beginning-of-line`.

By the way, `:foreign-keys nil` is the default setting, it's optional to specify.

**Comment by ksrb** [comment]
Oh that makes a lot of sense.
So given that I've defined my the hydra mode mapping on the global map it sits at the same 'level' as the global map.

I'm using evil mode so I've done this:
```elisp
(define-key evil-insert-state-map (kbd "C-a") 'hydra-tmux-mode/body)
```

But then I run into the same problem and the question still stands is there a way to have hydra pass C-a along to the next mode with less keybinding priority than the current one... oh.... now that I think about it this pretty complicated and not something that hydra would handle?

**Comment by abo-abo** [comment]
Passing the key to other mode is done automatically if the key isn't bound in a hydra.

The problem is that <kbd>C-a</kbd> is once again bound to `hydra-tmux-mode/body` in `evil-normal-state-map`, which has the highest priority after the hydra.  So you exit the first hydra, pass <kbd>C-a</kbd> to `evil` and it calls the second hydra.

You could try to turn off `evil` in `hydra-tmux-mode/body`, and then turn it back on somehow. But it seems too much bother.

**Comment by ksrb** [comment]
So just to be clear you mean something like this is happening:
Press <kbd>C-a</kbd> -> ```evil-normal-state-map``` ->  enters```hydra-tmux-mode/body``` -> Press <kbd>C-a</kbd> -> leaves ```hydra-tmux-mode/body``` -> <kbd>C-a</kbd> passed through picked up by ```evil-normal-state-map``` ... 

**Thinking aloud**
I'm not sure if toggling evil mode on/off is what I want. I'm trying to emulate tmux's behavior as if you had the prefix key bound to <kbd>C-a</kbd>, which means I still want evil mode keybindings active to receive <kbd>C-a</kbd>.

It sounds like I would need create some kind of minor mode with a high key priority (above ```evil``` mode), that would have would do the toggling you mentioned above. 

Alternatively I could have the hydra defined in ```evil-normal-state-map``` with a ```(cond);; with mode specific stuff``` for the <kbd>C-a</kbd> head.

Welp, this is something I can probably live without for awhile :smile:, thanks!
