### ISSUE TITLE
Error messages not getting evaluated

### ISSUE THREAD

**Issue by ackien** [abo-abo/hydra#209]
Normally, if you call e.g. `previous-line` when you're already at the top of the buffer, or call `outline-up-heading` when you're at the top level of an outline etc., you get messages like:

    Beginning of buffer
    Already at top level of the outline

But when I do the same thing with the hydra-fied versions of them, I get

    (beginning-of-buffer)
    (error "Already at top level of the outline")

**Comment by abo-abo** [comment]
More info, please. Show me the code and the key sequence.

**Comment by ackien** [comment]
A minimal example:

    (defhydra hydra-move (global-map "M-m")
      "move"
      ("p" previous-line))

Then `M-m p p p p p ...` until you reach the top of the buffer, at which point `(beginning-of-buffer)` appears in the echo area, instead of the usual `Beginning of buffer`.

For this example, I have an empty init file, and am running the code+keys in the scratch buffer, but if I put the code in my init file, use the key sequence in other buffers/modes etc. I still get the same result.

**Comment by abo-abo** [comment]
Thanks.
