### ISSUE TITLE
Cannot use window management commands using hydra

### ISSUE THREAD

**Issue by basus** [abo-abo/hydra#210]
I'm not sure if this is a bug, or a problem with what I'm doing, but I'm trying to define window management commands using the following hydra:

```emacs
(global-set-key
 (kbd "C-w")
 (defhydra hydra-window ()
   "Window Control Commands"
   ( "|"   (lambda () (interactive) (split-window-right) (windmove-right))
   ( "-"   split-window-bottom )
   ( "+"   balance-windows )
   ( "d"   delete-window )
   ( "D"   delete-other-windows )
   ( "o"   other-window)
   ( "O"   other-window-backward)
)))
```

However, when I try to run any of the commands I get a message saying `"Cannot resize the root window of a frame"`. Calling the functions either using `M-x` or their standard keybindings seems to work just fine.

**Comment by abo-abo** [comment]
You have an error in your code, here's the fixed version:

```elisp
(global-set-key
 (kbd "C-w")
 (defhydra hydra-window ()
   "Window Control Commands"
   ("|" (lambda () (interactive) (split-window-right) (windmove-right)))
   ("-" split-window-bottom)
   ("+" balance-windows)
   ("d" delete-window)
   ("D" delete-other-windows)
   ("o" other-window)
   ("O" other-window-backward)))
```

Seems to work fine for me, but some commands like `split-window-bottom` are missing.

**Comment by basus** [comment]
Ahh silly me. Thank you.
