### ISSUE TITLE
Docs out of sync with code?

### ISSUE THREAD

**Issue by alphapapa** [abo-abo/hydra#211]
I'm confused: the readme says that these keys can be passed to the `BODY-PLIST` in `defhydra`:

* `:hint`
* `:pre`
* `:post`

But when I look in Emacs itself, I see only this:

```
The heads inherit their PLIST from BODY-PLIST and are allowed to
override some keys.  The keys recognized are :exit and :bind.
:exit can be:

- nil (default): this head will continue the Hydra state.
- t: this head will stop the Hydra state.

:bind can be:
- nil: this head will not be bound in BODY-MAP.
- a lambda taking KEY and CMD used to bind a head.
```
When I try to use:

```
(defhydra a-hydra (:hint nil)
...)
```
...the hint is always displayed, even though I disabled it.  I also see many examples on the wiki using this pattern, but it doesn't seem to work.

To make it even more confusing, when I look at `hydra.el` I see plenty of references to `body-pre`, even though it's missing from the docstring.

I'm using the latest version from MELPA: 20160913.216.

Thanks for your work on Hydra.

**Comment by alphapapa** [comment]
Okay, I realized that the hints were being printed because I specified a `HINT` string, and the individual ones override the global one.  It seems confusing, though: what's the purpose of specifying `:hint` in the `defhydra` when you can just not specify one in each head?

Still not sure about the other keys missing from the docstring...

**Comment by abo-abo** [comment]
> what's the purpose of specifying :hint in the defhydra when you can just not specify one in each head?

Each head with `:hint` nil won't have its key displayed in the docstring. It's also possible to quote the hint with e.g. `?a?`.

> Still not sure about the other keys missing from the docstring...

Nothing too critical is missing. I wouldn't want to put the whole manual into the docstring.

**Comment by alphapapa** [comment]
> Nothing too critical is missing. I wouldn't want to put the whole manual into the docstring.

Oh, okay.  Might want to mention at least that there are other keys listed in the readme or wiki, because I was expecting the docstring to be comprehensive.  :)  Thanks.

**Comment by abo-abo** [comment]
> because I was expecting the docstring to be comprehensive

I kind of agree with you. But looking at the style of the Elisp docs in Emacs core, none of them are comprehensively documented in a docstring.
Only the essentials are given, and it's assumed that the user will look in info pages for extra info.

And there's a link to the wiki in the top-level comment of hydra.el.
