### ISSUE TITLE
Function called from hydra fails to respect scroll-preserve-screen-position

### ISSUE THREAD

**Issue by ivanbrennan** [abo-abo/hydra#213]
I wrote a hydra to provide some convenient scroll commands. One of its heads does a simple `scroll-down-line`. Since the text moves down relative to the window, this carries the cursor  closer to the window's bottom edge. Once it reaches the bottom, the cursor jumps midway up the window. I'd rather it stayed at the bottom of the window as the text continues to scroll, and in fact, when called outside the hydra it does exactly that.

I can reproduce this with minimal setup.
```elisp
(global-set-key (kbd "<f2>") 'scroll-down-line)
(defhydra hydra-scroll (global-map "<f3>") ("k" scroll-down-line "scroll"))
```
Scrolling with `F2` keeps the cursor at the bottom edge of the window as the buffer scrolls, but scrolling with `F3 k` causes the cursor to jump to the middle of the window when it reaches the bottom.

I've also tried with more explicit control of `scroll-preserve-screen-position` inside a wrapper function:
```elisp
(defun my-scroll ()
  (interactive)
  (let ((scroll-preserve-screen-position t))
    (scroll-down-line)))
```
I tried all variations -- `nil`, `t`, and other non-nil values. What's *really* weird is that non-nil values other than `t` *are* respected -- the buffer scrolls in a scroll-lock style and cursor stays on the same screen line.

I've tried the following scroll functions and observed the same behavior:
```elisp
(scroll-down 1)
(scroll-down-line)
(scroll-down-command 1)
```
Here are my scroll settings, though I reproduced the described behavior both with and without any of my personal settings:
```elisp
(setq scroll-step    1
      scroll-margin  0
      scroll-conservatively    200
      scroll-up-aggressively   0.0
      scroll-down-aggressively 0.0)I can reproduce this with minimal setup:
```

By the way, thanks so much for this package. It's really great!

**Comment by abo-abo** [comment]
By default, Hydra displays its tool tip in a separate window and not the echo area. It's so that if a called head wants to use the echo area, it won't interfere with the tool tip.
But creating a new window will mess up a few things, like some scrolling edge cases.

Here's a possible solution that turns off `hydra-lv` for the duration of this hydra and makes it use the echo area instead:

```elisp
(defhydra hydra-scroll (global-map "<f3>"
                        :pre (setq hydra-lv nil)
                        :after-exit (setq hydra-lv t))
  ("k" scroll-down-line "scroll"))
```

> By the way, thanks so much for this package. It's really great!

You're welcome.

**Comment by ivanbrennan** [comment]
@abo-abo Thanks for the fast response. Interestingly, your solution works unless the frame is narrow enough to force line-wrapping in the echo-area. I can work with this though, as I need to make the tooltips in this hydra more concise anyway.

Thanks for you help.
