### ISSUE TITLE
Percent sign in docstring

### ISSUE THREAD

**Issue by xiongtx** [abo-abo/hydra#215]
It's unclear how (or whether it's even possible) to have a percent sign in a hydra docstring.

For example, the following:

```
%s(format \"%d%%\" 50)
```

throws an error:

```
Debugger entered--Lisp error: (error "Not enough arguments for format string")
```

Even though `(format \"%d%%\" 50)` gives `50%`.

**Comment by abo-abo** [comment]
This works:

```elisp
(defhydra hydra-test (:hint none)
  "
_d_: ?d?
"
  ("d" delete-char (format "%d%%%%" 50)))
```

As you see, double quoting is necessary.

**Comment by xiongtx** [comment]
Ahh, the legendary Lotus Palm Tiger Heart Quadruple Percent Sign technique. Thanks!
