### ISSUE TITLE
`hydra-timeout` not working

### ISSUE THREAD

**Issue by rgtk** [abo-abo/hydra#218]
Example from [Emacs/Find file with <kbd>xf</kbd> (a29ab18)](https://github.com/abo-abo/hydra/wiki/Emacs/a29ab187d3522390203b5f0683bac3e4174721d9#find-file-with-xf) wiki page using `hydra-timeout` doesn't work:

```lisp
(defun x-hydra-pre ()
  (insert "x")
  (hydra-timeout 0.5))

(defhydra x-hydra (:body-pre x-hydra-pre
                   :color blue
                   :hint nil)
  ("f" (progn (zap-to-char -1 ?x) (ido-find-file))))

(global-set-key "x" #'x-hydra/body)
```

As stated in the text, "waiting a moment" should timeout a hydra and allow to type "xf" without calling a function. It's not, hydra is still active after few seconds.

Tested it with `emacs -q` with following code:

```lisp
(require 'hydra)

(defun x-hydra-pre ()
  (insert "x")
  (hydra-timeout 0.5))

(defhydra x-hydra (:body-pre x-hydra-pre
                   :color blue
                   :hint nil)
  ("f" (progn (zap-to-char -1 ?x) (ido-find-file))))

(global-set-key "x" #'x-hydra/body)
```

Hydra version: 0.13.6
Emacs version: 26.0.50.1

**Comment by abo-abo** [comment]
Thanks, I've updated the wiki. Here's the code that should work:

```elisp
(defun x-hydra-pre ()
  (insert "x")
  (let ((timer (timer-create)))
    (timer-set-time timer (timer-relative-time (current-time) 0.5))
    (timer-set-function timer 'hydra-keyboard-quit)
    (timer-activate timer)))
```
