### ISSUE TITLE
hydra--face: Unknown color

### ISSUE THREAD

**Issue by srid** [abo-abo/hydra#22]
I tried out the amaranth example in README, and this is what I see: `hydra--face: Unknown color for ("l" forward-char)`

For quick reference, here's the code:
```elisp
  (global-set-key
   (kbd "C-z")
   (defhydra hydra-vi
       (:pre
        (set-cursor-color "#40e0d0")
        :post
        (set-cursor-color "#ffffff")
        :color amaranth)
     "vi"
     ("l" forward-char)
     ("h" backward-char)
     ("j" next-line)
     ("k" previous-line)
     ("q" nil "quit")))
```

**Comment by abo-abo** [comment]
I think the issue here could be that you're not using the most current version.
Just update to `0.8.1` and see if the issue persists.

**Comment by srid** [comment]
`M-x package-refresh-contents` followed by `U x` (to upgrade all packages) shows that I have the following version installed:

```
  hydra              20150206.922 installed             Make bindings that stick around
```

i.e., the version installed, apparently, is "20150206.922" - however you are saying that I should update to 0.8.1. Perhaps my hydra installation was done incorrectly? I use `use-package` [as shown here](http://www.srid.ca/emacs/#sec-1-4-16) to automatically install packages.

**Comment by srid** [comment]
Oh, never mind. Restarting the emacs fixed it.

**Comment by abo-abo** [comment]
Hah, good:)
