### ISSUE TITLE
Discussion for automatic lookup of remapped command

### ISSUE THREAD

**Issue by Mugu-Mugu** [abo-abo/hydra#221]
This is a discussion for a case I have encountered:
I have an hydra that defines basic hjkl binding for magit. This hydra is meant to be inherited by other  hydra (log, status, diff etc...).
``` elisp
(defhydra mugu-magit-navigation-hydra (:color red :hint nil)
  ("b" magit-section-up "↖ section" :column "Navigation")
  ("j" magit-section-forward "↓ section")
  ("k" magit-section-backward "↑ section")
  ("l" magit-section-forward-sibling "↓ sibling section")
  ("h" magit-section-backward-sibling "↑ sibling section")
  ("g" magit-visit-thing "visit")
  ("v" (progn
         (hydra-push hydra-curr-body-fn)
         (mugu-magit-visual-hydra/body)) "visual" :color blue "visual mode"))
``` 

it happens that `magit-visit-thing` is a placeholder that is remapped according to the current magit submode. Thus calling it from hydra does nothing instead of the dynamic dispatch behavior granted by the ```[remap xxx]``` feature of standard keymap bindings.

I have a workaround by redefining the head like this:
 ``` elisp
 ("g" (call-interactively (eval '(command-remapping 'magit-visit-thing))) "visit")
``` 
But this workaround exists because I knew of the remapping in the first place. 

I think there is some cases the user might not know that a command has been remapped by some package and might bind the wrong one in an hydra. For instance, evil-integration.el performs a lot of remapping in the background and I'm sure a lot of package do the same when extending/redefining an existing feature.

### TL,DR
I think it would be nice if hydra could automatically look up for remapped command (toogleable by a property and/or a `defcustom`).
I think I will probably try to hack this feature for my configuration but if you find it sensible, I can try to implement it properly in a PR.

**Comment by abo-abo** [comment]
> I think it would be nice if hydra could automatically look up for remapped command (toogleable by a property and/or a defcustom).
> I think I will probably try to hack this feature for my configuration but if you find it sensible, I can try to implement it properly in a PR.

Sounds like a nice feature.
