### ISSUE TITLE
[Support] Creating multiple hydras with different name

### ISSUE THREAD

**Issue by jojojames** [abo-abo/hydra#225]
Hi, 

I'm trying to define duplicate hydras with different names. I'm trying to wrap the defhydra call with my own macro but I'm getting stuck on the macro definition part.

    (defmacro jojo/defhydras (names body &optional docstring &rest heads)
      `(dolist (name ',names)
         (lexical-let ((ds ,docstring))
           (eval `(defhydra ,name '@body ,ds '@heads)))))
    
    (macroexpand (jojo/defhydras (hydra-test-1 hydra-test-2)
                                 (:color blue :columns 3)
                                 "Elisp"
                                 ("u" emacs-lisp-byte-compile "Byte Compile")
                                 ("l" emacs-lisp-byte-compile-and-load "Byte Compile And Load")
                                 ("rd" byte-recompile-directory "Recompile Directory")
                                 ("rD" disassemble "Disassemble")
                                 ("z" ielm "IELM")))

I end up seeing these errors.

Error in defhydra hydra-test-1: (integer-or-marker-p quote)
Error in defhydra hydra-test-2: (integer-or-marker-p quote)

Thanks for any help!

**Comment by abo-abo** [comment]
You missed a quote in your `macroexpand` call.

Also, you should avoid using `eval` in macros. Here's a better-looking code:

```elisp
(defmacro jojo/defhydras (names body &optional docstring &rest heads)
  (cons 'progn
        (mapcar (lambda (name)
                  `(defhydra ,name ,body ,docstring ,@heads))
                names)))
(macroexpand '(jojo/defhydras (hydra-test-1 hydra-test-2)
               (:color blue :columns 3)
               "Elisp"
               ("u" emacs-lisp-byte-compile "Byte Compile")
               ("l" emacs-lisp-byte-compile-and-load "Byte Compile And Load")
               ("rd" byte-recompile-directory "Recompile Directory")
               ("rD" disassemble "Disassemble")
               ("z" ielm "IELM")))
;; =>
;; (progn
;;   (defhydra hydra-test-1 (:color blue :columns 3)
;;     "Elisp"
;;     ("u"
;;      emacs-lisp-byte-compile
;;      "Byte Compile")
;;     ("l"
;;      emacs-lisp-byte-compile-and-load
;;      "Byte Compile And Load")
;;     ("rd"
;;      byte-recompile-directory
;;      "Recompile Directory")
;;     ("rD"
;;      disassemble
;;      "Disassemble")
;;     ("z" ielm "IELM"))
;;   (defhydra hydra-test-2 (:color blue :columns 3)
;;     "Elisp"
;;     ("u"
;;      emacs-lisp-byte-compile
;;      "Byte Compile")
;;     ("l"
;;      emacs-lisp-byte-compile-and-load
;;      "Byte Compile And Load")
;;     ("rd"
;;      byte-recompile-directory
;;      "Recompile Directory")
;;     ("rD"
;;      disassemble
;;      "Disassemble")
;;     ("z" ielm "IELM")))
```

**Comment by jojojames** [comment]
Thanks! (For the solution and advice)
