### ISSUE TITLE
feature require : synchronous minibuffer

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [abo-abo/hydra#226]
sometimes it seems possible to have two function calling minibuffer at the same time(when hydra is activity)
and also can't handle two function (include hydra) simultaneously
if hydra is automatic closed when other function(like C-x C-f) local in minibuffer
it will be clearly

<img width="245" alt="2016-12-19 11 07 46" src="https://cloud.githubusercontent.com/assets/16307328/21299980/7e5fc546-c5db-11e6-8b08-518854e0bb6b.png">

**Comment by abo-abo** [comment]
Sorry, I don't understand what you're asking. Can you give an example?

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
## hydra activity
<img width="285" alt="2016-12-25 4 54 23" src="https://cloud.githubusercontent.com/assets/16307328/21470416/e095954c-cac2-11e6-9525-f05e30373bac.png">

## type C-x C-f
<img width="259" alt="2016-12-25 4 55 55" src="https://cloud.githubusercontent.com/assets/16307328/21470420/0cf3f318-cac3-11e6-8a2f-be8429301dcf.png">

## mine wish
<img width="207" alt="2016-12-25 4 57 25" src="https://cloud.githubusercontent.com/assets/16307328/21470430/78e94758-cac3-11e6-9ff3-4815fc942837.png">

**Comment by abo-abo** [comment]
The hydra will quit when you <kbd>C-x C-f</kbd> if <kbd>C-x C-f</kbd> isn't a part of it. That's the default behavior.

In your first screenshot, I see you use `amaranth` option, which specifically requests that hydra should not quit. Just adjust that option. What you see is the expected behavior.
