### ISSUE TITLE
how to use another color name build in emacs

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [abo-abo/hydra#229]
just like :color green ...

**Comment by abo-abo** [comment]
Not clear what you're asking.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
> ("q" quit-window "quit" :color blue)
how can I change blue to green?

**Comment by abo-abo** [comment]
<kbd>M-x</kbd> `customize-face` `hydra-face-blue`.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
is there a way to add green directly?
in my case
I need many colors in a hydra body
