### ISSUE TITLE
[Support] Dynamically assigning color to a hydra

### ISSUE THREAD

**Issue by yyadavalli** [abo-abo/hydra#230]
I have set of bindings that I'd like to use both as one off (`C-c j a C-c j b`) and persistent (`C-c k a b`).  The bindings I'd like to re-use are `a b` in the above examples. 

I am trying to achieve this by changing the `:color` of the hydra through inheritance. 
Is this possible? Can the achieve the same result with some other technique?

Thanks a lot for this wonderful package

**Comment by yyadavalli** [comment]
I tried writing a macro inspired by #225 
```emacs-lisp
(defmacro yy/defmultihydra (names-body &optional docstring &rest heads)
  (cons 'progn
        (mapcar (lambda (nb)
                  `(defhydra ,(car nb) ,(cdr nb) ,docstring ,@heads))
                names-body)))

(yy/defmultihydra ((hydra-test-1 :color red )
               (hydra-test-2 :color blue ))
              "Elisp"
              ("q" nil :color blue)
              ("0" sp-backward-sexp "Back")
              ("$" sp-forward-sexp "Forward"))

(progn
  (defhydra hydra-test-1 (:color pink) "Elisp"
    ("q" nil :color blue)
    ("0" sp-backward-sexp "Back")
    ("$" sp-forward-sexp "Forward"))
  (defhydra hydra-test-2 (:color blue) "Elisp"
    ("q" nil :color blue)
    ("0" sp-backward-sexp "Back")
    ("$" sp-forward-sexp "Forward")))
```

The expansion seems to working fine, but the heads in the resulting `hydra-test-2` all have color red (except for `q`).

(p.s I am new to emacs this is my first macro)

**Comment by abo-abo** [comment]
> I am new to emacs this is my first macro

Very nice, this macro is a sound way to do it.

**Comment by yyadavalli** [comment]
@abo-abo Thanks. 
Any idea why the colors are wrong, even though the expansion seems to be working?

Also any other ideas to change the properties of the hydra dynamically would be greatly appreciated

**Comment by abo-abo** [comment]
> Any idea why the colors are wrong, even though the expansion seems to be working?

Thanks for noticing, this should be fixed now. The problem was that after the expansion, the heads were two different lists. But inside the macro expansion, it's a single list. And `defhydra` modifies that list, so that the second call to `defhydra` gets a modified list instead of a fresh one.

**Comment by yyadavalli** [comment]
@abo-abo Thanks, its working now.
