### ISSUE TITLE
possible to define a nested hydra?

### ISSUE THREAD

**Issue by introom** [abo-abo/hydra#231]
Currently, hydra supports pseudo nested hydra.

(defhydra hydra-a blabla)

(defhydra my-hydra 
  "somekey" hydra-a/body ...)

I wonder if the following is supported.

(defhydra my-hydra 
  "somekey" (defhydra hydra-a blabla) ...)

**Comment by abo-abo** [comment]
> pseudo nested hydra.

There's nothing pseudo about it, each key of a hydra is associated to an interactive function, and another hydra's body is an interactive function. So you can nest them arbitrarily.

I don't want allowing `defhydra` inside `defhydra` for the same reason `defun` isn't allowed inside `defun`: it's bad design and reduces readability.

**Comment by hrehfeld** [comment]
```
(eval `(defhydra my-hydra "somekey" 
    ,(progn (defhydra hydra-a blabla) ...) 
            (quote hydra-a/body))
```

seems to work fine. Even more pretty when you wrap subhydra into your own my-defsubhydra macro that automatically returns the symbol.
