### ISSUE TITLE
Hydra and EXWM

### ISSUE THREAD

**Issue by Stebalien** [abo-abo/hydra#232]
In https://github.com/abo-abo/hydra/issues/12#issuecomment-282656458, you advised me to use `advice` to hook into hydra enabling/disabling to make it work with EXWM. Unfortunately, it doesn't appear to be working.

For example, given:

```elisp
      (define-advice hydra-keyboard-quit (:after () exwm-passthrough)
        (message "after"))
      (define-advice hydra-default-pre (:before () exwm-passthrough)
        (message "before"))
```

Hydra will print "after" *immediately* after "before" while the hydra menu is still visible.

Note: I've also tried advising `hydra-disable` but it doesn't work any better.

---

Somewhat related, advice seems like a really hacky way to do this.

**Comment by abo-abo** [comment]
> Somewhat related, advice seems like a really hacky way to do this.

Advice isn't hacky in Emacs. When you use it, means you know what you're doing. It's easily audited and controlled, and needs zero changes in the source package.

Here's what I got after fiddling with your code:

    (defhydra hydra-zoom (global-map "<f2>")
      "zoom"
      ("g" text-scale-increase "in")
      ("l" text-scale-decrease "out")
      ("r" (text-scale-set 0) "reset")
      ("0" (text-scale-set 0) :bind nil :exit t)
      ("1" (text-scale-set 0) nil :bind nil :exit t))

    (defvar test-history nil)

    (define-advice hydra-keyboard-quit (:after () exwm-passthrough)
      (unless hydra--ignore
        (push "after1" test-history)))

    (define-advice hydra-default-pre (:before () exwm-passthrough)
      (push "before" test-history))


After `f2 gggg0` the variable is `("after1" "after1" "before" "before" "before" "before" "before" "before")`, which should be good enough for your needs, I think.

Note one advantage of advice over hooks: you can't update anonymous hooks. With advice, you can use `eval-defun` to update it and have the change take effect immediately.

**Comment by Stebalien** [comment]
That's a bit buggy. If I run `hydra-zoom/body` manually instead of through the key-binding, I get an "after1" immediately after after the first "before" `(... "before" "before" <wait-for-input> "after1" "before")`. Unfortunately, spacemacs does exactly this: it manually binds `SPC l` to `spacemacs/layouts-transient-state/body`.

---

Slightly off topic...

> Note one advantage of advice over hooks: you can't update anonymous hooks. With advice, you can use eval-defun to update it and have the change take effect immediately.

Technically, that's just a property of the `define-advice` macro, not advice itself; the `define-advice` macro puts the advice in a function named `advised-function-name@advice-name`. One could easily define a `define-hook` macro that names the hook

```elisp
(define-hook hydra-pre-hook ()
  :name exwm-passthrough
  :body
  (progn ...))
```

which would `(defun hydra-pre-hook@exwm-passthrough () (progn ...))`

> Advice isn't hacky in Emacs.

From the manual:

> For these reasons, advice should be reserved for the cases where you cannot modify a function’s behavior in any other way. If it is possible to do the same thing via a hook, that is preferable (see Hooks). If you simply want to change what a particular key does, it may be better to write a new command, and remap the old command’s key bindings to the new one (see Remapping Commands). In particular, Emacs’s own source files should not put advice on functions in Emacs. (There are currently a few exceptions to this convention, but we aim to correct them.) 

Based on my reading, this *is* a valid use-case for advice but a hook would be preferable if you are willing to add one. However, I'm still an EMACS newbie so I may be misunderstanding this passage.

Given that advice may be considered more palatable than I thought, is the following considered kosher?:

```elisp
      (add-variable-watcher 'hydra-curr-map
                            (lambda (s value o w)
                              (setq exwm-input--line-mode-passthrough (not (null value)))))
```

**Comment by abo-abo** [comment]
> Based on my reading, this is a valid use-case for advice but a hook would be preferable if you are willing to add one. However, I'm still an EMACS newbie so I may be misunderstanding this passage.

Hooks are fine, and good hooks are good. But many packages have too much hooks that inexperienced users like to change by copy pasting snippets from the internet.
When some inter-package interaction goes wrong, it's very often due to some hook being used that the user was not aware of.

Hydra is still a new package. I'm fine with adding a hook or two if they are really necessary. But I'd rather avoid gratuitous hooks.

Also note that the statement in the manual was written way back, before the new advice system that landed a few years ago.

> Given that advice may be considered more palatable than I thought, is the following considered kosher

I don't have `add-variable-watcher` on my system.

**Comment by abo-abo** [comment]
> That's a bit buggy. If I run hydra-zoom/body manually instead of through the key-binding, I get an "after1" immediately after after the first "before" (... "before" "before" <wait-for-input> "after1" "before"). Unfortunately, spacemacs does exactly this: it manually binds SPC l to spacemacs/layouts-transient-state/body.

See `hydra--ignore` from my snippet above. You can bind it in your code.

**Comment by Stebalien** [comment]
> I don't have add-variable-watcher on my system.

It may be new in emacs 26.

> See hydra--ignore from my snippet above. You can bind it in your code.

In the `hydra-default-pre` advice? That's definitely hacky.

---

Regardless, I've found an advice solution that works well:

```elisp
      (define-advice hydra-set-transient-map (:around (fun keymap on-exit &optional foreign-keys) exwm-passthrough)
        (setq exwm-input--line-mode-passthrough t)
        (let ((on-exit (lexical-let ((on-exit on-exit))
                         (lambda ()
                           (setq exwm-input--line-mode-passthrough nil)
                           (when on-exit (funcall on-exit))))))
          (funcall fun keymap on-exit foreign-keys)))
```
