### ISSUE TITLE
Switches à la magit-popup ?

### ISSUE THREAD

**Issue by vindarel** [abo-abo/hydra#234]
Hi !
It would be great if hydras could have switches, like in a `magit-popup` buffer. Has that any chance to happen ? 
(it wasn't really asked before ?)

magit-popup is great but… it doesn't have hydra's features, which is what I  am using. 

##### My use case

My use case is the following: I'd like each action of my hydra to act on something slightly different depending on the switch: I have actions kill, copy, comment, … that by default act on an indentation tree, and I'd like to make them act on a paragraph (or something else) with a switch. 

I first considered:
- lower and upper case letters but that's only 2 switches, 
- then more keys, unreadable with a few actions, 
- then sub-hydras that would ask again on what to act (so a key for indentation, paragraph, …) which is a bit long **and** that doesn't remember my previous choice. With a switch, I could choose it first, and then fire many actions in a row.

The last possibility could be to create as many hydras as switches (hydra-act-on-paragraph, hydra-act-on-indentation, …) and has many keybindings.

Thanks !

**Comment by abo-abo** [comment]
See `hydra-ox.el`.

**Comment by vindarel** [comment]
Looks there is all we need !

I saw a `defhydradio` (not documented ;) ) that defines parameters that we can toggle with `C-key`.

```
(defhydradio hydra-ox ()
  (body-only "Export only the body.")
…
```
it's like a button radio. Looks like it's even persistent. We'll be able to use the variable `hydra-ox/body-only`. In our hydra we define the keys to switch them:

```
(defhydra hydra-ox ()
  "
_C-b_ Body only:    % -15`hydra-ox/body-only
"
…
```

and we just use our switches as variables:

```
("h" (org-html-export-to-html
        hydra-ox/async-export
        (eq hydra-ox/export-scope 'subtree)
        hydra-ox/visible-only
        hydra-ox/body-only) "As HTML file")
```

hydra-ox: https://github.com/abo-abo/hydra/blob/master/hydra-ox.el
hydradio: https://github.com/abo-abo/hydra/blob/master/hydra.el#L1312

Great !
Thanks.

**Comment by abo-abo** [comment]
@vindarel Looks like your problem is solved. Please close the issue if that's the case.

**Comment by vindarel** [comment]
I also try to use `C-b` but its original function `evil-scroll-page-up` takes precedence. Is there something to know about this ?

```
(defhydradio indent-tools-switches ()
  (on-indentation "doc")
…

(defhydra indent-tools-hydra (:color red :hint nil)
  "
_C-b_ Indentation block: % -5`indent-tools-switches/on-indentation'
"
  ("C-b" (indent-tools-switches/on-indentation) t)
```

thanks

**Comment by abo-abo** [comment]
No idea. I thought hydra keys take precedence over evil.
