### ISSUE TITLE
Named columns and column numbers

### ISSUE THREAD

**Issue by unbildung** [abo-abo/hydra#235]
I very much like using the `:column` feature described here: https://github.com/abo-abo/hydra/wiki/internals#column. Is there a way to avoid having the column number showing up in the hint? The example in the wiki is as follows:

```
(defhydra hydra-window
                (:color red :hint nil)
               "
                               -- WINDOW MENU --

"
               ("z" ace-window "ace" :color blue :column "1-Switch")
               ("h" windmove-left "← window")
               ("j" windmove-down "↓ window")
               ("k" windmove-up "↑ window")
               ("l" windmove-right "→ window")
               ("s" split-window-below "split window" :color blue :column "2-Split Management")
               ("v" split-window-right "split window vertically" :color blue)
               ("d" delete-window "delete current window")
               ("f" follow-mode "toogle follow mode")
               ("u" winner-undo "undo window conf" :column "3-Undo/Redo")
               ("r" winner-redo "redo window conf")
               ("b" balance-windows "balance window height" :column "4-Sizing")
               ("m" maximize-window "maximize current window")
               ("M" minimize-window "maximize current window")
               ("q" nil "quit menu" :color blue :column nil))
```

Which generates this hint:

```
     -- WINDOW MENU --


1-Switch    | 2-Split Management         | 3-Undo/Redo         | 4-Sizing
----------- | -------------------------- | ------------------- | --------------------------
z: ace      | s: split window            | u: undo window conf | b: balance window height
h: ← window | v: split window vertically | r: redo window conf | m: maximize current window
j: ↓ window | d: delete current window   |                     | M: maximize current window
k: ↑ window | f: toogle follow mode      |                     |
l: → window |                            |                     |
[q]: quit menu.
```

I would like the column named "1-Switch" to appear simply as "Switch". I understand that the "1-" prefix helps with sorting the columns and displaying them in the right order. But is there a way to have the hint be stripped of the column number when being displayed?

Thanks for reading and thanks for your work!

**Comment by abo-abo** [comment]
Simple, replace `"1-Switch"` with `"Switch"` in your code.

**Comment by unbildung** [comment]
Thanks. My question may have been unclear. I am asking about the hint layout. The problem with your suggestion is that the columns are ordered alphabetically in the hint. Renaming `"1-Switch"`, `"2-Split Management"`, etc. without the numbers makes the columns display in a different order from the original one, with `Sizing` at extreme left and `Undo-Redo` at extreme right. I want to order/number the columns, but I don't want the numbers to appear in the hint. This isn't a major issue of course; but with the named columns feature your package is getting to the point where very little of the hint layout has to be arranged manually, and I think the change I am suggesting would be in keeping with the spirit of that. I'm not sure how complicated it would be to implement.

**Comment by Mugu-Mugu** [comment]
Hello, I participated to the implementation of this feature, so I'm interested in improving it provided @abo-abo approves the change (as you said, its a minor issue). 

The biggest problem would be to define a simple and consistent interface that would allow user to define the column order. I don't think this should be done during initial `defhydra` generation as it would be very cumbersome to write. Imho, the best would be a post-definition optional mechanism such as `ivy-set-action`. Maybe something like:
```elisp
(defun hydra-set-column-order (hydra-name column-sort-fun)
" Recompute docstring of an hydra defined with HYDRA-NAME using COLUMN-SORT-FUN.
COLUMN-SORT-FUN must be a comparison function between 2 string.")
```
That would require that we record arguments `body` and `docstring` during defhydra call (we already do this for `heads`).
```elisp 
(defmacro defhydra (name body &optional docstring &rest heads))
```

**Comment by abo-abo** [comment]
@Mugu-Mugu I would prefer to just number the columns in the order that they appear in `defhydra`. This seems like a very reasonable default, and it's very flexible if the users wants to move some s-expressions around.

**Comment by Mugu-Mugu** [comment]
Indeed, it is a better default and it seems easy enough to implement. It would not enable full order control for hydra with inherited heads with column but I don't think this is a common use case.

I'll open a PR with your idea.

**Comment by unbildung** [comment]
Thank you both! This sounds great.

**Comment by abo-abo** [comment]
Closing the issue. Thanks again, @Mugu-Mugu .
