### ISSUE TITLE
case insensitivity in hydra heads

### ISSUE THREAD

**Issue by wbolster** [abo-abo/hydra#238]
is it possible to have a hydra that reacts to both `b` (lowercase) and `B` (uppercase) without specifying two (almost identical) heads?

**Comment by abo-abo** [comment]
No, it's not possible. Support for this could be added, but I don't think it's worth it.

**Comment by wbolster** [comment]
ok, thanks for the reply. i'll try to hack something into my helper routines to accomplish my (perhaps arcane) desires.
