### ISSUE TITLE
Unable to call M-x when within a Hydra

### ISSUE THREAD

**Issue by sawan** [abo-abo/hydra#240]
Consider the following Hydra and its helper:

```elisp

(defun warn-hydra-move()
  (ov-set (ov-line (point)) 'face '(:foreground "red"))
  (sit-for 0.5)
  (ov-clear))

(defhydra hydra-move
  (:timeout 5
	    :pre (warn-hydra-move)
	    :post (ov-clear))
  "move"
  ("a" smarter-move-beginning-of-line)
  ("e" move-end-of-line)
  ("n" next-line)
  ("p" previous-line)
  ("f" forward-char)
  ("b" backward-char)
  ("w" forward-word)
  ("q" backward-word)
  ("d" scroll-up)
  ("u" scroll-down)
  ("t" beginning-of-buffer)
  ("T" end-of-buffer)
  ("g" avy-goto-line "goto-line")
  ("c" avy-goto-char-2 "goto-char-2")
  ("l" recenter-top-bottom "re-center")
  ("<ESC>" nil "quit" :color blue)
  ("<return>" nil "quit" :color blue)
  ("<RETURN>" nil "quit" :color blue)
)

(global-set-key (kbd "C-n") #'hydra-move/next-line)
(global-set-key (kbd "C-p") #'hydra-move/previous-line)
(global-set-key (kbd "C-f") #'hydra-move/forward-char)
(global-set-key (kbd "C-b") #'hydra-move/backward-char)
(global-set-key (kbd "M-f") #'hydra-move/forward-word)
(global-set-key (kbd "M-b") #'hydra-move/backward-word)
```

This works fine ***except*** in the case when you wish to abort the hydra by doing `M-x` i.e `execute-extended-command`.  In fact it doesn't work when you try to execute anything that begins with `M-`.  Strangely enough, executing commands starting with `C-` works perfectly i.e. executes the command and returns back to the hydra.

Example:

1. Activate hydra.
2. Navigate to the line you want.
3. Mark region with `C-space`.  Note: *Hydra is still active.*
4. Navigate further using the hydra keys.
5. `M-w` to copy the marked region

At this point, the following message is displayed and nothing is copied: 
`M-x is undefined `

Even changing the hydra to accommodate `M-x` does not work.
```elisp
(defhydra hydra-move
  (:timeout 5
	    :pre (warn-hydra-move)
	    :post (ov-clear))
  "move"
  ("a" smarter-move-beginning-of-line)
  ("e" move-end-of-line)
  ("n" next-line)
  ("p" previous-line)
  ("f" forward-char)
  ("b" backward-char)
  ("w" forward-word)
  ("q" backward-word)
  ("d" scroll-up)
  ("u" scroll-down)
  ("t" beginning-of-buffer)
  ("T" end-of-buffer)
  ("g" avy-goto-line "goto-line")
  ("c" avy-goto-char-2 "goto-char-2")
  ("l" recenter-top-bottom "re-center")
  ("<ESC>" nil "quit" :color blue)
  ("<return>" nil "quit" :color blue)
  ("<RETURN>" nil "quit" :color blue)
  ("<M-x>" smex :color blue)
)
```

Any ideas?

**Comment by abo-abo** [comment]
> ("<ESC>" nil "quit" :color blue)

There's your problem. <kbd>M-x</kbd> and <kbd>ESC x</kbd> are similar. Removing that one head fixes the problem.

Off topic, I really wonder why you want to add `0.5`s keyboard lag with `sit-for`.

**Comment by sawan** [comment]
Oh wow. Fixed.

Re. the `(sit-for 0.5)`: This hydra is slightly mad but also save a lot of key-presses when used. So I'm using that function to flash me a **brief visual indicator** (via changing the text color) that I am within the hydra and should use the shorter keys provided as opposed to the `C-n, C-p, C-f, M-f` etc that are bound in my muscle memory.

I am still tuning the visual indicator. I would like something more 'prominent but discreet' (maybe a corner of the buffer turns a different color?) but out of constant exasperation have resorted to using what I know: the `ov.el` library. I will be exploring the doc string option as well -- that should make the minibuffer grow bigger and stick around as a visual indicator.

Happy for you to suggest something else?

Many thanks for your stellar work on this and Avy.

**Comment by sawan** [comment]
@abo-abo `0.5` had been changed to `0.3` since I posted.

**Comment by abo-abo** [comment]
> I would like something more 'prominent but discreet'

I simply change the cursor color:

```elisp
(defhydra hydra-vi (:pre (set-cursor-color "#e52bff")
                    :post (set-cursor-color "#ffffff")
                    :color pink
                    :hint none)
  "
vi. arr: _h__j__k__l_, word: _w__b_, sen: _(__)_, par: _{__}_ del: _x__d_, quit: _q_"
  ;; movement
  ("w" hydra-vi-w)
  ("b" backward-word)
  ("E" forward-word)
  ;; scrolling
  ("C-v" scroll-up-command nil)
  ("M-v" scroll-down-command nil)
  ("v" recenter-top-bottom)
  ;; arrows
  ("h" hydra-vi-h)
  ("j" hydra-vi-j)
  ("k" previous-line)
  ("l" hydra-vi-l)
  ;; sentences
  ("(" hydra-vi-op)
  (")" hydra-vi-cp)
  ;; paragraphs
  ("{" hydra-vi-ob)
  ("}" hydra-vi-cb)
  ;; delete
  ("x" delete-char)
  ("d" hydra-vi-d "del")
  ("u" undo)
  ;; misc
  ("f" hydra-vi-f)
  ("r" hydra-vi-r)
  ("." hydra-vi-dot)
  ("," hydra-vi-comma)
  ;; bad
  ("m" set-mark-command "mark")
  ("a" move-beginning-of-line "beg")
  ("e" move-end-of-line "end")
  ("y" kill-ring-save "yank" :exit t)
  ;; avy
  ("g" avy-goto-char)
  ;; exit points
  ("q" nil "ins")
  ("C-n" (forward-line 1) nil :exit t)
  ("C-p" (forward-line -1) nil :exit t))
(hydra-set-property 'hydra-vi :verbosity 1)
```

> Many thanks for your stellar work on this and Avy.

You're welcome. I close the issue.

**Comment by sawan** [comment]
@abo-abo 

Sometimes the most obvious solutions are overlooked.

I am going to combine this with my solution: on hydra activate, flash the line and change cursor color, one hydra exit, flash again and restore cursor color.

**Comment by sawan** [comment]
@abo-abo 

One question about ```:pre (set-cursor-color "#e52bff")``` and similar approaches: isn't it rather expensive to run and re-run this on every head? I tried using `:body-pre` but it did not work.

**Comment by abo-abo** [comment]
> isn't it rather expensive to run and re-run this on every head?

Not really. So you move the cursor: the work to redraw it at new position encompasses the work to change the color.

> I tried using :body-pre but it did not work.

`:body-pre` works if your only entry point is e.g `hydra-move/body`. But you have other entry points, like `hydra-move/next-line`, `hydra-move/previous-line` etc.
