### ISSUE TITLE
(invalid-function remove-function) in when launching hydra

### ISSUE THREAD

**Issue by jdahm** [abo-abo/hydra#241]
I'm getting an error with the version oh hydra in melpa-stable on some remote machines using the CLI. This is the setup

```
(defhydra hydra-counsel (:color blue)
  ("r" ivy-resume "resume")
  ("i" counsel-imenu "imenu")
  ("g" counsel-git "git")
  ("j" counsel-git-grep "grep")
  ("u" counsel-unicode-char "unicode")
  ("f" counsel-locate "find")
  ("a" counsel-ag "ag")
  ("l" counsel-info-lookup-symbol "symbol")
  ("m" bookmark-jump "bookmark"))
(global-set-key (kbd "C-x c") #'hydra-counsel/body)
```

Gives this error when typing `C-x c`
```
Debugger entered--Lisp error: (invalid-function remove-function)
  remove-function(list hydra--imf)
  hydra-disable()
  hydra-keyboard-quit()
  (let ((hydra--ignore nil)) (hydra-keyboard-quit) (setq hydra-curr-body-fn (quote hydra-counsel/body)))
  hydra-counsel/body()
  funcall-interactively(hydra-counsel/body)
  call-interactively(hydra-counsel/body nil nil)
  command-execute(hydra-counsel/body)
```

I'm using Emacs 25.1.1 that I compiled on the machine. Can you give me some guidance on how to resolve this issue?

**Comment by abo-abo** [comment]
`remove-function` is defined in nadvice.el. Try `(require 'nadvice)`.

**Comment by jdahm** [comment]
I just tried adding the `require' before hydra loads, and/or before and/or after the definition of the hydras, but nothing removed the error. This is really strange because I see you even check with `fbound' if it's defined

```
    (if (fboundp 'remove-function)
        (remove-function input-method-function #'hydra--imf)
```

**Comment by abo-abo** [comment]
Might be a byte compiler issue. Remove hydra.elc and restart. Maybe remove also your own elc file and nadvice.elc later.

**Comment by jdahm** [comment]
Removing the package from the `elpa/` directory and letting it recompile worked. Thanks!
