### ISSUE TITLE
hydra-global-org/body: Symbol’s function definition is void: hydra-default-pre

### ISSUE THREAD

**Issue by paul-alkhimov** [abo-abo/hydra#242]
I took the code from https://oremacs.com/2015/04/14/hydra-org-mode/

For the first time `hydra` worked fine (after I manually executed the code).

Then, after the restart of Emacs I get
`hydra-global-org/body: Symbol’s function definition is void: hydra-default-pre`

I put the `hydra` in the list of required packages, so it is guarantied to be required.

In case you want to check or reproduce my setup, it is here (I have just committed the config with this bug): https://github.com/paul-alkhimov/emacs-configurations

**Comment by paul-alkhimov** [comment]
PS. Windows, GNU Emacs 25.1.1 (i686-w64-mingw32) of 2016-11-16

**Comment by abo-abo** [comment]
Looks like a byte compiler issue. Recompile the relevant files and restart Emacs.

**Comment by paul-alkhimov** [comment]
I have just compiled complete .emacs.d folder from the scratch. It remains. BTW, it is same on Linux, emacs25.

**Comment by paul-alkhimov** [comment]
You implement the hydra with macros, right?

**Comment by paul-alkhimov** [comment]
Damn, I found. It is my bad. Loaded, but not required. I have two separate lists. Don't ask, why.
Anyway, sorry. Maybe this thread will help anyone in future.
