### ISSUE TITLE
Keys not sent to hydra in EXWM X window buffers

### ISSUE THREAD

**Issue by QiangF** [abo-abo/hydra#243]
Exwm is a popular window manager using emacs
(https://github.com/ch11ng/exwm/wiki). I have the following setting to scroll windows.

   (when (package-installed-p 'hydra)
     (defhydra hydra-window-scroll (:color red)
       "Scroll other window"
       ("n" joe-scroll-other-window "scroll")
       ("p" joe-scroll-other-window-down "scroll down"))
     (add-to-list 'aw-dispatch-alist '(?o hydra-window-scroll/body) t))

The above fails to work in X window buffers, after hydra-window-scroll/body is
called, keys are send to the X window. I don't know how hydra works. If hydra
can let the focus change to minibuffer and keep it until it quits, it may work
in this case.

**Comment by QiangF** [comment]
Sovled in https://github.com/ch11ng/exwm/issues/254

**Comment by abo-abo** [comment]
Thanks.

**Comment by WJCFerguson** [comment]
Am I understanding this correctly?  To make hydras work from X window buffers, we need to set `exwm-input-line-mode-passthrough` to `t` on entry to the hydra and set it to `nil` on exit?  This could be done with advice (on `<hydra-name>/body`), but I think it also works with 
``` elisp
(defhydra xxxx (...
                         :body-pre (setq exwm-input-line-mode-passthrough ''t)
                         :post (setq exwm-input-line-mode-passthrough nil))
```

At least this seems to be working for me, but I haven't tested very thoroughly yet.

Thank you both @abo-abo and @QiangF.

**Comment by QiangF** [comment]
I have to use           (apply orig-fun keymap on-exit (list foreign-keys))     to get rid of a error in the latest hydra.

    (defun exwm-passthrough (orig-fun keymap on-exit &optional foreign-keys)
        (setq exwm-input-line-mode-passthrough t)
        (let ((on-exit (lexical-let ((on-exit on-exit))
                        (lambda ()
                        (setq exwm-input-line-mode-passthrough nil)
                        (when on-exit (funcall on-exit))))))
          (apply orig-fun keymap on-exit (list foreign-keys))))

    (advice-add 'hydra-set-transient-map :around #'exwm-passthrough)
