### ISSUE TITLE
pink hydra - wrong type argument

### ISSUE THREAD

**Issue by sho-87** [abo-abo/hydra#244]
I'm trying to set up a zoom hydra so that when I press `SPC z +` it will increase text size. I'd like to use a pink hydra so incorrect key presses wont close the hydra menu

I'm using general to define a top level menu (`SPC`):

```
(general-define-key
 :states '(normal visual emacs)
 :prefix "SPC"
 :non-normal-prefix "C-SPC"

 "SPC" 'helm-M-x
 "z" '(hydra-zoom/body :which-key "zoom")
 )
```

And my hydra looks like this:

```
(defhydra hydra-zoom (:color pink)
  "
Zoom
----
_+_ in
_-_ out
_r_eset
"
  ("+" text-scale-increase)
  ("-" text-scale-decrease)
  ("r" (text-scale-adjust 0) :color blue)
  )

```

When I press `SPC z` I'm expecting to see the hydra menu, but instead it gives me an error:

`Wrong type argument: commandp, hydra-zoom/body`

When I change the hydra colour to `red`, for example, everything seems to work

Am I using the color incorrectly?

**Comment by abo-abo** [comment]
Your `defhydra` statement is correct and works for me if I do e.g.:

    (global-set-key (kbd "C-c t") 'hydra-zoom/body)

Check if there's any problem with `general-define-key`, I'm not familiar with that package.

**Comment by sho-87** [comment]
I couldn't find anything about evil mode in the wiki - does it still work for you if you try to bind only in evil normal state (which is what my original was doing via general)?

**Comment by sho-87** [comment]
This seems to be working now with the original code - I'm not sure what the issue was
