### ISSUE TITLE
Numbers got sent to hydra--digit-argument as arguments which is not what I want.

### ISSUE THREAD

**Issue by beacoder** [abo-abo/hydra#247]
I used to use hydra combind with multiple-curosor mode to insert number into files.
but recently with hydra--digit-argument, after me using hydra to mark a few lines, and try to insert the number.
but the numbers all treated as global-argument, which is definitly not what I wanted.

Is there anything I could do to fix this ?

**Comment by beacoder** [comment]
Here is my hydra config:

(defhydra hydra-multiple-cursors (:hint nil)
  "
     ^Up^            ^Down^        ^Other^
----------------------------------------------
[_p_]   Next    [_n_]   Next    [_l_] Edit lines
[_P_]   Skip    [_N_]   Skip    [_a_] Mark all
[_M-p_] Unmark  [_M-n_] Unmark  [_r_] Mark by regexp
^ ^             ^ ^             [_q_] Quit
"
  ("l" mc/edit-lines :exit t)
  ("a" mc/mark-all-like-this :exit t)
  ("n" mc/mark-next-like-this)
  ("N" mc/skip-to-next-like-this)
  ("M-n" mc/unmark-next-like-this)
  ("p" mc/mark-previous-like-this)
  ("P" mc/skip-to-previous-like-this)
  ("M-p" mc/unmark-previous-like-this)
  ("r" mc/mark-all-in-region-regexp :exit t)
  ("q" nil))
(global-set-key (kbd "C-x m")  'hydra-multiple-cursors/body)

**Comment by abo-abo** [comment]
The default behavior for <kbd>0</kbd>-<kbd>9</kbd> is `digit-argument`.

If you don't like it, redefine `hydra-base-map` in your config:

    (setq hydra-base-map (make-sparse-keymap))

**Comment by beacoder** [comment]
Thanks, I will have a try.

**Comment by abo-abo** [comment]
You're welcome.
