### ISSUE TITLE
Add a defcustom for a default :idle duration

### ISSUE THREAD

**Issue by angrybacon** [abo-abo/hydra#248]

**Comment by abo-abo** [comment]
I don't think it's viable. Most users will not want to have `:idle` on for all of their hydras, so that leaves turning it on for each hydra as it is now. When doing that, might as well specify the duration, since it's a plist format anyway: `:idle 2.0` is simpler than `:idle t` + some custom var.

**Comment by angrybacon** [comment]
Not sure what you had in mind. But I was referring to have a variable with default to `nil`. If the variable is a number then idle all heads that don't have a idle timer specified.

**Comment by abo-abo** [comment]
Keeping the variable at `nil` is the current behavior.

Setting the variable to anything but `nil` isn't convenient: all your new hydras will have a delay, even though you really need the hint. You might say that there should be a way to override the setting in a new hydra, but that's just added incidental complexity compared to the current setup.

In my experience, I have only a single hydra with `:idle 0.8`; I haven't added it to any other of my hydras.

**Comment by angrybacon** [comment]
> all your new hydras will have a delay

Exactly, that's the whole point. That way, I don't have to mention it for my 10-something hydras, nor for the next I'll write.

> but that's just added incidental complexity

That, however, I can understand. 

Please note though, I mainly use `hydra` to group up keybindings and the visual cue is secondary (after all, I added the heads myself and I know what they do), although it *is* useful from time to time. So, for anyone in my case, you can see how that variable can be useful. Useful in the same way specifying the color can be done either on the hydra or directly on the heads.

**Comment by abo-abo** [comment]
Might be useful to add a default value for the whole `body-plist` arg of `defhydra`. But that's a good amount of work to make sure it works correctly. Currently, the repo is very stable: no new stuff means no random bugs.

I don't have a lot of free time in the next few months. But if anyone wants to add this feature with proper testing, it's fine with me.
