### ISSUE TITLE
Use-package keyword?

### ISSUE THREAD

**Issue by therockmandolinist** [abo-abo/hydra#250]
This seems fairly low priority, but it would be cool to have hydra integration with use-package via a keyword, as in (kind of a hydra equivalent to the :bind keyword?):

```emacs-lisp
(use-package evil-multiedit
  :hydra
  (hydra-multiedit
   (:hint nil)
   "
multiedit:
_r_estore  _t_oggle/restrict  match _a_ll
_n_ext     match and _N_ext   _q_: abort
_p_rev     match and _P_rev
"
   ("a"   evil-multiedit-match-all)
   ("n"   evil-multiedit-next)
   ("p"   evil-multiedit-prev)
   ("r"   evil-multiedit-restore)
   ("t"   evil-multiedit-toggle-or-restrict-region)
   ("N"   evil-multiedit-match-and-next)
   ("P"   evil-multiedit-match-and-prev)
   ("q"   evil-multiedit-abort :exit t)))
```
I only ask this because I have a bunch of `with-eval-after-load` hydras that I feel could be better integrated to the package declaration itself. I've worked (briefly) with use-package keywords before, so I wouldn't be opposed to looking into this myself, though I don't have an FSF copyright assignment yet.

**Comment by therockmandolinist** [comment]
On second thought, this seems kinda superfluous, since I could just but the `defhydra` in the `:config` section, obviously.

**Comment by abo-abo** [comment]
Agreed :)
