### ISSUE TITLE
command hints not showing when inheriting from :hint none

### ISSUE THREAD

**Issue by marczz** [abo-abo/hydra#254]
Say that I have this code:

    (defhydra hydra-test (:hint none);
      "
    _ a_ctive region=?a?"

      ("a"
      (if (region-active-p)
          (deactivate-mark)
        (push-mark-command nil))
           (if (region-active-p)
               "[x]" "[ ]"))
      ("A" (if (region-active-p)
          (deactivate-mark)
          (push-mark-command nil))
       :hint "Set Mark")
      ("g" nil))`

Both "a" and "A" keys work ok but the hint  "Set Mark" is not shown.
If I put  `(:hint nil)` in the `defhydra` I get an error for the "a" hint sexp.

Of course I can use as docstring:

     "
    _ a_ctive region=?a?
    _A_ ?A?"

and remove the `:hint` keyword and it will work as expected, but what is needed is too mix both the extended syntax and the automatic `:hint` display.

I also suggest that you explain in the documentation this use of `'none`  for the extended docstring syntax, I spent a couple of hours before understanding that my code is rejected if I put an other hint or nothing in the `defhydra`.

**Comment by abo-abo** [comment]
Thanks. I made a small fix, this should work better now:

```elisp
(defhydra hydra-test ()
  "
_a_ctive region=?a?
"
  ("a"
   (if (region-active-p)
       (deactivate-mark)
     (push-mark-command nil))
   (if (region-active-p)
       "[x]" "[ ]"))
  ("A" (if (region-active-p)
           (deactivate-mark)
         (push-mark-command nil))
       "Set Mark")
  ("g" nil))
```


> I also suggest that you explain in the documentation this use of 'none for the extended docstring syntax

PRs welcome.

**Comment by marczz** [comment]
OK your abo-abo@b4fb3298cd071d56aa9a5fc6be51ae9871ad451e fix the problem I can use as you say `defhydra hydra-test ()` which add the hint for "A" but also an empty hint for "g". But what I need and is working perfectly now is `defhydra hydra-test (:hint nil)` which add the hint for "A"  and nothing for "g".

About my request to _explain in the documentation this use of 'none_, with your fix it boils down to _don't use it!_ 😊
