### ISSUE TITLE
Unrecognized key warnings with Company Mode

### ISSUE THREAD

**Issue by jojojames** [abo-abo/hydra#255]
Recipe:
```
(add-to-list 'load-path "/Users/james/.emacs.d/elpa/25/hydra-20170813.1058")
(add-to-list 'load-path "/Users/james/.emacs.d/elpa/25/company-20170828.414")

(require 'hydra)
(require 'company)
(company-mode)

(defhydra hydra-emacs-lisp-mode (:color blue :hint nil)
  "

    Elisp:

    ^^Do^^
  ------------------------------------------------------------------------------
     _l_ Library
     _f_ Function
     _v_ Variable

"
  ("s" aaa| ;; type "aaa" --> throws unrecognized key warnings
  ("l" find-library)
  ("f" find-function)
  ("v" find-variable))

;; or

(defhydra hydra-emacs-lisp-mode (:color blue :hint nil)
  "
    Elisp:
        _l_ Library
     f Function
     v Variable

"
  ("s" aaasssssssssfsafasfsfssfffff ;; throws unrecognized key warnings
  ("l" find-library)
  ("f" find-function)
  ("v" find-variable))

```

Warnings:
```
Warning (emacs): Unrecognized key: _l_
Warning (emacs): Unrecognized key: _f_
Warning (emacs): Unrecognized key: _v_
Warning (emacs): Unrecognized key: _l_
Warning (emacs): Unrecognized key: _f_
Warning (emacs): Unrecognized key: _v_
```

**Comment by abo-abo** [comment]
This is actually a `company` issue, not a `hydra` issue.

Fix with:

```elisp
(add-to-list 'company-backends 'company-elisp)
```

@dgutov could you look into this? Looks like you put `company-elisp` on `company-backends` by default only for older Emacs versions. This issue shows it's needed in the new ones as well.

**Comment by dgutov** [comment]
@abo-abo How does it show that? The newer versions should use `company-capf` with built-in completion. It's pretty capable these days.

**Comment by abo-abo** [comment]
> The newer versions should use company-capf with built-in completion. It's pretty capable these days.

I agree that `company-capf` is probably better. Still, the above issue remains, and the above "fix" works. It looks like `company-capf` is evaluating/macroexpanding the code around the cursor. I don't think it should do that.

**Comment by dgutov** [comment]
> It looks like company-capf is evaluating/macroexpanding the code around the cursor.

It does. And it's a handy way to find all local variables generated by arbitrary macros. So the completion code doesn't need to know all the macros in advance.

**Comment by dgutov** [comment]
> I don't think it should do that.

You're free to report that to Emacs, but if it's at all possible to fix on your side, you should rather do that.

**Comment by abo-abo** [comment]
@dgutov OK, I see the same issue with `complete-symbol`, not just `company`. Sorry for the noise.
@jojojames I added a workaround that detects macroexpansion by elisp-mode.el. Please test.

**Comment by jojojames** [comment]
Thanks, working for me!
