### ISSUE TITLE
Feature request: Optional delay in showing hydra

### ISSUE THREAD

**Issue by diamond-lizard** [abo-abo/hydra#258]
When a hydra/body is called, I'd like there to be a user-customizable delay during which the hydra does not show but only reads keystrokes so that if the user types one of the keystrokes in the hydra the corresponding action can be taken without even displaying the hydra at all.  On the other hand, if that delay expires without the user typing anything, the hydra can be shown as usual.

Ideally, there'd be a global setting, along with a per-hydra way of overriding it, so different hydras could potentially have different display delays.  Also, it would be nice to have sub-second resolution for the delay, to accommodate fast typers.

This would be really useful for me as I have a large number of nested hydras and good muscle memory for many of the keystrokes, so that I really don't need to see the hydras popping up all over the place most of the time.  But occasionally I do need to see them -- especially for less-frequently-used keystroke combinations and actions -- and that's when I'd like to have them show up.  I think this delay feature would be a good way to address this use case.

**Comment by abo-abo** [comment]
There's already a feature for this: add `:idle 1.5` to the body description; see the docs for more info.

**Comment by diamond-lizard** [comment]
Thanks!  This feature does exactly what I need!

**Comment by abo-abo** [comment]
You're welcome.
