### ISSUE TITLE
functions might not be defined at runtime

### ISSUE THREAD

**Issue by liuxueyang** [abo-abo/hydra#259]
When I turn on `flycheck-mode` in `init.el` with the following configuration:

```elisp
(use-package hydra
  :config
  (defhydra hydra-zoom (global-map "<f2>")
    "Zoom"
    ("g" text-scale-increase "in")
    ("l" text-scale-decrease "out")))
```

I got the following warning:

```
the following functions might not be defined at runtime: hydra-default-pre, hydra-keyboard-quit, hydra--call-interactively-remap-maybe, hydra-show-hint, hydra-set-transient-map
```

After some googling and read some info about elisp, I found two solutions:

1. use `with-no-warnings`

```elisp
(use-package hydra
  :config
  (with-no-warnings
    (defhydra hydra-zoom (global-map "<f2>")
      "Zoom"
      ("g" text-scale-increase "in")
      ("l" text-scale-decrease "out"))))
```

2. use `declare-function`

```
(use-package hydra
  :config
  (declare-function hydra-default-pre "hydra.el")
  (declare-function hydra-keyboard-quit "hydra.el")
  (declare-function hydra--call-interactively-remap-maybe "hydra.el")
  (declare-function hydra-show-hint "hydra.el")
  (declare-function hydra-set-transient-map "hydra.el")
  (defhydra hydra-zoom (global-map "<f2>")
    "Zoom"
    ("g" text-scale-increase "in")
    ("l" text-scale-decrease "out")))
```

- What's the reason that causes the warning?

- Is there any more elegant way to avoid this kind of warning?

Thanks!

**Comment by abo-abo** [comment]
> Is there any more elegant way to avoid this kind of warning?

I use `use-package`, but not for everything. A simple `(require 'hydra)` before `use-package` will fix your issue. It might be possible to fix it in `use-package`, I'm not sure.

**Comment by andreyorst** [comment]
I've solved this issue by using [`:commands`](https://github.com/jwiegley/use-package#byte-compiling-your-emacs) from `use-package`.

**Comment by abo-abo** [comment]
Thanks, closing.
