### ISSUE TITLE
Merge hints for mutiple heads bound to the same function [Feature request]

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/hydra#26]
Hi,

I have a defined the following hydra that calls my custom functions and binds them to my custom mode map using `bind-key`:

```elisp
(defhydra hydra-font-resize
    (nil "C-x" :bind (lambda (key cmd) (bind-key key cmd modi-mode-map)))
  "font-resize"
  ("_"   modi/font-size-incr  "Increase")
  ("-"   modi/font-size-decr  "Decrease")
  ("C-0" modi/font-size-reset "Reset to default size")
  ("="   modi/font-size-reset "Reset to default size" :bind nil)
  ("0"   modi/font-size-reset "Reset to default size" :bind nil))
```

Currently the hint is repeating the description for the `C-0`, `=` and `0` bindings. If the bound function is identical, `modi/font-size-reset` in this case, can you merge the hints so that it says something like below?

        font-resize: [_]: Increase, [-]: Decrease, [C-0 / = / 0] Reset to default size

**Comment by abo-abo** [comment]
Nice idea. I'll try to implement this soon.

**Comment by kaushalmodi** [comment]
Works great! Thanks!
