### ISSUE TITLE
Possible issue with :pre

### ISSUE THREAD

**Issue by igorepst** [abo-abo/hydra#261]
There is a possible issue with :pre
```
(defhydra ig-hydra-ivy-views (:color teal :pre (delete-other-windows))
    ("c" (ivy-set-view-recur  `(horz
		      (file ,(expand-file-name "ig-init.el" ig-additional-lisp-dir))
		      (file "~/.emacs.d-various/.emacs.d-new/lisp"))) "copy config")
    ("o" (ivy-set-view-recur `(horz
		      (file ,(expand-file-name "org-tutorial.org" ig-org-directory))
		      (sexp (eww "http://orgmode.org/guide/index.html#Top")))) "org tutorial")
    ("SPC" nil))
```
`delete-other-windows` executes as soon as `ig-hydra-ivy-views/body` is called and not when head is chosen. Is this a bug or I'm misunderstanding something?
Hydra: 20170924.2259, Emacs: 25.3.1 on ArchLinux 64b
Thanks

**Comment by abo-abo** [comment]
> Is this a bug or I'm misunderstanding something?

Not a bug, `:pre` is added to all functions, including the body. There was an example in the documentation for setting the cursor color when the hydra is active: it makes sense to do it for the body as well.

You can work around like this:

```elisp
(defhydra ig-hydra-ivy-views (:color teal)
  ("c"
   (progn
     (delete-other-windows)
     (ivy-set-view-recur `(horz
                           (file ,(expand-file-name "ig-init.el" ig-additional-lisp-dir))
                           (file "~/.emacs.d-various/.emacs.d-new/lisp")))) "copy config")
  ("o"
   (progn
     (delete-other-windows)
     (ivy-set-view-recur `(horz
                           (file ,(expand-file-name "org-tutorial.org" ig-org-directory))
                           (sexp (eww "http://orgmode.org/guide/index.html#Top"))))) "org tutorial")
  ("SPC" nil))
```

Or even better, write a wrapper around `ivy-set-view-recur` that calls `delete-other-windows` and maybe does more.

**Comment by igorepst** [comment]
Yes, I saw the example. OK, thanks :)
