### ISSUE TITLE
Error in defhydra foo: (plistp (nil :exit t))

### ISSUE THREAD

**Issue by diamond-lizard** [abo-abo/hydra#263]
In Emacs [26.0.90](https://lists.gnu.org/archive/html/emacs-devel/2017-10/msg00408.html), when I eval even the simplest of hydras:

```
(defhydra foo ()
  "
"
  ("q" nil nil nil :exit t))
```

Emacs complains:  `Error in defhydra foo: (plistp (nil :exit t))`.  Other, more complicated hydras also trigger the same error.

On Emacs 25.3.1 all these hydras are no problem for me, so I think this error may indicate some sort of incompatibility between hydra and emacs 26.0.90

**Comment by abo-abo** [comment]
Looks like you have one nil too many: one's for function, second's for doc, third one marks the start of plist. A plist of `'(nil :exit t)` is actually wrong, since they should have an even number of elements. It's nice of Emacs26 to warn you of this error.

**Comment by diamond-lizard** [comment]
Thank you.  Removing the extra `nil` got rid of the warning.  My bad.  Sorry to waste your time, and thanks for hydra!

**Comment by abo-abo** [comment]
No problem, and you're welcome.
