### ISSUE TITLE
Display string in minibuffer

### ISSUE THREAD

**Issue by brotzeit** [abo-abo/hydra#271]
I know `hydra-is-helpful`, but I don't want the echo area to be empty. It would be nice if I could add a colored string.

**Comment by abo-abo** [comment]
Please clarify.

**Comment by brotzeit** [comment]
I don't want to see anything in the minibuffer except a short string so I know the hydra is currently active.
Probably there's already a solution for this, but I couldn't find it. I mentioned `hydra-is-helpful` as it removes the "noise" from the minibuffer. But I need something being displayed in the minibuffer to see if a hydra is active.

So I basically just need an indicator in the echo area.

**Comment by abo-abo** [comment]
So you want this?

```elisp
(defhydra hydra-test ()
  "hydra-test"
  ("f" forward-char nil))
```

**Comment by brotzeit** [comment]
Yes, but it would be nice if I could choose a color for the docstring.

**Comment by abo-abo** [comment]
Try to set `hydra-test/hint` after defining the hydra:

```elisp
(defhydra hydra-test ()
  "hydra-test"
  ("f" forward-char nil))

(setq hydra-test/hint (propertize "hydra-test" 'face 'warning))
```

**Comment by brotzeit** [comment]
Nice. Thanks !
