### ISSUE TITLE
Remove newline at the end in minibuffer?

### ISSUE THREAD

**Issue by sandric** [abo-abo/hydra#273]
All my hydras fit the window width, but nevertheless, hydra selection window in minibuffer always ended with newline. I wonder, if there's any way that newline can be eliminated? Or its essential stuff and because of echoing and things like eldoc that can not be done?

**Comment by abo-abo** [comment]
If I understand you correctly, this has to do with Hydra not using the Echo Area by default.n
The reason for this is that when any other command prints anything to the Echo Area, they will wipe out the Hydra.

You can turn off this setting with:

```elisp
(setq hydra-lv nil)
```

It's also possible to do so for individual hydras with `hydra-set-property`.

```elisp
(defhydra hydra-zoom (global-map "<f2>")
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))
;; use LV
(hydra-set-property 'hydra-zoom :verbosity 2)
;; use Echo Area
(hydra-set-property 'hydra-zoom :verbosity 1)
```

**Comment by sandric** [comment]
```elisp
(setq hydra-lv nil)
```
Just what I was looking for, thanks alot!
