### ISSUE TITLE
how to tell if hydra is active.

### ISSUE THREAD

**Issue by introom** [abo-abo/hydra#276]
I have a function run periodically by the idle timer:

> (defun my-auto-save-silent ()
>   (unless (eq major-mode 'undo-tree-visualizer-mode)
>     (let ((inhibit-message t))
>       (save-some-buffers t))))
> 
> (run-with-idle-timer 1.5 t #'my-auto-save-silent)

The problem is, this interferes with hydra :timeout.  

Whenever the function is run, the hydra output in the echo area is cleared, (even though I set inhibit-message).

I want to know if hydra is active, so that I can exit the function immediately in that case.

**Comment by introom** [comment]
on the other hand, how to make the hydra hint *persistent*.

even the echo area message is cleared, the hydra is actually *active*.  it would be better if hydra message comes back on its own.

**Comment by abo-abo** [comment]
If you have `(setq hydra-lv t)` (the default setting), other programs won't interfere with the hydra hint.

**Comment by introom** [comment]
hi.  I don't use lv.  
If *persistent* is not possible without lv,  is there a way to know if hydra is active?

**Comment by abo-abo** [comment]
`hydra-curr-map`

**Comment by introom** [comment]
thanks.
