### ISSUE TITLE
Feature Request: Controlling Columns

### ISSUE THREAD

**Issue by dustinlacewell-wk** [abo-abo/hydra#279]
The new `:columns` feature is great! Thanks for it.

I was thinking about an enhancement that would allow for a bit more control over how the columns are displayed. Would some sort of sentinel value in the list of heads work to control a break in the columns? This would allow me to group relevant commands into columns without resorting to the manual string stuff.  Thanks for Hydra, it is a game changer!

**Comment by abo-abo** [comment]
Can you give an example with some code of how you'd like it to work?

**Comment by dustinlacewell-wk** [comment]
```lisp
(defhydra hydra-registers (:color pink :hint nil)
  "
  ^ ^                 ^ ^                  ^ ^                    ╭───────────┐
    ^^Point             ^^Text               ^^Macro              │ Registers │
╭─^─^─────────────────^─^──────────────────^─^────────────────────┴───────────╯
 [_r_] save point    [_c_] copy region    [_m_] store
 [_j_] jump          [_C_] copy rect      [_e_] execute
 [_v_] view all      [_i_] insert
  ^ ^                [_p_] prepend
  ^ ^                [_a_] append
  ^ ^                 ^ ^                  ^ ^                _<f19>_ to close
└─^─^─────────────────^─^──────────────────^─^────────────────────────────────
  "
  :column "Point"
  ("r" point-to-register)
  ("j" jump-to-register)
  ("v" view-register)
  :column "Text"
  ("c" copy-to-register)
  ("C" copy-rectangle-to-register)
  ("i" insert-register)
  ("a" append-to-register)
  ("p" prepend-to-register)
  :column "Macro"
  ("m" kmacro-to-register)
  ("e" jump-to-register)

  ("<f19>" nil))
```

With the use of two sentinel values, a `:column` symbol followed by a string, the columns can be controlled directly. This means you don't need an equal number of options evenly divided among the columns.

**Comment by dustinlacewell** [comment]
I wish there was a way to put a bounty on this one.

**Comment by abo-abo** [comment]
@dustinlacewell Have a look at https://www.bountysource.com/, it offers a way to put bounties on open issues on Github. It even looks like there's not much to none interaction needed from my side to set it up, but I'd be glad to do so if needed.

**Comment by abo-abo** [comment]
@Mugu-Mugu Thanks for the pointer. Indeed, I think the feature was already implemented.
