### ISSUE TITLE
Multi-key hydras don't use custom labels.

### ISSUE THREAD

**Issue by it3ration** [abo-abo/hydra#284]
I noticed that when I have multiple heads with a common initial prefix that `hydra` shows the narrowed candidates at the bottom of the window. Unfortunately, it shows the actual function name, not the custom label that's specified when defining the hydra. For example, if I had the following head definition, I'd expect the text at the bottom to say `splice-sexp`:

 `("ss" paredit-splice-sexp "splice-sexp")`

Instead it shows the long _actual_ function name, in this case something like:

`hydra-paredit/paredit-splice-sexp`

Is it possible to change this behavior? Like maybe the candidates could be highlighted instead of being duplicated at the bottom, or if not, could it use the same labels? I've attached a screenshot as a reference.

EDIT: Here is the `hydra` definition:

```clojure
    ;; The hydra.
    (defhydra hydra-paredit
      (:columns 3)
      "paredit"

      ;; Forward / backward.
      ("f" paredit-forward "forward")
      ("b" paredit-backward "backward")

      ;; Down / up.
      ("d" paredit-forward-down "forward-down")
      ("u" paredit-backward-up "backward-up")

      ;; Down / up (backwards).
      ("D" paredit-backward-down "backward-down")
      ("U" paredit-forward-up "forward-up")

      ;; Next / previous.
      ("n" paredit-next-sexp "next-sexp")
      ("p" paredit-previous-sexp "previous-sexp")

      ;; Beginning / end.
      ("a" paredit-beginning-sexp "beginning-sexp")
      ("e" paredit-end-sexp "end-sexp")

      ;; Slurping / barfing.
      ("(" paredit-backward-slurp-sexp "backward-slurp-sexp")
      (")" paredit-forward-slurp-sexp "forward-slurp-sexp")
      (">" paredit-backward-barf-sexp "backward-barf-sexp")
      ("<" paredit-forward-barf-sexp "forward-barf-sexp")

      ;; Wrapping.
      ("w(" paredit-wrap-round "wrap-round")
      ("w[" paredit-wrap-square "wrap-square")
      ("w{" paredit-wrap-curly "wrap-curly")
      ("w<" paredit-wrap-angled "wrap-angled")
      ("w\"" paredit-meta-doublequote "meta-doublequote")
      
      ;; Splicing.
      ("ss" paredit-splice-sexp "splice-sexp")
      ("sf" paredit-splice-sexp-killing-forward "splice-sexp-killing-forward")
      ("sb" paredit-splice-sexp-killing-backward "splice-sexp-killing-backward")

      ;; Split / join.
      ("S" paredit-split-sexp "split-sexp")
      ("J" paredit-join-sexps "join-sexps")

      ;; Raise.
      ("r" paredit-raise-sexp "raise-sexp")

      ;; Convolute.
      ("c" paredit-convolute-sexp "convolute-sexp")

      ;; Reindent.
      ("i" paredit-reindent-defun "reindent-defun")

      ;; Comment.
      (";" paredit-comment-dwim "comment-dwim")
      
      ;; Cancel.
      ("q" nil "quit" :exit t))
```

If this functionality already exists somehow and I'm not groking it, I apologize. Thanks!

<img width="1035" alt="screen shot 2018-03-18 at 12 12 33 pm" src="https://user-images.githubusercontent.com/1028792/37560940-c41a8eb4-2aa6-11e8-8c09-1c6e5bb553dc.png">

**Comment by abo-abo** [comment]
Please include the code as well.

**Comment by it3ration** [comment]
Hey @abo-abo, sorry about that, I edited my previous post with the `hydra` definition. Thanks!

**Comment by abo-abo** [comment]
The bottom line does not come from `hydra`. It's likely `which-key`. So this is expected behavior and not a bug.

**Comment by it3ration** [comment]
Ah that makes sense, thanks for your time / energy. -Kevin

**Comment by abo-abo** [comment]
You're welcome :)
