### ISSUE TITLE
Ability to override hydra-base-map for each hydra?

### ISSUE THREAD

**Issue by mhcerri** [abo-abo/hydra#285]
Hi,

I noticed that there's no easy way to override hydra-base-map in a per hydra base. That can be very useful to implement some kind of mini modes while preserving the ability to edit text (currently you can't enter numbers or a dash when a hydra is active).

I was able to globally override hydra-base-map using:

```
(setq hydra-base-map (make-sparse-keymap))
```
But if I set it right before a `defhydra`, with the intention of restoring it later, it does work. When using `use-package` I'm not even able to redefine it in the `:init`, it needs to be done outsite the `use-package` block. That's probably related to how elisp macros work.

Do you think it would be acceptable to introduce a new body option `:base-map` to override that? When the option is missing it could use the current hydra-base-map and with `nil` it could use an empty keymap.

What do you think?

**Comment by abo-abo** [comment]
Implemented, thanks. See the commit message for example code.

**Comment by mhcerri** [comment]
Thanks!
