### ISSUE TITLE
Allow M-? in docstrings

### ISSUE THREAD

**Issue by binshengliu** [abo-abo/hydra#286]
Hi there. I was trying to define "M-?" in the docstring, but the following code complained `Warning (emacs): Unrecognized key: _M-_`.

``` lisp
(defhydra hydra-test (:color teal :hint nil)
  "
_M-?_ References
"
  ("M-?" xref-find-references)
  ("q" nil  :color blue))
```

I found #178 but adding either one or two backslashes didn't work.

**Comment by abo-abo** [comment]
Related: 5be27f4b61672a4b8e9dcec2e78bacd1a95fa0d7. This commit introduced the option of introducing e.g. `?C-f?` into the docstring. This is where the conflict for `M-?` comes from, because of `?` being both key and boundary.

**Comment by abo-abo** [comment]
Thanks.

**Comment by binshengliu** [comment]
Tested. It worked. Thank you!
