### ISSUE TITLE
iedit hydra wrong type argument

### ISSUE THREAD

**Issue by thorstengrothe** [abo-abo/hydra#288]
I got this hydra for iedit

```
(defhydra my/hydra-iedit (:hint nil :color pink)
  "
_n_: → _p_: ← _t_:oogle | _SPC_:quit
"
  ("n" iedit-next-occurance)
  ("p" iedit-prev-occurance)
  ("t" iedit-toggle-unmatched-lines-visible)
  ("SPC" nil :color blue)
  )
```

but hitting `n` leads to an error message

`wrong type argument commandp`

iedit is loaded before the hydra and I can `M-x` `iedit-next-occurance`.

What's wrong?

**Comment by abo-abo** [comment]
You have a typo:

    - iedit-next-occurance
    + iedit-next-occurrence

**Comment by thorstengrothe** [comment]
Oh no a typo, I did not see that, I'm sorry!

**Comment by abo-abo** [comment]
No problem:)
