### ISSUE TITLE
Running a named macro from within Hydra

### ISSUE THREAD

**Issue by Grimscythe1983** [abo-abo/hydra#289]
I have a couple of neat macros saved with `C-x (`, I named them and saved them for future use. I'd love to use those macros in hydra, but I get a `Wrong type argument: commandp`.

I tried this: `("i" (lambda () (interactive) (my-named-macro)))` or this: `("i" my-named-macro)` and neither unfortunately work.

**Comment by abo-abo** [comment]
Keyboard macros aren't commands, you can't call them like that.

One option is to rewrite them as a command. `view-lossage` can help you here.

Another option is to use `execute-kbd-macro` as here:

```elisp
(defun ivy-with (expr keys)
  "Evaluate EXPR followed by KEYS."
  (let ((ivy-expr expr))
    (execute-kbd-macro
     (vconcat (kbd "C-c e")
              (kbd keys)))
    ivy-result))
```

**Comment by Grimscythe1983** [comment]
Thank you for a quick response.

Could you give an example of how the `ivy-with` function would be used with a macro called (for instance) `get-bearer-token`? Not sure how to work it :(

**Comment by abo-abo** [comment]
I meant just to use the `execute-kbd-macro` part. For example:

    (execute-kbd-macro (kbd "C-f C-f"))

This code is equivalent to pressing <kbd>C-f</kbd> two times. Of course `(forward-char 2)` is the code equivalent, but the point of keyboard macros is to repeat the commands in terms of the keys to which they are bound. So `execute-kbd-macro` is basically that.

**Comment by Grimscythe1983** [comment]
Ahhhh I see. Thank you very much for the clarification. This helps a great deal!
