### ISSUE TITLE
Empty string in the hydra docstring returns error

### ISSUE THREAD

**Issue by sewkokot** [abo-abo/hydra#291]
Why evaluating the following code gives an error? In some cases there is no need for redundant docstring when e.g. `:column "docstring1"` is provided. Also as a work-around I could set " " as the docstring but still I have " :" (space + colon) in the minibuffer. I looked at the hydra.el code but could not figure out where the colon is hard-coded? What i can do in this situation?

```
(defhydra hydra-clock (:color blue)
  ""
  ("q" nil "quit" :column "Clock")
  ("c" org-clock-cancel "cancel" :color pink :column "Do")
  ("d" org-clock-display "display")
  ("e" org-clock-modify-effort-estimate "effort")
  ("i" org-clock-in "in")
  ("j" org-clock-goto "jump")
  ("o" org-clock-out "out")
  ("r" org-clock-report "report"))
```

> Debugger entered--Lisp error: (args-out-of-range "" 0)
>   aref("" 0)
>   (eq 10 (aref docstring 0))
>   (if (eq 10 (aref docstring 0)) (list (quote concat) (cons (quote format) (cons (substring docstring 1) (nreverse varlist))) rest) (let ((r (list (quote replace-regexp-in-string) " +$" "" (list (quote concat) docstring ": " (list (quote replace-regexp-in-string) "\\(%\\)" "\\1\\1" rest))))) (if (stringp rest) (list (quote format) (eval r)) (list (quote format) r))))
>

**Comment by sewkokot** [comment]
I found where the colon after 'docstring' is hard-coded. The problem was that I have hydra package from melpa and local hydra from github. I removed the colon in hydra.el from local git, but hydra from melpa directory had been loaded first and the colon persisted. Anyway I left the colon as it is and now I use the newline as the docstring
```
(defhydra hydra-clock (:color blue)
  "
"
  ("q" nil "quit" :column "Exit")
  ("c" org-clock-cancel "cancel" :color pink :column "Clock")
...
  ("r" org-clock-report "report"))
```
I would be happy to see a new feature that if an empty string "" is used as docstring then the docstring in the minibuffer is omitted.

**Comment by abo-abo** [comment]
Thanks, your example should now work like this:

```elisp
(defhydra hydra-clock (:color blue)
  ("q" nil "quit" :column "Clock")
  ("c" org-clock-cancel "cancel" :color pink :column "Do")
  ("d" org-clock-display "display")
  ("e" org-clock-modify-effort-estimate "effort")
  ("i" org-clock-in "in")
  ("j" org-clock-goto "jump")
  ("o" org-clock-out "out")
  ("r" org-clock-report "report"))
```

**Comment by sewkokot** [comment]
Thank you very much, it works as I expected!
