### ISSUE TITLE
key-chord cannot triggered hydra-ivy in minibuffer when first tapped

### ISSUE THREAD

**Issue by BooAA** [abo-abo/hydra#292]
I want to use both "fd" to trigger hydra-vi  in global-map while trigger hydra-ivy in ivy-minibuffer

Below is the simple version of the code I used
```lisp
(require 'hydra)
(require 'ivy)
(require 'key-chord)
(key-chord-mode 1)


(defhydra hydra-vi (:color amaranth :hint nil)
    "vi"
    ("l"  forward-char)
    ("h"  backward-char)
    ("j"   next-line)
    ("k"  previous-line)
    ("SPC SPC" counsel-M-x)
    ("i"  nil))

(defhydra hydra-ivy (:color amaranth :hint nil)
  "vi under ivy-minibuffer"
  ("j" ivy-next-line)
  ("k" ivy-previous-line)
   ("i" nil)

(key-chord-define-global "fd" 'hydra-vi/body)
(key-chord-define ivy-minibuffer-map "fd" 'hydra-ivy/body)


```

The problem is that when I was in normal emacs ( e.g. without activating hydra-vi),  I hit M-x and hit the key-chord "fd" , it will trigger hydra-ivy in the minibuffer, everything works fine.

But when I was under hydra-vi, I hit SPC SPC and hit "fd",  it will not trigger hydra-ivy but self-insert-comment , What's more strange is that when I hit C-o (the default key to trigger hydra-ivy in ivy.el),  and hit "i" back to normal emacs, now when I hit "fd" again , it will trigger hydra-ivy correctly (I'm so confused about this)

I have done another experiment by setting both C-o to trigger hydra-vi globally and hydra-ivy under ivy-minibuffer,  and it works well as expectation,  C-o can trigger right things under both situation, so I'm not sure whether it's key-chord's problem or if I miss something in my hydra configuration.

Last but not least , it works by adding ":exit t" after  ("SPC SPC counsel-M-x"), but this will leave hydra-vi after I finished using counsel-M-x which is what I don't prefered.

PS: I'm not sure whether it's the problem of key-chord or hydra, I post this issue here only because the author of key-chord had not updated his package for more than 2 years.  If it's key-chord's problem than I will close this issue immediately.

**Comment by abo-abo** [comment]
I think your problem can be fixed with this hack:

    (defun hydra-default-pre ())

I don't recommend to use key chord. It has poor performance, because the base Emacs wasn't designed to support a feature like that.

**Comment by BooAA** [comment]
Thanks, your solution fixes the problem well.

Besides, I will try using C-o to switch between vi and emacs instead of "fd". (I saw many people using C-z but it seems to be painful because it requires users to use little finger of both hands at the same time.


And I have another question off topic,  I want to let a key has different behavior under different major mode in one hydra. For instance,  when under c++-mode, I want "," to trigger hydra-c++ when I was in hydra-vi, but under python-mode, I want "," to trigger hydra-python , etc. What's your recommendation about implementing this?

Hydra is so awesome  that I can't stop hacking it. Thanks for making this wonderful package.

**Comment by abo-abo** [comment]
> What's your recommendation about implementing this?

You can write a helper command like this:

```elisp
(defun major-mode-hydra ()
  (interactive)
  (cl-case major-mode
    (c++-mode (hydra-c++/body))
    (python-mode (hydra-python/body))
    (t
     (hydra-text/body))))
```

In case you have really a lot of hydras defined, using a uniform naming scheme, you can use this trick:

```elisp
(let* ((cmd-name (format "hydra-%s/body"
                         (mapconcat
                          #'identity
                          (butlast
                           (split-string (symbol-name major-mode) "-"))
                          "-")))
       (cmd (intern-soft cmd-name)))
  (if cmd
      (call-interactively 'cmd)
    (user-error "`%s' not defined" cmd-name)))
```

Then you don't have to update the helper command each time you add a new hydra.

> Hydra is so awesome that I can't stop hacking it. Thanks for making this wonderful package.

You're welcome.

**Comment by BooAA** [comment]
Thanks , the major-mode-hydra function works well. BTW, I saw a package also called [major-mode-hydra](https://github.com/jerrypnz/major-mode-hydra.el),  how do you think about this package and will you recommend using it?

**Comment by abo-abo** [comment]
> how do you think about this package and will you recommend using it?

It's a nice package, although I don't use it myself yet. I typically use the major-modes that I've used for years already, and I remember the bindings for them. Or at least I think so)

**Comment by BooAA** [comment]
Recently I found there are two ways to implement using "," to become leader key by hydra.

The first one is by what you taught me recently,  I used it with the [Nesting Hydra](https://github.com/abo-abo/hydra/wiki/Nesting-Hydras) tutorial

```lisp

(defvar hydra-stack nil)

(defun hydra-push (expr)
  (push `(lambda () ,expr) hydra-stack))

(defun hydra-pop ()
  (interactive)
  (let ((x (pop hydra-stack)))
    (when x
      (funcall x))))

(defun major-mode-hydra ()
  (interactive)
  (cl-case major-mode
    (c++-mode (hydra-c++/body))
    (python-mode (hydra-python/body))
    (t (progn
	 (message "no corresponding hydra for current major-mode yet")
	 (hydra-pop)))))

(defhydra hydra-c++ (:color teal :hint nil :after-exit (hydra-pop))
  "
  --C++--
"
  ("d" xref-find-definitions)
  ("r" xref-find-references))


(defhydra hydra-python (:color teal :hint nil :after-exit (hydra-pop))
  "
--PYTHON--
"
  ("d" anaconda-mode-find-definitions)
  ("r" anaconda-mode-find-references))

(defhydra hydra-vi (:color amaranth :hint nil)
"VI"
  ("," (progn
	 (hydra-push '(hydra-vi/body))
	 (major-mode-hydra)) :exit t)
  ("i" nil))
```


Another one is that I found it can be easily implemented with the **hydra-look-for-remap** feature .
Code below seems to work too.
```lisp
(setq hydra-look-for-remap t)

(defun major-mode-find-definitions ()
  (interactive))
  
(defun major-mode-find-references ()
  (interactive))

(defhydra hydra-vi (:color amaranth :hint nil)
  "VI"
  (", d" major-mode-find-definitions)
  (", r" major-mode-find-references)
  ("i" nil))

(define-key c++-mode-map [remap major-mode-find-definitions] 'xref-find-definitions)
(define-key c++-mode-map [remap major-mode-find-references] 'xref-find-references)
(define-key python-mode-map [remap major-mode-find-definitions] 'anaconda-mode-find-definitions)
(define-key python-mode-map [remap major-mode-find-references] 'anaconda-mode-find-references)

```



Can you tell me which one is better ? The second one seems to be easier and without the cost to switch between different hydra. But the first one may be more flexible? I cannot make choice between them.

Thanks for your help and patience.

**Comment by abo-abo** [comment]
The second one seems simple enough, since you're not using nesting.

But you can simplify the first one like this:

```elisp
(defhydra hydra-vi (:color amaranth :hint nil)
  "VI"
  ("," major-mode-hydra :exit t)
  ("i" nil))
```

You'll be losing only a tiny bit of functionality.

**Comment by BooAA** [comment]
I find the second version have some bugs

For xref I have config below, which will prevent emacs asking which symbol to find but using the symbol under cursor

```lisp
(setq xref-prompt-for-identifier '(not xref-find-definitions
                                               xref-find-definitions-other-window
                                               xref-find-definitions-other-frame
                                               xref-find-references))
;;the default one
;;(setq xref-prompt-for-identifier '(not xref-find-definitions
;;                                               xref-find-definitions-other-window
;;                                               xref-find-definitions-other-frame
;;                                               xref-find-references))
	
```
So xref-find-definitions and xref-find-references shouldn't prompt in my config,  the first version(e.g. using nesting hydra) works as expectation, but the second one prompt for both two functions, which is also not the default one. By the documentation of xref, it might be set to t.

I have checked the value of xref-prompt-for-identifier under c++-mode, which is what I set. Also I use 
M-x  to call these two functions and it also works correctly.
Maybe there's something wrong during the process of lookup? I have no idea what happened.
