### ISSUE TITLE
Why some function can exit hydra automatically?

### ISSUE THREAD

**Issue by BooAA** [abo-abo/hydra#294]
I'm confusing about different function having different behavior in same hydra.

For instance, for swiper in hydra,
``` lisp
(defhydra hydra-vi (:color pink :hint nil)
  "VI
"
  ("/" swiper)
  ("i" nil))
```
When I pressed "/" , it will trigger swiper, and I can type any word to search , after finishing searching , I will back to hydra-vi because of the pink hydra-color.

But for another case,  isearch cannot exit hydra automatically

``` lisp
(defhydra hydra-vi (:color pink :hint nil)
  "VI
"
  ("/" isearch-forward)
  ("i" nil))
```

After pressing "/", it runs isearch-forward ,however, I'm still in hydra-vi so I have to press "i" to leave hydra so that I can insert character to search.

I found some native emacs function having same behavior like swiper, like find-file,  switch-to-buffer etc...

But isearch will not exit hydra automatically( or it doesn't exit hydra but have other mechanism under the hood?)

**Comment by abo-abo** [comment]
This happens for all commands that use `read-from-minibuffer` and `read-char`. I think this is a good behavior and not a bug.
