### ISSUE TITLE
Hydra and display-line-numbers-mode

### ISSUE THREAD

**Issue by drot** [abo-abo/hydra#298]
Hello, I have the following enabled on Emacs 26:

`(add-hook 'text-mode-hook #'display-line-numbers-mode)`

but this also displays line numbers in Hydra windows unless I set `hydra-lv` to nil to use `message`. I've tried advising the `lv-message` function but that doesn't seem to work. Any help is greatly appreciated.

**Comment by drot** [comment]
Managed to solve it with help from the #emacs IRC channel, gonna post it here in case somebody stumbles on the same issue.

```
  (defun drot-lv-window (orig-fun &rest args)
    "Disable line numbers in LV window."
    (let ((turn-off-line-numbers (not (or (window-live-p lv-wnd)
                                          (get-buffer " *LV*")))))
      (prog1 (apply orig-fun args)
        (when turn-off-line-numbers
          (with-current-buffer " *LV*"
            (setq-local display-line-numbers nil))))))

  (advice-add 'lv-window :around #'drot-lv-window)
```

**Comment by abo-abo** [comment]
Thanks. I've added code to disable `display-line-numbers` in `lv-window`.
