### ISSUE TITLE
using hydra to launch a direct yasnippet template?

### ISSUE THREAD

**Issue by zeltak** [abo-abo/hydra#299]
Hi

im trying to figure a way to launch a direct yasnippet template using hydra

after reading the yasnippet DOCU im still struggling. i read one can use `yas-expand-snippet` to do so

but this command does nothing in hydra

```
(yas-expand-snippet "insert.bash.clip")
```

anyone know how to address this ?

best

Z

**Comment by abo-abo** [comment]
The issue is that you have to use the snippet's body instead of it's name. This works for me:

```elisp
(defhydra hydra-yasnippet (:exit t)
  "yasnippet"
  ("d"
   (progn
     (yas-global-mode)
     (yas-expand-snippet
      "(defun $1 ($2)\n$0)"))
   "defun"))
```

**Comment by abo-abo** [comment]
Yes, you've understood correctly. Maybe there's a function in yasnippet API to get the snippet body by it's name. But I don't know it.

If you have the snippet bound to key "ibp", you can rewrite your hydra like this:

```elisp
(defhydra hydra-yasnippet (:exit t)
  "yasnippet"
  ("d"
   (progn
     (yas-global-mode)
     (insert "ibp")
     (yas-expand))))
```

Extract function, and now your hydra is very simple:

```elisp
(defun my-expand-snippet (key)
  (yas-global-mode)
  (insert key)
  (yas-expand))

(defhydra hydra-yasnippet (:exit t)
  "yasnippet"
  ("d" (my-expand-snippet "ibp")))
```

**Comment by zeltak** [comment]
perfect!

**Comment by abo-abo** [comment]
You're welcome.
