### ISSUE TITLE
When using hydra-create to bind with a minor mode map, it is wiping off my earlier bindings

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/hydra#3]
Hi,

I have created [this gist ](https://gist.github.com/kaushalmodi/b04368e07aa89a28545b) to explain this problem better.

`bind-key` package is required for the gist code to work.

What the gist does:

- Create a minor mode called `xyz-mode`
- Set `xyz-mode-map` to have the highest priority.. overrides all global and major/minor mode bindings
- Binds `previous-line` command to `C-M-o p` and `next-line` command to `C-M-o n` (just for the sake of demonstrating this issue).
- Enables the minor mode

After that you will see that `C-M-o p` calls `previous-line` as you would expect.

But when below is evaluated, the `C-M-o p` and all the bindings made earlier to `C-M-o` prefix are gone!

<pre>
(hydra-create "C-M-o"
  '(("h" . hydra-move-splitter-left)
    ("j" . hydra-move-splitter-down)
    ("k" . hydra-move-splitter-up)
    ("l" . hydra-move-splitter-right))
  xyz-mode-map)
</pre>

**Comment by abo-abo** [comment]
OK, I see what's happening here. I have some special code to unbind e.g. <kbd>C-M-o</kbd>, assuming
that it's a global binding. This is because Emacs doesn't allow to bind <kbd>C-M-o j</kbd> if <kbd>C-M-o</kbd> is bound previously.
Now, I should just make sure not to do this for minor maps.

**Comment by abo-abo** [comment]
You might be interested in a less aggressive approach to giving priority to a minor mode: https://github.com/abo-abo/lispy/blob/master/lispy.el#L280.
It also works better if many minor modes try to be aggressive.

**Comment by kaushalmodi** [comment]
Thanks! It works great now! 

I will have a look at your suggested approach for overriding the binding priority. I'll need to understand the core difference between the code that I borrowed from elsewhere and the code you have to raise the minor mode.

**Comment by abo-abo** [comment]
I got my approach from here: http://www.emacswiki.org/emacs/minor-mode-hack.el. Didn't want to add a dependency for just one simple function.
