### ISSUE TITLE
Anonymous hydras? 

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/hydra#30]
I'd like to programmatically generate hydras at runtime. Is there any way I can avoid polluting the global function space by making anonymous hydras?

I'm sure you can come up with something clever to call them. :)

EDIT: reading more into this, it looks pretty hard to do.

**Comment by abo-abo** [comment]
A weird application. Doable with `eval` probably.

> avoid polluting the global function space

`defhydra` already does that by assigning a name prefix to all generated defuns.
In my Emacs, there are 35000 entries in the function space. I don't thing 10-20 would make much difference.
If you think they do, just `mapatoms` and `fmakunbound`: you know the prefix.

**Comment by PythonNut** [comment]
I suppose. I realize that adding this would probably be too much work.
