### ISSUE TITLE
Removal of newline in `hydra--hint` breaks layout of auto-formatted hydras

### ISSUE THREAD

**Issue by WJCFerguson** [abo-abo/hydra#306]
Checking git, with commit d071278f you removed the newline you used to add before `hydra--hint-from-matrix`, but the result is my hydras are now mis-formatted, with the docstring heading concatenated with the column headings without newline.  e.g.

```
(defhydra foo (:color blue)
  "    Silly hydra"
  ("x" forward-char "forward" :column "sideways")
  ("y" backward-char "back")
  ("a" next-line "down" :column "vertical")
  ("b" previous-line "up"))
``` 

Gives a hydra like:
```
    Silly hydra: sideways     | vertical
-------- | ---------
etc...
```

**Comment by WJCFerguson** [comment]
(sorry for the post-submit edits - ctrl-enter submitted my issue before I'd finished creating it)

**Comment by abo-abo** [comment]
Thanks.

**Comment by WJCFerguson** [comment]
Thank you!
