### ISSUE TITLE
:column feature and others not well-documented

### ISSUE THREAD

**Issue by alphapapa** [abo-abo/hydra#307]
I hate to complain, but the awesome `:column` feature was merged almost two years ago, but I had no idea until someone kindly [mentioned](https://www.reddit.com/r/emacs/comments/aa3t60/announcing_usepackagehydra/ecox0ri/) it to me on Reddit.  Had it been mentioned in the `defhydra` docstring, or even in the readme, I would have surely seen it--it hasn't been long since I last consulted the readme.

I see it's mentioned on the wiki, but IMHO that's not enough.  Wikis tend to feel unofficial and become messy.  I think these options should be officially documented in the readme--and in Emacs, so it's not necessary to consult a web site for the "self-documenting editor."  :)

Also, putting everything in an Org readme allows one to easily generate an info manual from it, e.g. as Magit and `org-super-agenda` do.  Then it's easy to consult the docs from inside Emacs.

**Comment by abo-abo** [comment]
Thanks. Feel free to PR with further improvements if they come up.
