### ISSUE TITLE
Specify an unhelpful hydra

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/hydra#31]
I love how hydras can be helpful, but one of my hydras shows information in the echo area, which is hidden by the hydra help. Is there any way I can disable help just for that hydra?

Ideally, I'd like to just wrap the whole (anonymous) hydra in a `(let ...)`, but that doesn't seem to work.

**Comment by abo-abo** [comment]
This can probably can be done with `:pre` and `:post`.
Post an example if you need help.

**Comment by PythonNut** [comment]
Okay, it seems to work, I just hope it's robust enough (i.e. `:post` will be called, even after an error).
