### ISSUE TITLE
Hydras with sexp hints not displayed

### ISSUE THREAD

**Issue by stianse** [abo-abo/hydra#311]
The example at https://github.com/abo-abo/hydra/wiki/internals#hint-1 doesn't work. In general it seems like hints that are sexp are not displayed, although their action works. Could be related to issue #304?

The snippet below will only show the head "l" with hint "forward". Note that I've removed `:column` which was used in the example because of #304.
```lisp
(defhydra hydra-test ()
  "Test"
  ("j" next-line (format-time-string "%H:%M:%S" (current-time)))
  ("k" previous-line (format-time-string "%H:%M:%S" (current-time)))
  ("h" backward-char (format-time-string "%H:%M:%S" (current-time)))
  ("l" forward-char "forward"))
  
(eval hydra-test/hint)
#("Test: [l]: forward." 7 8 (face hydra-face-red))
```

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by stianse** [comment]
Tested and confirmed fixed. Thanks @abo-abo for the quick fix.
