### ISSUE TITLE
Getting excessive windows when calling heads

### ISSUE THREAD

**Issue by dantheobserver** [abo-abo/hydra#313]
I'm using `hydra-0.14.0` with Emacs 26.1 and have the following hydra defined below.  I the problem I have is that when calling one of the heads to switch to another workspace a new minibuffer that is about 1 row high and contains the first line of the hydra buffer.  If I keep switching another buffer pops up one row high over and over. When quitting the multiple one row high buffers appear for me to delete.

Here you can see I have two buffers and if I keep switching between them, a new buffer is created when it goes to the second workspace, and after doing it many times I end up with something that looks like this

![screenshot from 2019-03-02 21-06-44](https://user-images.githubusercontent.com/35413469/53691271-40b6f480-3d2f-11e9-80e3-1aa2a9c1bc60.png)

and after quitting the hydra I get a bunch of 1 line high buffers with the line where my cursor lands when hydra is stopped.

![screenshot from 2019-03-02 21-08-58](https://user-images.githubusercontent.com/35413469/53691285-72c85680-3d2f-11e9-8059-37dc066a2eea.png)

```(defhydra hydra-eyebrowse-nav (:hint nil)
    "
_n_: next            _0_: window config 0   _6_: window config 6   _q_:quit
_p_: prev            _1_: window config 1   _7_: window config 7
_l_: last            _2_: window config 2   _8_: window config 8
_c_: create config   _3_: window config 3   _9_: window config 9
_D_: delete config   _4_: window config 4
_r_: rename config   _5_: window config 5
"
    ("n" eyebrowse-next-window-config)
    ("p" eyebrowse-prev-window-config)
    ("l" eyebrowse-last-window-config)

    ("c" eyebrowse-create-window-config)
    ("D" eyebrowse-close-window-config)
    ("r" eyebrowse-rename-window-config)

    ("0" eyebrowse-switch-to-window-config-0)
    ("1" eyebrowse-switch-to-window-config-1)
    ("2" eyebrowse-switch-to-window-config-2)
    ("3" eyebrowse-switch-to-window-config-3)
    ("4" eyebrowse-switch-to-window-config-4)
    ("5" eyebrowse-switch-to-window-config-5)
    ("6" eyebrowse-switch-to-window-config-6)
    ("7" eyebrowse-switch-to-window-config-7)
    ("8" eyebrowse-switch-to-window-config-8)
    ("9" eyebrowse-switch-to-window-config-9)

    ("q" nil :color blue))``

**Comment by abo-abo** [comment]
Please specify the code, minimal config, and key bindings so that I can reproduce.

**Comment by dantheobserver** [comment]
Thanks for replying, I should have added this but I've found this will do it

```(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives '(("org"   . "http://orgmode.org/elpa/")
                         ("gnu"   . "http://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

;; Bootstrap `use-package`
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)

(use-package eyebrowse
  :ensure t
  :config
  (eyebrowse-mode t)
  ;; (eyebrowse-setup-evil-keys)
  (setq eyebrowse-mode-line-separator " "
	eyebrowse-new-workspace t
	eyebrowse-wrap-around t
	eyebrowse-mode-line-style t))

(use-package hydra
  :load-path "site-lisp/hydra"
  :config
  (defhydra hydra-eyebrowse-nav (:hint nil)
    "
_n_: next            _0_: window config 0
_p_: prev            _1_: window config 1
_l_: last            _2_: window config 2
_c_: create config   _3_: window config 3
_D_: delete config   _4_: window config 4
_r_: rename config   _q_:quit"
    ("n" eyebrowse-next-window-config)
    ("p" eyebrowse-prev-window-config)
    ("l" eyebrowse-last-window-config)
    ("c" eyebrowse-create-window-config)
    ("D" eyebrowse-close-window-config)
    ("r" eyebrowse-rename-window-config)
    ("0" eyebrowse-switch-to-window-config-0)
    ("1" eyebrowse-switch-to-window-config-1)
    ("2" eyebrowse-switch-to-window-config-2)
    ("3" eyebrowse-switch-to-window-config-3)
    ("4" eyebrowse-switch-to-window-config-4)
    ("q" nil :color blue))
  (global-set-key (kbd "C-;") 'hydra-eyebrowse-nav/body)
  )
```

To reproduce.
- Save this in some location as `minimal-init.el`
 - Create a file and do `emacs -q minimal-init.el`
- do `M-x eval-buffer`
- type `C-;` to open the hydra.
- type `c c` to now have three perspectives.
- just keep typing `p` for previous perspective and `n` for next perspective.
- you should notice how the hydra itself shows repeating entries
- finally press `q` to end the hydra and you will see several window have replaced those repeating entries.

**Comment by abo-abo** [comment]
Try using `(setq hydra-lv nil)`. The default setting makes Hydra create an extra window, which probably messes up `eyebrowse`.
If this fixes your problem, I suggest transferring this issue to `eyebrowse`, which should add code to ignore the ` *LV*` buffer.

**Comment by dantheobserver** [comment]
That worked! other than this side effect any downsides to this being set to nil?

**Comment by abo-abo** [comment]
> That worked! other than this side effect any downsides to this being set to nil?

The downside is that the Echo Area is now used by the Hydra. So if any head uses `message` to inform you of something, it will be overwritten by the hydra doc:

```elisp
(defhydra hydra-test ()
  ("t" (message "time %S" (current-time)) "test"))

;; more fine-grain than (setq hydra-hint-display-type 'message)
(hydra-set-property 'hydra-test :verbosity 1)
```

In the hydra above, you will not see the message in the Echo Area, only in `*Messages*`.

You can use this as a "fix":

```elisp
(defhydra hydra-test ()
  ("t" (progn
         (message "time %S" (current-time))
         (sit-for 0.8)) "test"))
```

To summarize, you need to set this (I've made `hydra-lv` obsolete just now):

```elisp
(hydra-set-property 'hydra-eyebrowse-nav :verbosity 1)
```

**Comment by dantheobserver** [comment]
Cool, I've updated to the latest and set the var for my hydra.  I don't have a use case for sending a message (I usually use the eval lisp string for the docs), but glad to know it's possible.  Thanks, I think this can be considered closed.
