### ISSUE TITLE
Allow different display options for hydra hints

### ISSUE THREAD

**Issue by clemera** [abo-abo/hydra#315]
Hi, it would be nice to allow other display options for the hydra hints. As far as I know currently only `lv` or `message` can be used. I'm thinking of something like `ivy-display-function` for hydra.

**Comment by clemera** [comment]
For anyone interested [here](https://github.com/Ladicle/hydra-posframe) is a package which implements this already.

**Comment by abo-abo** [comment]
Thanks, the display is now customizable via `hydra-hint-display-type` (posframe is an option). It's also extendable via `hydra-hint-display-alist`.

**Comment by clemera** [comment]
Great, thank you!
