### ISSUE TITLE
FR: font-locking for `defhydra` macro

### ISSUE THREAD

**Issue by Fuco1** [abo-abo/hydra#32]
I find it useful to have these definition macros fontified, it makes the orientation in your .emacs easier.

Here's a snippet you can use to fontify `defhydra`s like `defclass`

```elisp
(font-lock-add-keywords 'emacs-lisp-mode '(("(\\(defhydra\\)\\>[[:blank:]]+\\(.*?\\)\\([[:blank:]]\\|$\\)"
                                                (1 font-lock-keyword-face)
                                                (2 font-lock-type-face))))
```

Some people might not like it so it would be a good idea to put it under a customize option so it can be disabled.

Sorry I'm too lazy to create a PR, I'm sure you can handle this in 3 minutes time.

Cheers.

**Comment by abo-abo** [comment]
Thanks!
