### ISSUE TITLE
How to lazy load hydra properly with use-package?

### ISSUE THREAD

**Issue by AmaiKinono** [abo-abo/hydra#321]
I would like to defer loading hydra by a few seconds. The following snippet works well:

``` emacs-lisp
(use-package hydra
  :defer 2
  :config
  (message "hydra loaded."))
```

`hydra loaded.` shows in the minibuffer after a while from startup. But when calling `defhydra` in the `:config` block:

``` emacs-lisp
(use-package hydra
  :defer 2
  :config
  (message "hydra loaded.")
  (defhydra my-hydra (:hint nil) "_s_wiper" ("s" swiper)))
```

`hydra loaded.` shows immediatly after startup. I wonder why hydra won't be deferred if calling `defhydra` in the `:config` block? What's the proper way to do it? I know hydra is lightweight and doesn't need to be lazy loaded anyway, but I'm just curious.

**Comment by abo-abo** [comment]
No idea, sorry. This is more of a `use-package` issue than a `hydra` issue. I don't recommend lazy-loading `hydra`, since `defhydra` is a macro. You will improve your performance and load time if you properly require and byte-compile your `defhydra` statements.

**Comment by AmaiKinono** [comment]
@abo-abo Thanks for your reply. Byte-compiling is definitely a reasonable suggestion.

I tried using some plain elisp code:

``` emacs-lisp
;; I use straight.el as my package manager, here's where hydra was built into.
(add-to-list 'load-path "~/.emacs.d/straight/build/hydra")
(run-with-idle-timer 2 nil #'require 'hydra nil t)
(with-eval-after-load 'hydra
  (message "hydra loaded.")
  (defhydra my-hydra (:hint nil) "_s_wiper" ("s" swiper)))
```

and it works as expected. So I think you are right, this should be a `use-package` issue.

**Comment by abo-abo** [comment]
OK, I close the issue then.
