### ISSUE TITLE
Strange behavior with multiple cursors

### ISSUE THREAD

**Issue by fikovnik** [abo-abo/hydra#327]
I tried the hydra with multiple cursors using the one from the hydra's [wiki](https://github.com/abo-abo/hydra/wiki/multiple-cursors), but the behavior is rather strange. I always get a power of 2 number of cursors. For example:

```
abc
abc
abc
abc
abc
abc
abc
abc
```

When select the first `abc` and launch the hydra selecting `n` (`mc/mark-next-like-this`), instead of the next `abc` selected I get the next two selected. Repeating `n` again gives me next 4 selected and so on. Perhaps it is somehow related to #214?

Does anyone has a suggestion what might be wrong?

**Comment by abo-abo** [comment]
Here's what happened when I tried to reproduce:

> Do hydra-multiple-cursors/mc/mark-next-like-this for all cursors? (y or n) n

I think in your case, you selected `y`, which results in an exponential behavior.

You can fix your choice by editing `~/.emacs.d/.mc-lists.el`. You need:

```elisp
(setq mc/cmds-to-run-once
      '(
        ;; ...
        hydra-multiple-cursors/mc/mark-next-like-this
        ))
```

**Comment by abo-abo** [comment]
@fikovnik Is your issue solved? Can I close it?

**Comment by fikovnik** [comment]
Sorry for keeping it open.
