### ISSUE TITLE
[Request] More customization for posframe

### ISSUE THREAD

**Issue by sewkokot** [abo-abo/hydra#328]
Thank you for the new posframe option.

Reading user remarks on reddit regarding the position of the posframe:
https://www.reddit.com/r/emacs/comments/bqe4m1/hydra_0150_is_out/
I also find the need to customize the display of posframe. For example for the theme I'm using now, other color than "red" for the posframe border is more suitable. Therefore user customization options for the posframe properties would help. Thank you in advance.

**Comment by abo-abo** [comment]
Thanks. Please let me know if `hydra-posframe-show-params` is sufficient for your needs.

**Comment by sewkokot** [comment]
Yes, it's OK now. Thank you, Oleh!
