### ISSUE TITLE
Flickering when hydra-hint-display-type is posframe

### ISSUE THREAD

**Issue by ubolonton** [abo-abo/hydra#329]
The new `posframe` support is awesome, but I'm running into a small annoyance. It's a bit hard to see in the GIF, but can be easily reproduced.

![hydra-with-posframe](https://user-images.githubusercontent.com/198359/58093510-df4d4600-7bf8-11e9-9a71-a6350d855f32.gif)

I think there are 2 possible ways to solve this:
- Skip `posframe-hide`if it's growing another head, or exiting into another hydra. I only took a brief look at the code, so I don't know how we can track this.
- Make `posframe` support "lazy display", i.e. don't redisplay until control is returned to the command loop. I don't know whether this is possible at the Lisp level. It may require changes to native frame handling.

**Comment by ubolonton** [comment]
This seems to fix the "growing another head" case for me, but not the "giving birth to another hydra" case.

```emacs-lisp
(setq hydra--work-around-dedicated nil)
```

**Comment by abo-abo** [comment]
Can't reproduce on GNU Linux, Emacs 26.1. What's your system? Is `hydra--work-around-dedicated` a full fix?

**Comment by ubolonton** [comment]
I'm on macOS 10.13, Emacs 26.2. This happens in both GNU Emacs and Emacs Mac port.
The `hydra--work-around-dedicated` only works for red heads, not blue heads.

**Comment by abo-abo** [comment]
Can you try to reproduce it with your config but on Linux?

**Comment by ubolonton** [comment]
I don't have access to a Linux desktop machine. I'll try to reproduce it when I have one, probably next month.
