### ISSUE TITLE
Jumping to register bookmarks

### ISSUE THREAD

**Issue by srid** [abo-abo/hydra#33]
I'm currently have bookmarks for frequently accessed files:

```elisp
  (mapcar
   (lambda (r)
     (set-register (car r) (cons 'file (cdr r))))
   '((?i . "~/.emacs.d/Srid.org")
     (?p . "~/Dropbox/Notes/Productive.org")
     (?w . "~/Dropbox/Notes/Work.org")))
```

Is this something I can use a hydra for (to save keystrokes)? Specifically I want to invoke `C-M-j` and hit `p` or `w` to directly go to the file. Please let me know if there is a better place to ask this kind of questions instead of opening a GitHub issue.

**Comment by srid** [comment]
To clarify, I would like to know if I can avoid having to hardcore the register enumeration here:

```elisp
      (global-set-key
       (kbd "C-M-j")
       (defhydra hydra-jump-to-register ()
         "scroll"
         ("j" (lambda () (interactive) (jump-to-register ?i)) "Srid.org" :color blue)
         ("p" (lambda () (interactive) (jump-to-register ?p)) "Productive.org" :color blue)
         ("w" (lambda () (interactive) (jump-to-register ?w)) "Work.org" :color blue)))
```

i.e., can the hydra automatically use j, p, w (from current register setup) without me having to enumerate them manually here?

**Comment by abo-abo** [comment]
> Please let me know if there is a better place to ask this kind of questions instead of opening a GitHub issue.

A Github issue is **the** place to ask, since it's very easy to paste snippets
here and it generates sort of a FAQ.

Here's something you can try:

```cl
(global-set-key
 (kbd "C-M-j")
 (defhydra hydra-bmk ()
   ("i" (find-file "~/.emacs.d/Srid.org") "Srid")
   ("p" (find-file "~/Dropbox/Notes/Productive.org") "Productive")
   ("w" (find-file "~/Dropbox/Notes/Work.org") "Work")))
```

See [my post](http://oremacs.com/2015/01/06/rushing-headlong/) on how
I'm dealing with bookmarks. I think that approach is more flexible
than using `defhydra`.

**Comment by srid** [comment]
Ah, yes. This is what I ended up doing just now before seeing your comment, except I had to wrap find-file with lambda and (interactive).
