### ISSUE TITLE
"Warning (emacs): Unrecognized key:" with defhydra+ and cond

### ISSUE THREAD

**Issue by tsuu32** [abo-abo/hydra#336]
I want to use `defhydra+` with conditional forms (such as `if` or `cond`).

I found following code shows warning.
```elisp
(defhydra hydra-extendable ()
  "extendable _j_"
  ("j" next-line "down"))
(cond
 (t
  (defhydra+ hydra-extendable ()
    "extendable _j_ _k_"
    ("k" previous-line "up"))
  (defhydra+ hydra-extendable ()
    "extendable _j_ _k_ _l_"
    ("l" forward-char "right"))))
```
=> Warning (emacs): Unrecognized key: \_k\_

This also shows warning.
```elisp
(defhydra hydra-extendable ()
  "extendable _j_"
  ("j" next-line "down"))
(cond
 (t
  (defhydra+ hydra-extendable ()
    "extendable _j_ _k_"
    ("k" previous-line "up"))
  (when nil
    (defhydra+ hydra-extendable ()
      "extendable _j_ _k_ _l_"
      ("l" forward-char "right")))))
```
=> Warning (emacs): Unrecognized key: \_k\_

However following code shows no warning.
```elisp
(defhydra hydra-extendable ()
  "extendable _j_ "
  ("j" next-line "down"))
(defhydra+ hydra-extendable ()
  "extendable _j_ _k_"
  ("k" previous-line "up"))
(defhydra+ hydra-extendable ()
  "extendable _j_ _k_ _l_"
```

Is there something good way to use `defhydra+` with `cond`?

**Comment by abo-abo** [comment]
Your problem is the `"extendable _j_"` docstring. This will work:

```elisp
(defhydra hydra-extendable ()
  "extendable"
  ("j" next-line "down"))


(cond
  (t
   (defhydra+ hydra-extendable ()
     "extendable"
     ("k" previous-line "up"))
   (defhydra+ hydra-extendable ()
     "extendable"
     ("l" forward-char "right"))))
```

Things like `"_j_"`, are for user-formatted docstrings. User-formatted docstrings start with a newline, which also serves to align them better.
If the docstring does not start with a newline, hydra will provide an automatic docstring.

So your issue here is using the syntax of a user-formatted docstring in an automatic docstring.

**Comment by abo-abo** [comment]
You could also do:

```elisp
(defhydra hydra-extendable (:hint none)
  "
extendable _j_
"
  ("j" next-line "down"))

(cond
  (t
   (defhydra+ hydra-extendable ()
     "
extendable _j_ _k_"
     ("k" previous-line "up"))
   (defhydra+ hydra-extendable ()
     "
extendable _j_ _k_ _l_"
     ("l" forward-char "right"))))
```

if you decide that you want user-formatted strings.

**Comment by tsuu32** [comment]
Thank you for your answer!
I'm sorry for docstring with no newline problem that is already answered in #189.

But I think there is another question.

Following shows no error.
And `M-x hydra-extendable/body` work as intended.
```emacs-lisp
(defhydra hydra-extendable (:hint none)
  "
extendable _j_"
  ("j" next-line "down"))
(defhydra+ hydra-extendable ()
  "
extendable _j_ _k_"
  ("k" previous-line "up"))
(defhydra+ hydra-extendable ()
  "
extendable _j_ _k_ _l_"
  ("l" forward-char "right"))
```

But following shows warning.(`Warning (emacs): Unrecognized key: _k_` in \*Warning\* buffer)
And `M-x hydra-extendable/body` show `extendable j _k_ l` in lv window.
So I can't use "k" key.
```emacs-lisp
(defhydra hydra-extendable (:hint none)
  "
extendable _j_"
  ("j" next-line "down"))
(cond
  (t
   (defhydra+ hydra-extendable ()
     "
extendable _j_ _k_"
     ("k" previous-line "up"))
   (defhydra+ hydra-extendable ()
     "
extendable _j_ _k_ _l_"
     ("l" forward-char "right"))))
```

I think this relate to macroexpansion.
Is there workaround?

**Comment by abo-abo** [comment]
It's indeed related to macroexpansion: both `defhydra+` statements are expanded together before they are evaluated. So in the context of their expansion, only the "j" head is defined, and "k" is not.

Here's a workaround:

```elisp
(defhydra hydra-extendable (:hint none)
  "
extendable _j_"
  ("j" next-line "down"))
(cond
  (t
   (eval '(defhydra+ hydra-extendable ()
           "
extendable _j_ _k_"
           ("k" previous-line "up")))
   (eval '(defhydra+ hydra-extendable ()
           "
extendable _j_ _k_ _l_"
           ("l" forward-char "right")))))
```

**Comment by tsuu32** [comment]
Thanks.
It works fine.
