### ISSUE TITLE
How can I hook the hydra docstring?

### ISSUE THREAD

**Issue by ema2159** [abo-abo/hydra#337]
I need to disable my tabs plugin in the hydra docstring that pops up, what is the hook to do so?

**Comment by abo-abo** [comment]
Please clarify, I don't understand what you're asking. If you want to turn off the hint, you can do it like this:

```elisp
(defun lispy-x ()
  "Forward to `hydra-lispy-x/body'"
  (interactive)
  (hydra-set-property 'hydra-lispy-x :verbosity 0)
  (hydra-lispy-x/body))
```

**Comment by ema2159** [comment]
Excuse me, I didn't explain my self properly. I am the owner of `centuar-tabs`. There's some buffers in which it's not desired to show tabs, so the user just has to configure a hook so the tabs doesn't show in that buffer. For example, if the user didn't wanted tabs in dired he juat needs to hook `centaur-tabs-local-mode` with `dired-mode-hook`, so my question is, is there a similar hook for the hydra docstring?

**Comment by abo-abo** [comment]
Hydra displays the docstring in a buffer named `" *LV*"`. You can try to have `centaur-tabs` check `(buffer-name)` and disable them accordingly.

**Comment by ema2159** [comment]
Found the solution, but it's external. The headerline must be disabled in the lv buffer similarly to the mode-line like this:
``` elisp
(defun lv-window ()
  "Ensure that LV window is live and return it."
  (if (window-live-p lv-wnd)
      lv-wnd
    (let ((ori (selected-window))
          buf)
      (prog1 (setq lv-wnd
                   (select-window
                    (let ((ignore-window-parameters t))
                      (split-window
                       (frame-root-window) -1 'below))))
        (if (setq buf (get-buffer " *LV*"))
            (switch-to-buffer buf)
          (switch-to-buffer " *LV*")
          (set-window-hscroll lv-wnd 0)
          (setq window-size-fixed t)
          (setq mode-line-format nil)
	  (setq header-line-format nil)
          (setq cursor-type nil)
          (setq display-line-numbers nil)
          (set-window-dedicated-p lv-wnd t)
          (set-window-parameter lv-wnd 'no-other-window t))
        (select-window ori)))))
```

Setting the header-line-format to nil just as the mode-line. Shall I submit a PR?

**Comment by abo-abo** [comment]
Thanks for the PR. Now we can close this issue.
