### ISSUE TITLE
:pre :post gives hydra-keyboard-quit: Symbol’s function definition is void: nil

### ISSUE THREAD

**Issue by muihlinn** [abo-abo/hydra#341]
specifically with wiki's flycheck hydra.

To my understanding it should open the flycheck error list, display the hydra and close when it quits. It only opens the error list, hydra fails to load with subject error.

**Comment by abo-abo** [comment]
I've updated the code on the wiki to this:

```elisp
(defhydra hydra-flycheck
    (:pre (flycheck-list-errors)
     :post (quit-windows-on "*Flycheck errors*")
     :hint nil)
  "Errors"
  ("f" flycheck-error-list-set-filter "Filter")
  ("j" flycheck-next-error "Next")
  ("k" flycheck-previous-error "Previous")
  ("gg" flycheck-first-error "First")
  ("G" (progn (goto-char (point-max)) (flycheck-previous-error)) "Last")
  ("q" nil))
```

In an Elisp buffer, I call `flycheck-mode` and `hydra-flycheck/body`. I get shown a list of errors. I can navigate them with <kbd>j</kbd> and <kbd>k</kbd>. But when I press <kbd>C-f</kbd>, the list of errors is hidden. Looks like the correct behavior to me.

**Comment by muihlinn** [comment]
Works perfectly. Thanks much.
