### ISSUE TITLE
Completely remove obsolete hydra-lv option

### ISSUE THREAD

**Issue by tarsius** [abo-abo/hydra#344]
You tried to make `hydra-lv` an alias of `hydra-hint-display-type` when you added the latter but that did not work as intended and you should also not have done so.

The valid values of these two variables are different, so one cannot be an alias for another. What you should have done is to declare `hydra-lv` to be obsolete (but not an alias) *and* handle a customized `hydra-lv` *explicitly*.

Since apparently nobody complained about that (except the byte-compiler (which is why I am forwarding this ;-)), I think the appropriate action at this point is to simply remove all traces of `hydra-lv`.

If you want to instead make it obsolete but not an alias, then you should replace the call to `define-obsolete-variable-alias` with

```elisp
(make-obsolete-variable
 'hydra-lv
 "use either `hydra-hint-display-type' or `hydra-set-property' :verbosity."
 "0.14.0")
```

and adjust `hydra-show-hint` to respect `hydra-lv` iff it its value is different from the default while `hydra-hint-display-type`'s value matches its own default.

**Comment by abo-abo** [comment]
Thanks.
