### ISSUE TITLE
What to do when Hydra doesn't fit in window?

### ISSUE THREAD

**Issue by didibus** [abo-abo/hydra#345]
For very big Hydras, when the list of options go off screen, it doesn't seem there is any way to scroll.

![Screenshot_20190901_211522](https://user-images.githubusercontent.com/601540/64090006-c119da80-ccfd-11e9-9060-7eff2a900d98.png)

Is there a mechanism in place for this?

**Comment by abo-abo** [comment]
I suggest splitting your hydra into two and nesting one inside the other. Like this:

```elisp
(defhydra hydra-test ()
  ("n" next-line "next line" :column "Navigation")
  ("p" previous-line "prev line")
  ("TAB" indent-for-tab-command "dwim TAB" :column "Opening Nodes")
  ("ff" counsel-find-file "create file" :column "File Management" :exit t)
  ("m" hydra-test-more/body "more" :exit t))

(defhydra hydra-test-more ()
  ("v" visual-line-mode "vlm" :column "Toggles")
  ("Pf" projectile-find-file "pff" :column "Projects" :exit t)
  ("b" hydra-test/body "back" :exit t))
(global-set-key (kbd "C-c K") 'hydra-test/body)
```

**Comment by Alexander-Miller** [comment]
The hydra in question is split in 2 now, so I think this issue can be closed.

**Comment by abo-abo** [comment]
@Alexander-Miller Thanks.
