### ISSUE TITLE
How to display the `^` character in docstring?

### ISSUE THREAD

**Issue by msladecek** [abo-abo/hydra#346]
The character `^` is used for alignment, so it can't be displayed in a docstring the same way as other characters.

Example:
```emacs-lisp
(defhydra test-hydra (:color pink :hint nil)
  "
Test
-----------
_^_: org-todo
"
  ("^" org-todo)
  ("q" quit-window "quit" :color blue))
```

![image](https://user-images.githubusercontent.com/7304317/65822432-16d19c00-e244-11e9-8859-6ac768c48873.png)

Is there a way to escape the character so it can be displayed?

Any help is much appreciated

**Comment by msladecek** [comment]
Dang, literally one minute after I created the issue I tried double slash to escape it:
```emacs-lisp
(defhydra test-hydra (:color pink :hint nil)
  "
Test
-----------
_\\^_: org-todo
"
  ("^" org-todo)
  ("q" quit-window "quit" :color blue))
```

and the result is exactly what I wanted:
![image](https://user-images.githubusercontent.com/7304317/65822491-5f3d8980-e245-11e9-8043-d4cdf181f949.png)

Sorry for the noise, I much appreciate this awesome package!

**Comment by abo-abo** [comment]
No problem :)
