### ISSUE TITLE
hydra-disable: Lisp nesting exceeds `max-lisp-eval-depth'

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/hydra#35]
After updating to the version with `lv.el`, I am getting this error

> hydra-disable: Lisp nesting exceeds `max-lisp-eval-depth'

Here is a sample of my [`defhydras`](https://github.com/kaushalmodi/.emacs.d/blob/bb5ea5af91e34ed0b3d091a16b4881afc4544c8d/setup-files/setup-misc.el#L111-140). In general, I get this error when trying to execute any hydra.

**Update**: The problem persists even when I set `hydra-lv` to `nil`.

**Update 2**: I have verified that that issue does not occur if I revert to a version older commit

    git checkout 06b35f77fdd77ce2c86d9cb5ad30d1c13134d176

*I was able to repeat this problem on both emacs 25.0 and stable emacs 24.4.*

**Comment by abo-abo** [comment]
Can you give me a minimal example? I did check my own hydras before
pushing, and the updated tests look reasonable.

**Comment by abo-abo** [comment]
Confirmed issue with Emacs version. Works fine with 24.4.1.

**Comment by kaushalmodi** [comment]
Looks like this problem occurs due to coexistence of one of the installed packages. I'll bisect my init later on today to figure out which package causes this.

As I mentioned, the issue goes away even if I revert to one version prior commit of hydra.

**Comment by abo-abo** [comment]
I know the issue now. It will only occur for Emacs 25.
It's fixable with `flet`, but obviously I can't use that. I'll need a bit more time to fix.

**Comment by kaushalmodi** [comment]
It is not yet fixed for me. The problem is something else.. I'll update when I get a chance later today.

**Comment by kaushalmodi** [comment]
I correct myself. The Melpa version of hydra was causing the problem even though `use-package` was configured to pick the `hydra` version using `:load-path`. After deleting the folder from the elpa directory, I see that this fix worked in fixing that issue.

I don't see that recursion problem but the hydras don't work:

- The text appears in the \*LV\* window but is not colored
- I get errors like these when I try to execute any hydra: `window-normalize-window: #<window 10> is not a valid window`.

*This is on emacs 25.0.*

**Comment by abo-abo** [comment]
Try to recompile both hydra.el and your code that uses it. Then restart Emacs.
I see no problems both for 24.4.1 and for 25.
