### ISSUE TITLE
"#<window 22> is not a valid window"

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/hydra#36]
Hi,

after installing the latest version (through Melpa), whenever I quit a hydra, I get an error message the main part of which is `#<window 22> is not a valid window`. (The window number varies). Setting `hydra-lv` to `nil` gets rid of the error.

Note that the exact error message I get varies. I've defined a launcher (blue hydra) much like the one in the README,  which gives the following error:

    window-normalize-window: #<window 32> is not a valid window

while a red hydra gives:

    set-transient-map PCH: (error "#<window 42> is not a valid window")

Any idea what's wrong here?

**Comment by abo-abo** [comment]
This issue is related to the Emacs version, and I can't reproduce it at the moment.
Can you give your Emacs version with a minimal example and steps to reproduce?

**Comment by joostkremers** [comment]
The output of `(emacs-version)` is:

    GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.4.2) of 2014-10-22 on IdeaPad

I installed `hydra.el` version 20150217.1113 from Melpa (which identifies itself as version 0.10.0).

The launcher I defined looks like this:

```
(defhydra hydra-launch (:color blue)
  "Launch"
  ("m" jk-mu4e "Mail")
  ("n" jk-mu4e-search-new "New mail")
  ("e" ebib "Ebib")
  ("d" deft "Deft")
  ("s" eshell "Eshell")
  ("S" (eshell t) "New Eshell")
  ("g" magit-status "Magit")
  ("p" paradox-list-packages "Packages"))
(bind-key "s-v" 'hydra-launch/body)
```

Note that calling this launcher doesn't do anything except producing the error message.

Toggling `debug-on-error` produces the following backtrace:

```
Debugger entered--Lisp error: (error "#<window 13> is not a valid window")
  signal(error ("#<window 13> is not a valid window"))
  error("%s is not a valid window" #<window 13>)
  window-normalize-window(#<window 13>)
  delete-window(#<window 13>)
  (progn (kill-buffer (window-buffer lv-wnd)) (delete-window lv-wnd))
  (if (window-live-p lv-wnd) (progn (kill-buffer (window-buffer lv-wnd)) (delete-window lv-wnd)))
  hydra-cleanup()
  hydra-launch/jk-mu4e()
  call-interactively(hydra-launch/jk-mu4e nil nil)
  command-execute(hydra-launch/jk-mu4e)
```

**Comment by abo-abo** [comment]
> GNU Emacs 24.4.1

Thanks for the info. Is that a version from git or a tarball?

From the backtrace I see that the first check `window-live-p` passes,
but then `delete-window` fails. Which could be because `kill-buffer`
somehow make `lv-wnd` not live anymore. Maybe it's an advice in action here.
I'll add another `window-live-p` check.

**Comment by kaushalmodi** [comment]
This is the same issue I mentioned in Issue #35 

I see it on both emacs 24.4 and emacs 25.0.

**Comment by abo-abo** [comment]
Does the latest commit have an effect?

**Comment by kaushalmodi** [comment]
I ran `ag 'defadv.*wind'` and these were the results

> elpa_25_0/multi-term-20141203.1658/multi-term.el
787:(defadvice delete-other-windows (around multi-term-delete-other-window-advice activate)
800:(defadvice delete-window (before multi-term-delete-window-advice activate)
829:(defadvice other-window (after multi-term-dedicated-other-window-advice)

> elpa_25_0/volatile-highlights-20141004.2240/volatile-highlights.el
681:    (defadvice occur-mode-goto-occurrence-other-window (before vhl/ext/occur/pre-hook ())
683:    (defadvice occur-mode-goto-occurrence-other-window (after vhl/ext/occur/post-hook ())

> elpa_25_0/org-20150216/org.el
21832:  (defadvice occur-mode-goto-occurrence-other-window

> elpa_25_0/git-gutter-20150106.659/git-gutter.el
501:  (defadvice linum-update-window (after git-gutter:linum-update-window activate)
844:(defadvice quit-window (after git-gutter:quit-window activate)

> elpa_25_0/neotree-20150206.1900/neotree.el
502:(defadvice delete-other-windows
513:(defadvice delete-window
554:     (defadvice popwin:close-popup-window

**Comment by kaushalmodi** [comment]
That definitely helped. Now one last hurdle.. colors.

The hydras are now functioning fine but the hints have lost the colors.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/6239637/aa7c0dc4-b6d3-11e4-8787-23e7cddf3792.png)

**Comment by abo-abo** [comment]
> The hydras are now functioning fine but the hints have lost the colors.

Could this be an issue with another package interfering?
Could you check with `emacs -Q -l hydra.el`?

**Comment by joostkremers** [comment]
I compiled my Emacs from a tar ball, not from a git repo.

Note that I get the error even in an Emacs with minimal configuration: `emacs -Q -l .emacs.d/simple-init.el`, where `simple-init.el` is:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(setq package-user-dir "~/.simple-elpa"
      package-enable-at-startup nil)
(package-initialize)

(defhydra hydra-launch (:color blue)
  "Launch"
  ("m" jk-mu4e "Mail")
  ("n" jk-mu4e-search-new "New mail")
  ("e" ebib "Ebib")
  ("d" deft "Deft")
  ("s" eshell "Eshell")
  ("S" (eshell t) "New Eshell")
  ("g" magit-status "Magit")
  ("p" paradox-list-packages "Packages"))
(global-set-key (kbd "s-v") 'hydra-launch/body)
```

The only package in `~/.simple-elpa/` is `hydra`.

**Comment by abo-abo** [comment]
> Note that I get the error even in an Emacs with minimal configuration: emacs -Q -l .emacs.d/simple-init.el:

Thanks a lot for the details. I'll try to reproduce it tomorrow.

**Comment by kaushalmodi** [comment]
@joostkremers I have seen that the problem persists if the Melpa hydra folder exists even when you choose to load the latest hydra version from git.

Try deleting the Melpa version and load only the latest git version.

**Comment by kaushalmodi** [comment]
@abo-abo Found the color culprit - The [`hl-anything`](https://github.com/boyw165/hl-anything) is causing the highlights to disappear.

@boyw165 Can you please look into this? One of the hl-anything defadvices is clearing the color highlights set in a buffer by this package.

**Comment by joostkremers** [comment]
Ok, the lastest Melpa version (20150217.1522) fixes it.

**Comment by joostkremers** [comment]
BTW, from the doc string of `kill-buffer`:

> This function calls `replace-buffer-in-windows' for cleaning up all windows currently displaying the buffer to be killed.

And the doc string of `replace-buffer-in-windows`:

> When a window showing BUFFER-OR-NAME is dedicated, that window is deleted.

So looks like it's expected behaviour (`lv-window` makes the `lv-wnd` window dedicated), at least in the Emacs version I'm running.

**Comment by abo-abo** [comment]
> So looks like it's expected behaviour (lv-window makes the lv-wnd window dedicated), at least in the Emacs version I'm running.

Yeah, I've made a silly mistake. I added `(set-window-dedicated-p lv-wnd t)` just for kicks, thinking it wouldn't hurt. At the same time I have on my system:

```cl
(defadvice set-window-dedicated-p (around no-dedicated-windows activate))
```

So I never actually ran with `set-window-dedicated-p` in place. I have a bare init target in my Makefile,
I just forgot to run it. Now it seems that the issue is resolved.

**Comment by abo-abo** [comment]
@kaushalmodi 

> Found the color culprit - The hl-anything is causing the highlights to disappear.

Can't reproduce, I need a recipe.

**Comment by kaushalmodi** [comment]
@abo-abo Found the problem finally! 

I had this in my `custom.el`

    '(major-mode (quote text-mode) nil nil)

Removing this customization fixed the problem.  I believe this issue can be closed.

Thanks!

**Comment by abo-abo** [comment]
Alright, I'm glad that's resolved. Feel free to open a new issue or
reopen this one if anything else comes up.
