### ISSUE TITLE
Feature request: make :exit support sexp

### ISSUE THREAD

**Issue by tshu-w** [abo-abo/hydra#361]
It would be nice if `:exit SEXP` is supported.

**Comment by abo-abo** [comment]
Sounds interesting. What's your use case?

**Comment by tshu-w** [comment]
I'm migrating from spacemacs to my own config and try to use hydra to simulate spacemacs [git blame transient state](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+source-control/git/packages.el#L182), it should exit when `magit-blame-mode` is `nil`, i.e. after the last time `magit-blame-quit` is called. For more info about `spacemacs|define-micro-state`, see [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-micro-state.el#L47)

**Comment by abo-abo** [comment]
Thanks, please test.

Here's how I tested it:

```elisp
(defvar hydra-test-v 1)

(defhydra hydra-test (:exit (= 0 (% hydra-test-v 5)))
  ("j" (progn
         (forward-char 1)
         (cl-incf hydra-test-v)) "char"))
```

**Comment by tshu-w** [comment]
@abo-abo Thx for you reply, but this code doesn't work on my side, I try to add `print` after `:exit`, and it seems like SEXP after `:exit` doesn't eval at all.
```emacs-lisp
  (defvar hydra-test-v 1)

  (defhydra hydra-test (:exit
                        (progn
                          (print (% hydra-test-v 5))
                          (= 0 (% hydra-test-v 5))))
    ("j" (progn
           (forward-char 1)
           (cl-incf hydra-test-v)) "char"))
```

**Comment by abo-abo** [comment]
Are you sure you're using the latest code in `master`?

I just tried your code with `print` and it works as expected.

**Comment by tshu-w** [comment]
@abo-abo sorry for my mistake, it works fine now.
