### ISSUE TITLE
Ensure `fundamental-mode` in `lv` buffer

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/hydra#364]
I recently installed [`mixed-pitch`](https://gitlab.com/jabranham/mixed-pitch), which defines a minor mode that combines fixed-pitch and variable-pitch fonts in a buffer. I added `mixed-pitch-mode` to `text-mode-hook` and was surprised to find out that hydras suddenly appeared in variable-pitch as well. That's annoying because it messes up the alignment.

After some searching, I found out that the issue was caused by the fact that I had customized the variable `major-mode` and set it to `text-mode`. As a result, the major mode of the `lv` buffer is `text-mode` and `mixed-pitch-mode` kicks in.

Would it make sense to ensure that the `lv` buffer is in `fundamental-mode`? I guess few people customize `major-mode` (I reverted the customization myself and I don't think I'll miss it), but it seems the right thing to do.

**Comment by abo-abo** [comment]
Thanks, I added `fundamental-mode`. Please test.

**Comment by joostkremers** [comment]
Yes, it works now, thanks.
