### ISSUE TITLE
Key's notation include underscore '_' popup warning with faild define!

### ISSUE THREAD

**Issue by c0001** [abo-abo/hydra#366]
Hi hydra maintainer:

I've temporary define a hydra on vanilla emacs env (27.0.90):

``` emacs-lisp
(defhydra temp/hydra
  (:hint nil :exit nil :foreign-keys nil)
  "

 temp/hydra

 Common Insert^^                                                                 
─────────────────────────────────────────────────────────────────────────────────
 _C-c C-,_: Insert a block structure of the type #+begin_foo/#+end_foo           
"
  ("C-c C-," org-insert-structure-template :exit t))
```
With follow warning:
    Warning (emacs): Unrecognized key:  _foo/#+end_

Its the bug when the key notation part contained '_' char, is that the ruby doc format limitation which can not using the underscore char in the key notation part (just can used in key stroke region)? Or is their a backslash escape like method to avoid thats strange doc defination?

I known this issue was strained, but what I want is let 'hydra' be more stronger :smiley: ,  hope for your help.

Thanks for your greate contribution!

**Comment by abo-abo** [comment]
Thanks, please test.
