### ISSUE TITLE
String doesn't show in minibuffer

### ISSUE THREAD

**Issue by dalu98** [abo-abo/hydra#367]
This is my hydra code:
```emacs lisp
(defhydra dalu/cycle-themes ()
  ("n" dalu/next-theme "next theme")
  ("p" dalu/previous-theme "prev theme")
  ("t" (message "test") "test"))
```
When I run `M-x dalu/cycle-themes/body` and press `t`, the string `test` doesn't show in minibuffer. I want to know how to solve this?

I use `next-theme` and `previous-theme` to change my current theme, and in these functions I put a `message` function to notify me which theme I am using when I change the theme. But the message only shows in `*Message*` and not in minibuffer.

Did I do something wrong somewhere? Thanks!

**Comment by abo-abo** [comment]
The issue is likely with your config. Try this:

```sh
git clone https://github.com/abo-abo/hydra/
cd hydra && make run
```

Then eval your code. For Emacs 26.3, it worked for me as expected.

**Comment by dalu98** [comment]
Thanks, I open this issue because it worked well before I upgrade `hydra`, now it looks like my config's problem. I'm going to check out where it is.
