### ISSUE TITLE
Upgrade from version 0.9.0 to 0.10.0: Deactivation of Mark within a hydra

### ISSUE THREAD

**Issue by affan-salman** [abo-abo/hydra#37]
Hi,

It's great to see hydra evolving rapidly.

For hydras (or heads thereof) intended to repeatedly operate on a
pre-defined region, upgrading from `hydra 0.9.0` to `hydra 0.10.0` seems
to cause a regression: the mark is deactivated after the first
invocation and subsequent head invocations within the hydra state either
fail to perform the intended function or behave different from the first
head invocation in that session e.g. operating on the current line
instead when using a whole-line-or-region function.

The minimal example below is for a subset of the shift-text package from
elpa:

```
(defhydra hydra-rigid-indent (global-map "C-x")
  "rigid-indent"
  ("<tab>" shift-text-right))
```

Can you let me know if you need more details please?

**Comment by abo-abo** [comment]
Can't reproduce at the moment on Emacs 25.
I'm not familiar with `shift-text` but <kbd>C-x tab tab tab</kbd>
appears to do the same as <kbd>M-x</kbd> `shift-text-right` for an active region.
Could you try again with the latest update, your code re-compiled and Emacs restarted?

**Comment by affan-salman** [comment]
> Could you try again with the latest update, your code re-compiled and
> Emacs restarted?

Yes, I have but to no avail unfortunately.

> I'm not familiar with shift-text but C-x tab tab tab appears to do the
> same as M-x shift-text-right for an active region.

That sounds like new behaviour in emacs 25.  I am on `GNU Emacs 24.4.1
(x86_64-unknown-linux-gnu, X toolkit, Xaw scroll bars)` and the
behaviour of `indent-rigidly` as summed up by this `describe-function`
excerpt is:

```
activate a transient mode in which the indentation can be adjusted
interactively by typing <left>, <right>, <S-left>, or <S-right>.  Typing
any other key deactivates the transient mode.
```
...which essentially sounds similar to the core of the hydra behaviour
but in addition to the lack of possibility of repeating <tab> with it,
it also lacks the four-direction movement that shift-text provides;
<up>, <down>, <left> and <right>.  However, none of those is my key use
case; I have a highly customised indentation function which I was
making heavy use of hydra for.  It has broken since the upgrade from
0.9.0.

Thanks for your reply.

**Comment by kaushalmodi** [comment]
I have been seeing this problem.

I noticed this when trying to use a hydra to toggle comment on the selected region. If `hydra-lv` is disabled, the comment toggling works fine over a selected region using a hydra.

But when `hydra-lv` is enabled, the selected region is deactivated. So any region-based action can't be done using a hydra. Is it because the focus is shifted to the `lv` window?

**Comment by affan-salman** [comment]
Thanks!  Yeah, I have been able to test and confirm this as well.

**Comment by kaushalmodi** [comment]
Here's how to recreate this:

- Download [hydra_issue_37.el](https://gist.github.com/51029361a5b3d44f9f34)
- `\emacs -Q -l hydra_issue_37.el`
- Try out commenting/uncommenting on a region; select some text.. you can select the default text in the \*scratch\* buffer itself and then do `M-c ;`. The function won't work.
- But now if you add `(setq hydra-lv nil)` to  `hydra_issue_37.el` after `(require 'hydra)` and re-do  `\emacs -Q -l hydra_issue_37.el`, the region commenting will work.

**Comment by abo-abo** [comment]
Thanks, I got it. Region is deactivated because `delete-region` was being called in another window.
Makes sense. Fix incoming.

**Comment by kaushalmodi** [comment]
Thanks! I confirm that the fix works.
