### ISSUE TITLE
Nesting Hydras with :post, :exit, :after-exit

### ISSUE THREAD

**Issue by caiohcs** [abo-abo/hydra#375]
After exiting an Hydra, I want to always call a function that might invoke another Hydra depending on a global variable.

Using **:post** to call the function kinda works as expected, the problem is that it keeps displaying an error message:
Error in pre-command-hook (hydra--clearfun): (wrong-type-argument keymapp nil)

I tried looking for alternative solutions:
Using **:exit** to call the function does nothing, it only exits the Hydra.
Using **:after-exit** to call the function calls it after executing every head (even red heads) instead of calling it only once after the body exits.

I don't know if it is relevant, but my function changes the variable hydra-is-helpful to nil.

I'm running hydra-20200504.1747 on Emacs 26.3.

**Comment by abo-abo** [comment]
Please post the code of your hydras.

**Comment by caiohcs** [comment]
This is the code using :post:

```
;;; Hydra A
(setq hydra-A-was-active nil)
(defun my-fn/conditionally-invoke-hydra-A ()
    (if hydra-A-was-active
        (my-fn/invoke-hydra-A)))

(defun my-fn/invoke-hydra-A ()
  (interactive)
  (set-cursor-color "#ff0000") 
  (setq hydra-is-helpful nil)
  (setq hydra-A-was-active t)
  (hydra-A/body))
  
(defhydra hydra-A (:color amaranth
		   :hint nil
                   :post (progn (set-cursor-color "#000000")
				(setq hydra-is-helpful t)))
  "
  _q_:uit   _h_:elp on/off   _b_: call hydra B

  _p_:rev line   _n_:ext line   _s_:ave pos   _j_:ump pos  
  "
    ("q" (setq hydra-A-was-active nil) :exit t)
    ("h" (setq hydra-is-helpful (not hydra-is-helpful)))
    ("n" next-line)
    ("p" previous-line)
    ("s" (point-to-register 'g))
    ("j" (jump-to-register 'g))
    ("b" hydra-B/body :exit t))

(global-set-key (kbd "<f4>") 'my-fn/invoke-hydra-A)

;;; Hydra B
(defhydra hydra-B (:color amaranth 
		   :hint nil
		   :post my-fn/conditionally-invoke-hydra-A)
  "
  _q_:uit
  _b_: left wind   _p_: up wind
  _f_: right wind  _n_: down wind
    "
  ("q" (hydra-movement/cond-body-call) :color blue)
  ("b" windmove-left)
  ("f" windmove-right)
  ("p" windmove-up)
  ("n" windmove-down))

(global-set-key (kbd "<f3>") 'hydra-B/body)
```
If I press "f4" to call hydra A, then "b" to call hydra B and then "q" to quit and go back to hydra A, when I try to press any other key that error message appears. For instance, if I press some key that isn't an hydra A head like the key "a", the character "a" is inserted despite hydra A being of color amaranth.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by caiohcs** [comment]
I downloaded and recompiled hydra.el, now the code above works as expected. Thanks.
