### ISSUE TITLE
Feature request: more control over hint-generation

### ISSUE THREAD

**Issue by Gallipo** [abo-abo/hydra#376]
I love doc-strings where you can do stuff like `_key_: some description`. But if you do so, all changes to a binding have to be done in 2 places (the binding and the doc-string).
And then there is the :hint which is generated from the information given in the binding section, but usually looks ugly.
Wouldn't it be possible generate customizable hints with special comments (something) like this:
`;; %colum general
("a" do-stuff "^do^")

;; %colum special
("b" do-special "extra")

;; %ascii
"some-ascii-art"`

I hope you get what I mean. 
This would make hydra-definitions and their editing more easy. And imo this would lead to shorter, nicer looking code in `(defhydra …`

**Comment by abo-abo** [comment]
You can already do this with `:column`. Here's an example:

```elisp
(defhydra hydra-clock (:color blue)
  ("q" nil "quit" :column "Clock")
  ("c" org-clock-cancel "cancel" :color pink :column "Do")
  ("d" org-clock-display "display")
  ("e" org-clock-modify-effort-estimate "effort")
  ("i" org-clock-in "in")
  ("j" org-clock-goto "jump")
  ("o" org-clock-out "out")
  ("r" org-clock-report "report"))
```

**Comment by Gallipo** [comment]
Oh, how could I miss that?
Sorry
Thank you!
