### ISSUE TITLE
Request: Amaranth Hydra but Unbound Keys Work

### ISSUE THREAD

**Issue by angelic-sedition** [abo-abo/hydra#38]
I'm not sure how easy or possible it would be, but I think it would be cool if there was another color that was like a mixture of amaranth and red. Keys that aren't bound in the hydra perform their default actions like with red except that the hydra isn't exited like with amaranth.

**Comment by abo-abo** [comment]
See if pink color does what you want.

**Comment by kaushalmodi** [comment]
Is this a correct summary?

<pre>
|----------+-----------+------------------+-------------------+-------------------|
| Color    | Impact    | Allows execution | Quits hydra after | Quits hydra after |
|          |           | of keys unbound  | execution of keys | executing head    |
|          |           | to heads         | unbound to heads  |                   |
|----------+-----------+------------------+-------------------+-------------------|
| amaranth | body      | No               | No                | No                |
| pink     | body      | Yes              | No                | No                |
| red      | body/head | Yes              | Yes               | No                |
| blue     | body/head | Yes              | Yes               | Yes               |
|----------+-----------+------------------+-------------------+-------------------|
</pre>

**Comment by abo-abo** [comment]
I'd phrase it like this:

1.. Heads can only be red or blue. Red heads continue the Hydra, blue heads quit.

2.. Body can be red or blue or amaranth or pink.

Each body type makes the heads inherit the appropriate color, which can be overridden in the head:

    - red - red
    - blue - blue
    - amaranth - red
    - pink - red

3.. Body types which quit when a non-head is pressed: red, blue. Both amaranth and pink will not quit.

    amaranth calls on intercepting non-head: warning
    pink calls on intercepting non-head: it

**Comment by abo-abo** [comment]
I'm thinking of adding a

    - teal - blue

that intercepts non-heads. This would be similar to `magit` dispatch.

**Comment by kaushalmodi** [comment]
@abo-abo `blue` anyways intercepts non-heads (or am I misunderstanding by what you mean by non-head interception?). For example if `a` is not bound to a hydra with blue body and if I press `a`, `a` will be input in the current buffer and the hydra will quit.

**Comment by abo-abo** [comment]
@kaushalmodi, blue doesn't intercept, it simply yields to the default Emacs. Pink intercepts and and calls command.

**Comment by abo-abo** [comment]
So if you type <kbd>a</kbd>, Hydra has already quit, and then Emacs sorts it out.

**Comment by kaushalmodi** [comment]
@abo-abo I didn't understand the difference between interception and Emacs sorting it out. I believe an example showing the difference between the `blue` body and the planned `teal` body would help.

For instance, how would the below behave if I pressed `a` if the body were `teal` vs `blue`?

``` elisp
;; test hydra
(defhydra hydra-test (:color blue)
  "test"
  ("p" previous-line "prev")
  ("n" next-line     "next")
  ("q" nil           "cancel" :color blue))
(global-set-key (kbd "C-c l") #'hydra-test/body)
```

**Comment by abo-abo** [comment]
Blue would quit and Emacs would insert `a`. Teal would say: "An teal Hydra can only exit through a blue head" and do nothing.

**Comment by abo-abo** [comment]
OK, teal update is here, you can try it out.

**Comment by kaushalmodi** [comment]
Great! Makes sense. Here's my updated reference table:

<pre>
|----------+-----------+------------------+----------------+-------------|
| Body     | Head      | Allows execution | Quits hydra    | Quits hydra |
| Color    | Inherited | of NON-HEADs     | after NON-HEAD | after HEAD  |
|          | Color     |                  | execution      | execution   |
|----------+-----------+------------------+----------------+-------------|
| amaranth | red       | No               | No             | No          |
| pink     | red       | Yes              | No             | No          |
| red      | red       | Yes              | Yes            | No          |
| teal     | blue      | No               | No             | Yes         |
| blue     | blue      | Yes              | Yes            | Yes         |
|----------+-----------+------------------+----------------+-------------|
</pre>

**Comment by kaushalmodi** [comment]
Also, it should be *A teal Hydra ..* instead of *An teal Hydra ..*.

**Comment by abo-abo** [comment]
I think less is more in this case:

    |----------+-----------+-----------------------+-----------------|
    | Body     | Head      | Executing NON-HEADS   | Executing HEADS |
    | Color    | Inherited |                       |                 |
    |          | Color     |                       |                 |
    |----------+-----------+-----------------------+-----------------|
    | amaranth | red       | Disallow and Continue | Continue        |
    | pink     | red       | Allow and Continue    | Continue        |
    | red      | red       | Allow and Quit        | Continue        |
    | teal     | blue      | Disallow and Continue | Quit            |
    | blue     | blue      | Allow and Quit        | Quit            |
    |----------+-----------+-----------------------+-----------------|

**Comment by angelic-sedition** [comment]
That was fast; thanks! It seems to work well for me. Though when I try to use backspace, it says "a pink hydra can only exit through a blue head". I don't have it bound in the hydra. Is there a way to have backspace act as normal too?

Also, there is a typo in the "can't currently handle prefixes" message. It says "aboring" instead of aborting.

**Comment by abo-abo** [comment]
> That was fast; thanks! It seems to work well for me. Though when I try to use backspace, it says "a pink hydra can only exit through a blue head". I don't have it bound in the hydra. Is there a way to have backspace act as normal too?

It seems that `(key-binding (this-command-keys))` somehow returns nil *specifically* for <kbd>DEL</kbd>, *specifically*
for when a Hydra is active. I don't see a solution yet.

> Also, there is a typo in the "can't currently handle prefixes" message. It says "aboring" instead of aborting.

Fixed.

**Comment by abo-abo** [comment]
Added a workaround specially for backspace.

**Comment by kaushalmodi** [comment]
@abo-abo About typos, shouldn't ["An teal"](https://github.com/abo-abo/hydra/blob/4f0ef6298ce4bb3204318a9dd1210794735eb106/hydra.el#L524) be fixed to "A teal"?

**Comment by abo-abo** [comment]
@kaushalmodi, I've missed a coffee and now I'm off my game:)

**Comment by abo-abo** [comment]
Since everything seems to be solved, closing the issue. Open a new one if something else comes up.
