### ISSUE TITLE
Please add regexes for hydra to imenu so that for example counsel-imenu allows you to jump to hydras

### ISSUE THREAD

**Issue by michaelmrose** [abo-abo/hydra#380]
Example 

        (defun mmr/enrich-imenu-emacs-lisp ()
        (interactive)
        (add-to-list  'imenu-generic-expression '("Hydras" "^.*(\\(pretty-hydra-define\\|defhydra\\) \\([a-zA-Z-]+\\)" 2) )
        )

        (add-hook 'emacs-lisp-mode-hook 'mmr/enrich-imenu-emacs-lisp)

imenu-generic-expression is buffer local I'm not sure if there is a better way include a particular regex for a particular mode.

**Comment by abo-abo** [comment]
Thanks.
