### ISSUE TITLE
hydra+ plus with-eval-after-load

### ISSUE THREAD

**Issue by jkroes** [abo-abo/hydra#382]
Any idea why the first section of code would work but not the second?

```
(use-package ace-window
  :after hydra
  :config
  (defhydra+ hydra-window ()
    ("a" ace-window)
    ("s" ace-swap-window)
    ("d" ace-delete-window)))
```

```
(use-package ace-window
  :config
  (with-eval-after-load "hydra"
    (defhydra+ hydra-window ()
      ("a" ace-window)
      ("s" ace-swap-window)
      ("d" ace-delete-window))))
```
The error message for the first code block: "Symbol's value as variable is void: hydra-window/params." I'm guessing this may be a use-package issue. If this is outside the scope of potential fixes, feel free to close the issue.

**Comment by aspiers** [comment]
What was the conclusion of this? I want to do something similar.
