### ISSUE TITLE
Move nadvice from outdated advice package

### ISSUE THREAD

**Issue by conao3** [abo-abo/hydra#396]
https://github.com/abo-abo/hydra/blob/2d553787aca1aceb3e6927e426200e9bb9f056f1/hydra.el#L332-L350
https://github.com/abo-abo/hydra/commit/27b7f40cb21157be0dabc37046b83ed99151a26e
It's 2021. please use latest advice package. (and easy remove feature is useful for user convenience)

**Comment by basil-conto** [comment]
See #413.  The version of `hydra` on [GNU-devel ELPA](https://elpa.gnu.org/devel/hydra.html) is already using `nadvice`.

**Comment by conao3** [comment]
Sorry for the rude comment. Honestly, I am a little shocked to see my comments from 3 years ago. I was just a beginner then. I'm glad it has been resolved.

**Comment by basil-conto** [comment]
> Sorry for the rude comment.

Don't worry, I can relate to the sentiment, and it wasn't so rude :).

> I'm glad it has been resolved.

The resolution is ongoing for archives other than GNU-devel ELPA, but it should be in soon!
