### ISSUE TITLE
Problem if you set the head to `C-x` in global map

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/hydra#4]
The below code can become a problem if the head is set to `C-x` instead of `C-M-=`.
 
    (hydra-create "C-M-="
      '(("=" modi/font-size-incr  "Increase font size")
        ("-" modi/font-size-decr  "Decrease font size")
        ("0" modi/font-size-reset "Reset font to default size")))

Is some other way possible than setting the binding of head to `nil` for any map (global or not)?

**Comment by abo-abo** [comment]
Would this work for you?

```cl
(hydra-create "C-x"
  '(("=" modi/font-size-incr  "Increase font size")
    ("-" modi/font-size-decr  "Decrease font size")
    ("0" modi/font-size-reset "Reset font to default size"))
  (lambda (key cmd)
    (global-set-key key cmd)))
```

**Comment by kaushalmodi** [comment]
I believe that will work. But can this be make the default?

**Comment by abo-abo** [comment]
I just want to avoid the `Key sequence C-y = starts with non-prefix key C-y` error.

I'd gladly simplify `hydra-create`, provided I can avoid confusing the users that try to define a Hydra on top of a binding that's not currently a prefix.

Would you prefer that hydra issues an error in this case, or attempts to fix it, as it currently does?

**Comment by kaushalmodi** [comment]
I would personally prefer to get the error as there is less hassle involved.

If I use `C-x` or `C-c` as a head for hydra, I would need to restart emacs to fix that.
But if I use `C-y`, I should know better what I am binding the hydra to.

I have tried my hand implementing the idea I have but I am not very good with the syntax so the below fails. But I hope you get the idea:

<pre>
    (lambda (key command) (define-key MAP key command))"
  (declare (indent 1))
  (let* ((keymap (make-sparse-keymap))
         (heads (eval heads))
         (names (mapcar
                 (lambda (x)
                   (define-key keymap (kbd (car x))
                     (intern (format "hydra-%s-%S" body (cadr x)))))
                 heads))
         ;; TODO set the default METHOD to `define-key' but the user can override
         ;; that if they wish e.g. override to key-chord-define-global
         (map (cond ((null map) global-map) ; bind to `global-map' by default
                    (t          (eval map)))) ; bind to MAP specified by user
         (hint (concat "hydra: "
                       (mapconcat
                        (lambda (h) (if (caddr h)
                                        (format "[%s]: %s"
                                                (propertize (car h)
                                                            'face 'font-lock-keyword-face)
                                                (caddr h))
                                      (propertize (car h) 'face 'font-lock-keyword-face)))
                        heads ", ")
                       ".")))
    `(progn
       ;; Unbind the key only if the BODY is not bound to another keymap
       ;; and it is also not an alist of bindings (in which case the `safe-length'
       ;; will be 0
       (when (and (= safe-length (lookup-key ,map ,body) 0)
                  (not (keymapp (lookup-key ,map ,body))))
         (define-key ,map ,(kbd body) nil))
       ,@(cl-mapcar
          (lambda (head name)
            `(defun ,name ()
               ,(format
                 "Create a hydra with a \"%s\" body and the heads:

%s.

Call the head: `%S'."
                 body
                 (mapconcat
                  (lambda (x)
                    (format "\"%s\":    `%S'" (car x) (cadr x)))
                  heads ",\n")
                 (cadr head))
               (interactive)
               (call-interactively #',(cadr head))
               (when hydra-is-helpful
                 (message ,hint))
               (set-transient-map ',keymap t)))
          heads names)
       ,@(cl-mapcar
          (lambda (head name)
            `(define-key ,map ,(vconcat (kbd body) (kbd (car head))) #',name))
          heads names))))
</pre>

**Comment by abo-abo** [comment]
OK, I get this part, and it will probably work:

```cl
(not (keymapp (lookup-key ,map ,body)))
```

But what is this?

```cl
;; Unbind the key only if the BODY is not bound to another keymap
;; and it is also not an alist of bindings (in which case the `safe-length'
;; will be 0
```

**Comment by kaushalmodi** [comment]
You're right, you probably don't need that.

I added that because when I evaluated 

    (lookup-key modi-mode-map "\C-xm")

I got 

<pre>
(keymap (111 . poporg-dwim) (110 . neotree-toggle) (105 . iregister-latest-text) (72 . hl-unhighlight-all-global) (104 . hl-highlight-thingatpt-global) (63 . modi/elisp-slime-nav-find-elisp-interactive) (59 . elfeed) (100 . de-ansify) (75 . buf-move-down) (107 . buf-move-up) (46 . buf-move-right) (44 . buf-move-left) (103 . ag-project-regexp) (97 . ag-project-regexp) (114 . set-rectangular-region-anchor) (109 . mc/mark-all-like-this-dwim) (108 . xah-run-current-file) (112 . ps-print-buffer-with-faces) (115 . search-all-buffers) (43 . balance-windows) (121 . bury-buffer) (102 . full-screen-center) (98 . modi/switch-to-scratch-and-back) (61 . what-cursor-position) (120 . eval-and-replace-last-sexp) (32 lambda nil (interactive) (insert-char 8203)) (62 lambda nil (interactive) (insert-char 9755)) (76 . modi/show-long-lines))
</pre>

I got confused because

    (lookup-key modi-mode-map "\C-xm")

returned `Control-x-prefix`, a `keymap` variable.

Now I see that the `alist` that was returned by my minor mode prefix map is also a `keymap`, just not stored in a variable. So the `safe-length` statement is redundant.

**Comment by abo-abo** [comment]
OK, please double check. Thanks for helping.

**Comment by kaushalmodi** [comment]
Related suggested: The check whether the BODY is bound to a keymap is required for all maps: global or not.

The same error when binding to a non-prefix key happens when I bind a non-prefix key in any mode map to the hydra.

That's why we would need something analogous to

    (not (keymapp (lookup-key ,map ,body)))

where `map` can be `global-map` or `xyz-mode-map`.
