### ISSUE TITLE
Programmatically creating hydras?

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/hydra#40]
Following up on http://oremacs.com/2015/02/19/hydra-colors-reloaded/#comment-1866197495

I post the example code below, but to get to the point quickly: It probably wouldn’t be difficult to write a macro that generates a call to `defhydra` based on some the contents of `pandoc--binary-options`. The problem is that I would like to have a nice menu like the ones generated by the new doc string but that the number of rows and columns in which the hydra’s heads are presented can’t be determined in advance. If the frame is wide, there can be more columns and fewer rows, if it is narrower, there will need to be more rows and fewer columns.

Anyway, to see what I do with the menus: the code creating the menu in `pandoc-mode` is here:

https://github.com/joostkremers/pandoc-mode/blob/master/pandoc-mode.el#L1522

As an example, I have an alist `pandoc--binary-options` which contains conses of the form `(<descr> . <option>)`. `<descr>` is a string that will appear in the menu, `<option>` is a symbol that is used internally to keep track of the option’s value. Using this alist, I create a submenu with the following code in`easy-menu-define` (starting at line 1613):

```
("Switches"
     ;; put the binary options into the menu
     ,@(mapcar (lambda (option)
                 (vector (car option) `(pandoc--toggle (quote ,(cdr option)))
                         :active t
                         :style 'toggle
                         :selected `(pandoc--get (quote ,(cdr option)))))
               pandoc--binary-options))
```

The alist `pandoc--binary-options` is populated by a macro `pandoc-define-binary-option`, which takes `<descr>` and `<option>` as arguments (and does a few other things as well). This way, when Pandoc adds a new option, I only need to add a single line to `pandoc-mode.el`, everything else is generated automatically.

**Comment by abo-abo** [comment]
Wow, that's a lot to think about. I'll install pandoc-mode tomorrow and
see how this easy-menu looks like.

A possible choice is just to nest hydras in exactly the same way as
easy-menu nests its lists.

Another choice is to write a function to generate nicely aligned
docstring templates with a configurable amount of columns.
Probably a challenge to implement, but it'll look cool in the end.

**Comment by joostkremers** [comment]
> A possible choice is just to nest hydras in exactly the same way as easy-menu nests its lists.

Not sure what you mean here. I don’t see how that solves the issue I’m having.

Calling a hydra from within a hydra works just fine, so hydras work perfectly for creating static “menus”.

(Though I could envisage a `define-nested-hydra` macro that defines a set of nested hydras in one go.)

> Another choice is to write a function to generate nicely aligned docstring templates with a configurable amount of columns.

That would be cool, yeah. In order for it to work for my purpose, the docstring would have to be created anew every time the hydra body is called, in order to adjust it to the available lv-window width.

Of course, there’s no need for you to cater to my wishes. :) If you’d be interested in this in principle but it’s not high on your list of priorities, I’d be happy to take a look myself and see what I can come up with.

**Comment by abo-abo** [comment]
> That would be cool, yeah. In order for it to work for my purpose, the docstring would have to be created anew every time the hydra body is called, in order to adjust it to the available lv-window width.

That's the flexibility that I'm looking for in the end: an alternate menu implementation.
Menus can be created on the fly, extended and modified.

It will take some time to make hydra work like this.

**Comment by joostkremers** [comment]
Cool. +1 for Package of the Month Award.

**Comment by abo-abo** [comment]
See an initial approximation for making it more automatic.
It does require a switch to my data structures though, although they're very simple.

**Comment by joostkremers** [comment]
That looks cool.

I noticed that instead of a doc string, there's a Lisp expression in the `defhydra` of `pandoc-binary

**Comment by abo-abo** [comment]
Yes, the Lisp expression will be evaled dynamically. Eventually it will adapt to window width.
Also, it's possible to eval it in-place to generate a static string that can be edited by hand.

**Comment by joostkremers** [comment]
The data I want to present in the doc string isn't easily amenable to a `defhydradio`, so I wrote my own tabulation function, which works quite well. It adapts to the (root) window width, but I noticed that the doc string is created when the hydra is defined and therefore doesn't adapt to the window width at the moment the hydra is called. Will the functionality to adapt to the window width be available to custom docstring functions as well?

I've also tried to create the list of heads programmatically, but haven't had any luck so far... Do you have any plans to make this easier? Thanks.

**Comment by abo-abo** [comment]
> the doc string is created when the hydra is defined and therefore doesn't adapt to the window
> width at the moment the hydra is called

Yes, this should be fixed at some point. There's already some progress towards this: thanks to Ruby-style
interpolation, the hint is re-computed on each display. However, a large part of the hint is still static.

> I've also tried to create the list of heads programmatically, but haven't had any luck so
> far... Do you have any plans to make this easier? Thanks.

I'm not sure if creating the list of heads on-the-fly is a good idea.
But I'd like to make it easy to re-generate content for the current interface: if you look
at what `hydra--table` does in `pandoc-binary` example, it makes re-generating the docstring quite easy,
while still maintaining the default interface.

`defhydra` generates lots of code, and the current interface already looks quite minimal and not too
different from some on-the-fly implementation that I can imagine, so I'd like to keep things more
explicit.

In any case, I'd like to see what you have at the moment, and what the current bottleneck is.

**Comment by joostkremers** [comment]
> I'm not sure if creating the list of heads on-the-fly is a good idea.

It wouldn't really have to be on the fly. What I'd like to do is instead of specifying all the heads explicitly in the `defhydra`, I'd like to write something like:

```
(defhydra pandoc-output-format-hydra (:foreign-keys warn :exit t :hint nil)
  (concat "\n" (pandoc--tabulate-output-formats) "\n\n")
  (mapcar (lambda (it)
            (cons (cadddr it) (car it)))
          pandoc-output-formats))
```

`pandoc-output-formats` contains info about the output formats. This information is needed in several places in the source, but I’d like to avoid having to specify it more than once in order to avoid inconsistencies. Its value is set in the source code, though, and doesn't change, so the hydras wouldn't have to be (re)created at run time. They can still be defined at load time.

Of course, the definition doesn’t have to be in this form. I also tried writing a macro that produces a `defhydra`, but wasn’t successful. (I think I’m running into the limits of my understanding of macros, though, so possibly I just need to delve deeper into them to figure out how to make it work.)

> In any case, I'd like to see what you have at the moment, and what the current bottleneck is.

The code I’ve written so far is here:

https://github.com/joostkremers/pandoc-mode/tree/hydra

Let me know if you have any more questions. Thanks for looking into it.

**Comment by joostkremers** [comment]
Specifically, the hydra code starts here:

https://github.com/joostkremers/pandoc-mode/blob/hydra/pandoc-mode.el#L1624

**Comment by joostkremers** [comment]
>  I also tried writing a macro that produces a `defhydra`, but wasn’t successful.

I think I figured it out. Wasn't as complicated as I thought...

**Comment by abo-abo** [comment]
OK, I see that you went with manual Ruby-style string interpolation. I think it's quite reasonable, and flexible enough. Maybe you noticed that I turned off the truncation in `lv-message`, so large messages are just truncated instead of falling apart.

Let me know when your system is ready for use, maybe I'll see some issues that I could fix in hydra.

**Comment by joostkremers** [comment]
Well, everything now seems to be working. I've updated the `hydra` branch of the `pandoc-mode` repo.

To give you a quick overview of how it works: `pandoc-mode-utils.el` first defines a number of macros called `define-pandoc-*-option`, where the asterisk stands for the type of option (file, string, number, choice, etc.), and one macro `define-pandoc-switch`, for binary switches. These macros, among other things, populate several global variables called `pandoc--*-hydra-list` with data that will be used to create the hydras.

The hydras themselves are created in `pandoc-mode.el`. (I split the original `pandoc-mode.el` so that I wouldn’t have to write `eval-and-compile` all the time.) Some of the hydras are created with `defhydra`, but I’ve also written a hydra-creating macro called `define-pandoc-hydra`, which is basically just a call to `defhydra`. Compared to `defhydra`, it takes an additional argument that is evaluated and should return a list of hydra heads. This macro makes it possible to define hydras programmatically, which was my goal.

There are two more hydras created with `define-pandoc-hydra`. These control the input and output formats for Pandoc, which are also stored in global variables.

I have to say, it works very well. Using the hydras to navigate all the options and settings that `pandoc` has is very pleasant. Much more so than using the menu.

**Comment by abo-abo** [comment]
It looks really, really cool. Extensive, but very clean.

> `define-pandoc-hydra`

Nice idea. I'm currently thinking of adding an OOP-like inheritance for `defhydra`. It could serve
here as well.

> `define-pandoc-switch`

You should probably prefer `push` or `cl-pushnew` instead of `add-to-list`.

> Using the hydras to navigate all the options and settings that pandoc has is very pleasant

Yes, it looks very nice. On a small note, from a first-time user, it would be cool to know which
parts of the main menu are explorable (i.e. you can press `back` to undo), and which really leave
the hydra. It's a small thing that probably goes away quickly with use, but it's nice to have for
new users.

It seems that you've solved all the issues, so I'm closing this one. Let me know when the hydra
branch will be published so that I can link the README.md to a nice example of what is possible to
do with nested hydras.

**Comment by joostkremers** [comment]
> It looks really, really cool.

Thanks, but it’s mostly your work, of course.

> > `define-pandoc-switch`

> You should probably prefer `push` or `cl-pushnew` instead of `add-to-list`.

Yup, true. Fixed.

> Yes, it looks very nice. On a small note, from a first-time user, it would be cool to know which parts of the main menu are explorable (i.e. you can press back to undo), and which really leave the hydra. It's a small thing that probably goes away quickly with use, but it's nice to have for new users.

I made every submenu behave in the same way: exit with `q`, go back with `b`, while setting an option doesn’t leave the hydra. That should make it possible to move around the menus and see what’s there.

> It seems that you've solved all the issues, so I'm closing this one.

There’s one thing I’ve been meaning to ask: would it be possible to make the warning message that is printed with `:foreign-keys warn` customisable? Perhaps by passing a string instead of `warn` as the value for `:foreign-keys`? The standard message is rather cryptic if you got `hydra.el` through `pandoc-mode.el`.

> Let me know when the hydra branch will be published so that I can link the README.md to a nice example of what is possible to do with nested hydras.

I just merged it. Should appear in Melpa in a few hours.

**Comment by abo-abo** [comment]
> There’s one thing I’ve been meaning to ask: would it be possible to make the warning message that
> is printed with :foreign-keys warn customisable? Perhaps by passing a string instead of warn as
> the value for :foreign-keys? The standard message is rather cryptic if you got hydra.el through
> pandoc-mode.el.

It will be possible to do soon, I just have to merge the `term-fix` branch.  It already has a [hydra-amaranth-warn](https://github.com/abo-abo/hydra/blob/term-fix/hydra.el#L114) function that has nothing in it but the message statement.

I just want to be careful with `term-fix` since it stops using `set-transient-map`, and that may
result in bugs, since `set-transient-map` has 3 different implementations depending on the Emacs
version. It's supposed to improve the stability of amaranth and pink hydras by not using the `t`
catch-all binding in the keymaps.
