### ISSUE TITLE
Timer is no longer correctly stopped and prevents hydra from working

### ISSUE THREAD

**Issue by rememberYou** [abo-abo/hydra#402]
First of all, thank you for `hydra`. It helps me a lot on a daily basis.

Unfortunately, recently I have `hydra` that stopped working returning the following error:
```
cancel-timer: Wrong type argument: timerp, [t nil nil nil nil nil nil nil nil]
```
To fix this error, I had to skip the `cancel-timer` instructions in the `hydra-keyboard-quit` function:
```lisp
(defun hydra-keyboard-quit ()
  "Quitting function similar to `keyboard-quit'."
  (interactive)
  (hydra-disable)
  (when hydra--posframe-timer ; <---- cancel the timers
    (cancel-timer hydra-timeout-timer)
    (cancel-timer hydra-message-timer))
  (unless (and hydra--ignore
               (null hydra--work-around-dedicated))
    (funcall
     (nth 2 (assoc hydra-hint-display-type hydra-hint-display-alist))))
  nil)
```
Since I doubt that this is the way to solve this problem, I did not open a pull request.

Do you have any recommendations to fix this? I would like to point out that I use GNU Emacs 28.0.50 and `hydra` has been working with it for a long time. However, this is still a development version of GNU Emacs. I haven't tested to see if the error is present with a more stable version.

**Comment by Jehops** [comment]
Its looks like @larsmagne made some timer changes: https://github.com/emacs-mirror/emacs/commit/50765f3f511d467ff024dda7c84530c759253d18

**Comment by rememberYou** [comment]
@Jehops Well seen! That explains it. Probably the issue should be kept open to allow `hydra` to adapt to future GNU Emacs releases. Thanks once more.

**Comment by cormacc** [comment]
I don't think any change to hydra is required -- just need to delete and reinstall the hydra package to force emacs to recompile it with the new timer type. Worked for me anyway (using spacemacs -- deleted the 'hydra-<date/versionstamp>' dir within .emacs.d/elpa/28.0/develop'

**Comment by deusmax** [comment]
Same issue here. FWIW, here is the backtrace:

> Debugger entered--Lisp error: (wrong-type-argument timerp [t nil nil nil nil nil nil nil nil])
> cancel-timer([t nil nil nil nil nil nil nil nil])
>  hydra-keyboard-quit()
> (let ((hydra--ignore nil)) (hydra-keyboard-quit) (setq hydra-curr-body-fn 'hydra-zoom/body))
>  hydra-zoom/body()
>  funcall-interactively(hydra-zoom/body)
 > command-execute(hydra-zoom/body)

will try above suggestions and report.

**Comment by Jehops** [comment]
Thanks all.

Something to bump the package on melpa (new release? dummy commit?) might save everyone else some time.

**Comment by rememberYou** [comment]
Thanks @deusmax. Reinstalling `hydra` and reloading GNU Emacs fixed the issue. 

Since this issue doesn't seem to be related to `hydra`, I'll close it. At least people who have encountered the same problem will be able to find the solution in this issue :-)
