### ISSUE TITLE
Default command when `defhydra` first called

### ISSUE THREAD

**Issue by nurdann** [abo-abo/hydra#416]
If I got following hydra definition
```
(defhydra hydra-window (global-map "C-x o")
  ("o" other-window))
```

Is it possible so that `other-window` is issued right away once without waiting when I press `C-x o`?

**Comment by dericbytes** [comment]
(defhydra hydra-window (global-map "C-x o")
  ("o" other-window :exit t))

**Comment by nurdann** [comment]
What I was looking for is issuing `other-window` right-away, in many cases if I have two windows so I am pressing extra command to switch to a window

**Comment by dericbytes** [comment]
I am sorry. I do not understand.

With the added ':exit t'. If you type 'C-x o o' fast it jumps straight to other-window, if available. You will not even see the hydra menu.

By adding the hydra code you have over-written the default keybinding 'C-x o' which runs `other-window', which is one less key press. Just remove the code from your config and restart emacs.

You can set `other-window' to any keybinding you want without hydra. Here are 3 examples

```
(global-set-key  [f12] 'other-window)    ;;  F12
(global-set-key (kbd "C-k") 'other-window)  ;; Control + k
(global-set-key (kbd "C-x o") 'other-window)  ;; Control + x o
```
