### ISSUE TITLE
where is hydra-create function? 

### ISSUE THREAD

**Issue by yi-tang** [abo-abo/hydra#43]
Hi,

I would like to try hydra package and install it from melpa.  When I run this example 

``` emacs-lisp
(require 'hydra)
(hydra-create "<f2>"
  '(("g" text-scale-increase)
    ("l" text-scale-decrease)))
```
I got this error message: 

Symbol's function definition is void: hydra-create

Did I miss something from the manual?

**Comment by abo-abo** [comment]
You must have seen some outdated post. There's no reference anymore
to `hydra-create` in README.md and the comment in hydra.el says this:

```cl
;; Initially, Hydra shipped with a simplified `hydra-create' macro, to
;; which you could hook up the examples from hydra-examples.el.  It's
;; better to take the examples simply as templates and use `defhydra'
;; instead of `hydra-create', since it's more flexible.
```

Nine examples for the new `defhydra` macro are in hydra-examples.el.
The one that you tried now looks like this:

```cl
(require 'hydra)
(defhydra hydra-zoom (global-map "<f2>")
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))
```

**Comment by yi-tang** [comment]
Hi, you are right, I was reading your post [Behold The Mighty Hydra!](http://oremacs.com/2015/01/20/introducing-hydra/) that is linked in this README.md.
