### ISSUE TITLE
Passing arguments to selected functions

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/hydra#45]
Hi, Thanks a lot for hydra, it is pretty awesome! I am trying to use it to provide a menu for org-mode links. I have a working solution here:

See http://kitchingroup.cheme.cmu.edu/blog/2015/02/22/org-mode-links-meet-hydra/

But I wondered if there might be some other way to pass arguments to the functions selected in hydra. Any ideas?

**Comment by abo-abo** [comment]
Nice idea. Actually, your code looks pretty clean to me.
There's no harm in keeping state in a well-documented global variable - it's the Emacs way.

I'm guessing that you want to see this:

```cl
(org-add-link-type
 "doi"
 (lambda (path) (doi-hydra/body path)))
```

But then `doi-hydra/body` itself has nothing better to do than store `path` in a global var.
It may not be pointless, since the var could be prefixed with the current hydra prefix.
The mechanism could look like this:

```cl
(org-add-link-type
 "doi"
 (lambda (path) (doi-hydra/body :set `((path . ,path)))))

(defun doi-google-scholar ()
  "Google scholar the doi."
  (interactive)
  (browse-url
   (format
    "http://scholar.google.com/scholar?q=%s"
    (hydra-get 'doi-hydra 'path))))
```

But then, `doi-google-scholar` has no idea that it would be used as part of `doi-hydra`, so
the reference has to be baked in.
At this point, your way looks a lot more elegant: you have three functions of one argument (implicit)
that do a useful thing without knowing about hydra, and a not-very-complicated way to tie them together.
Maybe there's another approach that I've overlooked, I'm open to suggestions.

**Comment by jkitchin** [comment]
Oleh Krehel writes:

> Nice idea. Actually, your code looks pretty clean to me.
> There's no harm in keeping state in a well-documented global variable - it's the Emacs way.
>
> I'm guessing that you want to see this:
>
> ```cl
> (org-add-link-type
>  "doi"
>  (lambda (path) (doi-hydra/body path)))
> ```

Yes that is what I had hoped for. I am not sure what doi-hydra/body does
with the selection, but if it did something like (funcall selection
path) or used apply/map to do something similar it would do what I had
in mind. It would even be useful for doi-hydra/body to return its
selected function (but not run it), and then the lambda function itself
could do that. Maybe a :return argument or :execute (t/nil) argument
could be used for that.

The reason is that I would rather have (I actually already have a lot of
these) a function like:

(defun doi-utils-crossref (doi)
  "Search DOI in CrossRef."
  (interactive "sDOI: ")
  (browse-url
   (format
    "http://search.crossref.org/?q=%s" doi)))

that could be called interactively and independently of the hydra or an
org-link. You can type or paste in the DOI here. I would prefer not to
have a wrapper function with no arguments around it to pass the doi in,
but I guess a little macro might reduce cut and paste code to get that.

This seems like it would take the greatest advantage of information
already available to you when you click a link, and reusability of code
that can work with a hydra or something else..

Yesterday I could not get my code to parse the link at point, but today
it seems to work fine, so now I can can avoid the global variable, but
the functions then only work on links, and not independently of them.

>
> But then `doi-hydra/body` itself has nothing better to do than store `path` in a global var.
> It may not be pointless, since the var could be prefixed with the current hydra prefix.
> The mechanism could look like this:
>
> ```cl
> (org-add-link-type
>  "doi"
>  (lambda (path) (doi-hydra/body :set `((path . ,path)))))
>
> (defun doi-google-scholar ()
>   "Google scholar the doi."
>   (interactive)
>   (browse-url
>    (format
>     "http://scholar.google.com/scholar?q=%s"
>     (hydra-get 'doi-hydra 'path))))
> ```
Something like this is what I worked out this morning:
(defun doi-google-scholar ()
  "Google scholar the doi."
  (interactive)
  (browse-url
   (format
    "http://scholar.google.com/scholar?q=%s"
    (url-hexify-string
     (org-element-property :path (org-element-context))))))

but now this function only works on a link. I suppose I could add some
logic to check if we are on a doi link and use it, and if not, prompt
for a DOI.

>
> But then, `doi-google-scholar` has no idea that it would be used as part of `doi-hydra`, so
> the reference has to be baked in.
> At this point, your way looks a lot more elegant: you have three functions of one argument (implicit)
> that do a useful thing without knowing about hydra, and a not-very-complicated way to tie them together.
> Maybe there's another approach that I've overlooked, I'm open to suggestions.
>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/abo-abo/hydra/issues/45#issuecomment-75518308

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by abo-abo** [comment]
OK, here's what I've come up with:

```cl
(defun org-get-doi ()
  "Get DOI at point or read it"
  (let (context)
    (if (setq context (org-element-property
                       :path (org-element-context)))
        (url-hexify-string context)
      (read-string "DOI: "))))

(defun doi-crossref (doi)
  "Search DOI in CrossRef."
  (interactive (list (org-get-doi)))
  (browse-url
   (format
    "http://search.crossref.org/?q=%s" doi)))

(defun doi-google-scholar (doi)
  "Google scholar the doi."
  (interactive (list (org-get-doi)))
  (browse-url
   (format
    "http://scholar.google.com/scholar?q=%s" doi)))

(defun doi-pubmed (doi)
  "Pubmed the doi."
  (interactive (list (org-get-doi)))
  (browse-url
   (format
    "http://www.ncbi.nlm.nih.gov/pubmed/?term=%s"
    (org-get-doi))))

(defhydra doi-hydra ()
  "org-ref"
  ("c" doi-crossref "Crossref")
  ("g" doi-google-scholar "Google Scholar")
  ("p" doi-pubmed "Pubmed"))

(org-add-link-type
 "doi" (lambda (path) (doi-hydra/body)))
```

This looks pretty much optimal, since the first four functions are completely independent of hydra.
The only overhead is wrapping `(lambda (path) (doi-hydra/body))`.

**Comment by jkitchin** [comment]
Yep, that is the way to do it. This is totally reasonable. Thanks.

Oleh Krehel writes:

> OK, here's what I've come up with:
>
> ```cl
> (defun org-get-doi ()
>   "Get DOI at point or read it"
>   (let (context)
>     (if (setq context (org-element-property
>                        :path (org-element-context)))
>         (url-hexify-string context)
>       (read-string "DOI: "))))
>
> (defun doi-crossref (doi)
>   "Search DOI in CrossRef."
>   (interactive (list (org-get-doi)))
>   (browse-url
>    (format
>     "http://search.crossref.org/?q=%s" doi)))
>
> (defun doi-google-scholar (doi)
>   "Google scholar the doi."
>   (interactive (list (org-get-doi)))
>   (browse-url
>    (format
>     "http://scholar.google.com/scholar?q=%s" doi)))
>
> (defun doi-pubmed (doi)
>   "Pubmed the doi."
>   (interactive (list (org-get-doi)))
>   (browse-url
>    (format
>     "http://www.ncbi.nlm.nih.gov/pubmed/?term=%s"
>     (org-get-doi))))
>
> (defhydra doi-hydra ()
>   "org-ref"
>   ("c" doi-crossref "Crossref")
>   ("g" doi-google-scholar "Google Scholar")
>   ("p" doi-pubmed "Pubmed"))
>
> (org-add-link-type
>  "doi" (lambda (path) (doi-hydra/body)))
> ```
>
> This looks pretty much optimal, since the first four functions are completely independent of hydra.
> The only overhead is wrapping `(lambda (path) (doi-hydra/body))`.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/abo-abo/hydra/issues/45#issuecomment-75566105

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by abo-abo** [comment]
Glad to help, and thank you for the idea: I'll find a use for `doi-hydra` as well.

**Comment by jkitchin** [comment]
Thanks. I just added a hydra type menu for cite links in org-ref:
https://github.com/jkitchin/org-ref/blob/master/org-ref.org#a-hydra-click-interface that is based on this idea.

**Comment by abo-abo** [comment]
You seem to have a duplicate "p" key.
With minor renaming, you can have `cusp`, `prego` and `frown` as columns.

```cl
(defhydra org-ref-cite-hydra (:color blue)
  "
_c_: WOS citing                   _P_: Pubmed                _f_: Copy bibtex entry to file
_u_: Open url                     _r_: WOS related           _R_: Crossref
_s_: Copy citation to clipboard   _e_: Email entry and pdf   _o_: Open entry
_p_: Open pdf                     _g_: Google Scholar        _w_: WOS
                                  _O_: Copy key to clipboard _n_: Open notes
"
  ("o" org-ref-open-citation-at-point nil)
  ("p" org-ref-open-pdf-at-point nil)
  ("n" org-ref-open-notes-at-point nil)
  ("u" org-ref-open-url-at-point nil)
  ("w" org-ref-wos-at-point nil)
  ("r" org-ref-wos-related-at-point nil)
  ("c" org-ref-wos-citing-at-point nil)
  ("g" org-ref-google-scholar-at-point nil)
  ("P" org-ref-pubmed-at-point nil)
  ("R" org-ref-crossref-at-point nil)
  ("s" org-ref-copy-entry-as-summary nil)
  ("O" (progn
	 (kill-new
	  (car (org-ref-get-bibtex-key-and-file)))) nil)
  ("f" org-ref-copy-entry-at-point-to-file nil)

  ("e" (save-excursion
	 (org-ref-open-citation-at-point)
	 (email-bibtex-entry)) nil))
```

**Comment by jkitchin** [comment]
Thanks for catching that!
