### ISSUE TITLE
`:exit` not getting overridden

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/hydra#46]
The following hydra has two heads, one red and one blue:

```
(defhydra test-hydra (:color blue)
  "Test"
  ("e" (message "Exiting now") "blue")
  ("c" (message "Continuing") "red" :color red))
```

As far as I understand, the following hydra should be identical:

```
(defhydra test-hydra (:exit t)
  "Test"
  ("e" (message "Exiting now") "blue")
  ("c" (message "Continuing") "red" :exit nil))
```

However, the second head `c` is blue rather than red. Is this a bug or am I overlooking something?

Emacs 24.4.1, hydra version 20150221.844 (installed from Melpa).

**Comment by abo-abo** [comment]
Thanks for noticing the bug. I've put many more checks now.

**Comment by joostkremers** [comment]
Yup, works now. Thanks!
