### ISSUE TITLE
Extra properties for head with nil body

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/hydra#47]
Hi,

The commits on Feb 23 started giving me this error for almost all of my hydra definitions:

<pre>
Debugger entered--Lisp error: (error "Extra properties for head with nil body: (\"q\" nil \"cancel\" :color blue)")
  signal(error ("Extra properties for head with nil body: (\"q\" nil \"cancel\" :color blue)"))
  error("Extra properties for head with nil body: %S" ("q" nil "cancel" :color blue))
  hydra--head-color(("q" nil "cancel" :color blue) (nil nil :color red))
  #[(head name) "\306\307	\211A@\262!\310	\n\"\311\312	\211A@\262#\f
\f
&	\207" [name head body doc hint-name keymap hydra--make-defun hydra--make-callable hydra--head-color format "%s\n\nCall the head: `%S'." body-color body-pre body-post] 10](("q" nil "cancel" :color blue) hydra-change-case/nil)
  cl-mapcar(#[(head name) "\306\307	\211A@\262!\310	\n\"\311\312	\211A@\262#\f
\f
&	\207" [name head body doc hint-name keymap hydra--make-defun hydra--make-callable hydra--head-color format "%s\n\nCall the head: `%S'." body-color body-pre body-post] 10] (("c" modi/capitalize "Capitalize") ("u" modi/upcase "UPCASE") ("l" modi/downcase "downcase") ("M-c" xah-cycle-letter-case "→Cap→UP→down→") ("q" nil "cancel" :color blue)) (hydra-change-case/modi/capitalize hydra-change-case/modi/upcase hydra-change-case/modi/downcase hydra-change-case/xah-cycle-letter-case hydra-change-case/nil))
  #[(name body &optional docstring &rest heads) ";\204
</pre>

Here is one of just defhydras:

<pre>
(defhydra hydra-change-case(:color red)
  "change-case"
  ("c"   modi/capitalize       "Capitalize")
  ("u"   modi/upcase           "UPCASE")
  ("l"   modi/downcase         "downcase")
  ("M-c" xah-cycle-letter-case "→Cap→UP→down→")
  ("q"   nil                   "cancel" :color blue))
</pre>

**Comment by abo-abo** [comment]
Having `nil` in the `CMD` slot automatically means that the `:color` is `blue`.
I wanted to eliminate some redundancies.

I don't have a strong feeling about this; Do you want a revert?

**Comment by kaushalmodi** [comment]
Can you please revert it? I like to specify the blue heads or exit heads. Even if that is redundant, I believe it shouldn't error out. I have about a dozen hydras by now using the same convention.
