### ISSUE TITLE
Never bind a nil cmd

### ISSUE THREAD

**Issue by glucas** [abo-abo/hydra#48]
It seems fairly common to use nil heads to define quit keys, and hydra will automatically treat a nil command as an exit point. 

It would be convenient to also automatically set `:bind` to nil for nil commands. Since such a head's only purpose is to exit the hydra, there is no need to create an externally visible binding to `my-cool-hydra/nil`.

**Comment by abo-abo** [comment]
You mean something like:

```cl
(defun hydra-interactive-disable ()
  (interactive)
  (hydra-disable)
  (hydra-cleanup))
```

And then bind to `hydra-interactive-disable` instead of `my-cool-hydra/nil` with the same body?
It makes sense, I could add that tomorrow.

**Comment by glucas** [comment]
I had two thoughts here, really.. One is that the xxx/nil commands are all the same and you could use a command with a meaningful name like what you've suggested above. 

The other is to avoid creating a direct binding to the hydra quit command. So for example, if I had this hydra:

    (defhydra hydra-goto-line (goto-map)
      ("g" goto-line "goto-line")
      ("q" nil "quit"))

I end up with `M-g q` bound to `hydra-goto-line/nil`, which seems like a useless binding. In practice I'm avoiding this explicitly (see below), but it seems like something hydra could automatically handle. I can't think of a reason one would ever need an externally visible binding to a command that does nothing outside a hydra.  

    (defhydra hydra-goto-line (goto-map)
      ("g" goto-line "goto-line")
      ("q" nil "quit" :bind nil))

**Comment by abo-abo** [comment]
I see now, thanks for explaining.  The `define-key` statements for outside keymaps are a big bug.
I'll try to fix this soon.
