### ISSUE TITLE
Ruby style heading indentation 

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/hydra#49]
Currently, to show the help text for my projectile hydra with good alignment, I need to format it in the `defhydra` as below:

<pre>
    (defhydra hydra-projectile (:color teal)
      "
     PROJECTILE

     Find File            Search/Tags          Buffers                Cache
------------------------------------------------------------------------------------------
_s-f_: file            _a_: ag              _i_: Ibuffer           _c_: cache clear
_ff_: file dwim       _g_: update gtags    _b_: switch to buffer  _x_: remove known project
_fd_: file curr dir   _o_: multi-occur     _s-k_: Kill all buffers  _X_: cleanup non-existing
_r_: recent file                                                 _z_: cache current
_d_: dir
"
</pre>

[Here is the full code](https://github.com/abo-abo/hydra/wiki/Projectile)

That gives me:

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/6336142/752aeaf6-bb6e-11e4-9ff4-a261490b639b.png)

If I prettify the alignment in the `defhydra` code, it messes up the actual alignment.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/6336214/dfecb3ec-bb6e-11e4-9bbc-06b3bb3c0436.png)

What's the best workaround to get proper alignment both in the `defhydra` definition and the visual representation?

Thanks.

**Comment by abo-abo** [comment]
There's a special char `^` that has zero width in the resulting docstring.
Here's how the padding looks like:

```cl
(defhydra hydra-projectile (:color teal)
  "
     PROJECTILE

     Find File            Search/Tags          Buffers                Cache
------------------------------------------------------------------------------------------
_s-f_: file            _a_: ag              ^^_i_: Ibuffer           _c_: cache clear
^_ff_: file dwim       _g_: update gtags    ^^_b_: switch to buffer  _x_: remove known project
^_fd_: file curr dir   _o_: multi-occur     _s-k_: Kill all buffers  _X_: cleanup non-existing
^^_r_: recent file                                                 ^^_z_: cache current
^^_d_: dir

"
  ("a"   projectile-ag                      nil)
  ("b"   projectile-switch-to-buffer        nil)
  ("c"   projectile-invalidate-cache        nil)
  ("d"   projectile-find-dir                nil)
  ("s-f" projectile-find-file               nil)
  ("ff"  projectile-find-file-dwim          nil)
  ("fd"  projectile-find-file-in-directory  nil)
  ("g"   ggtags-update-tags                 nil)
  ("s-g" ggtags-update-tags                 nil)
  ("i"   projectile-ibuffer                 nil)
  ("K"   projectile-kill-buffers            nil)
  ("s-k" projectile-kill-buffers            nil)
  ("m"   projectile-multi-occur             nil)
  ("o"   projectile-multi-occur             nil)
  ("s-p" projectile-switch-project          "switch project")
  ("p"   projectile-switch-project          nil)
  ("s"   projectile-switch-project          nil)
  ("r"   projectile-recentf                 nil)
  ("x"   projectile-remove-known-project    nil)
  ("X"   projectile-cleanup-known-projects  nil)
  ("z"   projectile-cache-current-file      nil)
  ("`"   hydra-projectile-other-window/body "other window")
  ("q"   nil                                "cancel" :color blue))
```

If you come up with an invisible char that is as easy to enter as `^` and looks better, can update.

**Comment by kaushalmodi** [comment]
That works for me. Thanks!
