### ISSUE TITLE
Error when trying example

### ISSUE THREAD

**Issue by ndegruchy** [abo-abo/hydra#5]
When I try the text zoom example:

```elisp
(require 'hydra)
(setq hydra-is-helpful t)
(hydra-create "<f2>"
  '(("g" text-scale-increase)
    ("l" text-scale-decrease)))
```

I get the following error (image, because it won't let me copy or save it all...)

![Imgur](http://i.imgur.com/4j1Xgwz.png)

I'm not sure how to proceed, but the keybinding doesn't get set at all.

**Comment by kaushalmodi** [comment]
Try adding `(require 'cl)` to your init file before you do `(require 'hydra)`.

**Comment by ndegruchy** [comment]
That works. Any reason why I had to add it?

**Comment by kaushalmodi** [comment]
`caddr` is defined in that package. Nowadays most of the packages include that and so no one needs to explicitly `require` it.

**Comment by ndegruchy** [comment]
Interesting. Well, that fixes it.

Thanks

**Comment by abo-abo** [comment]
This problem does not occur in newer versions of Emacs, since `caddr` is provided by `cl-lib`. Older versions need to require `cl`, which I just added.
