### ISSUE TITLE
Docstring special characters & spaces

### ISSUE THREAD

**Issue by hura** [abo-abo/hydra#50]
Two things:

1. I can't seem to get _/_ and _9_ (or any number) work in docstrings. Can this be supported?

2. _f_ in docstring will result in 2 spaces before the word. I think it'd be nice to also allow _f_ in the middle of a word: "in_f_use". I know this would break alignment in the source code where the docstring is defined.

**Comment by abo-abo** [comment]
See the commit message for an example and let me know if it works for you.

**Comment by TauPan** [comment]
With that commit I still have the problem that '<' and the direction keys in my window manager hydra are not highlighted properly. See https://gist.github.com/TauPan/513a529281ff98e406b2

Thanks for this insanely useful package! ;)

**Comment by abo-abo** [comment]
@TauPan, here's how to align your hydra with more ease:

```cl
(setq hydra-key-format-spec "%s")
(defhydra hydra-window (global-map "C-M-o")
  "
Move Point^^^^   Move Splitter   ^Ace^                       ^Split^                          Tranpose
--------------------------------------------------------------------------------------------------
_w_, _<up>_      Shift + Move    _C-a_: ace-window           _2_: split-window-below         _1_: transpose-frame
_a_, _<left>_                    _C-s_: ace-window-swap      _3_: split-window-right         _e_: rotate-frame-clockwise
_s_, _<down>_                    _C-d_: ace-window-delete    _<_: toggle-split-direction     _y_: flip-frame vertically
_d_, _<right>_                   ^   ^                       ^ ^                             _c_: flop-frame horizontally
You can use arrow-keys or WASD.
"
  ("2" split-window-below nil)
  ("3" split-window-right nil)
  ("a" windmove-left nil)
  ("s" windmove-down nil)
  ("w" windmove-up nil)
  ("d" windmove-right nil)
  ("A" hydra-move-splitter-left nil)
  ("S" hydra-move-splitter-down nil)
  ("W" hydra-move-splitter-up nil)
  ("D" hydra-move-splitter-right nil)
  ("<left>" windmove-left nil)
  ("<down>" windmove-down nil)
  ("<up>" windmove-up nil)
  ("<right>" windmove-right nil)
  ("<S-left>" hydra-move-splitter-left nil)
  ("<S-down>" hydra-move-splitter-down nil)
  ("<S-up>" hydra-move-splitter-up nil)
  ("<S-right>" hydra-move-splitter-right nil)
  ("C-a" ace-window nil)
  ("u" hydra-universal-argument nil)
  ("C-s" (lambda () (interactive) (ace-window 4)) nil)
  ("C-d" (lambda () (interactive) (ace-window 16)) nil)
  ("<" window-toggle-split-direction nil)
  ("1" transpose-frame nil)
  ("e" rotate-frame-clockwise nil)
  ("y" flip-frame nil)
  ("c" flop-frame nil)
  ("q" nil "quit"))
```

The char `^` does not appear in the final docstring, it's just used to align the code.
`hydra-key-format-spec` is `"% 3s"` by default, to set the fill width for each key to 3.
Set it to `"%s"` to fill manually.

Finally, in order to align both the code and the result, make sure that the amount of
`_` and `^` matches on each line, like I did in the example above.

**Comment by TauPan** [comment]
Thanks for the alignment tips, I found that already in another issue.

But the remaining problem is that e.g. \_\<down\>\_ and \_<\_ are not highlighted at all, i.e. I still see the underscores in the output.

**Comment by abo-abo** [comment]
`_<down>_` works fine for me. Did you update to the latest commit?

**Comment by TauPan** [comment]
Oops... now I did, sorry. It appears melpa was a bit behind and since it already had the hydra-key-format-spec setting, I thought it was new enough.

Case closed, and thanks a bunch! ;)

**Comment by hura** [comment]
Also works for me. Thanks a ton for the quick fix/feature.

**Comment by hura** [comment]
Also would like   ?|  as characters allow.
