### ISSUE TITLE
Increased sluggishness when calling a function via hydra

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/hydra#51]
I have noticed that over time, after launching emacs, the execution of hydra heads, especially the ones you would normally use in a repeated fashion would become too sluggish.

Here's an example:

```el
(defhydra hydra-vi (:color amaranth)
  "vi"
  ;; basic navigation
  ("l"        forward-char                  nil)
  ("h"        backward-char                 nil)
  ("j"        next-line                     nil)
  ("k"        previous-line                 nil)
  ("q"        nil :color blue))
```

After calling `hydra-vi/body` if I randomly move the point around using `j` and `k`, I find the movement to gradually become more sluggish.

I don't find that behavior when doing normal `C-p`/`C-n`.

I used `M-x elp-instrument-function` to figure out how much wall time the `next-line` and `hydra-vi/next-line` commands took and this was the result:

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/6338757/2b0c9b02-bb7f-11e4-9cd4-d4dd6a83e96f.png)

Here is how the command execution speed was perceived in practice:
- Slamming down the `C-n`/`C-p` key smoothly moves the cursor up and down and I can see it switching to each consecutive line.
- After executing `hydra-vi/body`, slamming down `j`/`k` made the cursor jump few lines at a time. If I held down either key for too long, I would literally need to wait for few seconds to see where the cursor ends up being.

The sluggishness is considerably less if I relaunch emacs. But the same issue comes back very soon. Before I start bisecting my init, I'd like to know if you or anyone else can repeat this issue.

I have disabled the `key-chord-mode` and `guide-key` packages to test this. They are the ones which are think could mess this up.

Here are the performance numbers after some more time:

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/6338956/931b7758-bb80-11e4-86b2-a5b3bf975099.png)

**Comment by abo-abo** [comment]
How long (how may calls) do you need to get sluggish? Here's what I'm getting:

    hydra-vi/next-line                     228         3.3833543699  0.0148392735
    next-line                              228         3.1928829079  0.0140038724
    hydra-vi/hint                          234         0.1356692649  0.0005797831
    hydra-disable                          234         0.0513601860  0.0002194879
    hydra-vi/body                          3           0.00512015    0.0017067166
    hydra-set-transient-map                234         0.003273709   1.399...e-05
    hydra-vi/nil                           2           0.000625313   0.0003126565

Also, what's your Emacs version?

**Comment by kaushalmodi** [comment]
Thanks for confirming. I am on emacs trunk built about a week ago. So it's time for bisecting my init.

**Comment by kaushalmodi** [comment]
I believe the problem was because I had aggressive indentation enabled for emacs lisp mode. The aggressive indentation causes sluggishness as it uses `post-command-hook`. Out of curiosity, does using hydra cause `post-command-hook` to run more often than running a bare function like `next-line` ? 

In either case I am closing this issue as I believe the problem is gone once I disable aggressive indentation.

**Comment by abo-abo** [comment]
> does using hydra cause post-command-hook to run more often than running a bare function like next-line

It can do so a bit, since each non-lambda hydra head, while being a command, will use
`call-interactively` once.

But it's not strange for an Emacs package to do so.  Doing heavy processing in `post-command-hook` -
now that's strange.

**Comment by kaushalmodi** [comment]
Nope, it wasn't the aggressive indent mode. The issue is still there. I bet it has to do with `next-line`, `previous-line`, etc being called through a wrapper instead of directly. I am still investing it. It's a pain as I can't edebug those base functions that integrate with C implementation. I'll still leave the issue closed as no one else is apparently seeing it.

**Comment by abo-abo** [comment]
Is it fixed for you if you replace e.g. `("j" next-line)` with `("j" (forward-line 1))`?
I know that there's a byte compiler warning about not using `next-line` and `previous-line` in code.

Also, I just noticed that the lambda heads also use `call-interactively`. I'll fix this soon.
