### ISSUE TITLE
nil heads no longer executes :post action?

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#53]
I have the following hydra (pseudo code):

```elisp
(defvar vi-motion-init-pos nil)
(defhydra vi-motion
  (:body-pre (progn (set-cursor-color "yellow") (setq vi-motion-init-pos (point)))
   :post (set-cursor-color "red"))
""
  ("h" ...) ;; non-exiting heads
  ("q" (goto-char vi-motion-init-pos) :exit t)
  ("<escape>" nil))
```
Before MELPA version 20150224.655, pressing the escape key used to be able to restore the cursor color after exiting from the hydra. Now it exits but the cursor color stays in yellow. Pressing "q", on the other hand, still sets the cursor color back to red, in addition to returning to initial position.

I have the two exiting heads for different side effects: "q" returns to the initial position, ESC stays where the point is at after navigation.

I am guessing the fix for #48 might have caused this regression. If that is the desired behavior onwards, is there a workaround?

**Comment by abo-abo** [comment]
You're right, I didn't think about `:post`. I guess I'll have to revert the change a bit.

**Comment by zhaojiangbin** [comment]
Wow you are quick.

I found a workaround: bind the ESC key to a non-nil command without side-effect and add :exit t to it. Like:

```elisp
   ("<escape>" (message "") :exit t)
```

It works for my purpose. I will give your new version a try later.

**Comment by zhaojiangbin** [comment]
Yeah now it works great without having to use that workaround. Thanks.
