### ISSUE TITLE
Hydra with golden-window-mode

### ISSUE THREAD

**Issue by llcc** [abo-abo/hydra#54]
Hi, @abo-abo 

First, thanks for this aweful package.

I am using golden-ratio package [1] which can split windows according to golden ratio. 
When i call hydra keybinds, the hydra window occupys most of screen like below because it needs to obey golden ratio. Of course, this is not what I want.
![image](https://cloud.githubusercontent.com/assets/3996879/6370163/dc0e4d76-bd30-11e4-843b-ebd8a72d3ced.png)

Golden-ratio offers `golden-ratio-exclude-modes` function to exclude some modes, but since hydra is not a mode, so it can not help.

But since you are the author, I think maybe you can give a solution. So can you do me a favor?

[1] https://github.com/roman/golden-ratio.el

**Comment by abo-abo** [comment]
> this aweful package

I hope there's a typo in there somewhere.

The fix is as follows:

```cl
(setq golden-ratio-exclude-buffer-names '("*LV*"))
```

**Comment by llcc** [comment]
@abo-abo thanks, has been fixed....
