### ISSUE TITLE
Add support for ace-jump-mode

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/hydra#58]
I would be nice if Hydra can be made to work with `ace-jump-mode` for more powerful movement.

**Comment by abo-abo** [comment]
I don't really see how this relates to Hydra.
Hydra is a framework for binding keys, not a buffer-navigation package.
You can bind `ace-jump-mode` like any other command.

**Comment by tuhdo** [comment]
I tried it, and I could not jump to a character because hydra is active. For example:

```elisp
(defhydra hydra-movement (global-map "M-m")
  "Move"
  ("l" forward-char)
  ("j" backward-char)
  ("k" next-line)
  ("i" previous-line)
  ("o" forward-word)
  ("u" backward-word)
  ("a" ace-jump-word-mode)
  ("q" nil))
```

When you active `ace-jump-word-mode` with <kbd>a</kbd> and enter a character, when buffer turns gray you cannot enter a highlighted character to jump to it.

**Comment by abo-abo** [comment]
This can only be fixed like this at the moment:

```cl
(defhydra hydra-movement (global-map "M-m")
  "Move"
  ("l" forward-char)
  ("j" backward-char)
  ("k" next-line)
  ("i" previous-line)
  ("o" forward-word)
  ("u" backward-word)
  ("a" ace-jump-word-mode :exit t)
  ("q" nil))
```

This means that <kbd>a</kbd> will exit the Hydra. You can play tricks to re-enter it by
setting `ace-jump-mode-end-hook`.

It's a major deficiency of `ace-jump-mode`: it splits its execution into two parts:

```cl
(progn
  (ace-jump-do "f")
  (foobar))
```

Here, `foobar` will be called immediately, *before* any user input for the char `f`.
I already moved away from this scheme in `ace-window`.

If you don't want the hassle, use [better-jump](https://github.com/Fuco1/better-jump).
If you want the hassle and the `ace-jump-mode-end-hook` tricks, see [lispy](https://github.com/abo-abo/lispy).

**Comment by tuhdo** [comment]
Alright, `better-jump` fixed it. Thanks for your suggestion. You should update the documentation above for users who want to use Hydra with `ace-jump-mode`. Thanks for this great package.

> If you want the hassle and the ace-jump-mode-end-hook tricks, see lispy.

My problem with Lispy is that it only works with Lisp modes, and I have to constantly switch between its default bindings (i.e. hjkl) with sexp movement bindings in other modes like C/C++ ("C-M-f", "C-M-b"...). I think hydra will solve this issue for me.

**Comment by abo-abo** [comment]
> If you want the hassle and the ace-jump-mode-end-hook tricks, see lispy.

I meant see how `lispy` implements ace-jump-mode-end-hook tricks, in case you're loyal to `ace-jump-mode`.
