### ISSUE TITLE
Hydra heads for control keys (<tab>, <up>, <down>, etc) 

### ISSUE THREAD

**Issue by vkazanov** [abo-abo/hydra#6]
Love your idea, but noticed a limitation: hydra heads get cut the second time I press <tab>. The setup is the following:

```emacs-lisp 
(hydra-create "<f2>"
  '(
    ;; navigation
    ("u" outline-up-heading)
    ("f" org-forward-heading-same-level)
    ("b" org-backward-heading-same-level)
    ("n" outline-next-visible-heading)
    ("p" outline-previous-visible-heading)

    ;; manipulation
    ("<tab>" org-cycle)
    )
  org-mode-map)
```

Same goes to other control keys. I didn't yet dive into hydra.el code, can't give any more details. Is it a fundamental limitation or a bug?

**Comment by abo-abo** [comment]
> second time I press .

You press what? I didn't understand.

**Comment by vkazanov** [comment]
Oh, pardon. Here's what I do:

1. press <f2> + <tab>
I get into the "hydra" mode with the possible heads listed in the minibuffer, including the <tab> itself
2. press <tab>
I leave the "hydra", although I expected to continue.

Is this the intended behavior?

**Comment by abo-abo** [comment]
No it's a bug based on interpretting `<tab>` as `<`, `t`, `a`, ... . I'll fix this soon.

**Comment by abo-abo** [comment]
Check out https://github.com/abo-abo/worf for an org-mode bindings implementation similar to what you have here.
