### ISSUE TITLE
hydra-repeat assumes prefix arg of 1 when omitted

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#61]
I am trying to take advantage of the new hydra-repeat function as below:
```elisp
(defhydra page-motion
  (:pre  (setq hydra-lv nil)
   :post (setq hydra-lv t))
  "page"
  ("C-v" scroll-up)
  ("M-v" scroll-down)
  ("SPC" hydra-repeat))
(bind-keys ("C-v" . page-motion/scroll-up)
           ("M-v" . page-motion/scroll-down))
```
But due to ```(setq hydra-repeat--prefix-arg (or last-prefix-arg 1))``` in line 230 of hydra.el, the scroll-up/down commands are called as ```(scroll-up 1)``` and ```(scroll-down 1)``` which scroll up/down only 1 line instead of the "a near full screen" when called with nil.

Given how commands can treat the prefix arg in different ways when omitted or not, I don't know if there can be an easy fix.

So as a workaround, I end up having to "eat" the prefix arg when calling the scroll-up/down commands for "a near full screen":
```elisp
(defun my-scroll-up (arg)
  (interactive "p")
  (scroll-up nil))
...
(defhydra page-motion ()
  ...
  ("C-v" my-scroll-up)
  ...
  ("SPC" hydra-repeat))
(bind-keys ("C-v" . page-motion/my-scroll-up)(...))
```

**Comment by abo-abo** [comment]
I would write it down like this:


```cl
(defun bnd-key (key cmd)
  (bind-key key cmd))

(defhydra hydra-page-motion (:pre (setq hydra-lv nil)
                             :post (setq hydra-lv t)
                             :bind #'bnd-key)
  "page"
  ("C-v" (scroll-up nil))
  ("M-v" (scroll-down nil))
  ("SPC" hydra-repeat))
```

**Comment by zhaojiangbin** [comment]
I need to digest this. I have seen :bind as head property. But didn't know that it also works as a body property. What does it do here?

**Comment by glucas** [comment]
As a body property, :bind applies to all the heads. So in this case all heads are bound using `bjnd-key` -- except for SPC, since that head overrides :bind to nil.

**Comment by zhaojiangbin** [comment]
Very cool. Thanks.

**Comment by abo-abo** [comment]
I assume that this is solved. Feel free to reopen if you have any questions.

**Comment by jhonnyseven** [comment]
What is the rationale for that `(or last-prefix-arg 1)` in
`hydra-repeat`?

If you go with the suggested workaround (give explicit `nil` as an argument), you cannot give prefix
arguments to commands.

**Comment by abo-abo** [comment]
> What is the rationale for that (or last-prefix-arg 1) in hydra-repeat?

The rationale is that I copy-pasted the code from `lispy`, where most commands choke unless the
argument is a number. Thanks for noticing. 

@zhaojiangbin, you can revert to the old version of your code, it should work now.

**Comment by zhaojiangbin** [comment]
@abo-abo Verified. Thanks.
