### ISSUE TITLE
Hydra suddenly resizing

### ISSUE THREAD

**Issue by ReneFroger** [abo-abo/hydra#63]
Hello Abo Abo, thanks for sharing this nice plugin!

I use Hydra in combination with Helm, from this blog post: http://angelic-sedition.github.io/blog/2015/02/03/a-more-evil-helm/

However, lately there is a issue with window resizing in Helm. Suddenly when I activate Helm, the window will resize. I don't know how this is caused, or there is something wrong 
with my settings. 

I have created a Gif, to show the issue. 

![hydra-helm](https://cloud.githubusercontent.com/assets/5211845/6480382/72c165ec-c253-11e4-8006-5f80f2fdfb32.gif)

Could you perhaps tell me how I could disable the resizing when Hydra becomes active? 

Thanks in advance for your reply!

**Comment by abo-abo** [comment]
Looks like `golden-ratio-mode` in play. Are you using that? In that case the fix is in #54.

**Comment by ReneFroger** [comment]
Yes you're right! Spot on. I disabled golden ratio recently, and this issue was not arising anymore. I added 

`(setq golden-ratio-exclude-buffer-names '("*LV*"))`

to my dot-emacs. And now the Hydra window is not so large as first, but still larger than it was some weeks ago. But that's just fine, I can live with it. 

Thanks for your help, it's really appreciated!

**Comment by hura** [comment]
Offtopic: @ReneFroger you might be interested in https://github.com/abo-abo/hydra/wiki/Helm

**Comment by ReneFroger** [comment]
Thanks @hura , I haven't noticed that! Much appreciated!
