### ISSUE TITLE
golden-ratio-mode and hydra (again)

### ISSUE THREAD

**Issue by vkazanov** [abo-abo/hydra#64]
I use both facilities actively, but did not manage to get the echo window work right. Note, that I have seen other related issues, but specifying the *LV* buffer does not help. 

Actually, it shouldn't, because the golden-ratio-mode works before the buffer is even created, it works on the split. I edebuged the `lv-message` function and noticed that it *first* creates the window split (and golden-ratio-mode changes the sizes) and *then* creates the buffer( if it's not available already).

Maybe it should be the other way around? Buffer first, split next? This should fix the issue (along with specifying the *LV* buffer).

**Comment by abo-abo** [comment]
Could you specify a minimal recipe to reproduce the bug?

**Comment by vkazanov** [comment]
Nothing special, actually.

I have the following in my .emacs.d `(setq golden-ratio-exclude-buffer-names '("*LV*"))`.

I horizontally split my window into two with the golden-ratio-mode on (everything is okay). Then I call my helpful hydra, and the echo window takes the bottom half of the screen (splitting it vertically).

**Comment by vkazanov** [comment]
I did study the situation a bit more. I've changed the `lv-message` function into following:
```emacs-lisp
(defun lv-message (format-string &rest args)
  "Set LV window contents to (`format' FORMAT-STRING ARGS)."
  (let ((ori (selected-window))
        (str (apply #'format format-string args))
        deactivate-mark)
    (golden-ratio-mode -1)
    (select-window (lv-window))
    (golden-ratio-mode t)
    (unless (string= (buffer-string) str)
      (delete-region (point-min) (point-max))
      (insert str)
      (fit-window-to-buffer nil nil 1))
    (goto-char (point-min))
    (select-window ori)))

```

...and it worked perfectly! I think I can come up with a fix for the issue (disabling window-related function advising before the `lv-window` function, enabling afterwards). What do you think?

**Comment by abo-abo** [comment]
My fix *should* work, but it doesn't since `golden-ratio-mode` is programmed in a strange way:
it disables itself inappropriately. You should raise an issue for `golden-ratio-mode`.

Your fix kind of works, but it entails too much overhead for a library that a user *might* have.
Binding `golden-ratio-mode` to nil should work as it does with many other packages.

**Comment by vkazanov** [comment]
Could you be a bit more concrete? What do mean by "a strange way"? I think I will raise an issue for golden-ratio-mode, but the owner seems to be out of place for now - he has a dangling pull request, and no contributions for a few weeks.

**Comment by abo-abo** [comment]
See the code:

```cl
(defun golden-ratio ()
  "Resizes current window to the golden-ratio's size specs."
  (interactive)
  (unless (or (window-minibuffer-p)
              (one-window-p)
              (member (symbol-name major-mode)
                      golden-ratio-exclude-modes)
              (member (buffer-name)
                      golden-ratio-exclude-buffer-names)
              (and golden-ratio-inhibit-functions
                   (loop for fun in golden-ratio-inhibit-functions
                         thereis (funcall fun))))
    (let ((dims (golden-ratio--dimensions))
          (golden-p (if golden-ratio-mode 1 -1)))
      ;; Always disable `golden-ratio-mode' to avoid
      ;; infinite loop in `balance-windows'.
      (golden-ratio-mode -1)
      (balance-windows)
      (golden-ratio--resize-window dims)
      (when golden-ratio-recenter
        (scroll-right) (recenter))
      (golden-ratio-mode golden-p))))
```

It disables itself for fear of recursion (it could be avoided without disabling).
So if I bind `golden-ratio-mode` to nil temporarily, `golden-ratio` will be called by its own advice
and will disable itself without re-enabling, since `golden-p` becomes -1.

Other packages do it in a proper way, for instance I have:

```cl
(global-set-key "\C-t" (lambda () (interactive) (let (flx-ido-mode) (smex))))
```

This way, I have `flx-ido-mode` everywhere, except for a single command. And the author of `smex`
had to do no adjustments for `flx-ido-mode`.

**Comment by vkazanov** [comment]
Yes, I see, you are right. Thank you.

I fixed it (with your hydra patch and the alternative way to fix recursion), and it works for me now, but there's still a problem with propagating my fix to golden-ratio-mode... It is quite popular, and you already had at least three issues about.

**Comment by abo-abo** [comment]
Try to merge your change to `golden-ratio-mode`. I imagine that a lot of package writers get issues
about it, not just me.

It could all be fixed for everyone at once if the same approach as with `flx-ido-mode` worked for `golden-ratio-mode`.

**Comment by vkazanov** [comment]
I am on it already.

**Comment by vkazanov** [comment]
Done: https://github.com/roman/golden-ratio.el/pull/45

Not sure, though, if I should close the issue.

**Comment by abo-abo** [comment]
Thanks, leave it open for now. It's good info for people with the same issue.

**Comment by syl20bnr** [comment]
There is no need to patch golden-ratio.
Here is a solution which works in spacemacs:
https://github.com/syl20bnr/spacemacs/blob/master/core/libs/lv.el#L58-72

**Comment by vkazanov** [comment]
Yes, we've already discussed the option, but decided that it's just wrong to do that. The fix in golden-ration would allow to deal with similar golden-ratio-mode problems in other modes easily.

**Comment by abo-abo** [comment]
@syl20bnr, activating/deactivating `golden-ratio-mode` is expensive in both
run time and programming time (many package writers have to do it).

The solution to bind a single variable `golden-ratio-mode` to nil without disabling the advises and
hooks of `golden-ration-mode` would be an optimal solution.

So the advise of `golden-ratio-mode` would be permanent, but will do nothing if the variable
`golden-ratio-mode` is nil.

**Comment by syl20bnr** [comment]
I'm not sure that's more conventional or more usual to use the variable of a mode to disable. In the documentation is appears that using the variable directly should be done via customize.

If setting a mode variable to `nil` should disable the mode then _all_ functions of the mode should check for the variable to be non nil which does not sound a very practical convention.

Using the bound function instead of the bound variable is what appears to me to be the most conventional way to do it, YMMV.

**Comment by syl20bnr** [comment]
@abo-abo To me using the bound function is the right way to do it. It will deactivate the hooks as expected and it is way more clean.
I'm not sure that performance is valid criteria here.

**Comment by syl20bnr** [comment]
I will add that there is a reason why in the conventions it is written that you should not set explicitly the variable except via customize. It is because `customize` will evaluate the `:set` property which assure that the mode is correctly enabled/disabled.

Setting the variable directly is a ugly hack to me.

**Comment by syl20bnr** [comment]
If you want an elegant way to do it, then a little macro will do the trick, it is even possible that such macro already exists in Emacs.

**Comment by abo-abo** [comment]
Except `golden-ratio-mode` isn't a proper minor mode, so the usual conventions don't apply.

The approach that I want is very efficient, flexible and easy to understand.
And it's used in the Emacs core a lot, see `case-fold-search`, `deactivate-mark`, `inhibit-quit` etc.

> If you want an elegant way to do it

An elegant way to do it would be for other packages to know nothing of
`golden-ratio-mode`.  Just bind a variable to `nil` if someone
complains that let the author of `golden-ratio-mode` sort it out.  95%
of Emacs users don't even have `golden-ratio-mode`; why should I check for its presence on each
(frequent) call?

**Comment by syl20bnr** [comment]
> Just bind a variable to nil

This is not what the conventions promote.

A simple condition check is what make you discard the proper way to disable a mode ? You are patching a package because you don't want a condition check but you prefer a variable set ?

BTW are your sure that your examples are minor mode related ?

**Comment by abo-abo** [comment]
> This is not what the conventions promote.

Conventions are just that - conventions. You still have to use your judgment.

> BTW are you sure that your examples are minor mode related ?

"Minor mode" is just a convention just like Hydra. It's not an intrinsic Emacs feature.
Essentially, a minor mode is a variable that changes Emacs behavior when it's set.  The difference
between `case-fold-search`, `deactivate-mark` etc. and `auto-fill-mode` is just a presence of a
convenience function that sets the variable.

**Comment by syl20bnr** [comment]
You are right, but minor modes and major modes are _very strong_ conventions in Emacs, not the one you want to mess with when it is simple to avoid it.

For a little gain of convenience (and for being lazy to define a macro) you are by passing the conventions which is a bad reason to do it.

I don't buy the performance argument, not for `LV` window.

**Comment by abo-abo** [comment]
> and for being lazy to define a macro

I don't appreciate the tone.

> that package maintainers do the same

I maintain enough packages to know what I'm doing. Now, look at the definition:

```cl
(define-minor-mode golden-ratio-mode
    "Enable automatic window resizing with golden ratio."
  :lighter " Golden"
  :global t
  (if golden-ratio-mode
      (progn
        (add-hook 'window-configuration-change-hook 'golden-ratio)
        (add-hook 'post-command-hook 'golden-ratio--post-command-hook)
        (add-hook 'mouse-leave-buffer-hook 'golden-ratio--mouse-leave-buffer-hook)
        (ad-activate 'other-window)
        (ad-activate 'pop-to-buffer))
      (remove-hook 'window-configuration-change-hook 'golden-ratio)
      (remove-hook 'post-command-hook 'golden-ratio--post-command-hook)
      (remove-hook 'mouse-leave-buffer-hook 'golden-ratio--mouse-leave-buffer-hook)
      (ad-deactivate 'other-window)
      (ad-deactivate 'pop-to-buffer)))
```

If I plainly call:

```cl
(defun lv-window ()
  (golden-ratio-mode -1)
  (useful-stuff)
  (golden-ragion-mode 1))
```

that means that I'm calling `remove-hook` 3 times, `add-hook` 3 times, `ad-deactivate` 3 times
(which is actually is bad implementation since it touches all advice, not only `golden-ratio`-specific),
and `ad-activate` 3 times. All this in a function that is called after each key press.

Now look at a proper implementation for this sort of thing:

```cl
(defadvice ido-read-internal (before flx-ido-reset activate)
  "Clear flx narrowed hash beforehand."
  (when flx-ido-mode
    (flx-ido-reset)))

(define-minor-mode flx-ido-mode
  "Toggle flx ido mode"
  :init-value nil
  :lighter ""
  :group 'ido
  :global t)
```

**Comment by syl20bnr** [comment]
I didn't want to offend you, _all_ programmers are lazy but sometimes a lot more than required :-)

The numbers of calls don't imply that the complexity is much worst.

The proper way to fix your issue is to improve the `golden-ratio-mode` function, not to propose a bypass of the conventions.

**Comment by abo-abo** [comment]
> The proper way to fix your issue is to improve the golden-ratio-mode function, not to propose a bypass of the conventions.

That was the plan all along. The way to fix `golden-ratio-mode` is to make it behave exactly like `flx-ido-mode`.
And I'm not bypassing conventions, let-binding a variable is perfectly acceptable and encouraged.

**Comment by syl20bnr** [comment]
So maybe a variable called `deactivate-golden-ratio` set to `t` is the correct way to do it.

Once again the conventions say that the bound variable of a mode should be manipulated via `customize`.

**Comment by abo-abo** [comment]
> So maybe a variable called deactivate-golden-ratio set to t is the correct way to do it.

You're complecting things. Why have a variable `golden-ratio-mode` and `not-golden-ratio-mode` and
keep them in sync?

**Comment by syl20bnr** [comment]
Keep them in sync ? Setting `golden-ratio-mode` directly is not the same thing, try it for yourself:
- enable `golden-ratio-mode`
- evaluate `(setq golden-ratio-mode nil)`

You are left in a not consistent state, the lighter is gone but the advices are still running.

With a proper additional variable, it maintains the state consistency.

**Comment by abo-abo** [comment]
> You are left in a not consistent state, the lighter is gone but the advices are still running.

That's the point. It should work. It's easy and makes things simpler for all involved.
Besides, I'm using `let`, not `setq`:

```cl
(defun lv-window ()
  (let (golden-ratio-mode)
    (useful-stuff)))
```

**Comment by syl20bnr** [comment]
It works but it is not conventional whereas the PR (and you) suggests that it is the right way to do it, I don't believe that I have to repeat it so often.

You even gave examples where it is an additional variables which is used and it makes sense, cf. the conventions one more time.

```elisp
(defun lv-window ()
  (let (golden-ratio-mode)
    (useful-stuff)))
```

Even your example above does not work...

**Comment by syl20bnr** [comment]
For reference, after this I'm out.

> The minor mode should, if possible, support enabling and disabling via Custom (see Customization). To do this, the mode variable should be defined with defcustom, usually with :type 'boolean. If just setting the variable is not sufficient to enable the mode, you should also specify a :set method which enables the mode by invoking the mode command. Note in the variable's documentation string that setting the variable other than via Custom may not take effect. Also, mark the definition with an autoload cookie (see autoload cookie), and specify a :require so that customizing the variable will load the library that defines the mode. For example:

     ;;;###autoload
     (defcustom msb-mode nil
       "Toggle msb-mode.
     Setting this variable directly does not take effect;
     use either \\[customize] or the function `msb-mode'."
       :set 'custom-set-minor-mode
       :initialize 'custom-initialize-default
       :version "20.4"
       :type    'boolean
       :group   'msb
       :require 'msb)

Source: https://www.gnu.org/software/emacs/manual/html_node/elisp/Minor-Mode-Conventions.html#Minor-Mode-Conventions

**Comment by tarsius** [comment]
> [let-binding the minor-mode variable to nil] is not what the conventions promote.

I could not find a written reference, but the conventions *are* to let-bind either the mode variable or a dedicated `inhibit-some-mode` or `disable-some-mode` (not `deactivate-some-mode`) variable. If you grep the Emacs sources for it you will find such let-bindings. They are not very frequent but they do exist - I expect they are much more frequent in third-party code. Here is an example from Emacs:

```lisp
(defun ido-read-internal (...)
  (let (... (icomplete-mode nil) ...)
    ...))
```

The convention you quote

> Define a variable whose name ends in `-mode`. We call this the mode variable. The minor mode command should set this variable. The value will be nil if the mode is disabled, and non-nil if the mode is enabled.

concerns the user interface.

Right after the part you quoted comes

> This variable is used in conjunction with the `minor-mode-alist` to display the minor mode name in the mode line.  It also determines whether the minor mode keymap is active, via `minor-mode-map-alist`. **Individual commands or hooks can also check its value.**

Now that doesn't mention advices and says "can" not "should". But when a mode uses advices then it modifies existing functionality which is expect to behave a certain way to behave a different way -  and by doing so it can break other code which relies on the original behavior. I would say that it is common sense that such an advice should allow other code to override it - and the easiest way is to check whether the value of the mode variable is non-nil. In some cases it might more appropriate to use a dedicated `inhibit-*` variable for this, but if such a variable is not provided then each advice should forgo doing anything if the respective mode variable is nil.

Ultimately it is the responsibility of the package which advices functions belonging to other packages, to not break anything. Or provide a *convenient* way to override the advice. Let-bindings are perfect for that, anything more involved is not acceptable. Packages that rely on the original behavior should not have to do any *work* to get things back to normal.

----

Off-topic: I see you have patched `lv`, and probably other libraries, in spacemacs. Try to avoid that. It's always better to fix things upstream.

**Comment by syl20bnr** [comment]
In this case an `inhibit` variable is the way to go, see the proposed PR upstream. I got merging right upstream so I may add the `inhibit` to golden-ratio.

You agree that manipulating the mode variable is not clean since it does not guarantee that proper de-initialization is done. A `inhibit` variable convey the meaning of what we are doing that is `don't uninitialize the mode, just inhibit it`. Using it in a `let` says `temporarily` and `locally`.

**Comment by tarsius** [comment]
Yes, using an `inhibit` function is cleaner. I don't think it's really necessary, but it's definitely cleaner and it certainly helps to have a place where one can document what "inhibiting the mode actually does" (for example it would not disable to mode keymap).
