### ISSUE TITLE
Consider %s instead of %S for docstring sexps

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/hydra#65]
I'm trying to make a magit-like hydra and would like to include the output of git-status in the help window.

Unfortunately, the quotes around the output and escape characters are quite ugly.

I'd expect

     %(shell-command-to-string "git status --short")

to transform to

     M  file1
     M  file 2

and not 

    "M file1
    M file2
    "

**Comment by abo-abo** [comment]
Good point, thanks.
