### ISSUE TITLE
Document nesting hydras

### ISSUE THREAD

**Issue by pgroce** [abo-abo/hydra#66]
It looks like nesting hydras (hydrata?) is implemented, and I even see some oblique references to it from search engines, but I can find no documentation of it in the Readme or the wiki. I infer that this is a sensible example usage:

```elisp

(defhydra foo ()
  "Foo"
  ("a" (message "a pressed") "a")
  ("b" (message "b pressed") "b"))

(defhydra bar ()
  "Bar"
  ("c" (message "c pressed") "c")
  ("d" (message "d pressed") "d"))

(global-set-key
 (kbd "C-c C-o")
 (defhydra master (:exit t)
   "master hydra"
   ("F" foo/body "foo")
   ("B" bar/body "bar"))) 
```

However, the name of ``foo/body`` etc. is an implementation detail, and it's unclear if it's intended as an external interface.

Is this a supported feature? If so, it should be documented somewhere.  If there's another preferred way to nest hydras that is already documented somewhere, or if there are subtleties I'm missing (dragons among the hydras, as it were), please pardon my ignorance. :)

**Comment by abo-abo** [comment]
Nesting Hydras is supported, although currently there isn't a good example of using this option.

I've started on the org-mode export emulation. It's not yet finished, but you can
see how the nesting should work.
It's quite straightforward - almost the same as in your snippet,
although the requirement is only for the nested head to have `:exit t`, not
specifically the whole body.

**Comment by pgroce** [comment]
I'll take a look.

FWIW, I did find an explicit mention of the ``/body`` construct in the docstring for ``defhydra`` (when all else fails, read directions :) ), so I suppose it is documented after all, just not where I expected.

**Comment by abo-abo** [comment]
Documented on [the wiki](https://github.com/abo-abo/hydra/wiki/Nesting-Hydras).
