### ISSUE TITLE
stay in isearch mode after executing hydra heads

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#69]
By default during isearch, with matches highlighted, pressing C-v/M-v scrolls without exiting the isearch mode and moves the current match to the bottom/top of screen respectively.

Now I have C-v/M-v bound to hydra heads that call (scroll-down nil) and (scroll-up nil) respectively, pressing C-v/M-v exits from isearch after scrolling.

A similar case is with C-l which by default recenters the line of current match without losing isearch mode. After binding C-l to a hydra head that calls (recenter-top-bottom), pressing C-l exits isearch mode after the line is recentered.

Is it possible that I can stay in isearch after executing these hydra heads?

**Comment by abo-abo** [comment]
> By default during isearch, with matches highlighted, pressing
> C-v/M-v scrolls without exiting the isearch mode and moves the
> current match to the bottom/top of screen respectively.

This isn't the default behavior - <kbd>C-v</kbd>/<kbd>M-v</kbd> exit isearch by default.

> Is it possible that I can stay in isearch after executing these hydra heads?

I don't see a problem with this hydra:

```cl
(defhydra hydra-isearch (isearch-mode-map "")
  ("C-v" (scroll-down nil))
  ("M-v" (scroll-up nil)))
```

**Comment by zhaojiangbin** [comment]
You're right. What I had is not the default behavior. It must be my customizations. Closing the issue.

**Comment by zhaojiangbin** [comment]
Turns out that I have ```(setq isearch-allow-scroll t)``` in my .emacs. After reading the comments in isearch.el, I tried giving the hydra heads the ```scroll-command``` property:

```elisp
(defhydra jzhao/hydra-page-motion
  ()
  "page"
  ("v"       (scroll-up nil)   "up")
  ("V"       (scroll-down nil) "down")
  ("SPC"     hydra-repeat      "repeat")
  ("<escape>" nil))
(bind-keys ("C-v"     . jzhao/hydra-page-motion/lambda-v)
           ;;("<next>"  . jzhao/hydra-page-motion/lambda-v)
           ("M-v"     . jzhao/hydra-page-motion/lambda-V)
           ;;("<prior>" . jzhao/hydra-page-motion/lambda-V)
           )
(put 'jzhao/hydra-page-motion/lambda-v 'scroll-command t)
(put 'jzhao/hydra-page-motion/lambda-V 'scroll-command t)
```
Now pressing C-v/M-v in isearch no longer cancels the highlights, but still exits from isearch mode as far as I can tell. So I tried the following just to compare. It works as expected:

```elisp
(defun my-page-down ()
  (interactive)
  (scroll-up nil))
(defun my-page-up ()
  (interactive)
  (scroll-down nil))
(put 'my-page-down 'scroll-command t)
(put 'my-page-up 'scroll-command t)

(bind-keys :map global-map
           ("<next>" . my-page-down)
           ("<prior>" . my-page-up))
```
Did I get it right when putting the property in the hydra heads?

**Comment by abo-abo** [comment]
> Did I get it right when putting the property in the hydra heads?

It looks to be correct, but there are things that could go wrong with
interaction of `ispell` and `set-transient-map`. I don't have the time to investigate it,
but it seems that the earlier approach with using `ispell-mode-map` works.

**Comment by zhaojiangbin** [comment]
I assume you meant "isearch" by "ispell"? Your suggestion earlier using isearch-mode-map does not work as I expect: C-v/M-v still terminates isearch and can move point offscreen.

Perhaps my idea of having a hydra just for page up/down is not worth it in the first place. We should move on.

**Comment by abo-abo** [comment]
> Perhaps my idea of having a hydra just for page up/down is not worth it in the first place. We should move on.

You're right. The idea is OK, but figuring out the intricacies of `isearch-mode` just to
get page up/page down working during `isearch` isn't worth it.
