### ISSUE TITLE
The lispy example is not great

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/hydra#7]
It actually prevents you from inserting `z` everywhere, because `z` will activate Hydra.  :)

Of course, it can be amended to:

```
(hydra-create "z"
  '(("l" forward-char)
    ("h" backward-char)
    ("j" next-line)
    ("k" previous-line)
    ("z" (lambda () (interactive) (insert-char ?z))))
  lispy-mode-map)
```

But that doesn't feel great either.

**Comment by abo-abo** [comment]
You're right, I caught that late yesterday, and already started fixing it
in https://github.com/abo-abo/hydra/tree/next, where this is possible:

```cl
(hydra-create "C-z"
  '(("l" forward-char)
    ("h" backward-char)
    ("j" next-line)
    ("k" previous-line)
    ("z"))
  lispy-mode-map)

(lispy-define-key lispy-mode-map "z" 'hydra-C-z-body)
```

Now, <kbd>C-z</kbd> is a global binding and <kbd>z</kbd> is a local binding
for the same Hydra in `lispy-mode`.

I still have to figure out some kinks before I merge `next` into `master`,
but it works now almost as intended.

**Comment by bcarrell** [comment]
Always two steps ahead!
