### ISSUE TITLE
menu not displayed

### ISSUE THREAD

**Issue by jney** [abo-abo/hydra#70]
the plugin works great. but i never get the menu displayed. i can't figure out why.

**Comment by thisch** [comment]
Please provide more details: What version of emacs do you use, steps to reproduce the problem, ...

**Comment by abo-abo** [comment]
There's a custom var from way back that could turn off the menu
(if that is what you call the hint near the mode line) with:

```cl
(setq hydra-is-helpful nil)
```

But it's on by default, and I don't know a case for turning it off.

**Comment by jney** [comment]
sorry guys, for the lack of details in the first report, i'm running emacs 24.3.1 on ubuntu linux.
i tried forcing `hydra-is-helpful` to true, but it didn't change anything

**Comment by abo-abo** [comment]
In hydra repository, type into your shell:

    make compile

It will start a new Emacs with only hydra enabled, no other packages.
Then test if e.g. `<f2> g` or anything else defined in hydra-examples.el works.

**Comment by jney** [comment]
it works. now i "just" need to find out which parameter enter in conflict with hydra

**Comment by abo-abo** [comment]
Yes, it's normal for this Hydra:

```cl
(defhydra hydra-zoom (global-map "<f2>")
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))
```

If you want an immediate hint after `<f2>` use it like this:

```cl
(defhydra hydra-zoom ()
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))
(global-set-key (kbd "<f2>") 'hydra-zoom/body)
```

The disadvantage of second approach is that you can no longer
use `<f2>` as a prefix: e.g. `<f2> f` will not work. But with the
first approach it will.

**Comment by jney** [comment]
thanks for making it clearer to me.
It was a misunderstanding from my side, all of my keys in a `hydra` function were "blue" so it  didn't make sense for not being displayed immediately. but you showed me a me a way to do it. cool
