### ISSUE TITLE
Proposal to clarify the documentation and value of Hydra

### ISSUE THREAD

**Issue by jakubholynet** [abo-abo/hydra#71]
Hello, I have just discovered Hydra and it looks great! However I had troubles understanding what it can do for me and why I would want to use it. I had to read a lot to figure it out and I still don't understand the full power of it. The introductory paragraphs about Hydra heads and Hercules are fancy but did not calrify anything to me. I therefore propose to write the intro in a clearer, more approachable way.

For example *something* like this (excuse the inexact but perhaps more comprehensible terminology):

> Hydra enables you to define easily your own menus that pop up unobtrusively when you press a key or key chord and then to select items or sub-menus with a single key. You can even invoke multiple items or a single item repeatedly, for example to increase the text size three times via the Hydra defined below you would type `<f2> g g g`.
>
> Here is an example of a [Projectile-specific menu](https://github.com/abo-abo/hydra/wiki/Projectile), that you could bind to and invoke with f.ex. `C-x p`:
>
> ![Projectile Hydra menu](https://camo.githubusercontent.com/f70fa18a89869b081d46575c745ac0252659b5e4/687474703a2f2f692e696d6775722e636f6d2f7a6d5679526d6e2e706e67)
> You can define global and mode-specific menus, use custom colors and do many more cool things - read on to find them out!.

**Comment by abo-abo** [comment]
Thanks for the suggestions. I'll try to update this at some point.

I would gladly accept pull requests for README.md fixes, but since hydra is in GNU ELPA,
each contributor needs a FSF emacs copyright assignment to contribute over 15 lines.

However, this does not apply to the wiki: https://github.com/abo-abo/hydra/wiki.
You can have free reign there, writing down descriptions and code as you see fit.
I only make minor corrections there sometimes.

**Comment by jakubholynet** [comment]
The problem with the wiki is that it is not the first thing a visitor sees. Once she has got to the wiki, she has likely read enough to already understand the value proposition of hydra. So if this should add any value, it has to be at the beginning of the README, I think.
BTW Perhaps the screenshot and example from http://oremacs.com/2015/02/20/buffer-menu-hydra/ would be better than the Projectile one since it shows not only the menu buffer but also the buffer it was triggered for and it might be more familiar to users than Projectile.

**Comment by abo-abo** [comment]
I have no problem with reducing the amount of stuff in README.md.
That's the approach of [company-mode](https://github.com/company-mode/company-mode).

It remains to decide where to move the stuff: to github pages or to the wiki, or both.  Or maybe
just move the large README.md to a `doc` branch and have the README.md in the `master` branch point there, since I'm only merging `master` into ELPA.

**Comment by hura** [comment]
@jakubholynet abo's blog has a lot of exlanations:
http://oremacs.com/archive/ (Ctrl+F hydra)

Admittedly, it's not optimal since some of the code is now out of date due to changes and the location is obviously bad. Without having followed the blog I think it's tough for a beginner to understand the idea. I think the Wiki is a good start so everybody can contribute.
HTH

**Comment by jakubholynet** [comment]
@hura I am sure there is lot of good info. But I am here concerned with the first bit of information/docs a newcomer sees.

@abo-abo I was not complainign about the amount of info in the README, I think it is OK. I just propose to change / add to the initial paragraphs to make the purpose and value of Hydra clear.

Thank you!

**Comment by abo-abo** [comment]
@jakubholynet, is the issue solved for you?

**Comment by jakubholynet** [comment]
The new README is clearly better, the sample hydras really help to explain what it is used for.

I would still prefer the first 3 paragraphs to be clearer:

>This is a package for GNU Emacs that can be used to tie related commands into a family of short bindings with a common prefix - a Hydra.
When I first came here, I had no idea what "tie related commands into a family of short bindings with a common prefix" means. What is "a family of short bindings"? What is "common prefix" in this context? An example would help incredibly, f.ex.: *"You can for example create a Hydra for Projectile commands; typing their common prefix `C-c p` will pop-up an unbotrusive menu with the available Projectile commands (Hydra heads) that can be invoked by typing the letter assigned to them."*

>Once you summon the Hydra through the prefixed binding (the body + any one head), all heads can be called in succession with only a short extension.

Again unclear to a newcomer - what is "body"? what is a "head"? What is an "extension"? (I am used to "browser extensions" but that clearly isn't it). What "calling heads [in succession]" means?!

>The Hydra is vanquished once Hercules, any binding that isn't the Hydra's head, arrives. Note that Hercules, besides vanquishing the Hydra, will still serve his original purpose, calling his proper command. This makes the Hydra very seamless, it's like a minor mode that disables itself auto-magically.

What "vanquishing the Hydra" means?! What is meant by a "binding" in this context? What is the original purpose/command of Hercules?

The Hydra/Hercules metaphor is cute but little difficult to comprehend. Speaking about menus, sub-menus and menu items (= commands) would give me, as a new user, much clearer image because these are terms I am used to. So explaining Hydra in these terms and then adding the Hydra/Hercules metaphor would be, IMHO, much clearer.
But it is up to you how clear you want to be or how stupid users you want to support. So just close this if you prefer. Thank you!

**Comment by abo-abo** [comment]
I think the current description is more or less sufficient for now.  It was clearly in a bad state
before, since I was just piling on snippets without restructuring, so thanks for bringing it to my
attention. Maybe I'll revisit it later, if I ever get into documentation-writing mood again.
