### ISSUE TITLE
Kill hydra on frame change

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/hydra#73]
If I jump to another emacs frame using my window manager (i3) any active
hydra stays alive in the original frame. This is confusing because it
seems like emacs has just freezed when in reality the keypresses go to
the frame where the hydra is active.

So my suggestion is to check on keypress if the current frame has
changed. If it has, exit the hydra.

**Comment by jhonnyseven** [comment]
The hydra exits, but inserted characters go to where the cursor is in the original frame.

**Comment by abo-abo** [comment]
I don't get it.

**Comment by jhonnyseven** [comment]
It acts as if the keypresses were going to the original frame where
the hydra was active.

If I activate and exit some hydra in the new frame it starts working
normally again.

**Comment by jhonnyseven** [comment]
Using emacs 24.3.1 with emacs server and clients in rxvt-unicode.
