### ISSUE TITLE
Support multiple simultaneously active hydras

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/hydra#74]
I came up with a situation where I was browsing some code with outline
mode related hydra. The I wanted to make changes to a file in other
buffer using a vi-movement hydra. Of course, I had to exit the outline
hydra first. Then after the edit I jumped back to the first buffer and
re-enabled my outline mode hydra.

In theory both vi-movement hydra and outline-mode hydra could be
active for each window. Whereas something like window-movement hydra
makes more sense as having only one instance active at once.

What are your thoughts on this?

**Comment by abo-abo** [comment]
This can't be done easily with current Emacs facilities.
Hydra is based around `set-transient-map` - it's a keymap that overrides all others.
There can be only one transient map for the whole Emacs instance.

If I use anything other than `set-transient-map`, other packages could get the keyboard priority,
which would defeat the purpose of Hydra.

You could play some tricks advising `select-window` to disable one hydra and re-enable another,
but that code should be on the user side, not in hydra.el.

**Comment by jhonnyseven** [comment]
I see. Maybe I'll try playing with select-window some time.
Thanks anyway.
