### ISSUE TITLE
2 issues with docstring

### ISSUE THREAD

**Issue by zeltak** [abo-abo/hydra#75]
hi 

i have 2 issued with the docsting in the hydra below. one is that the the :hint nil is being ignored and i see alongside the docstring the normal hints. also for some reason _;_ will not get a highlight

thx alot

Z

(defhydra hydra-commenting (:color blue :hint nil )
     "
comment  _;_ // comment _t_o line // comment para_g_raph // co_p_y-paste-comment 
     "
     (";" evilnc-comment-or-uncomment-lines  "comment" ) 
     ("t" evilnc-quick-comment-or-uncomment-to-the-line   "c 2 line"  nil ) 
     ("g" evilnc-comment-or-uncomment-paragraphs  "c paragraph"  nil ) 
     ("p" evilnc-copy-and-comment-lines  "c,c,p"  nil ) 
     ("d" downcase-region  "downcase"  nil ) 
     ("q" nil "cancel" nil)

**Comment by abo-abo** [comment]
Your `:hint nil` is being ignored because you specify the hint
manually in each head. How it works: each head *inherits* `:hint`, so
it is that value *if* you don't override it (which you did).

Here's the fix:

```cl
(defhydra hydra-commenting (:color blue :hint nil)
  "
comment _;_ // comment _t_o line // comment para_g_raph // co_p_y-paste-comment
"
  (";" evilnc-comment-or-uncomment-lines)
  ("t" evilnc-quick-comment-or-uncomment-to-the-line)
  ("g" evilnc-comment-or-uncomment-paragraphs)
  ("p" evilnc-copy-and-comment-lines)
  ("d" downcase-region "downcase")
  ("q" nil "cancel"))
```

`;` did not get a highlight, because it was not underscored.

**Comment by zeltak** [comment]
thx for the quick reply, but using your code above both issues seems still unsolved :)
here is a screenshot showing this: https://paste.xinu.at/9yL2/

thx again, hydra is my fav all time emacs package (well at least competing for the title with org-dl ;-) )

best

Z

**Comment by abo-abo** [comment]
I think I've fixed the issue with the semicolon.

For the other thing, make sure that:

- you have the newest Hydra
- you have re-compiled the source file with `defhydra`, if you compile your files
- you have restarted Emacs

If it still doesn't work, tell me your Emacs version.

**Comment by zeltak** [comment]
Hi again
yup the semi-colon fix worked :)

the other issue is still present as i still see both the docstings and hint. i just updated from MELPA and restart emacs and its still there. some info you requested:

GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.7)
 of 2015-01-17 on bisson
best

Z

**Comment by abo-abo** [comment]
Can you eval this and show me the result:

```cl
(nth 7 (macroexpand '(defhydra hydra-commenting (:color blue :hint nil)
                      "
comment _;_ // comment _t_o line // comment para_g_raph // co_p_y-paste-comment
"
                      (";" evilnc-comment-or-uncomment-lines)
                      ("t" evilnc-quick-comment-or-uncomment-to-the-line)
                      ("g" evilnc-comment-or-uncomment-paragraphs)
                      ("p" evilnc-copy-and-comment-lines)
                      ("d" downcase-region "downcase")
                      ("q" nil "cancel"))))
```

**Comment by zeltak** [comment]
as requested:

#+BEGIN_SRC emacs-lisp 
(nth 7 (macroexpand '(defhydra hydra-commenting (:color blue :hint nil)
                      "
comment _;_ // comment _t_o line // comment para_g_raph // co_p_y-paste-comment
"
                      (";" evilnc-comment-or-uncomment-lines)
                      ("t" evilnc-quick-comment-or-uncomment-to-the-line)
                      ("g" evilnc-comment-or-uncomment-paragraphs)
                      ("p" evilnc-copy-and-comment-lines)
                      ("d" downcase-region "downcase")
                      ("q" nil "cancel"))))
#+END_SRC

#+RESULTS:
| defun | hydra-commenting/hint | nil | (if hydra-lv (lv-message (concat (format comment _;_ // comment %so line // comment para%sraph // co%sy-paste-comment |
t g p) [d]: downcase, [q]: cancel)) (message (concat (format comment _;_ // comment %so line // comment para%sraph // co%sy-paste-comment
t g p) [d]: downcase, [q]: cancel))) |

**Comment by abo-abo** [comment]
Could you just do it in `*scratch*` (just press <kbd>C-j</kbd> after the expression).
It's hard to see the code behind the `|` symbols.

**Comment by zeltak** [comment]
sorry here it is

(nth 7 (macroexpand '(defhydra hydra-commenting (:color blue :hint nil)
                      "
comment _;_ // comment _t_o line // comment para_g_raph // co_p_y-paste-comment
"
                      (";" evilnc-comment-or-uncomment-lines)
                      ("t" evilnc-quick-comment-or-uncomment-to-the-line)
                      ("g" evilnc-comment-or-uncomment-paragraphs)
                      ("p" evilnc-copy-and-comment-lines)
                      ("d" downcase-region "downcase")
                      ("q" nil "cancel"))))
(defun hydra-commenting/hint nil (if hydra-lv (lv-message (concat ... #("[d]: downcase, [q]: cancel" 1 2 ... 16 17 ...))) (message (concat ... #("[d]: downcase, [q]: cancel" 1 2 ... 16 17 ...)))))

**Comment by abo-abo** [comment]
Could you set the following custom variables before the eval:

```cl
(setq eval-expression-print-length nil)
(setq eval-expression-print-level nil)
```

That should remove the ellipses in the result.

**Comment by zeltak** [comment]
here it is

(defun hydra-commenting/hint nil (if hydra-lv (lv-message (concat (format "comment %s // comment %so line // comment para%sraph // co%sy-paste-comment
" #(";" 0 1 (face hydra-face-blue)) #("t" 0 1 (face hydra-face-blue)) #("g" 0 1 (face hydra-face-blue)) #("p" 0 1 (face hydra-face-blue))) #("[d]: downcase, [q]: cancel" 1 2 (face hydra-face-blue) 16 17 (face hydra-face-blue)))) (message (concat (format "comment %s // comment %so line // comment para%sraph // co%sy-paste-comment
" #(";" 0 1 (face hydra-face-blue)) #("t" 0 1 (face hydra-face-blue)) #("g" 0 1 (face hydra-face-blue)) #("p" 0 1 (face hydra-face-blue))) #("[d]: downcase, [q]: cancel" 1 2 (face hydra-face-blue) 16 17 (face hydra-face-blue))))))

**Comment by abo-abo** [comment]
Can you

1. evaluate `(hydra-commenting/hint)`, confirming that the bug is still there.
2. evaluate the code that you just gave me
3. evaluate `(hydra-commenting/hint)` again, you should not see the bug now.

**Comment by zeltak** [comment]
Hi again

i may be doing the above wrong but this is what i did (again i may have misunderstood the instructions)

1. i start by eval these 2 lines
```
(setq eval-expression-print-length nil)
(setq eval-expression-print-level nil)
```
then i issue this
```
(hydra-commenting/hint)
```

now the hint and docstring appear and there dosent seem anyway to make them go away (pressing any key including the `q` key does nothing

then i eval (you wrote evaluate the code that you just gave me which i assume is this)
```
(defun hydra-commenting/hint nil (if hydra-lv (lv-message (concat (format "comment %s // comment %so line // comment para%sraph // co%sy-paste-comment
" #(";" 0 1 (face hydra-face-blue)) #("t" 0 1 (face hydra-face-blue)) #("g" 0 1 (face hydra-face-blue)) #("p" 0 1 (face hydra-face-blue))) #("[d]: downcase, [q]: cancel" 1 2 (face hydra-face-blue) 16 17 (face hydra-face-blue)))) (message (concat (format "comment %s // comment %so line // comment para%sraph // co%sy-paste-comment
" #(";" 0 1 (face hydra-face-blue)) #("t" 0 1 (face hydra-face-blue)) #("g" 0 1 (face hydra-face-blue)) #("p" 0 1 (face hydra-face-blue))) #("[d]: downcase, [q]: cancel" 1 2 (face hydra-face-blue) 16 17 (face hydra-face-blue))))))
```
this returns nothing

finally i eval
```
(hydra-commenting/hint)
```
which again bring upthe hint and docstring appear and there dosent seem anyway to make them go away

happy to keep on debugging this to finally get it working

thx!

z

**Comment by abo-abo** [comment]
> there dosent seem anyway to make them go away

This is fine, since you're only calling the hint code, not the whole Hydra.

The question now is: did you get a proper hint in either of the calls to
`hydra-commenting/hint`?

**Comment by zeltak** [comment]
Hi again

no still got both the hints and the docstring above in both calls

best

Z

zeltak

**Comment by abo-abo** [comment]
But this is the code that you're running:

```cl
(defun hydra-commenting/hint nil
  (lv-message
   (concat (format "comment %s // comment %so line // comment para%sraph // co%sy-paste-comment\n"
                   #(";" 0 1 (face hydra-face-blue))
                   #("t" 0 1 (face hydra-face-blue))
                   #("g" 0 1 (face hydra-face-blue))
                   #("p" 0 1 (face hydra-face-blue)))
           #("[d]: downcase, [q]: cancel"
             1 2 (face hydra-face-blue)
             16 17 (face hydra-face-blue)))))
```

There's no way it should produce a wrong output:

![hydra-docstring-1](https://cloud.githubusercontent.com/assets/2937359/6651150/ca17453e-ca35-11e4-8842-06355347b024.png)

**Comment by zeltak** [comment]
hi again

ok i think i dont understand a few things .in the screenshot above i see both the docstring text ie (comment ; ) AND the "hints" ie [d] :downcase etc. are they both suppose to appear each time? i thought only the upper (docstring) part appears if :hints: nil is set. if thats the normal behivour then yes this is what i get like in the screen above

thx 

z

**Comment by abo-abo** [comment]
For this code:

```cl
(defhydra hydra-commenting (:color blue :hint nil)
  "
comment _;_ // comment _t_o line // comment para_g_raph // co_p_y-paste-comment
"
  (";" evilnc-comment-or-uncomment-lines)
  ("t" evilnc-quick-comment-or-uncomment-to-the-line)
  ("g" evilnc-comment-or-uncomment-paragraphs)
  ("p" evilnc-copy-and-comment-lines)
  ("d" downcase-region "downcase")
  ("q" nil "cancel"))
```

The hint should be as in my screenshot, but not as in your screenshot.
`:hint nil` means that all heads *inherit* it. Inherit means that they
have that value if no other is provided. <kbd>d</kbd> and <kbd>q</kbd>
inherit the hint `nil`, but *override* it to be `"downcase"` and `"cancel"` respectively.
Inheritance is a trick used in most common programming languages. I hope it's more clear now.

**Comment by zeltak** [comment]
thx!

its clear now and it works :)!!

best and thx again

Z

**Comment by abo-abo** [comment]
Alright, I'm glad it's cleared up.
