### ISSUE TITLE
[Feature Request] Add menu options that we could use <TAB> to circle through

### ISSUE THREAD

**Issue by andyque** [abo-abo/hydra#76]
If I want to choose a item in a  list, I want to put a few options in the hydra window, then I could use TAB key to circle through these options and press Return to choose.

In this way, I don't need to remember keys.

This will be really handy.

**Comment by abo-abo** [comment]
You need to be a lot more specific about what you're trying to do. As it sounds now, `ido` or `helm`
would suit you better.

**Comment by andyque** [comment]
@abo-abo 
Hmmm, maybe helm is better for my needs. Thanks.
