### ISSUE TITLE
Why won't hydra work with winner?

### ISSUE THREAD

**Issue by WorldsEndless** [abo-abo/hydra#79]
I'm trying to get winner-mode working with hydra in order to enhance the window navigation hydra here: http://oremacs.com/2015/02/03/one-hydra-two-hydra/

But when I bind winner to my hydra, it never actually works; winner won't activate, even though calling winner-undo out of hydra works fine. This simple bit is all I'm trying: 

    (global-set-key
     (kbd "C-c p")
     (defhydra hydra-winner ()
       "Winner"
       ("p" winner-undo "back")
       ("o" winner-redo "forward")
       ))

**Comment by abo-abo** [comment]
This is the way to do it:

```cl
(global-set-key
 (kbd "C-c p")
 (defhydra hydra-winner ()
   "Winner"
   ("p" (progn
          (winner-undo)
          (setq this-command 'winner-undo))
        "back")
   ("o" winner-redo "forward"
        :exit t)))
```

The thing with the first one is that <kbd>p</kbd> will call `hydra-winner/winner-undo`, and
`winner-undo` function is checking specifically if the last command was named `winner-undo`.

The second one should be set with `:exit t`, since it can't be called twice anyway. Also there would
be some interference from hydra in the window configuration.

Finally, I think that this code would do better:

```cl
(defhydra hydra-winner (global-map "C-c")
  "Winner"
  ("p" (progn
         (winner-undo)
         (setq this-command 'winner-undo))
       "back")
  ("o" winner-redo "forward"
       :exit t :bind nil))
```

It will bind <kbd>C-c p</kbd> to `hydra-winner/winner-undo`, but <kbd>C-c o</kbd> will not be bound,
since it doesn't make sense.

**Comment by abo-abo** [comment]
Is the issue resolved?

**Comment by WorldsEndless** [comment]
Yes; I'll note that the key bindings above were frivolous because I was just developing this hydra to plug it into my window-nav hydra, which is now all the awesomer. Your trick for getting the undo to repeat was perfect. I took the exit and bind commands off of forward because sometimes I need to try the whole sequence again. Thanks!

**Comment by ffevotte** [comment]
Is there a reason not to always set `this-command` for hydra heads which are directly defined as commands?
I think this would be harmless, and maybe easier for unaware users...

**Comment by abo-abo** [comment]
> Is there a reason not to always set this-command for hydra heads which are directly defined as commands?

I don't know. It should work, but maybe something obscure could come up.

> I think this would be harmless, and maybe easier for unaware users...

OK, I can make this change and see if any regressions come up. Probably they won't.

**Comment by abo-abo** [comment]
@WorldsEndless, you can now simplify the code to this:

```elisp
(global-set-key
 (kbd "C-c p")
 (defhydra hydra-winner ()
   "Winner"
   ("p" winner-undo "back")
   ("o" winner-redo "forward" :exit t)))
```

**Comment by ffevotte** [comment]
I think it should be better to set `this-command` earlier, before calling the actual command. From Emacs' documentation, it is actually possible for commands to set `this-command` to a non-default value themselves. I don't think `hydra` should be allowed to modify the variable after this.

> this-command is a variable defined in `C source code'.
>
> Documentation:
> The command now being executed.
> **The command can set this variable; whatever is put here
> will be in `last-command' during the following command.**

Unless I missed something, the commit referenced above (e0db11e) should set `this-command` at an appropriate time (just before calling the command).

**Comment by abo-abo** [comment]
I'm guessing it's not a big deal, especially for this use case, but it makes sense to do it right.
Thanks for the info.

**Comment by ffevotte** [comment]
Thanks!

**Comment by WorldsEndless** [comment]
Very good. Thanks!
