### ISSUE TITLE
Issue binding multiple keys to the same function

### ISSUE THREAD

**Issue by glucas** [abo-abo/hydra#8]
It seems like a hydra with multiple keys for the same target function does not behave properly. For example:

    (hydra-create "M-g" '(("n" next-error "next error")
                          ("p" previous-error "previous error")
                          ("M-n" next-error "next error")
                          ("M-p" previous-error "previous error")))

The `M-n` / `M-p` bindings only work once, while the `n` and `p` bindings are repeatable.

**Comment by abo-abo** [comment]
This was fixed earlier today. I'm getting proper behavior now. Make sure that you re-compile your config, since `hydra-create` is a macro.

**Comment by abo-abo** [comment]
Great Hydra, btw. I'll surely add this idea to my config.

**Comment by glucas** [comment]
Yup - I pulled the latest and it is working now. Thanks!
