### ISSUE TITLE
timeout does not clear the echo area when hydra-lv is nil

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#80]
I have `(setq hydra-lv t)` before defining any hydra. But for a few hydras I'd like to keep their "visual footprint" to the minimum, for example:
```elisp
(defhydra foo (:timeout 2.0 :pre (setq hydra-lv nil) :post (setq hydra-lv t))
  "foo"
  ("a" 't)
  ("b" 't)
  ("q" nil))
```
The hydra hints remain in the echo area after timeout. The hints do disappear if the hydra is dismissed before timeout by either <kbd>C-g</kbd> or the nil head <kbd>q</kbd>.

This can also be reproduced with:
```elisp
(setq hydra-lv nil)
(defhydra foo (:timeout 2.0)
  "foo"
  ("a" 't)
  ("b" 't)
  ("q" nil))
```

For hydras that show hints using `hydra-lv`, timeout does hide the LV window which gives a nice clue for what happened.

**Comment by abo-abo** [comment]
The commit should fix the second example.
The first example can be updated like this:

```cl
(defhydra foo (:timeout 2.0 :pre (setq hydra-lv nil) :post
               (progn
                 (setq hydra-lv t)
                 (message "")))
  "foo"
  ("a" 't)
  ("b" 't)
  ("q" nil))
```

**Comment by zhaojiangbin** [comment]
Right I should have thought of adding `(message "")` in the body's post handler. Thanks for fix and the tip. Hydra becomes more awesome everyday.
