### ISSUE TITLE
Amaranth exiting on non-head key sequences

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/hydra#81]
This hydra exits for me if I type any sequence starting with `f` not followed by `o`. How do I make it not do that?

```emacs-lisp
(defhydra hydra-test (:color amaranth)
  "foo"
  ("fo" (message "yay"))
  ("q" nil))
```

**Comment by abo-abo** [comment]
The issue here is with <kbd>f</kbd> being spun off into its own keymap that doesn't have the
override of the original one.

I'll try to fix this eventually, although I don't yet know how, short of writing my own version of
`define-key`.

**Comment by abo-abo** [comment]
Let me know if it works fine.

**Comment by jhonnyseven** [comment]
Seems to work perfectly here. Thanks :)
