### ISSUE TITLE
How to call original key binding in amaranth hydra?

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/hydra#82]
I'm currently doing `(progn (hydra-pink-fallback))`. Is this the best way?

**Comment by abo-abo** [comment]
I think it could work without a `progn`.

Can you give more context? What are you trying to do?

**Comment by jhonnyseven** [comment]
It would be handy when using `vi-movement` hydra on different major
modes. For example , I'd like to use `η` to call the mode specific
documentation function.

`hydra-pink-fallback` is a function, not a command, so it doesn't work.

**Comment by jhonnyseven** [comment]
Perhaps a better example: 
I have `M-m` bound to mode specific hydras with frequently forgotten commands. So it would be nice to be able to access this from `vi-movement` hydra.

**Comment by abo-abo** [comment]
> hydra-pink-fallback is a function, not a command, so it doesn't work.

`(hydra-pink-fallback)` will work.

**Comment by jhonnyseven** [comment]
Indeed it does, thanks.
