### ISSUE TITLE
After a helm-swoop-edit I'm stuck in a full screen hydra buffer

### ISSUE THREAD

**Issue by hura** [abo-abo/hydra#83]
I can kill `*LV*` buffer with `C-x k` but I think it's a bug.

To reproduce:

https://github.com/abo-abo/hydra/wiki/Helm

(And add `helm-swoop-edit`). Then start a helm swoop and edit something. Quit & save with `C-x C-s` and I end up in one full screen hydra buffer.

**Comment by abo-abo** [comment]
This head should work:

```cl
("s" (progn
       (hydra-keyboard-quit)
       (helm-swoop-edit))
     :exit t)
```

**Comment by hura** [comment]
I see, so not considered a bug I guess but just needed due to the way things work? Thanks for the code.

**Comment by abo-abo** [comment]
I don't think it's a bug. It's just that hydra puts the window configuration and the keymaps in a
certain state, and other commands, like `helm-swoop-edit` assume a different state to be in place.
So you have to restore that state with `hydra-keyboard-quit`.

If the suggested head works for you, you can close the issue.

**Comment by hura** [comment]
Fantastic. Works. Thanks. I like your recent addition to the helm wiki page too (kill buffers).
