### ISSUE TITLE
hydra--format appends an 'S' to the output of %s`var in docstring

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#85]
Given:
```elisp
(defvar foo "a b c")
(defhydra bar ()
  "
  bar %s`foo
"
  ("a" 't)
  ("q" nil))
```
`bar/body` produces "bar a b cS", as shown in the attached image, too:

![screen shot 2015-03-22 at 6 02 49 pm](https://cloud.githubusercontent.com/assets/4935788/6772526/dc075a0c-d0bd-11e4-927a-32f08169948c.png)

Meanwhile, `%s(identity var)` gives the expected output: "bar a b c". This is what I am using to work around the issue.

**Comment by zhaojiangbin** [comment]
Turns out that an 'S' is appended to the output of "%S`var", too:
 ```
  bar "a b c"S
```

**Comment by abo-abo** [comment]
So far, `%s` spec is only for s-expressions, i.e. `%s(foo)`. I haven't yet seen a use-case for
variables, since quoting a variable should be fine if it's a string.

I guess that I should extend it to make the variable quoting also work.

**Comment by zhaojiangbin** [comment]
I see. It'd be nicer to have the consistency if it's not too much effort. Otherwise, documenting the difference somewhere would suffice.

**Comment by abo-abo** [comment]
Your example should work now. Let me know if there are any regressions elsewhere.
