### ISSUE TITLE
suggestion: maybe hydra can learn the configuration way from yasnippet

### ISSUE THREAD

**Issue by hick** [abo-abo/hydra#87]
hehe,  repost from http://oremacs.com/2015/03/22/hydra-0.12.0/

thx for so good a tool "hydra", I've introduced it in a new blog in chinese: http://blog.hickwu.com/posts/336 , and reposted it in several Chinese Emacs communities. 

it seems like the instruction in github is not so easy to understand, there is no text about how to install, and I suggest hydra can learn the configuration way from yasnippet, that can group by different topics(or maybe programming languages), and even one topic can inherits from another...

sorry for I can only have suggest but no code contribution for my poor Emacs Lisp.  and sorry for my poor English, hehe

thanks again for hydra

**Comment by abo-abo** [comment]
I think at this point hydra is well described on [the wiki](https://github.com/abo-abo/hydra/wiki).  If some particular points are still unclear, raise an issue and the wiki will be amended to address these points.
