### ISSUE TITLE
defhydra fails in a non-obvious way

### ISSUE THREAD

**Issue by stsquad** [abo-abo/hydra#88]
I think I must have screwed up the formatting somehow but it's not clear how:

```
;; Trying hydra                                                                                                                                                        
(global-set-key
 (kbd "C-x t")
 (defhydra my-hydra-toggle (:color blue)
   "toggles: debug-on-error: %`debug-on-error "
  ("a" abbrev-mode "bbrev-mode")

  ("d" toggle-debug-on-error "d-o-e")
  ("q" toggle-debug-on-quit "d-o-q")

  ("n" my-narrow-or-widen-dwim "arrow-or-widden")
  ("e" er/expand-region "xpand-region")

  ("f" auto-fill-mode "auto-fill-mode")
  ("w" whitespace-mode "whitespace-mode")

  ("t" toggle-truncate-lines "truncate-lines")
  ("l" visual-line-mode "visual-line-mode")
  ("q" nil "quit" :color red)))
```

When I run C-x t I get the following in messages:

```lv-message: Not enough arguments for format string```

**Comment by abo-abo** [comment]
It's solved with a single newline after the first quote in docstring:

```cl
(defhydra my-hydra-toggle (:color blue)
  "
toggles: debug-on-error: %`debug-on-error "
  ("a" abbrev-mode "bbrev-mode")

  ("d" toggle-debug-on-error "d-o-e")
  ("q" toggle-debug-on-quit "d-o-q")

  ("n" my-narrow-or-widen-dwim "arrow-or-widden")
  ("e" er/expand-region "xpand-region")

  ("f" auto-fill-mode "auto-fill-mode")
  ("w" whitespace-mode "whitespace-mode")

  ("t" toggle-truncate-lines "truncate-lines")
  ("l" visual-line-mode "visual-line-mode")
  ("q" nil "quit" :color red))
```

Reason being that if you want to align your large docstring, you probably will have the newline
after the first quote anyway. Docstrings without the leading newline are used in a way compatible
with version 0.1.0 (at that point, Ruby-style didn't exist).

**Comment by stsquad** [comment]
The behaviour is a little non-obvious (nothing is mentioned about the requirements for DOCSTRING in the DOCTRING for defhydra). Also seems a little arbitrary as I don't want to waste a line with my status.

**Comment by abo-abo** [comment]
> The behaviour is a little non-obvious

Here's a citation from [the doc](https://github.com/abo-abo/hydra#awesome-docstring):

> This can be a simple string used to build the final hydra hint. However, if you start it with a
> newline, the key-highlighting and Ruby-style string interpolation becomes enabled, as you can see
> in hydra-buffer-menu above.

I didn't cite this in `defhydra` docstring, since it's already huge and I can't put the whole README
and the wiki into the docstring.

> Also seems a little arbitrary as I don't want to waste a line with my status

The empty line will be stripped in the resulting string. I don't think that it's a big deal to spend
one newline in the source, especially when you're already planning to align stuff.

**Comment by braham-snyder** [comment]
the required newline was breaking my auto-indentation for some reason--to my surprise (I'm new to elisp), beginning the docstring with `\n` instead of an actual new line in the source code works as well (though perhaps this will break something else?)
