### ISSUE TITLE
FR: Make hydra-repeat take repeat count prefix argument

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/hydra#92]
I tried this with simple `do` loop around the current body and it seemed to work ok.

**Comment by abo-abo** [comment]
Nice idea, thanks.

**Comment by jhonnyseven** [comment]
This implementation doesn't work on commands where prefix argument doesn't mean repeat count, e.g. `join-lines`.

**Comment by jhonnyseven** [comment]
Maybe there should be another `hydra-repeat` like function that repeats the last command with last prefix argument. Both  behaviours the current, and something that repeats the last command multiple times forcibly, make sense to me.

**Comment by abo-abo** [comment]
> Maybe there should be another hydra-repeat like function that repeats the last command with last prefix argument

hydra-repeat already does this.

**Comment by jhonnyseven** [comment]
If you call `join-line`  without arguments it joins one line. If you
repeat that with `hydra-repeat` using prefix argument of 2 it doesn't join two lines. It calls `join-lines` with prefix arg of 2 which means join current line with following line.

**Comment by abo-abo** [comment]
> If you
> repeat that with hydra-repeat using prefix argument of 2 it doesn't join two lines. It calls join-lines with prefix arg of 2 which means join current line with following line.

That's a problem of `join-lines` or your expectation of its behavior, not a problem in
`hydra-repeat`. Just define a function on top of `join-lines` that works in the way that you like.

**Comment by jhonnyseven** [comment]
Exactly. I'm using a different kind of `hydra-repeat` called `hydra-repeat-times` which repeats arbitrary functions without having to wrap the originals.

**Comment by abo-abo** [comment]
OK, that makes sense now.  So for `join-lines`, do you find both behaviors useful? They actually
coincide for most functions.

**Comment by jhonnyseven** [comment]
Actually I just want to joint with previous line. 

Hmm, maybe I should just wrap it, with a macro or something.

**Comment by abo-abo** [comment]
> Actually I just want to joint with previous line.

```el
(defun my-join-line (&optional arg)
  (interactive "p")
  (setq arg (or arg 1))
  (dotimes (_i arg)
    (join-line 1)))
```

Pretty standard wrapper.

**Comment by jhonnyseven** [comment]
Yeah. 
I forgot defhydra was a macro so you can't put macros in the head and expect it to work.
