### ISSUE TITLE
error: Unrecognized key: _,,,--,,_

### ISSUE THREAD

**Issue by brunoqc** [abo-abo/hydra#94]
I didn't have this problem yesterday. I'm wondering if it's because I changed my emacs version. I'm now using 'GNU Emacs 24.4.91.1 (x86_64-w64-mingw32) of 2015-03-08 on KAEL' from [emacs-w64](https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB0QFjAA&url=http%3A%2F%2Fsourceforge.net%2Fprojects%2Femacsbinw64%2F&ei=mVkUVfboA_aOsQSkj4KYDQ&usg=AFQjCNER6LItjWKnfs6XjQqRl1-UMlXV5w&sig2=uq9wsaLPe-ZMxvQI_WCk5Q&bvm=bv.89217033,d.cWc).

```
Warning (initialization): An error occurred while loading `c:/Users/bbigras/.emacs':

error: Unrecognized key: _,,,--,,_

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

```lisp
Debugger entered--Lisp error: (error "Unrecognized key: _,,,--,,_")
  signal(error ("Unrecognized key: _,,,--,,_"))
  error("Unrecognized key: _%s_" ",,,--,,")
  hydra--format(hydra-rectangle (nil nil :body-pre (rectangle-mark-mode 1) :color pink :post (deactivate-mark)) "\n  ^_k_^     _d_elete    _s_tring     |\\     _,,,--,,_\n_h_   _l_   _o_k        _y_ank       /,`.-'`'   ._  -;;,_\n  ^_j_^     _n_ew-copy  _r_eset     |,4-  ) )_   .;.(  `'-'\n^^^^        _e_xchange  _u_ndo     '---''(_/._)-'(__)\n^^^^        ^ ^         _p_aste\n" (("" hydra-keyboard-quit nil :cmd-name hydra-rectangle/hydra-keyboard-quit-and-exit :exit t) ("h" backward-char nil :cmd-name hydra-rectangle/backward-char :cmd-name hydra-rectangle/backward-char) ("l" forward-char nil :cmd-name hydra-rectangle/forward-char :cmd-name hydra-rectangle/forward-char) ("k" previous-line nil :cmd-name hydra-rectangle/previous-line :cmd-name hydra-rectangle/previous-line) ("j" next-line nil :cmd-name hydra-rectangle/next-line :cmd-name hydra-rectangle/next-line) ("e" hydra-ex-point-mark nil :cmd-name hydra-rectangle/hydra-ex-point-mark :cmd-name hydra-rectangle/hydra-ex-point-mark) ("n" copy-rectangle-as-kill nil :cmd-name hydra-rectangle/copy-rectangle-as-kill :cmd-name hydra-rectangle/copy-rectangle-as-kill) ("d" delete-rectangle nil :cmd-name hydra-rectangle/delete-rectangle :cmd-name hydra-rectangle/delete-rectangle) ("r" (if (region-active-p) (deactivate-mark) (rectangle-mark-mode 1)) nil :cmd-name hydra-rectangle/lambda-r :cmd-name hydra-rectangle/lambda-r) ("y" yank-rectangle nil :cmd-name hydra-rectangle/yank-rectangle :cmd-name hydra-rectangle/yank-rectangle) ("u" undo nil :cmd-name hydra-rectangle/undo :cmd-name hydra-rectangle/undo) ("s" string-rectangle nil :cmd-name hydra-rectangle/string-rectangle :cmd-name hydra-rectangle/string-rectangle) ("p" kill-rectangle nil :cmd-name hydra-rectangle/kill-rectangle :cmd-name hydra-rectangle/kill-rectangle) ("o" nil nil :cmd-name hydra-rectangle/nil :cmd-name hydra-rectangle/nil)))
```

**Comment by abo-abo** [comment]
Please check if the last commit solves it. If not, give the hydra code
that results in this error.

**Comment by brunoqc** [comment]
I still have the problem with the last commit. It seems it's caused by the `(require 'hydra-examples)`. I'm not even sure if I need it and if I shouldn't require it.

init.el
```lisp
(package-initialize nil)
(add-to-list 'load-path "~/Dropbox/config emacs/hydra")
(package-initialize t)
(setq package-enable-at-startup nil)

(require 'hydra-examples)
```

emacs -q --load init.el
```
Eager macro-expansion failure: (error "Unrecognized key: _,,,--,,_")
if: Unrecognized key: _,,,--,,_
```

**Comment by colbell** [comment]
If you remove the ASCII art from the hydra-rectangle hydra in hydra-examples.el the problem goes away.

**Comment by colbell** [comment]
Sorry, I just saw your last commit fe1cfee3125792d40606ab8820665c7f3f63b442 which fixes the problem.

**Comment by abo-abo** [comment]
Poor cat, if only he had sticks for legs, like the buffer-menu cow.

**Comment by jhonnyseven** [comment]
Is there any way to have characters between keys in the doc string? I had quite a lot of strings like `_j_,_k_` and `_n_/_p` that I had to change.

**Comment by abo-abo** [comment]
@jhonnyseven, no need to change. Just roll back to the version where everything worked and post an
issue with a good (expected) output of `hydra--format`. And I'll make the current one work like
that.

**Comment by jhonnyseven** [comment]
You mean like this: `(concat (format "%s,%s" #("j" 0 1 (face hydra-face-blue)) #("k" 0 1 (face hydra-face-blue))) "")`? That's the good output for `_j_,_k_`.

**Comment by abo-abo** [comment]
On Fri, Mar 27, 2015 at 10:42 AM, jhonnyseven <notifications@github.com> wrote:
>
> You mean like this: (concat (format "%s,%s" #("j" 0 1 (face
> hydra-face-blue)) #("k" 0 1 (face hydra-face-blue))) "")? That's the good
> output for _j_,_k_.
>
> —

I'd like it in form of a test, like this one from hydra-test.el:

```cl
(should (equal
         (let ((hydra-fontify-head-function
                'hydra-fontify-head-greyscale))
           (hydra--format
            'bar
            nil
            "\n  bar %s`foo\n"
            '(("a" (quote t) "" :cmd-name bar/lambda-a)
              ("q" nil "" :cmd-name bar/nil))))
         '(concat (format "  bar %s\n" foo) "{a}, [q]")))
```

The important part is to have the input arguments and the output.

**Comment by jhonnyseven** [comment]
```emacs-lisp
(should
 (equal (hydra--format
	 nil
	 '(nil nil :hint nil)
	 "\n_j_,_k_"
	 '(("j" nil) ("k" nil)))
	(concat (format "%s,%s"
			#("j" 0 1 (face hydra-face-blue))
			#("k" 0 1 (face hydra-face-blue))) "")))
```

**Comment by jhonnyseven** [comment]
I think this counts towards the legally significant contribution line count. Maybe I should reformat this to one line ;)
Or maybe I should ask for the papers to sign..

**Comment by abo-abo** [comment]
The test is passing though, with no changes to the code. So why did you have the problem?

**Comment by jhonnyseven** [comment]
It was broken in 5c3ab46988904293457d59aecfe3d4bae7448207, now it works.

**Comment by brunoqc** [comment]
I tested again with my init.el file and I don't have the problem anymore.

**Comment by jhonnyseven** [comment]
There's a `-` in the regexp which should be escaped `...a-z.,-~A-Z...` after the `,`.

**Comment by kaushalmodi** [comment]
@jhonnyseven `-` is a special char but it does not have to be escaped. But it of course should be present at either the beginning of end of the expression inside `[` and `]` for clarity.

https://github.com/abo-abo/hydra/commit/1bad0c40e668038430f47be889af497f62e4f9bb#commitcomment-10419865

http://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Special.html

**Comment by jhonnyseven** [comment]
Oh it's after a range, but wasn't earlier. One more reason to use `rx` for me :)

**Comment by abo-abo** [comment]
OK, it seems to be fixed.  

@kaushalmodi, I'd like to appease you, but I'm sentimental about my
`a-z-A-Z`. I've been writing it that way for some time. Besides, `hydra--format` is pretty well
covered with tests by now.

**Comment by kaushalmodi** [comment]
@abo-abo That's alright. It's not about appeasing anyone. My suggestion was based on what I learned from the elisp regexp rules.
