### ISSUE TITLE
similar packages

### ISSUE THREAD

**Issue by Pitometsu** [abo-abo/hydra#95]
It is very similar to [discover.el](http://www.masteringemacs.org/article/discoverel-discover-emacs-context-menus) and [guide-key.el](https://github.com/kai2nenobu/guide-key)
What advantages does **hydra** have compared to both?

**Comment by abo-abo** [comment]
> It is very similar to discover.el and guide-key.el

They're similar in a way that they're all Emacs packages.

> What advantages does hydra have compared to both?

`defhydra` is actually your own `define-minor-mode`, which neither of the above packages is.  So
whenever you find the two mentioned packages lacking, you can code up your own solution with
`defhydra`. If you don't feel like coding, use `discover` and `guide-key`, they're fine packages.
