### ISSUE TITLE
Deactivate the mark on cancel

### ISSUE THREAD

**Issue by atykhonov** [abo-abo/hydra#96]
Hello!

I have the following code:

```
(defun hydra-post ()
  (interactive)
  (deactivate-mark t))

(global-set-key
 (kbd "M-p")
 (defhydra kill-region
     (:post (hydra-post))
   "Kill region."
   ("a" mark-word "Mark a word.")
   ("g" nil "cancel")))
```

I press `M-p`, then "a" and see that mark is activated. Now I want the following behaviour:

1) I press any key (other than "a", let say "t")
2) The active region replaces by that key ("t")
3) Mark deactivates
4) Hydra deactivates

Is that possible?

**Comment by abo-abo** [comment]
Not easily. With the current code, you could make the hydra pink, and advise around
`hydra-pink-fallback` checking for active region.

Can you show me the whole code? Maybe it would be useful to extend pink with a lambda handler.

**Comment by abo-abo** [comment]
Try this code:

```cl
(global-set-key
 (kbd "M-p")
 (defhydra kill-region
     (:post (hydra-post)
      :color pink)
   "Kill region."
   ("a" mark-word "Mark a word.")
   ("g" nil "cancel")))

(defadvice hydra-pink-fallback (around hydra-pink-test activate)
  (if (region-active-p)
      (progn
        (delete-active-region)
        (deactivate-mark t)
        (self-insert-command 1)
        (hydra-keyboard-quit))
    ad-do-it))
```

**Comment by atykhonov** [comment]
Yes, it works!  Thank you very much!

Are you going in the future to add such a feature to the hydra so that it will be possible to use it without defadvice?

**Comment by atykhonov** [comment]
Only one issue is with the code above it seems doesn't executes properly.

My original `hydra-post`:

```
(defun hydra-post ()
  (interactive)
  (deactivate-mark t)
  (hydra-post-cursor-color))
```

And cursor doesn't changes. Actually, as I understand, `hydra-post` doesn't executes at all...

**Comment by atykhonov** [comment]
I added `hydra-post` to the `defadvice`:

```
(defadvice hydra-pink-fallback
    (around hydra-pink-test activate)
  (if (region-active-p)
      (progn (delete-active-region)
             (deactivate-mark t)
             (self-insert-command 1)
             (hydra-keyboard-quit)
             (hydra-post))
    ad-do-it))
```

and it works fine.

**Comment by atykhonov** [comment]
For sorry it doesn't sometimes correctly cancels a hydra.

**Comment by atykhonov** [comment]
And I want hydra cancelation when undefined key is pressed.

**Comment by atykhonov** [comment]
Also I want to press `M-;` and see that comment command is called.

**Comment by abo-abo** [comment]
You need to be more specific. The last three comments look like problems, but they are unclear.

If you want them fixed, I need a step-by-step to reproduce each bug and to see each expectation.

**Comment by atykhonov** [comment]
Ok, thank you! I'll provide more details later.

**Comment by abo-abo** [comment]
> I press M-p, then "a" and see that mark is activated. Now I want the following behaviour:
> 
> 1) I press any key (other than "a", let say "t")
> 2) The active region replaces by that key ("t")
> 3) Mark deactivates
> 4) Hydra deactivates
> 
> Is that possible?

You can try this code:

```elisp
(global-set-key
 (kbd "M-p")
 (defhydra kill-region ()
   "Kill region."
   ("a" mark-word "Mark a word.")
   ("g" nil "cancel")))
```

If you have `delete-selection-mode` on, pressing <kbd>t</kbd> will
deactivate the hydra and insert `t`.

**Comment by abo-abo** [comment]
Closing as outdated. If you still get a problem, open a new issue or re-open this one.
